---
permalink: windows/concept-what-database-restore-is.html 
sidebar: sidebar 
keywords: snapmanager, enable, perform, file-based, backup, restore, operation, database 
summary: SnapManager を使用すると、ファイルベースのバックアップとリストアの処理を実行できます。 
---
= データベースリストアとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager を使用すると、ファイルベースのバックアップとリストアの処理を実行できます。

次の表に、リストア方式を示します。

|===
| リストアプロセス | 詳細 


 a| 
ファイルベースのリストア
 a| 
ストレージ側のファイルシステムのフルリストア（プライマリまたはセカンダリから）： SnapManager は完全な論理ユニット番号（ LUN ）のリストアを実行します。

|===


== ストレージ側のフルファイルシステムのリストア

ストレージ側でファイルシステムのフルリストアは、ボリュームをリストアできない場合に実行されますが、ファイルシステム全体をストレージシステム上でリストアできます。

ストレージ側でファイルシステムのリストアを実行すると、次のような処理が行われます。

* SAN 環境では、ファイルシステムで使用されているすべての LUN （および基盤となるボリュームグループがある場合はそのボリュームグループ）がストレージシステム上でリストアされます。


ストレージ側でファイルシステムのリストアを実行すると、ストレージの場所に応じて次の処理が実行されます。

* SnapManager がプライマリストレージシステムからリストアする場合は、 SFSR を使用して LUN （ SAN ）を元の場所にリストアします。
* SnapManager でセカンダリストレージシステムをリストアすると、セカンダリストレージシステムからネットワーク経由でプライマリストレージシステムに LUN （ SAN ）がコピーされます。


ファイルシステムは完全にリストアされるため、バックアップに含まれていないファイルもリストアされます。リストア対象のファイルシステムに、リストア対象外のファイルが存在する場合は、上書きが必要です。



== ホスト側のファイルのリストア

ストレージ側のファイルシステムのリストアとストレージ側のファイルのリストアを実行できない場合、 SAN 環境ではホスト側のファイルコピーのリストアを最後の手段として使用します。

ホスト側のファイルコピーのリストアでは、次のタスクを実行します。

* ストレージをクローニングする
* クローニングされたストレージをホストに接続します
* クローン・ファイルシステムからアクティブ・ファイルシステムにファイルをコピーします
* ホストからクローンストレージを切断しています
* クローンストレージを削除しています

