---
permalink: windows/concept-what-cloning-is.html 
sidebar: sidebar 
keywords: clone, database, create, replica, original, full, backup 
summary: データベースをクローニングして、元のデータベースの正確なレプリカを作成できます。クローンは、フルバックアップから作成するか、またはデータベースの現在の状態から作成できます。 
---
= クローニングとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データベースをクローニングして、元のデータベースの正確なレプリカを作成できます。クローンは、フルバックアップから作成するか、またはデータベースの現在の状態から作成できます。

SnapManager を使用してクローンを作成する利点は次のとおりです。

|===
| 利点 | 詳細 


 a| 
スピード
 a| 
SnapManager のクローン処理には、 Data ONTAP の FlexClone 機能を使用します。これにより、大容量のデータボリュームのクローンをすばやく作成できます。



 a| 
スペース効率化
 a| 
SnapManager を使用してクローンを作成する場合、スペースが必要になるのは、バックアップとクローン間の変更分だけです。SnapManager クローンは、元のデータベースの書き込み可能な Snapshot コピーであり、必要に応じて拡張できます。一方、データベースの物理的なクローンの場合、データベース全体を複製するのに十分なスペースが必要になります。



 a| 
仮想コピー
 a| 
クローンデータベースは、元のデータベースと同様に使用できます。たとえば、テスト、プラットフォームと更新のチェック、大規模なデータセットに対する複数のシミュレーション、リモートオフィスのテストとステージングにクローンを使用できます。クローンに変更を加えても、元のデータベースには影響しません。クローニングされたデータベースは、完全に動作します。



 a| 
簡易性
 a| 
SnapManager コマンドを使用して、任意のホストにデータベースをクローニングできます。

|===
データベースをクローニングする前に、次の前提条件を満たしていることを確認する必要があります。

* 「$ORACLE_HOME\database'」から'spfile <SID>.ora'ファイルを削除します
* 「$ORACLE_HOME\database'」から'init<SID>.ora`ファイルを削除します
* クローン仕様ファイルで指定された Oracle ダンプの送信先を削除します。
* クローン仕様ファイルで指定されている Oracle 制御ファイルを削除します。
* クローン仕様ファイルに指定された Oracle REDO ログファイルを削除します。


クローンには新しいシステム識別子を指定する必要があります。同じホスト上で、システム ID が同じ 2 つのデータベースを同時に実行することはできません。同じシステム識別子を使用して、別のホストにクローンを作成できます。クローンにラベルを付けるか、またはクローン作成日時を使用して、 SnapManager でラベルを作成できるようにします。

ラベルを入力するときは、スペースや特殊文字は使用できません。

クローニングされたデータベースに必要な Oracle ファイルおよびパラメータは、クローニングプロセス中に SnapManager によって作成されます。必要なOracleファイルの例としては、「init<SID>.ora」があります。

データベースをクローニングすると、SnapManager はデータベース用の新しい「init <SID>.ora`ファイルを「$ORACLE_HOME\database'」ディレクトリに作成します。

データベースが配置されているホストまたは代替ホストに、データベースバックアップをクローニングできます。

クローン作成したデータベースが「spfile」を使用していた場合、SnapManager はクローン用の「spfile」を作成します。このファイルは'$ORACLE_HOME\database'ディレクトリに配置され'診断ファイルのディレクトリ構造が作成されますファイル名は「spfile <SID>.ora」です。
