---
permalink: windows/concept-what-snapmanager-for-oraclesnapmanager-for-sap-does.html 
sidebar: sidebar 
keywords: snapmanager, sap, simplify, simplifies, automate, database, backup, recovery, clone, leverage, snapshot, copies, copy, snaprestore, flexclone, technology, technologies 
summary: SnapManager for SAPでは、Snapshotコピー、SnapRestore 、FlexCloneテクノロジを活用することで、データベースのバックアップ、リカバリ、クローニングを簡易化し、自動化します。 
---
= SnapManager for SAPの機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager for SAPでは、Snapshotコピー、SnapRestore 、FlexCloneテクノロジを活用することで、データベースのバックアップ、リカバリ、クローニングを簡易化し、自動化します。

SnapManager を使用すると、 DBA （データベース管理者）は次のようなメリットを得ることができます。

* データベースプロファイルの操作
+
** ホストとデータベースの情報をプロファイルとして整理し、保持することができます。
+
プロファイルに基づいてバックアップを開始する場合、バックアップのたびに再入力するのではなく、情報を再利用できます。SnapManager では、プロファイルを使用して処理を迅速に監視することもできます。

** プロファイルでは、 Snapshot コピーの命名パターンを定義してカスタムの（プレフィックスまたはサフィックス）テキストを入力することで、すべての Snapshot コピーがビジネスポリシーと同じ命名規則を使用できるようになります。
** データベースファイルは関連付けられたストレージに自動的にマッピングされるため、ストレージシステム名を把握する必要はありません。
** 新しいプロファイルを作成する場合は、アーカイブ・ログ・バックアップをデータ・ファイル・バックアップから分離するオプションを指定できます。
+
また、既存のプロファイルを更新して、アーカイブログバックアップとデータファイルバックアップを分離することもできます。



* データベースバックアップ処理を実行しています
+
** フルデータベースおよびパーシャルデータベースのバックアップ
+
*** スペース効率に優れた方法でフルバックアップまたはパーシャルバックアップを迅速に作成できるため、バックアップの頻度を高めることができます。
+
フルデータベースバックアップには、すべてのデータファイル、制御ファイル、およびアーカイブログファイルが 1 つのバックアップに格納されます。

+
データベースのパーシャル・バックアップには、指定したデータ・ファイルまたは表領域、すべての制御ファイル、およびすべてのアーカイブ・ログ・ファイルが含まれます。

*** ポストプロセススクリプトを使用して、セカンダリストレージへのバックアップを保護できます。
*** バックアップのスケジュールは、毎時、毎週、毎日、毎月、または無制限に設定できます。


** データ・ファイルとアーカイブ・ログ・ファイルのバックアップを分離します
+
*** SnapManager （ 3.2 以降）では、データ・ファイルとアーカイブ・ログ・ファイルを個別にバックアップできます。この処理を実行するには、プロファイルの作成時または更新時にアーカイブログファイルを分割するオプションを指定する必要があります。
*** 保持ポリシーには、データファイルのバックアップを保持する数と期間を指定できます。
*** アーカイブログファイルのバックアップをアーカイブログの保持期間で保持する期間を指定できます。
*** SnapManager （ 3.2 以降）は、アーカイブ・ログ・バックアップを最小数のバックアップに統合します。これにより、アーカイブ・ログ・バックアップが重複したアーカイブ・ログ・ファイルによって解放され、アーカイブ・ログ・バックアップだけが一意のアーカイブ・ログ・ファイルとともに保持されます。ただし、この統合はオプションで無効にできます。




* アーカイブログファイルの管理
+
** SnapManager （ 3.2 以降）を使用すると、アーカイブ・ログ・デスティネーションからアーカイブ・ログ・ファイルを削除できます。
+
このようなアーカイブログファイルが含まれているアーカイブログのバックアップがパージされると、プルーニングされたアーカイブログファイルによって占有されていたスペースが解放されます。

** SnapManager では、アーカイブ・ログの宛先からアーカイブ・ログ・ファイルを削除する前に、アーカイブ・ログ・ファイルをバックアップします。
+
バックアップされていないアーカイブログファイルは削除されません。

** SnapManager では、アーカイブログファイルが Data Guard スタンバイデータベースに転送され、 Data Guard プライマリデータベースからアーカイブログファイルが削除されます。
** SnapManager では 'Oracle のストリームキャプチャ・プロセスによってアーカイブ・ログ・ファイルがキャプチャされていることが確認されます（存在する場合）
** 推奨事項
+
*** アーカイブログデスティネーションスペースを効率的に管理するには、アーカイブログバックアップを作成し、アーカイブログファイルも一緒に削除する必要があります。


** SnapManager はアーカイブログのバックアップを統合してバックアップの最小数を確保します。これにより、アーカイブログのバックアップが重複してアーカイブログファイルによって解放され、アーカイブログのバックアップだけが一意のアーカイブログファイルに保持されます。
+
ただし、この統合はオプションで無効にできます。重複したアーカイブログファイルが含まれているアーカイブログバックアップは解放され、一意のアーカイブログを持つ単一のバックアップが保持されます。



* データベースリストア処理を実行しています
+
** ファイルベースのリストア処理を実行できます。
+
リストア処理をプレビューし、処理の実行前にリストア処理のファイル単位分析を取得することもできます。

** SnapRestore を使用して、データベースの平均リストア時間を短縮できます。
** SnapManager （ 3.2 以降）を使用すると、アーカイブ・ログ・デスティネーションにアーカイブ・ログ・ファイルが存在しない場合でも、バックアップのアーカイブ・ログ・ファイルを使用してデータベースを自動的にリカバリできます。
+
SnapManager （ 3.2 以降）は、アーカイブ・ログ・ファイルを使用して外部の場所から特定の範囲内にデータベースをリカバリする方法も提供します。



* テストと開発のためにデータベースのクローニングを実行する
+
** データベースのクローンを作成して、本番環境以外でデータベースを設定することもできます。
+
たとえば、開発環境やテスト環境でクローニングして、重要なシステムへのアップグレードをテストすることができます。

** プライマリストレージシステム上でデータベースをクローニングすることができます。
** SnapManager （ 3.2 以降）では、バックアップ内にあるアーカイブ・ログ・ファイルを使用して、データ・ファイルのバックアップをクローニングできます。
+
*** データファイルのバックアップをクローニングできるのは、アーカイブログのバックアップが作成されている場合のみです。
*** また、個別に作成されたアーカイブログバックアップにアーカイブログファイルがある場合は、データファイルバックアップをクローニングすることもできます。
*** また、 Oracle からアクセス可能な外部の場所にあるアーカイブログファイルを使用して、スタンドアロンデータベースのデータファイルバックアップを特定のエクステントにクローニングすることもできます。
*** バックアップを外部の場所から利用できる場合、クローニング中に外部の場所を指定して、クローンデータベースを整合性のある状態にリカバリできます。


** アーカイブログのみのバックアップのクローニングはサポートされていません。


* 全般
+
** SAPのBR * Toolsと統合
+
BR * Toolsパッケージには、BRARCHIVE、BRBACKUP、BRCONNECT、BRRECOVER、BRRESTOREなどのSAPツールが用意されています。 BRSPACEおよびBRTools。





SnapManager を使用すると、ストレージ管理者は次のようなメリットを得ることが

* では、サポートする SAN プロトコルが異なります。
* 環境に最も適したバックアップのタイプ（フルまたはパーシャル）に基づいて、バックアップを最適化できます。
* スペース効率に優れたデータベースバックアップを作成します。
* スペース効率に優れたクローンを作成できます。


SnapManager は 'Oracle の次の機能とも連携します

* SnapManager では、 Oracle の RMAN を使用してバックアップのカタログを作成できます。
+
RMAN を使用する場合、 DBA は SnapManager バックアップを利用して、ブロックレベル・リストアなどのすべての RMAN 機能の値を保持できます。SnapManager を使用すると、 RMAN でリカバリまたはリストアを実行する際に、 Snapshot コピーを使用できるようになります。たとえば、 SnapManager を使用すると、表領域内のテーブルを RMAN でリストアし、 によって作成された Snapshot コピーからデータベースと表領域全体をリストアおよびリカバリできます。RMAN リカバリ・カタログは、バックアップ対象のデータベースには保管しないでください。


