---
permalink: windows/concept-what-repositories-are.html 
sidebar: sidebar 
keywords: snapmanager, information, profile, repositories, repository 
summary: SnapManager では、情報がプロファイルに整理され、プロファイルがリポジトリに関連付けられます。プロファイルには管理対象のデータベースに関する情報が格納され、リポジトリにはプロファイルに対して実行された処理に関するデータが格納されます。 
---
= リポジトリとは何ですか
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager では、情報がプロファイルに整理され、プロファイルがリポジトリに関連付けられます。プロファイルには管理対象のデータベースに関する情報が格納され、リポジトリにはプロファイルに対して実行された処理に関するデータが格納されます。

リポジトリには、バックアップの実行日時、バックアップされたファイル、およびバックアップからクローンが作成されたかどうかが記録されます。データベース管理者がデータベースをリストアしたり、データベースの一部をリカバリしたりする場合、 SnapManager はバックアップの内容を確認するためにリポジトリを照会します。

リポジトリにはバックアップ処理中に作成されたデータベース Snapshot コピーの名前が格納されているため、リポジトリデータベースを同じデータベースに配置することはできません。また、 SnapManager がバックアップしているデータベースと同じデータベースに含めることもできません。SnapManager 処理を実行するには、少なくとも 2 つのデータベース（ SnapManager リポジトリデータベースと SnapManager で管理されているターゲットデータベース）が起動して稼働している必要があります。

リポジトリデータベースがダウンしているときにグラフィカルユーザインターフェイス（GUI）を開こうとすると、「SM_GUI.logファイル」に「WARN」というエラーメッセージが記録されます。[WARN]：「SMSAP-01106：リポジトリの照会中にエラーが発生しました：ソケットから読み取るデータがありません」。また、リポジトリデータベースがダウンしていると、 SnapManager の処理が失敗します。さまざまなエラーメッセージの詳細については、「既知の問題のトラブルシューティング」を参照してください。

処理を実行するには、有効なホスト名、サービス名、またはユーザ名を使用します。SnapManager 操作をサポートするリポジトリのユーザ名とサービス名は ' アルファベット (A ～ Z)' 数字 (0 ～ 9) ' マイナス記号 (-) ' アンダースコア (_)' ピリオド (.) の文字だけで構成する必要があります

リポジトリポートには任意の有効なポート番号を使用でき、リポジトリホスト名には任意の有効なホスト名を使用できます。ホスト名にはアルファベット（ A~Z ）、数字（ 0~9 ）、マイナス記号（ - ）、およびピリオド（ . ）を使用する必要があります。アンダースコア（ _ ）は使用できません。

リポジトリは Oracle データベース内に作成する必要があります。SnapManager が使用するデータベースは、データベース設定に関する Oracle の手順に従って設定する必要があります。

1 つのリポジトリには、複数のプロファイルの情報を格納できます。ただし、各データベースは、通常、 1 つのプロファイルだけに関連付けられます。複数のプロファイルが含まれているリポジトリごとに、複数のリポジトリを作成できます。
