---
permalink: windows/concept-profile-usage-for-br-tools-backups.html 
sidebar: sidebar 
keywords: br, tools, command, backint, interface, interface, snapmanager, profile, repository, credential, user, run, backup 
summary: 'backintインターフェイスを使用するBR * Toolsコマンドを実行すると、SnapManager ではリポジトリのプロファイルが使用されます。リポジトリは"BR * Toolsコマンドを実行しているユーザーのSnapManager 資格情報によって決定されます' 
---
= BR * Toolsバックアップのプロファイルの使用方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
backintインターフェイスを使用するBR * Toolsコマンドを実行すると、SnapManager ではリポジトリのプロファイルが使用されます。リポジトリは'BR * Toolsコマンドを実行しているユーザーのSnapManager 資格情報によって決定されます

デフォルトでは、SnapManager はSAPデータベースシステムIDと同じ名前のプロファイルを使用します。



== リポジトリにアクセスするためのクレデンシャルの作成について

「SMSAP credential set」コマンドを使用してBR * Toolsユーザのリポジトリクレデンシャルを設定できます。



== 別のSnapManager プロファイル名の指定について

SnapManager プロファイルが特定のリポジトリ内にあるすべてのホストでシステム識別子が一意であるかぎり、デフォルトのプロファイル名で十分です。SnapManager プロファイルを作成し、データベースシステムIDの値を使用して名前を付けることができます。

ただし、同じシステムIDを別々のホストで使用する場合、または特定のSAPインスタンスのBR * Toolsで使用する複数のSnapManager プロファイルを指定する場合は、BR * Toolsコマンドのプロファイル名を定義する必要があります。

SAPアプリケーション内でスケジュールされたデータベース処理は、ユーザとして実行されます。BR*SAPアプリケーション内でスケジュールされたツールの操作は'SAPServiceSID'として実行されますこれらのユーザには、リポジトリおよびプロファイルへのアクセス権が必要です。

SAPサービスユーザのSAPServiceSIDによって、ユーザはローカルにログインできません。これを変更するには、次の手順を実行してローカルセキュリティポリシーを変更する必要があります。

.手順
. [*スタート*>*プログラム*>*管理ツール*>*ローカル・セキュリティ・ポリシー*]をクリックします。
. [ローカルポリシー]を展開し'[**ユーザー権限の割り当て**]を選択します
. 「*ローカルでログオンを拒否する*」ポリシーを検索します。
. 右クリックして、*プロパティ*を選択します。
. このリストから* SAPサービスユーザー*を削除します。




== バックアップユーティリティのパラメータファイルの作成について

BR * Toolsコマンドでは'オプションでバックアップ・ユーティリティ・パラメータ(`.utl`parameter)ファイルをbackintインターフェイスに渡すこともできますデフォルトでは'このファイルの名前はinitSID.utl'ですここで'sidはデータベースのシステム識別子です

デフォルトでは'BR * Toolsは'initSID.sapファイルの'util_par_file'パラメータで指定されたパラメータ・ファイルを使用しますバックアップ・ユーティリティのパラメータ・ファイルは'通常'initSID.sapファイルと同じディレクトリに格納されます

'profile_name=<profile>'を'.utl`ファイルに追加して保存しますプロファイルは、BR * Toolsコマンドに使用するSnapManager プロファイル_の名前です。

次の表に'バックアップの保存'高速リストア'データ保護などのオペレーション用に'.utl'ファイルに含まれる追加のバックアップ・ユーティリティ・パラメータを示します

|===
| 処理 | バックアップユーティリティのパラメータ 


 a| 
バックアップの保持
 a| 
* キー：retain
* 値：無制限




| 毎時 | 毎日 


| 毎週 | 毎月 
|===
次の表に、これらの処理のさまざまなバックアップユーティリティパラメータを示します。

|===
| 操作 | キーを押します | 価値 


 a| 
バックアップの保持
 a| 
速い=
 a| 
フォールバック

|===


== BR * Tools初期化ファイルへのバックアップ・ユーティリティ・パラメータの追加

SAPは'$ORACLE_HOME\database\'内の各SAPデータベース・インスタンスに対して'initSID.sap'という名前のバックアップ・プロファイル・ファイルを作成しますこのファイルを使用して'BR*Toolsコマンドに使用するデフォルトのバックアップ・ユーティリティ・パラメータ(`.utl')ファイルを指定できます

.手順
. initSID.sapファイルを編集し'util_par_file=で始まる行を探します
. この行のコメントを解除し'プロファイル名を含むバックアップ・ユーティリティ・パラメータ・ファイルへのパスを追加しますたとえば'util_par_file=initSA1.utl'のようにします
. 'util_par_file'に値を指定する場合は'ファイルが存在することを確認してください
+
ファイルが見つからない場合、BRBACKUPコマンドはそのファイルをバックアップに含めようとするので失敗します。



次のいずれかのエラー条件が見つかった場合は'プロファイル名として-uオプションを使用する必要があります

* 'parameter files does not exist'
* 「profile_nameエントリがありません」というメッセージが表示されます


「orasid'」と「sidadm」の両方とも、BR * Toolsで作成されたバックアップの作成または管理に使用されるプロファイルへのアクセスが必要です。



== BR * Toolsコマンドでバックアップ・ユーティリティのパラメータ・ファイル名を指定する

オプションで'-rオプションを使用して'BR * Toolsコマンドでバックアップ・ユーティリティ・パラメータ（.utlパラメータ）ファイルを指定できますコマンドラインの値は、SAP初期化ファイルで指定されている値よりも優先されます。

BR * Toolsは'$ORACLE_HOME\database\'ディレクトリ内のパラメータ・ファイルを検索しますファイルを別の場所に保存する場合は'-rオプションを使用してフル・パスを指定する必要があります例：

`*brbackup -r C:\oracle\NetApp_fcp_prate_10g_enterpry_inst_vol1\database\initCER.utl...*`
