---
permalink: windows/concept-how-snapmanager-retains-backups-on-the-local-storage.html 
sidebar: sidebar 
keywords: snapmanager, enable, create, backup, retention, policies, policy, successful, local, storage, retain, database 
summary: SnapManager を使用すると、保持ポリシーを満たすバックアップを作成できます。このバックアップは、ローカルストレージに保持する成功したバックアップの数を指定します。特定のデータベースのプロファイルに保持する、成功したバックアップの数を指定できます。 
---
= SnapManager がローカルストレージ上にバックアップを保持する方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager を使用すると、保持ポリシーを満たすバックアップを作成できます。このバックアップは、ローカルストレージに保持する成功したバックアップの数を指定します。特定のデータベースのプロファイルに保持する、成功したバックアップの数を指定できます。

以下のバックアップを作成できます。

* プライマリストレージに毎日 10 日分のバックアップを保存します
* プライマリストレージの月単位のバックアップを 2 カ月分保存します
* セカンダリストレージに毎日バックアップを 7 日
* セカンダリストレージに週 4 回のバックアップを作成します
* セカンダリストレージ上の月単位のバックアップを 6 カ月間保持


SnapManager の各プロファイルについて、次の非制限保持クラスの値を変更できます。

* 毎時
* 毎日
* 毎週
* 毎月


SnapManager は、保持数（ 15 個のバックアップなど）と保持期間（ 10 日分のバックアップなど）の両方を考慮して、バックアップを保持するかどうかを決定します。バックアップは、その保持クラスに設定された保持期間またはバックアップ数が保持数を超えると期限切れになります。たとえば、バックアップ数が 15 で（ SnapManager で成功したバックアップが 15 個作成された）、日次バックアップを 10 日間保持するように期間の要件が設定されている場合は、成功した順に 5 つのバックアップが期限切れになります。

バックアップの期限が切れたあと、 SnapManager は期限切れのバックアップを解放または削除します。SnapManager は、常に最後に作成されたバックアップを保持します。

SnapManager でカウントされるのは、成功したバックアップの保持数のみで、次のことは考慮されません。

|===
| 保持数にバックアップが含まれていません | 詳細については 


 a| 
バックアップに失敗しました
 a| 
SnapManager は、成功したバックアップと成功しなかったバックアップに関する情報を保持します。成功しなかったバックアップではリポジトリの最小限のスペースしか必要ありませんが、必要に応じて削除することもできます。成功しなかったバックアップは、削除するまでリポジトリに残ります。



 a| 
保持するバックアップを無制限ベースに保持するか、別の保持クラスのバックアップを保持します
 a| 
SnapManager では、保持するバックアップが無制限に削除されることはありません。また、 SnapManager では、同じ保持クラスのバックアップだけが考慮されます（たとえば、 SnapManager では、 1 時間ごとの保持数については 1 時間ごとのバックアップだけが考慮されます）。



 a| 
ローカルストレージからマウントされたバックアップ
 a| 
マウントされた Snapshot コピーもクローニングされるため、保持対象とはみなされません。SnapManager では、 Snapshot コピーがクローニングされている場合、 Snapshot コピーを削除できません。



 a| 
ローカルストレージ上でクローンを作成するために使用されるバックアップ
 a| 
SnapManager は、クローン作成に使用されるすべてのバックアップを保持しますが、バックアップの保持数については考慮しません。

|===
SnapManager には、各保持クラスのデフォルトの保持数と保持期間が用意されています。たとえば、時間単位の保持クラス数である SnapManager の場合、デフォルトでは 4 つの時間単位のバックアップが保持されます。これらのデフォルト値は、プロファイルの作成時または更新時に上書きして設定することも、「SMSAP_CONFIG」ファイルで保持数および保持期間のデフォルト値を変更することもできます。

保持ポリシーに基づいてローカルバックアップが期限切れになると、バックアップは削除されます。

オンラインデータベースバックアッププロセスとは異なり、アーカイブログのみのバックアップ処理では、 SnapManager は REDO ログファイルをアーカイブしません。アーカイブログのみのバックアップ操作を実行する前に、プリタスクスクリプトを追加して REDO ログファイルをアーカイブする必要があります。プリタスクスクリプトでは、「alter system switch logfile」コマンドを実行する必要があります。

次に、日次バックアップを 3 つ保持するポリシー（保持数が 3 に設定されているポリシー）に基づいて、さまざまなタイプのバックアップに対して SnapManager が実行する処理の例を示します。

|===
| バックアップ日 | ステータス | 保持ポリシーによる処理が実行されました | 説明 


 a| 
5/10.
 a| 
成功しました
 a| 
保持（ Keep ）
 a| 
これは、最新の成功したバックアップであるため、保持されます。



 a| 
5/9.
 a| 
成功、クローン作成済み
 a| 
スキップします
 a| 
SnapManager では、保持ポリシー数のクローニングに使用されるバックアップは考慮されません。このバックアップは成功したバックアップの数から除外されます。



 a| 
5/8
 a| 
成功、マウント済み
 a| 
スキップします
 a| 
SnapManager では、保持ポリシー数のマウントバックアップは考慮されません。このバックアップは成功したバックアップの数から除外されます。



 a| 
5/7.
 a| 
失敗しました
 a| 
スキップします
 a| 
失敗したバックアップはカウントされません。



 a| 
5/5.
 a| 
成功しました
 a| 
保持（ Keep ）
 a| 
SnapManager は、この 2 回目に成功した日次バックアップを保持し



 a| 
5/3.
 a| 
成功しました
 a| 
保持（ Keep ）
 a| 
SnapManager は、この 3 回目の成功した日次バックアップを保持し



 a| 
5/2
 a| 
成功しました
 a| 
削除
 a| 
SnapManager はこの成功したバックアップの数をカウントしますが、 SnapManager が日次バックアップを 3 回成功すると、そのバックアップは削除されます。

|===
* 関連情報 *

http://mysupport.netapp.com/["のドキュメントについては、ネットアップサポートサイトを参照してください"^]
