---
permalink: windows/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, user, allow, resource, repository, repositories, host, profile, credential, management 
summary: SnapManager では、ユーザ認証を適用してセキュリティを管理できます。ユーザ認証方式を使用すると、リポジトリ、ホスト、プロファイルなどのリソースにアクセスできます。 
---
= セキュリティと資格情報の管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager では、ユーザ認証を適用してセキュリティを管理できます。ユーザ認証方式を使用すると、リポジトリ、ホスト、プロファイルなどのリソースにアクセスできます。

コマンドラインインターフェイス（ CLI ）またはグラフィカルユーザインターフェイス（ GUI ）を使用して処理を実行すると、 SnapManager はリポジトリおよびプロファイルに設定されているクレデンシャルを取得します。SnapManager は以前のインストールのクレデンシャルを保存します。

リポジトリとプロファイルは、パスワードで保護できます。クレデンシャルとは、ユーザがオブジェクト用に設定したパスワードであり、パスワードはオブジェクト自体には設定されません。

認証とクレデンシャルを管理するには、次のタスクを実行します。

* ユーザ認証は、操作時にパスワードプロンプトを使用するか、または「smsapscredential set」コマンドを使用して管理します。
+
リポジトリ、ホスト、またはプロファイルのクレデンシャルを設定する

* アクセスできるリソースを制御するクレデンシャルを表示します。
* すべてのリソース（ホスト、リポジトリ、およびプロファイル）について、ユーザのクレデンシャルをクリアします。
* 個々のリソース（ホスト、リポジトリ、およびプロファイル）に対するユーザのクレデンシャルを削除する。



NOTE: リポジトリ・データベースが Windows ホスト上にある場合、ローカル・ユーザまたは管理者ユーザとドメイン・ユーザの両方に同じクレデンシャルが必要です。
