---
permalink: windows/concept-about-control-file-and-archive-log-file-handling.html 
sidebar: sidebar 
keywords: snapmanager, control, file, archive, log, backup, recovery, handle 
summary: SnapManager には制御ファイルが格納されており、必要に応じて各バックアップと一緒にアーカイブログファイルも格納されます。アーカイブログファイルはリカバリ処理に使用されます。 
---
= 制御ファイルおよびアーカイブログファイルの処理について
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager には制御ファイルが格納されており、必要に応じて各バックアップと一緒にアーカイブログファイルも格納されます。アーカイブログファイルはリカバリ処理に使用されます。

データベースは制御ファイルを使用して、データベースファイルの名前、場所、サイズを識別します。制御ファイルはリストアプロセスで使用されるため、 SnapManager の各バックアップには制御ファイルが含まれます。

データベースへの変更はオンライン REDO ログを使用して追跡されます。このログは最終的にアーカイブされ、アーカイブ REDO ログ（またはアーカイブログ）と呼ばれます。SnapManager （ 3.2 以降）を使用すると、保持期間および頻度が異なるデータファイルとアーカイブログファイルを別々にバックアップできます。SnapManager でバックアップを作成できるのは、アーカイブログのみです。または、データファイルとアーカイブログのバックアップを組み合わせることもできます。SnapManager では、アーカイブ・ログを完全に自動管理できます。また、データベース・リカバリ作業を手動で行う必要もなく、バックアップ作成後に 1 つ以上のアーカイブ・ログ・デスティネーションからアーカイブ・ログを削除できます。


NOTE: バックアップに含まれる表領域とデータ・ファイルを確認するには'backup showコマンドまたはBackup Propertiesウィンドウを使用します

次の表に、 SnapManager による各処理で制御ログファイルとアーカイブログファイルがどのように処理されるかを示します。

|===
| 処理のタイプ | 制御ファイル | アーカイブログファイル 


 a| 
バックアップ
 a| 
各バックアップに含まれています
 a| 
各バックアップに含めることができます



 a| 
リストア
 a| 
リストアは、単独で行うことも、表領域またはデータ・ファイルと一緒に行うこともできます
 a| 
リカバリプロセスに使用できます

|===