---
permalink: windows/concept-prerequisites-for-performing-a-rollback.html 
sidebar: sidebar 
keywords: perform, rollback, ensure, environment, certain, requirement, prerequisite 
summary: ロールバックを実行する前に、環境が一定の要件を満たしていることを確認する必要があります。 
---
= ロールバックを実行するための前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロールバックを実行する前に、環境が一定の要件を満たしていることを確認する必要があります。

* SnapManager 3.3 以降を使用していて、 SnapManager 3.1 よりも前のバージョンにロールバックする場合は、 3.2 にロールバックしてから、必要なバージョンにロールバックする必要があります。
* 外部データ保護またはデータ保持を実行するために使用する外部スクリプトをバックアップしておく必要があります。
* ロールバック先の SnapManager バージョンがインストールされている必要があります。
+

NOTE: SnapManager 3.3 以降から SnapManager 3.1 より前のバージョンへのロールバックを実行する場合は、まず SnapManager 3.2 をインストールしてロールバックを実行する必要があります。3.2 にロールバックしたら、 SnapManager 3.1 以前をインストールし、そのバージョンへのロールバックをもう一度実行できます。

* ロールバック先の SnapManager バージョンでサポートされる SnapDrive for Windows のバージョンがインストールされている必要があります。
+
SnapDrive のインストールについては、 SnapDrive のマニュアルセットを参照してください。

* リポジトリデータベースをバックアップしておく必要があります。
* リポジトリを使用しているホストをロールバックする場合は、同じリポジトリを使用している他のホストで SnapManager 処理を実行しないでください。
+
スケジュールされた処理または他のホストで実行されている処理は、ロールバックが完了するまで待機します。

* 同じリポジトリデータベースを参照するプロファイルは、 SnapManager サーバホスト内で別の名前を使用して作成する必要があります。
+
同じ名前のプロファイルを使用すると、そのリポジトリデータベースに関連するロールバック処理が失敗します。

* ロールバックするホストで SnapManager 処理を実行しないでください。
+
実行中の処理がある場合は、その処理が完了してからロールバックを実行する必要があります。




NOTE: ロールバック処理は、同時にロールバックされるホストのバックアップの累積数が増加するにつれて長く実行されます。ロールバックの所要時間は、特定のホストに関連付けられたプロファイルとバックアップの数によって異なります。

* 関連情報 *

http://mysupport.netapp.com/["ネットアップサポートサイトのドキュメント： mysupport.netapp.com"^]
