---
permalink: windows/concept-limitations.html 
sidebar: sidebar 
keywords: aware, scenario, limitation, environment, work, snapmanager 
summary: 環境に影響する可能性があるシナリオと制限事項を把握しておく必要があります。 
---
= SnapManager で作業する際の制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
環境に影響する可能性があるシナリオと制限事項を把握しておく必要があります。

* データベースのレイアウトとプラットフォームに関する制限 *

* SnapManager は、ファイルシステム上の制御ファイルをサポートしますが、 raw デバイス上の制御ファイルはサポートしません。
* SnapManager は MSCS （ Microsoft クラスタリング）環境で動作しますが、 MSCS 構成の状態（アクティブまたはパッシブ）は認識されず、 MSCS クラスタ内のスタンバイサーバにリポジトリのアクティブ管理を転送しません。
* リポジトリ・データベースは、複数の IP アドレスを使用してアクセスできるホスト上に存在する場合があります。
+
複数の IP アドレスを使用してリポジトリにアクセスする場合は、 IP アドレスごとにスケジュールファイルが作成されます。IP アドレスのいずれか（ IP1 など）の下にあるプロファイル（プロファイル A など）のスケジュールバックアップが作成されると、その IP アドレスのスケジュールファイルだけが更新されます。プロファイル A が別の IP アドレス（ IP2 など）からアクセスされている場合、 IP2 のスケジュールファイルに IP1 で作成されたスケジュールのエントリがないため、スケジュールされたバックアップはリストに表示されません。

+
その IP アドレスとスケジュールファイルが更新されるのを待ってスケジュールがトリガーされるか、サーバを再起動します。



* SnapManager 構成に関する制限 *

* SnapManager では、次の要件を持つ MultiStore ストレージシステム上のデータベースがサポートされます。
+
** MultiStore ストレージシステムのパスワードを設定するには、 SnapDrive を設定する必要があります。
** 基盤となるボリュームが同じ MultiStore ストレージ・システムに存在しない場合、 SnapDrive は MultiStore ストレージ・システムの qtree に常駐している LUN またはファイルの Snapshot コピーを作成できません。


* SnapManager では、単一のクライアント（ CLI と GUI の両方）から異なるポート上で実行されている 2 台の SnapManager サーバへのアクセスはサポートされていません。
+
ポート番号は、ターゲットホストとリモートホストで同じである必要があります。

* SnapManager 処理は失敗し、リポジトリデータベースがダウンしていると GUI にアクセスできません。
+
SnapManager の処理を実行するときは、リポジトリデータベースが実行されていることを確認する必要があります。

* SnapManager は、 LPM （ Live Partition Mobility ）および LAM （ Live Application Mobility ）をサポートしていません。
* SnapManager は、 Oracle Wallet Manager および Transparent Data Encryption （ TDE ）をサポートしていません。
* Virtual Storage Console （ VSC ）ではまだ MetroCluster 構成がサポートされていないため、 SnapManager では raw デバイスマッピング（ RDM ）環境での MetroCluster 構成はサポートされません。


* プロファイル管理に関する制限 *

* アーカイブログバックアップを分離するようにプロファイルを更新すると、ホストでロールバック処理を実行できなくなります。
* GUI からプロファイルを有効にしてアーカイブ・ログ・バックアップを作成し、後で [ マルチプロファイル・アップデート ] ウィンドウまたは [ プロファイル・アップデート ] ウィンドウを使用してプロファイルを更新しようとしても、そのプロファイルを変更してフル・バックアップを作成することはできません。
* Multi Profile Update ウィンドウで複数のプロファイルを更新し、一部のプロファイルでは * Backup archivelogs separately * オプションが有効になっていて、その他のプロファイルではオプションが無効になっている場合、 * Backup archivelogs separately * オプションは無効になります。
* 複数のプロファイルを更新した場合に、一部のプロファイルで * Backup archivelogs separately * オプションが有効になっていて、他のプロファイルでオプションが無効になっていると、 Multi Profile Update ウィンドウの * Backup archivelogs separately * オプションが無効になります。
* プロファイルの名前を変更した場合、ホストをロールバックすることはできません。


* ローリングアップグレードまたはロールバック操作に関する制限 *

* リポジトリ内のホストでロールバック処理を実行せずに、以前のバージョンの SnapManager をホストにインストールしようとすると、次のことができない場合があります。
+
** 以前のバージョンまたは新しいバージョンの SnapManager で作成されたホストのプロファイルを表示します。
** 以前のバージョンまたは新しいバージョンの SnapManager で作成したバックアップまたはクローンにアクセスします。
** ホストでローリングアップグレードまたはロールバック処理を実行します。


* プロファイルを分けてアーカイブログバックアップを作成したあとで、関連するホストリポジトリでロールバック処理を実行することはできません。


* バックアップ操作に関する制限 *

* リカバリ中に、バックアップがすでにマウントされている場合、 SnapManager はバックアップを再マウントしないので、すでにマウントされているバックアップを使用します。
+
バックアップが別のユーザによってマウントされており、以前にマウントしたバックアップにアクセスできない場合は、そのユーザに権限を付与する必要があります。

+
すべてのアーカイブ・ログ・ファイルには、グループに割り当てられたユーザに対する読み取り権限があります。バックアップが別のユーザ・グループによってマウントされている場合は、アーカイブ・ログ・ファイルへのアクセス権限がない可能性があります。マウントされたアーカイブログファイルに対する権限をユーザが手動で付与し、リストアまたはリカバリ処理を再試行できます。

* SnapManager は、データベース・バックアップの Snapshot コピーの 1 つがセカンダリ・ストレージ・システムに転送される場合でも、バックアップ状態を「 protected 」として設定します。
* スケジュールされたバックアップには、 SnapManager 3.2 以降のタスク仕様ファイルのみを使用できます。
* リポジトリデータベースが複数の IP アドレスを指していて、それぞれの IP アドレスが異なる場合、 1 つの IP アドレスに対するバックアップのスケジュール設定処理は成功しますが、もう 1 つの IP アドレスに対するバックアップのスケジュール設定処理は失敗します。
* ONTAP 環境では、 SnapManager でソースボリュームの複数のセカンダリデスティネーションがサポートされません。


* リストア操作に関する制限 *

* SnapManager では、 Windows で高速リストアまたはボリュームベースのリストア処理を使用したデータベースバックアップのリストアはサポートされていません。
+
SnapManager 3.3 では、 SnapManager CLI から高速リストア処理を実行しようとすると、エラーメッセージが表示されます。



* クローン操作に関する制限 *

* SnapManager 3.3 以降では、 SnapManager 3.2 より前のリリースで作成されたクローン仕様 XML ファイルの使用はサポートされていません。
* 一時表領域がデータファイルの場所とは異なる場所に配置されている場合、クローン処理を実行すると、データファイルの場所に表領域が作成されます。
+
一時表領域が、データファイルの場所とは異なる場所にある Oracle Managed Files （ oMFS ）の場合、クローン処理ではデータファイルの場所に表領域が作成されません。oMFS は SnapManager によって管理されません。

* --resetlogsオプションを選択すると、SnapManager はRACデータベースのクローンを作成できません。


* アーカイブ・ログ・ファイルおよびバックアップに関する制限 *

* SnapManager では、フラッシュリカバリ領域のデスティネーションからアーカイブログファイルを削除することはできません。
* SnapManager は、スタンバイ・デスティネーションからのアーカイブ・ログ・ファイルの削除をサポートしていません。
* アーカイブログのバックアップは、保持期間とデフォルトの時間単位保持クラスに基づいて保持されます。
+
SnapManager の CLI または GUI を使用してアーカイブログバックアップの保持クラスを変更した場合、アーカイブログのバックアップは保持期間に基づいて保持されるため、変更した保持クラスはバックアップの対象とはみなされません。

* アーカイブログデスティネーションからアーカイブログファイルを削除すると、欠落しているアーカイブログファイルよりも古いアーカイブログファイルはアーカイブログバックアップに含まれません。
+
最新のアーカイブログファイルがない場合は、アーカイブログのバックアップ処理が失敗します。

* アーカイブ・ログ・デスティネーションからアーカイブ・ログ・ファイルを削除すると、アーカイブ・ログ・ファイルの削除に失敗します。
* SnapManager は、アーカイブログデスティネーションまたはアーカイブログファイルが破損した場合でも、アーカイブログバックアップを統合します。


* ターゲット・データベースのホスト名の変更に関する制限 *

ターゲットデータベースのホスト名を変更する場合、次の SnapManager 処理はサポートされません。

* SnapManager GUI からターゲット・データベースのホスト名を変更します。
* プロファイルのターゲットデータベースのホスト名を更新したあとに、リポジトリデータベースをロールバックする。
* 新しいターゲットデータベースのホスト名について、複数のプロファイルを同時に更新する。
* SnapManager 処理の実行中にターゲット・データベースのホスト名を変更する場合


* SnapManager CLI または GUI* に関する制限事項

* SnapManager GUIから生成される「profile create」操作用のSnapManager CLIコマンドには、履歴設定オプションはありません。
+
SnapManager CLIから履歴保持設定を構成するには'profile createコマンドは使用できません

* Windows クライアントに使用できる Java Runtime Environment （ JRE ）がない場合、 Mozilla Firefox に SnapManager が GUI を表示しません。
* SnapManager 3.3 では、 Windows Server 2008 および Windows 7 上の Microsoft Internet Explorer 6 に SnapManager GUI が表示されません。
* SnapManager CLI を使用してターゲットデータベースのホスト名を更新する際に、 SnapManager GUI セッションが 1 つ以上開いていると、開いている SnapManager GUI セッションすべてが応答しません。
* Windows に SnapManager をインストールし、 UNIX で CLI を起動すると、 Windows でサポートされていない機能が表示されます。


* SnapMirror および SnapVault * に関する制限事項

* 場合によっては、ボリュームで SnapVault 関係が確立されていると、最初の Snapshot コピーに関連付けられていた最後のバックアップを削除できないことがあります。
+
バックアップを削除できるのは、関係を解除する場合のみです。この問題は、ベースの Snapshot コピーに関する ONTAP の制限が原因です。SnapMirror 関係では、ベースの Snapshot コピーは SnapMirror エンジンによって作成され、 SnapVault 関係では、ベースの Snapshot コピーは SnapManager を使用して作成されたバックアップです。ベースの Snapshot コピーは、更新のたびに、 SnapManager を使用して作成された最新のバックアップを参照します。



* Data Guard スタンバイ・データベースに関する制限 *

* SnapManager は、論理 Data Guard スタンバイデータベースをサポートしていません。
* SnapManager は、 Active Data Guard スタンバイデータベースをサポートしていません。
* SnapManager では、 Data Guard スタンバイデータベースのオンラインバックアップは許可されていません。
* SnapManager では、 Data Guard スタンバイデータベースのパーシャル・バックアップは許可されません。
* SnapManager では、 Data Guard スタンバイデータベースのリストアは許可されていません。
* SnapManager では、 Data Guard スタンバイ・データベースのアーカイブ・ログ・ファイルの削除は許可されません。
* SnapManager では、 Data Guard Broker はサポートされていません。


* 関連情報 *

http://mysupport.netapp.com/["のドキュメントについては、ネットアップサポートサイトを参照してください"^]
