---
permalink: windows/concept-what-database-backup-scheduling-is.html 
sidebar: sidebar 
keywords: schedule, update, monitor, backup, database, graphical, user, interface 
summary: グラフィカルユーザインターフェイスの Schedule タブでは、データベースのバックアップのスケジュール設定、更新、監視を行うことができます。 
---
= データベースバックアップのスケジュールとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グラフィカルユーザインターフェイスの Schedule タブでは、データベースのバックアップのスケジュール設定、更新、監視を行うことができます。

次の表に、スケジュールに関するよくある質問を示します。

|===
| 質問 | 回答 


 a| 
SnapManager サーバを再起動すると、スケジュールされたバックアップはどうなりますか。
 a| 
SnapManager サーバを再起動すると、すべてのスケジュールが自動的に再開されます。ただし、 SnapManager では、発生しなかったイベントはフォローアップされません。



 a| 
2 つのデータベースで同時に 2 つのバックアップが実行されるようにスケジュールを設定した場合、どうなりますか？
 a| 
SnapManager はバックアップ処理を 1 つずつ開始し、バックアップを並行して実行できるようにします。たとえば、データベース管理者が、 6 つの異なるデータベースプロファイルに対して 1 日ごとのバックアップスケジュールを 6 つ作成し、午前 1 時に実行する場合は、 6 つのバックアップすべてが同時に実行されます。

1 つのデータベースプロファイルで複数のバックアップが短時間に実行されるようにスケジュールされている場合、 SnapManager サーバは、保持期間が最も長いバックアップ処理のみを実行します。

SnapManager は、バックアップ処理を開始する前に、まず次の点を決定します。

* 過去 30 分以内に、同じプロファイルに対して、保持期間を延長したバックアップが別のスケジュールで正常に作成されていませんか？
* 今後 30 分以内に、同じプロファイルに対して、より長期的な保持を設定したバックアップを別のスケジュールで作成しますか？


いずれかの質問に対する回答が「はい」の場合、 SnapManager はバックアップをスキップします。

たとえば、データベース管理者は、データベースプロファイルに対して毎日、毎週、毎月のスケジュールを作成し、これらのスケジュールはすべて午前 1 時にバックアップを作成するようにスケジュールされます1 日のうちに 3 つのバックアップが同時に実行されるようにスケジュールされた午前 1 時に、 SnapManager は月次スケジュールに基づいてバックアップ処理のみを実行します。

SnapManager プロパティファイルでは、 30 分間の時間ウィンドウを変更できます。



 a| 
どのユーザの下でバックアップ処理が実行されますか？
 a| 
スケジュールを作成したユーザの下で処理が実行されます。ただし、データベースプロファイルとホストの両方に有効なクレデンシャルがある場合は、この ID を独自のユーザ ID に変更することができます。たとえば、 Avida Davis が作成したバックアップスケジュールのスケジュールバックアッププロパティを起動すると、 Stella Morrow はこの操作をユーザーとして実行し、スケジュールされたバックアップを実行できます。



 a| 
SnapManager スケジューラは、ネイティブのオペレーティングシステムスケジューラとどのように連携しますか。
 a| 
SnapManager サーバでは、スケジュールされたバックアップをオペレーティングシステムの標準スケジューラ経由で表示することはできません。たとえば、スケジュールされたバックアップを作成した後は、 [ スケジュールされたタスク ] ウィンドウに新しいエントリが表示されません。



 a| 
グラフィカルユーザインターフェイスとサーバのクロックが同期していない場合はどうなりますか？
 a| 
クライアントとサーバのクロックが同期されていません。そのため、バックアップのスケジュールを設定する際に、クライアントでは開始時刻が将来的に、サーバでは過去に開始時刻が設定されます。

繰り返しバックアップの場合は、サーバは要求を処理します。たとえば ' サーバが '2008 年 1 月 30 日午後 3 時以降の毎時バックアップを実行する要求を受信した場合などですしかし、現在の時刻は午後 3 時 30 分ですその日に、サーバは最初のバックアップを午後 4 時に実行します1 時間ごとにバックアップを実行し続けます。

ただし、 1 回限りのバックアップの場合、サーバは次のように要求を処理します。

* 開始時刻が現在のサーバ時刻の最後の 5 分以内である場合、 SnapManager はただちにバックアップを開始します。
* 開始時間が 5 分を超えると、 SnapManager はバックアップを開始しません。


たとえば、次のシナリオを考えてみましょう。

* グラフィカル・インターフェイス・ホストのクロックは、実際の時間の 3 分後です。
* クライアントの現在の時刻は午前 8 時 58 分です
* 1 回限りのバックアップを午前 9 時に実行するようにスケジュール設定したとします
* 別の 1 回限りのバックアップを午前 8 時 30 分に実行するようにスケジュールした場合


サーバが最初の要求を受信した時点での時間は午前 9 時 01 分ですバックアップの開始時刻は過去ですが、 SnapManager はただちにバックアップを実行します。

サーバが 2 回目の要求を受信した場合、バックアップの開始時刻が過去 5 分を超えています。開始時刻が過去のため、スケジュール要求が失敗したことを示すメッセージが表示されます。

SnapManager のプロパティファイルでは、 5 分間の時間を変更できます。



 a| 
プロファイルを削除した場合に、そのプロファイルのスケジュールされたバックアップはどうなりますか。
 a| 
データベース・プロファイルを削除すると、 SnapManager サーバは、そのプロファイルに定義されているスケジュールされたバックアップを削除します。



 a| 
夏時間中や SnapManager サーバの時間を変更する際、スケジュールされたバックアップはどのように動作しますか？
 a| 
SnapManager バックアップスケジュールは、夏時間や SnapManager サーバの時間を変更すると影響を受けます。

SnapManager サーバの時間を変更する場合は、次の点に注意してください。

* バックアップスケジュールの開始後に SnapManager サーバの時間がフォールバックしても、バックアップスケジュールは再度トリガーされません。
* スケジュールされた開始時刻より前に夏時間が開始されると、バックアップスケジュールが自動的に開始されます。
* たとえば、米国内で、毎時バックアップのスケジュールを午前 4 時に設定したとします4 時間ごとにバックアップが実行され、 3 月と 11 月の夏時間調整の前後の午前 4 時、午前 8 時、午前 4 時、午後 8 時、および午前 0 時にバックアップが実行されます。
* バックアップのスケジュールが午前 2 時 30 分に設定されている場合は、次の点に注意してください毎晩：
+
** すでにバックアップが開始されているため、クロックが 1 時間フォールバックしても、バックアップは再度トリガーされません。
** クロックが 1 時間前にスプリングすると、バックアップはすぐにトリガーされます。米国内でこの問題を使用しない場合は、午前 2 時以外にバックアップを開始するようにスケジュールを設定する必要があります午前 3 時まで間隔：




|===