---
permalink: windows/concept-how-to-organize-repositories.html 
sidebar: sidebar 
keywords: organize, snapmanager, repository, repositories, business, application, type, usage 
summary: SnapManager リポジトリは、ビジネスニーズに合わせて整理することができます。アプリケーションの種類や使用方法など、複数の方法で整理できます。 
---
= リポジトリを整理する方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager リポジトリは、ビジネスニーズに合わせて整理することができます。アプリケーションの種類や使用方法など、複数の方法で整理できます。

リポジトリはいくつかの方法で整理できます。次の 2 つの方法があります。

|===
| を入力します | 特性 


 a| 
アプリケーションごと
 a| 
異なるアプリケーションを実行する複数の Oracle データベースがある場合は、アプリケーションの種類ごとに SnapManager リポジトリを作成できます。各 SnapManager リポジトリには、特定のアプリケーション・タイプのデータベース用のプロファイルが設定されます。そのアプリケーションタイプの本番、開発、およびテスト用のデータベースは、すべて同じ SnapManager リポジトリで管理されます。このオプションを使用すると、類似したデータベースをグループ化してクローニングを簡単に行うことがただし、アプリケーションタイプが複数ある場合は、複数の SnapManager リポジトリを管理しなければならないことがあります。また、別のアプリケーションタイプを実装する場合は、別の SnapManager リポジトリを作成する必要があります。これらの SnapManager リポジトリは本番環境のデータベースを管理するため、高可用性を備えたサーバに各リポジトリを配置する必要があります。これはコストがかかる可能性があります。また、同じ SnapManager リポジトリ内で、本番データベースと、開発データベースおよびテストデータベースを同じタイプのデータベースとともに管理する必要がある場合も、セキュリティ問題になります。



 a| 
使用状況別
 a| 
データベースは、その使用状況（本番、開発、テスト、トレーニングなど）に基づいて SnapManager リポジトリに分散できます。このオプションを指定すると、リポジトリの数が、使用しているデータベースのタイプによって制限されます。すべての本番環境のデータベースは 1 つの SnapManager リポジトリで管理されるため、このリポジトリへのアクセス権を割り当てることができるのは、本番環境のデータベース管理者だけです。また、新しいアプリケーションタイプ用に別のデータベースを配置する場合は、新しいリポジトリを作成するのではなく、対応する SnapManager リポジトリにデータベースを登録するだけで済みます。高可用性を実現できるのは、すべての本番用データベースのプロファイルが格納された SnapManager リポジトリだけです。

|===
SnapManager for Oracle と SnapManager for SAP で同じリポジトリを共有することはできません。SnapManager for Oracle と SnapManager for SAP のどちらも使用している環境では、製品ごとに異なるリポジトリ（異なる Oracle データベースユーザ）を使用する必要があります。同じデータベースまたは異なるデータベース内にある異なるリポジトリを使用すると、製品ごとに個別にアップグレードを実行できるため、柔軟性が向上します。
