---
permalink: windows/concept-backup-recovery.html 
sidebar: sidebar 
keywords: snapmanager, perform, restore, recover, operation, backup 
summary: SnapManager では、リストア処理とリカバリ処理を同時に実行する必要があります。リストア処理のあとに SnapManager のリカバリ処理を実行することはできません。 
---
= バックアップリカバリ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager では、リストア処理とリカバリ処理を同時に実行する必要があります。リストア処理のあとに SnapManager のリカバリ処理を実行することはできません。

SnapManager 3.2 以前では、 SnapManager を使用してバックアップをリストアおよびリカバリするか、 SnapManager を使用してバックアップをリストアし、 Oracle Recovery Manager （ RMAN ）などの別のツールを使用してデータをリカバリできます。SnapManager はバックアップを RMAN に登録できるため、 RMAN を使用して、ブロックなどのより細かい単位でデータベースをリストアおよびリカバリできます。この統合では、 Snapshot コピーの速度とスペース効率という利点に加え、 RMAN を使用したリストアをきめ細かく制御することができます。


NOTE: データベースを使用する前に、データベースをリカバリする必要があります。データベースのリカバリには、任意のツールまたはスクリプトを使用できます。

SnapManager 3.2 for SAPから、SnapManager では、アーカイブ・ログ・バックアップを使用した、データベース・バックアップの自動リストアが可能になりました。アーカイブログのバックアップを外部の場所で利用できる場合でも、 SnapManager は外部の場所からアーカイブログのバックアップを使用して、データベースのバックアップをリストアします。

新しいデータファイルがデータベースに追加された場合は、新しいバックアップをすぐに作成することを推奨します。また、新しいデータファイルが追加される前に作成されたバックアップをリストアし、新しいデータファイルが追加されたあとの状態にリカバリしようとすると、データファイルを作成できないため、 Oracle の自動リカバリプロセスが失敗する場合があります。バックアップ後に追加されたデータ・ファイルをリカバリする手順については、 Oracle のマニュアルを参照してください。
