---
permalink: windows/concept-configuring-e-mail-notification.html 
sidebar: sidebar 
keywords: snapmanager, enable, email, notification, completion, status, profile-executed, database, operation, profile, execute, generate, status, configure 
summary: SnapManager を使用すると、プロファイルで実行されたデータベース処理の完了ステータスに関する E メール通知を受け取ることができます。SnapManager によって E メールが生成され、データベース処理の完了ステータスに基づいて適切な処理を実行できるようになります。E メール通知の設定はオプションパラメータです。 
---
= E メール通知の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager を使用すると、プロファイルで実行されたデータベース処理の完了ステータスに関する E メール通知を受け取ることができます。SnapManager によって E メールが生成され、データベース処理の完了ステータスに基づいて適切な処理を実行できるようになります。E メール通知の設定はオプションパラメータです。

個々のプロファイルの E メール通知をプロファイル通知として設定したり、リポジトリデータベース上の複数のプロファイルについてサマリー通知として設定したりできます。

* プロファイル通知 *

個々のプロファイルについて、成功したデータベース処理と失敗したデータベース処理の両方を記載した E メールを受信することができます。


NOTE: デフォルトでは、失敗したデータベース処理については E メール通知が有効になっています。

* サマリー通知 *

概要通知では、複数のプロファイルを使用して実行されたデータベース処理に関する概要 E メールを受信できます。毎時、毎日、毎週、または毎月の通知を有効にできます。


NOTE: SnapManager 3.3 以降では、通知の送信に必要なホストサーバを指定した場合にのみ、サマリー通知が送信されます。3.3 より前のバージョンから SnapManager をアップグレードした場合、通知概要設定でホストサーバを指定していないと通知が送信されないことがあります。


NOTE: Real Application Clusters （ RAC ）環境にあるデータベースの 1 つのノードにリポジトリを作成して概要通知を有効にした場合、あとで同じリポジトリをデータベースの別のノードに追加すると、概要通知 E メールが 2 回送信されます。

プロファイルレベルの通知またはサマリー通知のいずれかを一度に使用できます。

SnapManager を使用すると、プロファイルで実行された次のデータベース処理に関する E メール通知を有効にできます。

* プライマリストレージにバックアップを作成します
* バックアップをリストアする
* クローンを作成します
* バックアップを検証します


E メール通知を有効にしてプロファイルを作成または更新したら、無効にすることができます。E メール通知を無効にすると、プロファイルで実行されたこれらのデータベース処理に対する E メールアラートが受信されなくなります。

受信した E メールには、次の詳細が記載されています。

* バックアップ、リストア、クローンなど、データベース処理の名前
* データベース処理に使用するプロファイル名
* ホスト・サーバの名前
* データベースのシステム ID
* データベース処理の開始時刻と終了時刻
* データベース処理のステータス
* エラーメッセージ（存在する場合
* 警告メッセージ（存在する場合）


次の項目を設定できます。

* リポジトリのメールサーバ
* 新しいプロファイルの E メール通知です
* 既存のプロファイルの E メール通知
* リポジトリ内の複数のプロファイルに関する電子メール通知のサマリー



NOTE: E メール通知は、コマンドラインインターフェイス（ CLI ）とグラフィカルユーザインターフェイス（ GUI ）の両方から設定できます。
