---
permalink: windows/concept-partial-online-backups.html 
sidebar: sidebar 
keywords: full, backup, perform, partial, tablespace, database, snapmanager, snapshot, copy, volume, online 
summary: フル・バックアップの代わりに、データベースの表領域のパーシャル・バックアップを実行するように選択できます。SnapManager はフル・バックアップ用にボリュームの Snapshot コピーを作成しますが、 SnapManager は、指定された表領域ごとに、パーシャル・バックアップ用の Snapshot コピーを作成します。 
---
= パーシャル・オンライン・バックアップ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
フル・バックアップの代わりに、データベースの表領域のパーシャル・バックアップを実行するように選択できます。SnapManager がフルバックアップ用にボリュームの Snapshot コピーを作成する間、 SnapManager は、指定された各表領域の Snapshot コピーを _PARTIALL_backups に対して作成します。

Oracle でバックアップモードにできる最小単位は表領域レベルであるため、表領域にデータ・ファイルを指定していても、 SnapManager では表領域レベルのバックアップを処理します。

パーシャル・バックアップを使用すると、各表領域がバックアップ・モードになるため、フル・バックアップに比べて短時間で済みます。オンラインバックアップでは、データベースを常にユーザが使用できますが、データベースはより多くの処理を実行する必要があり、ホストはより多くの物理 I/O を実行する必要がありますまた、ボリューム全体ではなく、指定された各表領域の Snapshot コピー、または指定されたデータファイルを含む各表領域の Snapshot コピーが作成されるため、 SnapManager で作成される Snapshot コピー数が増加します。

SnapManager は、特定の表領域またはデータ・ファイルの Snapshot コピーを作成します。パーシャル・バックアップのアルゴリズムはループ方式で、 SnapManager では、指定されたすべての表領域またはデータ・ファイルの Snapshot コピーが完了するまで、同じ処理が繰り返されます。


NOTE: パーシャル・バックアップを実行できますが、データベース全体のフル・バックアップを常に実行することを推奨します。

パーシャル・バックアップを実行すると、 SnapManager は次の処理を実行します。

.手順
. データ・ファイルを含む表領域をバックアップ・モードにします。
. 表領域が使用しているすべてのボリュームについて、 1 つの Snapshot コピーを作成する
. 表領域のバックアップ・モードを終了する
. すべての表領域またはファイルで Snapshot コピーの作成が完了するまで、この処理が繰り返される
. ログ・スイッチを強制的に実行し、ログ・ファイルをアーカイブします。
. バックアップ制御ファイルを生成します。
. ログファイルとバックアップ制御ファイルの Snapshot コピーを作成します。

