---
permalink: windows/concept-restoring-database-backup.html 
sidebar: sidebar 
keywords: snapmanager, sap, enable, restore, database, snapshot, copy, backup, mean-time-to-recovery, mttrm restore 
summary: SnapManager for SAPでは、データベースをSnapshotコピーが作成されたときの状態にリストアできます。バックアップはより頻繁に作成されるため、適用する必要があるログの数が少なくなり、データベースの平均リカバリ時間（ MTTR ）が短縮されます。 
---
= データベースバックアップのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager for SAPでは、データベースをSnapshotコピーが作成されたときの状態にリストアできます。バックアップはより頻繁に作成されるため、適用する必要があるログの数が少なくなり、データベースの平均リカバリ時間（ MTTR ）が短縮されます。

データベース内のデータのリストアとリカバリに関連して実行できるタスクの一部を次に示します。

* ファイルベースのリストアを実行する
* バックアップ全体またはバックアップの一部をリストアできます。
+
一部をリストアする場合は、表領域またはデータ・ファイルのグループを指定します。制御ファイルは、データとともにリストアすることも、制御ファイル自体だけをリストアすることもできます。

* 特定の時点またはデータベースにコミットされた最後のトランザクションを格納している使用可能なすべてのログに基づいてデータをリカバリします。
+
特定の瞬間を指定する場合は、 Oracle System Change Number （ SCN ）または日付と時刻（ yyyy-mm-dd ： hh ： mm ： ss ）で指定します。SnapManager は 24 時間方式のクロックを使用します。

* プライマリストレージ上のバックアップからのリストア（ローカルバックアップ）
* SnapManager を使用してバックアップをリストアおよびリカバリするか、 SnapManager を使用してバックアップをリストアし、 Recovery Manager （ RMAN ）などの別のツールを使用してデータをリカバリします。
* 別の場所からバックアップをリストアする。


詳細については、を参照してください。

SnapManager 3.0 以降のバージョンを使用して、以前のバージョンの SnapManager で作成されたバックアップをリストアできます。

管理者は、 SnapManager のグラフィカルユーザインターフェイス（ GUI ）またはコマンドラインインターフェイス（ CLI ）を使用して、リストア処理またはリカバリ処理を実行できます。
