---
permalink: windows/reference-the-smosmsapbackup-restore-command.html 
sidebar: sidebar 
keywords: run, backup, restore, command, database, portion, information, smsap 
summary: backup restore コマンドを実行してデータベースまたはデータベースの一部のバックアップをリストアし、必要に応じてデータベース情報をリカバリすることができます。 
---
= SMSAPのbackup restoreコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「backup restore」コマンドを実行してデータベースまたはデータベースの一部のバックアップをリストアし、オプションでデータベース情報をリカバリすることができます。



== 構文

[listing]
----

smsap backup restore
-profile profile_name
[-label label | -id id]
[-files files [files...] |
-tablespaces tablespaces [tablespaces...]] |
-complete | -controlfiles]
[-recover {-alllogs | -nologs | -until until} [-using-backup-controlfile]]
[-restorespec restorespec | ]]
[-preview]

[-recover-from-location path1 [, path2]]
[-taskspec taskspec]
[-dump]
[-force]
[-quiet | -verbose]
----


== パラメータ

* *`-profile_name_`*
+
リストアするデータベースを指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* *`-label_name_`*
+
指定したラベルを持つバックアップをリストアします。

* *`-id_GUID_`*
+
指定した GUID を持つバックアップをリストアします。GUID はバックアップを作成するときに SnapManager によって生成されます。「SMSAP backup list」コマンドを使用して、各バックアップのGUIDを表示できます。

* *`すべてのファイルまたは指定されたファイルを選択してください*
+
必要に応じて、次のいずれかのオプションを使用できます。

+
** -complete:バックアップ内のすべてのデータファイルを復元します
** `-tableespaceslist`：指定した表領域だけをバックアップからリストアします。
+
リスト内で名前を区切るには、スペースを使用する必要があります。

** `-fileslist`：指定したデータファイルだけをバックアップからリストアします。
+
リスト内で名前を区切るには、スペースを使用する必要があります。データベースが稼働している場合、 SnapManager はファイルを含む表領域がオフラインであることを確認します。



* *`controlcontrols`*
+
制御ファイルをリストアします。SnapManager では、バックアップ内のデータ・ファイルと制御ファイルを一度にリストアできます。controlcontrolcontrolfilesオプションは'-scomplete '-tablespaces 'および-filesなどのリストア範囲パラメータから独立しています

* *`-recover`*
+
リストア後にデータベースをリカバリします。また、次のいずれかのオプションを使用して、 SnapManager でデータベースのリカバリ・ポイントを指定する必要があります。

+
** -nologs:データベースをバックアップ時刻までリカバリし'ログを適用しません
+
このパラメータは、オンラインバックアップまたはオフラインバックアップに使用できます。

** -alllogs:データベースを最後のトランザクションまたはコミットまでリカバリし'必要なすべてのログを適用します
** `-until date`:指定された日時までデータベースをリカバリします
+
年-月-日：時：分：秒（_yyyy-mm-dd：hh：mm：ss_）の形式で指定する必要があります。データベースの設定に応じて、 12 時間形式または 24 時間形式のどちらかを使用してください。

** `-until scn `:指定したシステム変更番号(scn)に達するまで'データファイルをロールして転送します
** `-using-backup-controlfile：バックアップ制御ファイルを使用してデータベースをリカバリします。


* *-restorespec`*
+
元の各 Snapshot コピーがアクティブファイルシステムにマッピングされているため、データをアクティブファイルシステムにリストアし、指定したデータからリストアすることができます。オプションを指定しない場合、 SnapManager はプライマリストレージ上の Snapshot コピーからデータをリストアします。次のいずれかのオプションを指定できます。

+
** `-restorespec`：リストアするデータとリストア形式を指定します。


* *`-プレビュー*
+
次の情報を表示します。

+
** 各ファイルのリストアに使用するリストアメカニズム（ストレージ側のファイルシステムのリストア、ストレージ側のファイルのリストア、またはホスト側のファイルコピーのリストア
** 各ファイルのリストアに'より効率的なメカニズムが使用されなかった理由-previewオプションを使用している場合'-verboseオプションを指定すると'次のことが必要になります
** 「-force」オプションは、コマンドには影響しません。
** -recoverオプションは'コマンドには影響しませんリストア処理をプレビューするには、データベースをマウントする必要があります。リストア計画をプレビューする際に、データベースが現在マウントされていない場合は、 SnapManager によってデータベースがマウントされます。データベースをマウントできない場合、コマンドは失敗し、 SnapManager はデータベースを元の状態に戻します。


+
「-preview」オプションを使用すると、最大20個のファイルが表示されます。「SMSAP_CONFIG FILE」に表示するファイルの最大数を設定できます。

* *`-recovery-from-location`*
+
アーカイブログファイルの外部アーカイブログの場所を指定します。SnapManager は外部の場所からアーカイブログファイルを取得し、リカバリプロセスに使用します。

* *`-taskspec`*
+
リストア処理の前処理アクティビティまたは後処理アクティビティのタスク仕様 XML ファイルを指定します。タスク仕様 XML ファイルの完全なパスを指定する必要があります。

* *`-dump`*
+
リストア処理後にダンプファイルを収集するように指定します。

* *`-force *
+
必要に応じて、データベースの状態を現在の状態よりも低い状態に変更します。

+
デフォルトでは、 SnapManager は処理中にデータベースを高いレベルの状態に変更できます。SnapManager でデータベースを高いレベルの状態に変更する場合、このオプションは必要ありません。

* *`-quiet `*
+
コンソールにエラーメッセージのみを表示します。デフォルト設定では、エラーおよび警告メッセージが表示されます。

* *`-verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。このオプションを使用すると、より効率的なリストアプロセスでファイルをリストアできなかった理由を確認できます。





== 例

次に、データベースおよび制御ファイルをリストアする例を示します。

[listing]
----
smsap backup restore -profile SALES1 -label full_backup_sales_May
-complete -controlfiles -force
----