---
permalink: windows/reference-troubleshooting-clone-issues.html 
sidebar: sidebar 
keywords: information, clone, operation, resolve, troubleshoot, issue 
summary: ここでは、クローニング処理中に発生する可能性がある情報と、その解決方法について説明します。 
---
= クローニングの問題のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ここでは、クローニング処理中に発生する可能性がある情報と、その解決方法について説明します。

|===
| 現象 | 説明 | 回避策 


 a| 
アーカイブ先が「use_DB_RECOVERY_FILE_dest」に設定されている場合、クローン処理は失敗します。
 a| 
アーカイブ先が Use_DB_RECOVERY_FILE_dest を参照している場合、 Flash Recovery Area （ FRA ）によってアーカイブログがアクティブに管理されます。SnapManager は、クローンまたはリストア処理中に FRA の場所を使用しないため、処理が失敗します。
 a| 
FRA の場所ではなく、アーカイブ先を実際のアーカイブログの場所に変更します。



 a| 
クローン処理は失敗し、「Cannot perform operation: Clone Create」というエラーメッセージが表示されます。Root 原因： Oracle-00001 ： SQL の実行中にエラーが発生しました： [ALTER DATABASE OPEN RESETLOGS;]コマンドが返されました:ORA-01195:ファイル1のオンライン・バックアップでは'整合性を保つために'より多くのリカバリが必要です
 a| 
この問題は、 Oracle リスナーがデータベースに接続できない場合に発生します。
 a| 
SnapManager GUI を使用してバックアップをクローニングする場合は、次の操作を実行します。

. リポジトリツリーで、 * リポジトリ * > * ホスト * > * プロファイル * をクリックして、バックアップを表示します。
. クローニングするバックアップを右クリックし、 * Clone * を選択します。
. Clone Initialization ページで ' 必須値を入力し ' クローン仕様方式を選択します
. Clone Specification ページで '* Parameters * を選択します
. [*パラメーター*（* Parameter *）]タブをクリックする。
. [*パラメータ名*]フィールドに'local_slistener]という名前を入力し'*OK*をクリックします
. local_listener 行の * デフォルトのオーバーライド * チェックボックスをオンにします。
. いずれかのパラメータをクリックしてから'local_listenerパラメータをダブルクリックし'次の値を入力します`(address=(protocol=tcp)(host=<Your_host_name>)(port=<port#>)```
. [ ファイルに保存（ Save to File ） ] をクリックします。
. 「 * 次へ」をクリックして、クローン作成ウィザードを続行します。


CLI を使用してバックアップをクローニングする場合は、クローン仕様ファイルの * <parameters> * タグに次の情報を含める必要があります。

[listing]
----

<parameters>
  <parameter>
  <name>local_listener</name>
  <value>(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=<hostname>)(PORT=<port#>)))</value>
  </parameter>
</parameters>
----


 a| 
使用しているマウント・ポイントがすでに使用中であることを示すエラー・メッセージが表示されて、クローン処理に失敗します。
 a| 
SnapManager では、既存のマウント・ポイントにクローンをマウントすることはできません。そのため、クローンが不完全なため、マウント・ポイントが削除されませんでした。
 a| 
クローンが使用する別のマウントポイントを指定するか、問題のあるマウントポイントをアンマウントします。



 a| 
データ・ファイルに .dbf 拡張子が含まれていないことを示すエラー・メッセージが表示されて、クローン処理に失敗します。
 a| 
Oracle NID ユーティリティのバージョンによっては、 .dbf 拡張子を使用していないデータ・ファイルが処理されないことがあります。
 a| 
* データ・ファイルの名前を変更し、 .dbf 拡張子を付加します。
* バックアップ処理を繰り返します。
* 新しいバックアップをクローニングする。




 a| 
要件を満たしていないためにクローニング処理が失敗する。
 a| 
クローンを作成しようとしていますが、いくつかの前提条件が満たされていません。
 a| 
前提条件を満たすための「クローンの作成」の説明に従ってください。



 a| 
SnapManager for SAPで、Oracle 10gR2（10.2.0.5）の物理Oracle Data Guardスタンバイデータベースのクローニングに失敗した場合。
 a| 
SnapManager for SAPでは、Oracle Data Guardサービスを使用して作成されたOracle 10gR2（10.2.0.5）の物理スタンバイデータベースのオフラインバックアップを実行している場合、管理対象リカバリモードを無効にすることはできません。この問題により、オフライン・バックアップには整合性がありません。SnapManager for SAPでオフライン・バックアップのクローニングを実行しようとしても、クローン・データベースに対してはリカバリも実行されません。バックアップは一貫性がないため、クローンデータベースのリカバリが必要になるため、SAPでクローンを正常に作成できません。
 a| 
Oracle データベースを Oracle 11gR1 （ 11.1.0.7 パッチ）にアップグレードします。

|===