---
permalink: windows/reference-the-smosmsap-schedule-create-command.html 
sidebar: sidebar 
keywords: schedule, create, command, backup, smsap 
summary: schedule create コマンドを使用して、特定の時間にバックアップを作成するようにスケジュールを設定できます。 
---
= SMSAPのschedule createコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップを特定の時刻に作成するようにスケジュールを設定するには'schedule createコマンドを使用します



== 構文

[listing]
----

smsap schedule create
-profile profile_name
[-full{-auto | -online | -offline}
[-retain -hourly | -daily | -weekly | -monthly | -unlimited]
[-verify]] |
[-data [[-files files [files]] |
[-tablespaces tablespaces [tablespaces]] {-auto | -online | -offline}
[-retain -hourly | -daily | -weekly | -monthly | -unlimited]
[-verify]] |
[-archivelogs]}
[-label label]
[-comment comment]

[-backup-dest path1 [ , path2]]
[-exclude-dest path1 [ , path2]]
[-prunelogs {-all | -until-scn until-scn | -until -date  yyyy-MM-dd:HH:mm:ss] | -before {-months | -days | -weeks | -hours}}
-prune-dest prune_dest1,[prune_dest2]]
-schedule-name schedule_name
[-schedule-comment schedule_comment]
-interval {-hourly | -daily | -weekly | -monthly | -onetimeonly}
-cronstring cron_string
-start-time {start_time <yyyy-MM-dd HH:mm>}
-runasuser runasuser
[-taskspec taskspec]
-force
[-quiet | -verbose]
----


== パラメータ

* *`-profile_name_`*
+
バックアップのスケジュールを設定するデータベースに関連するプロファイルの名前を指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* *`-autoオプション*
+
データベースがマウント済み状態またはオフライン状態の場合、 SnapManager はオフラインバックアップを実行します。データベースが OPEN または ONLINE 状態の場合、 SnapManager はオンライン・バックアップを実行します。--offline]オプションを指定して--forceオプションを使用した場合、SnapManager はデータベースが現在オンラインであってもオフライン・バックアップを強制します。

* *`-オンラインオプション*
+
オンライン・データベース・バックアップを指定します。

* *`-offlineオプション*
+
データベースがシャットダウン状態のときのオフラインバックアップを指定します。データベースが OPEN または MOUNTED の場合には、バックアップは失敗します。「-force」オプションを使用すると、SnapManager はオフライン・バックアップのためにデータベースをシャットダウンするためにデータベースの状態を変更しようとします。

* *`-full'*
+
データベース全体がバックアップされます。これには、すべてのデータ、アーカイブログ、および制御ファイルが含まれます。アーカイブ REDO ログおよび制御ファイルは、実行するバックアップのタイプに関係なくバックアップされます。データベースの一部のみをバックアップする場合は'-files'オプションまたは--tablespacesオプションを使用します

* *`-files_list_`*
+
指定されたデータファイル、およびアーカイブされたログファイルと制御ファイルのみをバックアップします。ファイル名のリストはスペースで区切ります。データベースが OPEN 状態の場合、 SnapManager は該当する表領域がオンライン・バックアップ・モードになっているかどうかを検証します。

* *`-tablespaces _ tablespaces _`*
+
指定されたデータベースの表領域、およびアーカイブされたログファイルと制御ファイルのみをバックアップします。表領域名はスペースで区切ります。データベースが OPEN 状態の場合、 SnapManager は該当する表領域がオンライン・バックアップ・モードになっているかどうかを検証します。

* *`-label_name_`*
+
このバックアップのオプション名を指定します。この名前はプロファイル内で一意である必要があります。名前には、アルファベット、数字、アンダースコア（ _ ）、およびハイフン（ - ）を使用できます。1 文字目をハイフンにすることはできません。

+
ラベルを指定しない場合、 SnapManager は scope_type_date 形式でデフォルトのラベルを作成します。

+
** 範囲は F でフル・バックアップを示し 'P ではパーシャル・バックアップを示します
** type は、オフライン（コールド）バックアップを示す C 、オンライン（ホット）バックアップを示す H 、または自動バックアップを示す A です（例： P_A_20081010060037IST ）。
** date は、バックアップを作成した年月日、および時刻です。
+
SnapManager は 24 時間方式のクロックを使用します。



+
たとえば、 2007 年 1 月 16 日の午後 5 時 45 分 16 分にデータベースをオフラインにしてフルバックアップを実行したとします東部標準時、 SnapManager はラベル F_C_20070116174516EST を作成します。

* *`-comment_string_`*
+
このバックアップに関するコメントを指定します。文字列は一重引用符（ ' ）で囲みます。

+

NOTE: 一部のシェルでは、引用符が除去されます。ご使用のシェルに当てはまる場合は、引用符にバックスラッシュ（ \ ）を含める必要があります。たとえば、「 \ 」と入力する必要があるかもしれません。これはコメントです。

* *`-verifyオプション*
+
Oracle の dbv ユーティリティを実行して、バックアップ内のファイルが破損していないかどうかが検証されます。

+

NOTE: -verifyオプションを指定した場合、検証処理が完了するまで、バックアップ処理は完了しません。

* *`-forceオプション*
+
データベースが正しい状態でない場合に、状態を強制的に変更します。たとえば、指定したバックアップのタイプおよびデータベースの状態に基づいて、 SnapManager によってデータベースの状態がオンラインからオフラインに変更されることがあります。

+
** ローカル・インスタンスがSHUTDOWN状態で'少なくとも1つのインスタンスがOPENの場合に'-forceオプションを使用して'ローカル・インスタンスをMOUNTEDに変更できます
** インスタンスが開いていない場合は'-forceオプションを使用して'ローカル・インスタンスをopenに変更できます


* *`-retain {-hourly|-daily|-weekly|-monthly|-unlimited }`*
+
バックアップを時間単位、日単位、週単位、月単位、または無制限単位で保持するかどうかを指定します。-retainオプションが指定されていない場合'保存クラスはデフォルトで-hourlyに設定されますバックアップを無期限に保持するには、「無制限」オプションを使用します。-unlimitedオプションを使用すると'バックアップは保持ポリシーによる削除の対象外になります

* *`-archivelogs`*
+
アーカイブログバックアップの作成を指定します。

* *`-backup-dest path1_,[,[_path2_]`*
+
アーカイブログバックアップのアーカイブログのデスティネーションを指定します。

* *`-exclude-dest_path1_,[,[_path2_]`*
+
バックアップから除外するアーカイブログの送信先を指定します。

* *`-prunelogs {-all|-until -scnuntil -scnuntil -date_yyyy-mm -dd：HH：MM:ss_|-before {-months |-days |-weeks |-hours｝`*
+
バックアップの作成時に指定したオプションに基づいて、アーカイブログデスティネーションからアーカイブログファイルを削除するかどうかを指定します。-allオプションを指定すると'アーカイブ・ログの保存先からすべてのアーカイブ・ログ・ファイルが削除されます--until scn’オプションを指定すると、指定したシステム変更番号（SCN）までアーカイブ・ログ・ファイルが削除されます。--until dateオプションは'指定した期間までアーカイブ・ログ・ファイルを削除します-beforeオプションを指定すると'指定した期間（日'月'週'時間）前のアーカイブ・ログ・ファイルが削除されます

* *`-schedule - name_schedule_name_`*
+
スケジュールに指定する名前を指定します。

* *`-schedule - COMMENT_schedule_comment_`*
+
バックアップのスケジュール設定に関するコメントを指定します。

* *`-interval {-hourly|-daily|-weekly|-monthly|-onetimeonly}`*
+
バックアップを作成する間隔を指定します。バックアップのスケジュールは、毎時、毎日、毎週、毎月、または 1 回のみ設定できます。

* *`cronstring_cron_string_`*
+
cronstring を使用してバックアップのスケジュールを指定します。CronTrigger のインスタンスの構成には cron 式が使用されます。cron 式は、次のサブ式で構成される文字列です。

+
** 1 は秒を表します。
** 2 は分を表します。
** 3 は時間を表します。
** 4 は 1 か月の 1 日を表します。
** 5 は月を表します。
** 6 は 1 週間のうちの 1 日を表します。
** 7 は年を表します（オプション）。


* *`-start-time_yyyy-mm-dd HH:mm_`*
+
スケジュールされた処理の開始時刻を指定します。スケジュールの開始時刻は、 yyyy-mm-dd HH ： MM 形式で指定します。

* *`-runAsUser_runAsUser_`*
+
バックアップのスケジュール設定時に、スケジュールされたバックアップ処理のユーザ（ root ユーザまたは Oracle ユーザ）を変更するように指定します。

* *`taskspec_taskspec_`*
+
バックアップ処理の前処理アクティビティまたは後処理アクティビティに使用できるタスク仕様 XML ファイルを指定します。XMLファイルの完全なパスは'-taskspec'オプションとともに指定する必要があります

* *`-quiet `*
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* *`-verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。


