---
permalink: windows/reference-the-smosmsapcredential-delete-command.html 
sidebar: sidebar 
keywords: command, delete, user, credential, particular, secure, resource, smsap 
summary: このコマンドは、特定のセキュアリソースのユーザクレデンシャルを削除します。 
---
= SMSAPのcredential deleteコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このコマンドは、特定のセキュアリソースのユーザクレデンシャルを削除します。



== 構文

[listing]
----

smsap credential delete
[-host -name host_name
-username username] |
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port] |
[-profile
-name profile_name]
[-quiet | -verbose]
----


== パラメータ

* *`-host_hostname_`*
+
SnapManager が実行されているホストサーバの名前を指定します。

+
-hostパラメータには'次のオプションがあります

+
** `-name host_name`：パスワードを削除するホストの名前を指定します。
** `-username USERNAME`：ホスト上のユーザ名を指定します。


* *`repository -dbdbname*
+
プロファイルが格納されたデータベースの名前を指定します。グローバル名または SID を使用します。

+
-repositoryパラメータには'次のオプションが含まれます

+
** `-dbnamerepo_service_name :プロファイルを格納するデータベースの名前を指定しますグローバル名または SID を使用します。
** `-hostrepo_host`:リポジトリ・データベースが稼働するホスト・サーバの名前またはIPアドレスを指定します
** `-login-username repo_userName`：リポジトリが格納されたデータベースにアクセスするために必要なユーザ名を指定します。
** `-port repo_port`：リポジトリが格納されたデータベースへのアクセスに使用するTCPポート番号を指定します。


* *`-profile-name_profile_name_`*
+
データベースに関連付けられたプロファイルを指定します。

+
「-profile」パラメータには、次のオプションが含まれています。

+
** `-name_profilename_`:パスワードを削除するプロファイルの名前を指定します


* *`-quiet `*
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* *`-verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== コマンドの例

次に、プロファイルのクレデンシャルを削除する例を示します。

[listing]
----
smsap credential delete -profile -name user1 -verbose
----
[listing]
----
SMSAP-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
次に、リポジトリのクレデンシャルを削除する例を示します。

[listing]
----
smsap credential delete -repository -dbname SMSAPREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMSAP-20023 [INFO ]: Deleted repository credentials for "user1@SMSAPREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
次に、ホストのクレデンシャルを削除する例を示します。

[listing]
----
smsap credential delete -host -name Host2
----
[listing]
----
SMSAP-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----