---
permalink: windows/reference-the-smosmsap-history-set-command.html 
sidebar: sidebar 
keywords: run, history, set, command, configure, operation, smsap 
summary: history set コマンドを実行すると、履歴を表示する操作を設定できます。 
---
= SMSAPのhistory setコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
履歴を表示する操作を設定するには'history setコマンドを実行します



== 構文

[listing]
----

smsap history set
-profile {-name profile_name [profile_name1, profile_name2] | -all
-repository
-login [password repo_password]
-username repo_username
-host repo_host
-dbname repo_dbname
-port repo_port}
-operation {-operations operation_name [operation_name1, operation_name2] | -all}
-retain
{-count retain_count | -daily daily_count | -monthly monthly_count | -weekly weekly_count}
[-quiet | -verbose]
----


== パラメータ

* *`-profile_`*
+
プロファイルの名前を指定します。名前は 30 文字以内で指定し、ホスト内で一意である必要があります。

* *`-repository`*
+
プロファイルが格納されるデータベースの詳細を指定します。

* *`-dbname_repo_dbname_`*
+
プロファイルが格納されたデータベースの名前を指定します。グローバル名またはシステム ID を使用できます。

* *`-host_repo_host_`*
+
リポジトリ・データベースが置かれているホストの名前または IP アドレスを指定します。

* *`-login`*
+
リポジトリ・ログインの詳細を指定します。

* *`-username_repo_username_`*
+
リポジトリ・データベースへのアクセスに必要なユーザ名を指定します。

* *`-port_repo_port_`*
+
リポジトリデータベースへのアクセスに使用する TCP （ Transmission Control Protocol ）ポート番号を指定します。

* *`-operation {-operation_operation_name_[operation_name1、operation_name2]|-all '*
+
履歴を設定する SnapManager 操作を指定します。

* *`-retain {-countre_tive_count|-dailydaily_count|-monthly -weeklyweeklyweekly_count}*
+
バックアップの作成、バックアップの検証、リストアとリカバリ、およびクローン作成の各処理の保持クラスを指定します。保持クラスは、処理数、日数、週数、または月に基づいて設定されます。

* *`-quiet `*
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* *`-verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== コマンドの例

次の例は、バックアップ処理に関する情報を表示します。

[listing]
----
smsap history set -profile -name PROFILE1 -operation -operations backup -retain -daily 6
-verbose
----