---
permalink: windows/reference-the-smosmsapprofile-update-command.html 
sidebar: sidebar 
keywords: run, profile, update, command, information, exist, smsap 
summary: profile update コマンドを実行して、既存のプロファイルの情報を更新できます。 
---
= SMSAPのprofile updateコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「profile update」コマンドを実行すると、既存のプロファイルの情報を更新できます。



== 構文

[listing]
----

smsap profile update
-profile profile
[-new-profile new_profile_name]
[-profile-password profile_password]
[-database
-dbname db_dbname
-host db_host
[-sid db_sid]
[-login
[-username db_username -password db_password -port db_port]
]
[{-rman  {-controlfile | {{-login
-username  rman_username
-password  rman_password }
[-tnsname  tnsname]}}} |
-remove-rman]


[-retain
[-hourly [-count n] [-duration m]]
[-daily [-count n] [-duration m]]
[-weekly [-count n] [-duration m]]
[-monthly [-count n] [-duration m]]]]
-comment comment
-snapname-patternpattern
[]
[-summary-notification]
[-notification
[-success
-email email_address1,email_address2
-subject subject_pattern]
[-failure
-email email_address1,email_address2
-subject subject_pattern]
[-separate-archivelog-backups
-retain-archivelog-backups
-hours  hours |
-days days |
-weeks weeks |
-months months
[]
[-include-with-online-backups | -no-include-with-online-backups]]
[-dump]
[-quiet | -verbose]
----


== パラメータ

* *`-profile_`*
+
プロファイルの名前を指定します。この名前には 30 文字まで使用でき、ホスト内で一意である必要があります。

* *`-profile-password_profile_password_`*
+
プロファイルのパスワードを指定します。

* *`-new-profile_new_profile_name_`*
+
プロファイルに指定できる新しい名前を指定します。

* *`-bたべ ーす`*
+
プロファイルに記述されるデータベースの詳細を指定します。このデータベースに対してバックアップ、リストアなどが実行されます。

* *`-dbname_db_dbname_`*
+
プロファイルに記述されるデータベースの名前を指定します。グローバル名またはシステム ID を使用できます。

* *`-host_db_host_`*
+
データベースが稼働しているホスト・コンピュータの名前または IP アドレスを指定します。

* *`-sid_db_sid_`*
+
プロファイルに記述されるデータベースのシステム識別子を指定します。デフォルトでは、 SnapManager はデータベース名をシステム識別子として使用します。システム識別子がデータベース名と異なる場合は'-sid`オプションを使用して指定する必要があります

* *`-login`*
+
リポジトリ・ログインの詳細を指定します。

* *`-username_repo_username_`*
+
リポジトリ・データベースへのアクセスに必要なユーザ名を指定します。

* *`-port_repo_port_`*
+
リポジトリ・データベースへのアクセスに必要な TCP ポート番号を指定します。

* *`-bたべ ーす`*
+
プロファイルに記述されるデータベースの詳細を指定します。このデータベースに対してバックアップ、リストア、またはクローニングが実行されます。

* *`-dbname_db_dbname_`*
+
プロファイルに記述されるデータベースの名前を指定します。グローバル名またはシステム ID を使用できます。

* *`-host_db_host_`*
+
データベースが稼働しているホスト・コンピュータの名前または IP アドレスを指定します。

* *`-login`*
+
データベース・ログインの詳細を指定します。

* *`-username_db_username_`*
+
プロファイルに記述されるデータベースにアクセスするために必要なユーザ名を指定します。

* *`-password_ddb_password_`*
+
プロファイルに記述されるデータベースにアクセスするために必要なパスワードを指定します。

* *`-port_db_port_`*
+
プロファイルに記述されるデータベースへのアクセスに必要な TCP ポート番号を指定します。

* *`-retain [-hourly [-countn][-duration m]][-daily [-daily [-count n][-duration m]][-weekly [-count n][-duration n][-duration n][-duration m]][-monthly [-monthly ][-duration m]`*
+
バックアップの保持クラス（毎時、毎日、毎週、毎月）を指定します。

+
各保持クラスについて、保持数または保持期間、あるいはその両方を指定できます。期間はクラスの単位で指定します（たとえば、時間単位の場合は時間単位、日単位の場合は日単位）。たとえば、日次バックアップの保持期間として 7 のみを指定した場合、 SnapManager ではプロファイルの日次バックアップの数が制限されません（保持数が 0 であるため）。ただし、 SnapManager では、 7 日前に作成された日次バックアップが自動的に削除されます。

* *`-comment_comment_`*
+
プロファイルのコメントを指定します。

* *`-snapname -pattern_pattern_`*
+
Snapshot コピーの命名パターンを示します。すべての Snapshot コピー名に、可用性の高い処理用の HAOPS などのカスタムテキストを含めることもできます。Snapshot コピーの命名パターンは、プロファイルの作成時、またはプロファイルの作成後に変更できます。更新後のパターンは、まだ実行されていない Snapshot コピーにのみ適用されます。存在する Snapshot コピーには、前の snapname パターンが保持されます。パターンテキストでは、複数の変数を使用できます。

* *`-summary notification`*
+
既存のプロファイルでサマリー E メール通知を有効にします。

* *`-notification [-success -email_email_address1,電子メールアドレス2__ subject_subject_pattern_]`*
+
既存のプロファイルに関する E メール通知を有効にして、 SnapManager 処理が成功したときに受信者から E メールが受信されるようにします。E メールアラートの送信先となる 1 つまたは複数の E メールアドレスと、既存のプロファイルの E メール件名のパターンを入力する必要があります。

+
件名のテキストは、プロファイルの更新中に変更することも、カスタムの件名テキストを含めることもできます。更新された件名は、送信されない E メールにのみ適用されます。E メールの件名にはいくつかの変数を使用できます。

* *`-notification[-failure-email_email-mail_address1, e-mail address2_-subject_subject_pattern_]`*
+
既存のプロファイルに関する E メール通知を有効にして、 SnapManager 処理が失敗したときに受信者に E メールを送信できるようにします。E メールアラートの送信先となる 1 つまたは複数の E メールアドレスと、既存のプロファイルの E メール件名のパターンを入力する必要があります。

+
件名のテキストは、プロファイルの更新中に変更することも、カスタムの件名テキストを含めることもできます。更新された件名は、送信されない E メールにのみ適用されます。E メールの件名にはいくつかの変数を使用できます。

* *`-cseparate -archivelog -bbackups *
+
アーカイブログバックアップとデータファイルバックアップを分離します。これは、プロファイルの作成時に指定できるオプションのパラメータです。このオプションを使用してバックアップを分けたあとで、データファイルのみのバックアップまたはアーカイブログのみのバックアップを作成できます。

* *`-retain-archivelog -hours_|-days_dys_|-pwe週_|-months_months_months_`*
+
アーカイブログの保持期間（毎時、毎日、毎週、毎月）に基づいてアーカイブログのバックアップを保持するように指定します。

* *`-include-with -online-backups|-no-include-with -online-backups*
+
オンラインデータベースバックアップにアーカイブログバックアップを含めるように指定します。

+
オンラインデータベースバックアップにアーカイブログバックアップを含めないように指定します。

* *`-dump`*
+
プロファイル作成処理が成功したあとにダンプ・ファイルを収集するように指定します。

* *`-quiet `*
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* *`-verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== 例

次に、プロファイルで説明されているデータベースのログイン情報を変更し、このプロファイルに電子メール通知を設定する例を示します。

[listing]
----
smsap profile update -profile SALES1 -database -dbname SALESDB
-sid SALESDB -login -username admin2 -password d4jPe7bw -port 1521
-host server1 -profile-notification -success -e-mail Preston.Davis@org.com -subject success
Operation Id [8abc01ec0e78ec33010e78ec3b410001] succeeded.
----