---
permalink: windows/reference-the-smosmsapbackup-create-command.html 
sidebar: sidebar 
keywords: run, backup, create, command, database, storage, system, smsap 
summary: backup create コマンドを実行すると、 1 つ以上のストレージシステム上にデータベースバックアップを作成できます。 
---
= SMSAPのbackup createコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
backup createコマンドを実行して'1つ以上のストレージ・システム上にデータベース・バックアップを作成できます



== 構文


NOTE: このコマンドを実行する前に'profile createコマンドを使用してデータベース・プロファイルを作成する必要があります

[listing]
----

smsap backup create
-profile profile_name
{[-full{-auto | -online | -offline}[-retain {-hourly | -daily | -weekly | -monthly | -unlimited} [-verify]  |
[-data [[-files files [files]] |
[-tablespaces tablespaces [tablespaces]] [-label label] {-auto | -online | -offline}
[-retain {-hourly | -daily | -weekly | -monthly | -unlimited} [-verify] |
[-archivelogs [-label label]] [-comment comment]}

[-backup-dest path1 [ , path2]]
[-exclude-dest path1 [ , path2]]
[-prunelogs {-all | -until-scn until-scn | -until-date yyyy-MM-dd:HH:mm:ss] | -before {-months | -days | -weeks | -hours}}
-prune-dest prune_dest1,[prune_dest2]]
[-taskspec taskspec]
[-dump]
-force
[-quiet | -verbose]
----


== パラメータ

* *`-profile_name_`*
+
バックアップするデータベースに関連するプロファイルの名前を指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* *`-autoオプション*
+
データベースがマウント済み状態またはオフライン状態の場合、 SnapManager はオフラインバックアップを実行します。データベースが OPEN または ONLINE 状態の場合、 SnapManager はオンライン・バックアップを実行します。--offline]オプションを指定して--forceオプションを使用した場合、SnapManager はデータベースが現在オンラインであってもオフライン・バックアップを強制します。

* *`-オンラインオプション*
+
オンライン・データベース・バックアップを指定します。

+
** ローカル・インスタンスがSHUTDOWN状態で、少なくとも1つのインスタンスがOPEN状態の場合には、「-force」オプションを使用して、ローカル・インスタンスをMOUNTED状態に変更できます。
** インスタンスがOPEN状態でない場合は、「-force」オプションを使用して、ローカル・インスタンスをOPEN状態に変更できます。


* *`-offlineオプション*
+
データベースがシャットダウン状態のときに、オフラインバックアップを実行するように指定します。データベースが OPEN または MOUNTED の場合には、バックアップは失敗します。「-force」オプションを使用すると、SnapManager はオフライン・バックアップのためにデータベースをシャットダウンするためにデータベースの状態を変更しようとします。

* *`-full'*
+
データベース全体がバックアップされます。これには、すべてのデータ、アーカイブログ、および制御ファイルが含まれます。アーカイブ REDO ログおよび制御ファイルは、実行するバックアップのタイプに関係なくバックアップされます。データベースの一部のみをバックアップする場合は'-files'オプションまたは--tablespacesオプションを使用します

* *`-ddataオプション*
+
データファイルを指定します。

* *`-files_list_`*
+
指定されたデータファイル、およびアーカイブされたログファイルと制御ファイルのみをバックアップします。ファイル名のリストはスペースで区切ります。データベースが OPEN 状態の場合、 SnapManager は該当する表領域がオンライン・バックアップ・モードになっているかどうかを確認します。

* *`-tablespaces _ tablespaces _`*
+
指定されたデータベースの表領域、およびアーカイブされたログファイルと制御ファイルのみをバックアップします。表領域名はスペースで区切ります。データベースが OPEN 状態の場合、 SnapManager は該当する表領域がオンライン・バックアップ・モードになっているかどうかを確認します。

* *`-label_label_`*
+
このバックアップのオプション名を指定します。この名前はプロファイル内で一意である必要があります。名前には、アルファベット、数字、アンダースコア（ _ ）、およびハイフン（ - ）を使用できます。1 文字目をハイフンにすることはできません。ラベルを指定しない場合、 SnapManager は scope_type_date 形式でデフォルトのラベルを作成します。

+
** 範囲は F でフル・バックアップを示し 'P ではパーシャル・バックアップを示します
** type は、オフライン（コールド）バックアップを示す C 、オンライン（ホット）バックアップを示す H 、または自動バックアップを示す A です（例： P_A_20081010060037IST ）。
** date は、バックアップを作成した年月日、および時刻です。
+
SnapManager は 24 時間方式のクロックを使用します。



+
たとえば、 2007 年 1 月 16 日の午後 5 時 45 分 16 分にデータベースをオフラインにしてフルバックアップを実行したとします東部標準時、 SnapManager はラベル F_C_20070116174516EST を作成します。

* *`-comment_string_`*
+
このバックアップに関するコメントを指定します。文字列は一重引用符（ ' ）で囲みます。

+

NOTE: 一部のシェルでは、引用符が除去されます。この場合は、引用符にバックスラッシュ（ \ ）を含める必要があります。たとえば、次のように入力する必要があります。「 \ 」これはコメントです。

* *`-verifyオプション*
+
Oracle の dbv ユーティリティを実行して、バックアップ内のファイルが破損していないかどうかが検証されます。

+

NOTE: -verifyオプションを指定した場合、検証処理が完了するまで、バックアップ処理は完了しません。

* *`-forceオプション*
+
データベースが正しい状態でない場合に、状態を強制的に変更します。たとえば、指定したバックアップのタイプおよびデータベースの状態に基づいて、 SnapManager によってデータベースの状態がオンラインからオフラインに変更されることがあります。

+
** ローカル・インスタンスがSHUTDOWN状態で'少なくとも1つのインスタンスがOPEN状態の場合に'-forceオプションを使用すると'ローカル・インスタンスがMOUNTED状態に変更されます
** オープン状態になっているインスタンスがない場合は'-forceオプションを使用して'ローカル・インスタンスをオープン状態に変更します


* *`-quiet `*
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* *`-verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。

* *`-retain {-hourly|-daily|-weekly|-monthly|-unlimited }`*
+
バックアップを時間単位、日単位、週単位、月単位、または無制限単位で保持するかどうかを指定します。-retainオプションが指定されていない場合'リテンション・クラスはデフォルトの-hourlyオプションに設定されますバックアップを無期限に保持するには、「無制限」オプションを使用します。-unlimitedオプションを使用すると'バックアップは保持ポリシーによる削除の対象外になります

* *`-archivelogsオプション*
+
アーカイブログバックアップを作成します。

* *`-backup-dest path1_,[,[_path2_]`*
+
アーカイブログバックアップ用にバックアップするアーカイブログのデスティネーションを指定します。

* *`-exclude-dest_path1_,[,[_path2_]`*
+
バックアップから除外するアーカイブログの送信先を指定します。

* *`-prunelogs {-all|-until -scnuntil -scnuntil -date_yyyy-mm -dd：HH：MM:ss_|-before {-months |-days |-weeks |-hours｝`*
+
バックアップの作成時に指定したオプションに基づいて、アーカイブログデスティネーションからアーカイブログファイルを削除します。-allオプションを指定すると'アーカイブ・ログの保存先からすべてのアーカイブ・ログ・ファイルが削除されます--until scn’オプションを指定すると、指定したSystem Change Number（SCN）までアーカイブ・ログ・ファイルが削除されます。--until dateオプションは'指定した期間までアーカイブ・ログ・ファイルを削除します-beforeオプションを指定すると'指定した期間（日'月'週'時間）前のアーカイブ・ログ・ファイルが削除されます

* *`prune-dest_prune_dest1'prune_dest2_`*
+
バックアップの作成時に、アーカイブログデスティネーションからアーカイブログファイルを削除します。

* *`taskspec_taskspec_`*
+
バックアップ処理の前処理アクティビティまたは後処理アクティビティに使用できるタスク仕様 XML ファイルを指定します。XMLファイルの完全なパスは'-taskspec'オプションを指定するときに指定する必要があります

* *`-dumpオプション*
+
データベースバックアップ処理が成功したか失敗したあとにダンプファイルを収集します。





== コマンドの例

次のコマンドでは、フルオンラインバックアップを作成し、セカンダリストレージにバックアップを作成して、保持ポリシーを daily に設定します。

[listing]
----
smsap backup create -profile SALES1 -full -online
-label full_backup_sales_May -profile SALESDB -force -retain -daily
Operation Id [8abc01ec0e79356d010e793581f70001] succeeded.
----