---
permalink: windows/reference-the-smosmsapbackup-mount-command.html 
sidebar: sidebar 
keywords: run, backup, mount, command, perform, recover, operation, external, tool, smsap 
summary: 外部ツールを使用してリカバリ処理を実行するには、 backup mount コマンドを実行してバックアップをマウントします。 
---
= SMSAPのbackup mountコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
外部ツールを使用してリカバリ操作を実行するために'バックアップをマウントする場合はbackup mountコマンドを実行できます



== 構文

[listing]
----

smsap backup mount
-profile profile_name
[-label label [-data | -archivelogs] | [-id id]
[-host  host]

[-dump]
[-quiet | -verbose]
----


== パラメータ

* *`-profile_name_`*
+
マウントするバックアップに関連付けられたプロファイルを指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* *`-id_GUID_`*
+
指定した GUID を持つバックアップをマウントします。GUID はバックアップを作成するときに SnapManager によって生成されます。「SMSAP backup list」コマンドを使用して、各バックアップのGUIDを表示できます。

* *`-label_label_`*
+
指定したラベルを持つバックアップをマウントします。

* *`-data`*
+
データファイルを指定します。

* *`-archivelogs`*
+
アーカイブログファイルを指定します。

* *`-host_host_`*
+
バックアップをマウントするホストを指定します。

* *`-dump`*
+
マウント処理が成功したか失敗したあとにダンプファイルを収集します。

* *`-quiet `*
+
コンソールにエラーメッセージのみを表示します。デフォルト設定では、エラーおよび警告メッセージが表示されます。

* *`-verbose *
+
エラー、警告、および情報メッセージがコンソールに表示されます。




NOTE: このコマンドは、 Oracle Recovery Manager （ RMAN ）などの外部ツールを使用する場合にのみ使用する必要があります。「smsapbackup restore」コマンドを使用してバックアップをリストアすると、SnapManager によってバックアップのマウントが自動的に処理されます。このコマンドを実行すると、 Snapshot コピーがマウントされているパスのリストが表示されます。このリストは'-verboseオプションが指定されている場合にのみ表示されます



== 例

次に、バックアップをマウントする例を示します。

[listing]
----
smsap backup mount -profile S10_BACKUP -label full_monthly_10 -verbose
[INFO ]: SMSAP-13051: Process PID=6852
[INFO ]: SMSAP-13036: Starting operation Backup Mount on host hadley.domain.private
[INFO ]: SMSAP-13036: Starting operation Backup Mount on host hadley.domain.private
[INFO ]: SMSAP-13046: Operation GUID 8abc01573883daf0013883daf5ac0001 starting on Profile FAS_P1
[INFO ]: SD-00025: Beginning to connect filesystem(s) [I:\] from snapshot smsap_fas_p1_fasdb_d_h_2_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SD-00016: Discovering storage resources for C:\SnapManager_auto_mounts\I-2012071400592328_0.
[INFO ]: SD-00017: Finished storage discovery for C:\SnapManager_auto_mounts\I-2012071400592328_0
[INFO ]: SD-00026: Finished connecting filesystem(s) [I:\] from snapshot smsap_fas_p1_fasdb_d_h_2_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SD-00025: Beginning to connect filesystem(s) [H:\] from snapshot smsap_fas_p1_fasdb_d_h_1_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SD-00016: Discovering storage resources for C:\SnapManager_auto_mounts\H-2012071400592312_0.
[INFO ]: SD-00017: Finished storage discovery for C:\SnapManager_auto_mounts\H-2012071400592312_0.
[INFO ]: SD-00026: Finished connecting filesystem(s) [H:\] from snapshot smsap_fas_p1_fasdb_d_h_1_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SMSAP-13048: Backup Mount Operation Status: SUCCESS
[INFO ]: SMSAP-13049: Elapsed Time: 0:19:05.620
----