---
permalink: windows/task-create-profiles.html 
sidebar: sidebar 
keywords: create, profile, assign, oracle, database, policy, set, retention, count, class 
summary: プロファイルの作成時に、特定の Oracle データベースのユーザ・アカウントをプロファイルに割り当てることができます。プロファイルに保持ポリシーを設定し、各保持クラスに保持数と保持期間を設定できます。 
---
= プロファイルを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プロファイルの作成時に、特定の Oracle データベースのユーザ・アカウントをプロファイルに割り当てることができます。プロファイルに保持ポリシーを設定し、各保持クラスに保持数と保持期間を設定できます。



== このタスクについて

データベースの「-login`」、「-password」、および「-port」パラメータの値を指定しない場合、オペレーティングシステム（OS）認証モードはデフォルトのクレデンシャルを使用します。

プロファイルの作成中に、 SnapManager はリストア適格性チェックを実行し、データベースのリストアに使用できるリストアメカニズムを決定します。

SnapManager （ 3.2 以降）を使用すると、新しいプロファイルの作成時または既存のプロファイルの更新時に、アーカイブ・ログ・ファイルをデータ・ファイルから分離できます。プロファイルを使用してバックアップを分離したら、データベースのデータファイルのみのバックアップを作成するか、アーカイブログのみのバックアップを作成できます。新しいプロファイルまたは更新したプロファイルを使用して、データ・ファイルとアーカイブ・ログ・ファイルの両方を含むバックアップを作成できます。ただし、プロファイルを使用してフル・バックアップを作成したり、設定を元に戻したりすることはできません。

* フル・バックアップおよびパーシャル・バックアップを作成するためのプロファイル *

プロファイルを作成すると、データ・ファイル、制御ファイル、アーカイブ・ログ・ファイル、および指定したデータ・ファイルまたは表領域を含むデータベースのパーシャル・バックアップ、すべての制御ファイル、およびすべてのアーカイブ・ログ・ファイルを含むフル・データベース・バックアップを作成できます。SnapManager では、フル・バックアップおよびパーシャル・バックアップ用に作成したプロファイルを使用して、個別のアーカイブ・ログ・バックアップを作成することはできません。

* データファイルのみのバックアップとアーカイブログのみのバックアップを作成するためのプロファイル *

新しいプロファイルを作成するときに'-sseparate archivelog -backup'を含めて'アーカイブ・ログ・バックアップをデータ・ファイル・バックアップから切り離すことができますまた、既存のプロファイルを更新して、アーカイブログバックアップとデータファイルバックアップを分離することもできます。

新しいプロファイル・オプションを使用してアーカイブ・ログ・バックアップを分離すると、次の SnapManager 処理を実行できます。

* アーカイブログのバックアップを作成します
* アーカイブログバックアップを削除する
* アーカイブログバックアップをマウントします
* アーカイブログのバックアップを解放します


プロファイルを作成して、データ・ファイルのバックアップとアーカイブ・ログ・バックアップを分離する際に、プロファイルが作成されたデータベースにアーカイブ・ログ・ファイルが存在しない場合は、警告メッセージが表示されます。


WARNING: アーカイブされたログ・ファイルは'アクティブ・ファイルシステムに存在しません<archive log thread version>ログ・ファイルより前のアーカイブ・ログ・ファイル・バージョンは'バックアップに含まれません

このデータベースのバックアップを作成する場合でも、データベースバックアップにアーカイブログファイルを使用できません。


NOTE: プロファイルの作成中にエラーが発生した場合は、「SMSAP system dump」コマンドを使用します。プロファイルを作成したあとにエラーが発生した場合は、「SMSAP operation dump」コマンドと「SMSAP profile dump」コマンドを使用します。

.ステップ
. ユーザ名、パスワード、およびポート（Oracle認証）を指定してプロファイルを作成するには、次のコマンドを入力します。
+
`*smsSMSAP profile create -profile profile[-profile-passwordprofileprofileprofile_password]-repository -dbname -hojectpo_host-jectbox_host-portcommentrepo_username -usernamedb_username -dbname -database -dbirds_host[-siddb_address_password-durerman [-drst_address_password][-drman [-drst_address_password-password-password-atum][-drst全員[-drst全員[-drst_addressm -email-password][-drst全員[-drst_addressm -email-email-password][-drst全員[--password-password-password-password-password][-drst全員 電子メール[-drst全員[--password][--password][-drst全員[--password]-password]-password-password][-dr全般[-drst_addressm -password][--password-password][-drn [--password]-password]-passwordパターン[-drst全員 電子メール[-dr全般]サブパターン[-drst全員[-drdb [-dr

+
このコマンドの他のオプションは、次のとおりです。

+
[`-force `][`-noprompt`]

+
[`quiet `|`verbose`]

+
また、プロファイルの作成時に、データベースへのアクセス方法に応じて、他のオプションを指定することもできます。

+
|===
| 状況 | 作業 


 a| 
* データベース認証を使用してプロファイルを作成する場合 *
 a| 
データベースログインの詳細を指定します。



 a| 
* バックアップの保持ポリシーを指定する場合 *
 a| 
保持クラスの保持数または保持期間、あるいはその両方を指定してください。期間はクラスの単位で指定します（たとえば、時間単位の場合は時間単位、日単位の場合は日単位）。

** `-hourly`は'時間単位の保存クラスですこのクラスでは'-count n`][-duration m`]は'それぞれ保存期間と保存期間です
** `-daily`は日次保持クラスであり'[-count n`][`-duration m`]はそれぞれ保持数と保持期間です
** -weekly'は'週単位の保存クラスですこの場合'[-count n`][`-duration m`]は'それぞれリテンション・カウントとリテンション・デュレーションです
** 「-monthly」は'月単位の保存クラスですこのクラスでは'-count n`][-duration m`]は'それぞれリテンションカウントとリテンション期間です




 a| 
* データベース処理の完了ステータスの E メール通知を有効にする場合 *
 a| 
次のオプションと変数を指定します。

** --summary-notification`を使用すると'リポジトリ・データベースの下にある複数のプロファイルのサマリー・メール通知を構成できます
** --notification'プロファイルのデータベース操作の完了ステータスに関する電子メール通知を受信できます
** --success -email_address2`新しいプロファイルまたは既存のプロファイルを使用して実行されたデータベース操作の成功に関する電子メール通知を受け取ることができます。
** `-failure-email_address2`新しいまたは既存のプロファイルを使用して実行した失敗したデータベース操作に関する電子メール通知を受け取ることができます
** 「-subjectsubject_text」には、新しいプロファイルまたは既存のプロファイルを作成するときの電子メール通知の件名を指定します。リポジトリに対して通知設定が設定されていない場合に、CLIを使用してプロファイル通知またはサマリー通知を設定しようとすると、コンソールログに「SMSAP-14577：Notification Settings not configured」というメッセージが記録されます。
+
通知設定を構成したあとに、リポジトリのサマリー通知を有効にせずにCLIを使用してサマリー通知を設定しようとすると、コンソールログに「SMSAP-14575：Summary notification configuration not available for this repository」というメッセージが表示されます





 a| 
* アーカイブ・ログ・ファイルをデータ・ファイルとは別にバックアップする場合 *
 a| 
次のオプションと変数を指定します。

** 「-separate archivelog -backups」を使用すると、アーカイブログのバックアップをデータファイルのバックアップから分離できます。
** 「-retain-archivelog -bbackups」は、アーカイブ・ログ・バックアップの保存期間を設定します。正の保持期間を指定する必要があります。
+
アーカイブログのバックアップは、アーカイブログの保持期間に基づいて保持されます。データファイルのバックアップは、既存の保持ポリシーに基づいて保持されます。

** --incluse-with -one-backup'には'オンライン・データベース・バックアップとともにアーカイブ・ログ・バックアップが含まれます
+
このオプションを使用すると、クローニング用にオンラインのデータファイルバックアップとアーカイブログバックアップを一緒に作成できます。このオプションを設定すると、オンラインデータファイルバックアップを作成するたびに、アーカイブログバックアップがデータファイルと一緒にただちに作成されます。

** 「-no-include-with -online-backups」には、データベース・バックアップとともにアーカイブ・ログ・バックアップは含まれません。




 a| 
* プロファイル作成処理が正常に完了したら、ダンプ・ファイルを収集できます。 *
 a| 
「profile create」コマンドの最後にある「-dump」オプションを指定します。

|===

