---
permalink: windows/task-cloning-databases-in-the-current-state.html 
sidebar: sidebar 
keywords: create, backup, clone, database, command, cloning, current, state 
summary: 単一のコマンドを使用して、データベースの現在の状態からデータベースのバックアップとクローンを作成できます。 
---
= 現在の状態のデータベースをクローニングしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
単一のコマンドを使用して、データベースの現在の状態からデータベースのバックアップとクローンを作成できます。

プロファイルに -current オプションを指定すると、 SnapManager は最初にバックアップを作成し、そのあとでデータベースの現在の状態からクローンを作成します。

プロファイル設定で、クローニングのためにデータ・ファイルとアーカイブ・ログのバックアップを有効にしている場合、オンライン・データ・ファイルをバックアップするたびに、アーカイブ・ログもバックアップされます。データベースをクローニングする際、 SnapManager は、データファイルのバックアップをアーカイブログのバックアップとともに作成し、データベースのクローンを作成します。アーカイブログバックアップを含まない場合、 SnapManager はアーカイブログバックアップを作成しないため、データベースのクローンを作成できません。

.ステップ
. 現在の状態でデータベースをクローニングするには、次のコマンドを入力します。
+
「SMSAP clone create -profile profile_name -current-labelclone_name -clonespecclonespec.xml」です

+
このコマンドは、フル・バックアップを自動作成し（バックアップ・ラベルを生成して）、使用する既存のクローン仕様を使用して、バックアップから即座にクローンを作成します。

+

NOTE: オプションのパラメータとして -dump オプションを指定すると、処理の成功後または失敗後にダンプファイルを収集できます。バックアップ処理とクローニング処理の両方でダンプが収集されます。


