---
permalink: windows/task-rename-profiles.html 
sidebar: sidebar 
keywords: snapmanager, enable, rename, profile, update, capabilities, capability, perform, retain 
summary: SnapManager を使用すると、プロファイルの更新時にプロファイルの名前を変更できます。プロファイルに設定されている SnapManager 機能と、名前を変更する前に実行できる操作は、名前を変更したプロファイルに保持されます。 
---
= プロファイルの名前を変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager を使用すると、プロファイルの更新時にプロファイルの名前を変更できます。プロファイルに設定されている SnapManager 機能と、名前を変更する前に実行できる操作は、名前を変更したプロファイルに保持されます。



== 必要なもの

* プロファイルの名前を変更するときは、そのプロファイルに対して SnapManager 処理が実行されていないことを確認する必要があります。




== このタスクについて

プロファイルの名前は、 SnapManager のコマンドラインインターフェイス（ CLI ）とグラフィカルユーザインターフェイス（ GUI ）の両方から変更できます。プロファイルの更新時に、 SnapManager はリポジトリ内のプロファイル名を検証して更新します。


NOTE: SnapManager では、 [ 複数プロファイルの更新 ] ウィンドウでプロファイルの名前を変更することはできません。

新しいプロファイル名を指定すると、新しいプロファイル名がクライアント側クレデンシャルキャッシュに追加され、以前のプロファイル名は削除されます。クライアントからプロファイルの名前を変更すると、そのクライアントのクレデンシャルキャッシュだけが更新されます。新しいクレデンシャルキャッシュを新しいプロファイル名で更新するには、各クライアントから「smsapprofile sync」コマンドを実行する必要があります。

プロファイルのパスワードは、「smsapscredential set」コマンドを使用して設定できます。

Snapshot コピーの命名パターンにプロファイル名が含まれていた場合、プロファイル名を変更すると、そのプロファイルの新しい名前が更新されます。プロファイルに対して実行されるすべての SnapManager 処理には、新しいプロファイル名が使用されます。以前のプロファイルを使用して作成されたバックアップには、引き続き以前のプロファイル名が付けられ、他の SnapManager 処理に使用されます。

SnapManager サーバホストのローリングアップグレードを実行する場合は、プロファイル名を変更する前に完全なアップグレードを実行してください。

プロファイルの新しい名前は、要求の送信元である SnapManager クライアントからのみ更新されます。SnapManager サーバに接続されている SnapManager クライアントには、プロファイル名の変更が通知されません。処理ログをチェックすると、プロファイル名の変更について確認できます。


NOTE: プロファイル名の変更時にスケジュールされたバックアップ処理が開始されると、スケジュールされた処理は失敗します。

.ステップ
. 次のコマンドを入力します。
+
`* SMSAP profile update -profile update_profile_[-new-profile_profile_name_]*`


