---
permalink: windows/task-creating-profiles.html 
sidebar: sidebar 
keywords: creating, create, profile, assign, oracle, database, policy, set, retention, count, class 
summary: プロファイルの作成時に、特定の Oracle データベースのユーザ・アカウントをプロファイルに割り当てることができます。プロファイルに保持ポリシーを設定し、各保持クラスに保持数と保持期間を設定できます。 
---
= プロファイルの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プロファイルの作成時に、特定の Oracle データベースのユーザ・アカウントをプロファイルに割り当てることができます。プロファイルに保持ポリシーを設定し、各保持クラスに保持数と保持期間を設定できます。

データベースの -login 、 -password 、および -port パラメータの値を指定した場合は、オペレーティングシステム（ OS ）認証モードでデフォルトクレデンシャルが使用されます。

プロファイルの作成中に、 SnapManager はリストア適格性チェックを実行し、データベースのリストアに使用できるリストアメカニズムを決定します。

SnapManager （ 3.2 以降）を使用すると、新しいプロファイルの作成時または既存のプロファイルの更新時に、アーカイブ・ログ・ファイルをデータ・ファイルから分離できます。プロファイルを使用してバックアップを分離したら、データベースのデータファイルのみのバックアップを作成するか、アーカイブログのみのバックアップを作成できます。新しいプロファイルまたは更新したプロファイルを使用して、データ・ファイルとアーカイブ・ログ・ファイルの両方を含むバックアップを作成できます。ただし、プロファイルを使用してフル・バックアップを作成したり、設定を元に戻したりすることはできません。

* フル・バックアップおよびパーシャル・バックアップを作成するためのプロファイル *

プロファイルを作成すると、データ・ファイル、制御ファイル、アーカイブ・ログ・ファイル、および指定したデータ・ファイルまたは表領域を含むデータベースのパーシャル・バックアップ、すべての制御ファイル、およびすべてのアーカイブ・ログ・ファイルを含むフル・データベース・バックアップを作成できます。SnapManager では、フル・バックアップおよびパーシャル・バックアップ用に作成したプロファイルを使用して、個別のアーカイブ・ログ・バックアップを作成することはできません。

* データファイルのみのバックアップとアーカイブログのみのバックアップを作成するためのプロファイル *

新しいプロファイルを作成するときは、 -Separate -archivelog -backup を含めて、アーカイブログのバックアップをデータファイルのバックアップから分離できます。また、既存のプロファイルを更新して、アーカイブログバックアップとデータファイルバックアップを分離することもできます。

新しいプロファイル・オプションを使用してアーカイブ・ログ・バックアップを分離すると、次の SnapManager 処理を実行できます。

* アーカイブログのバックアップを作成します
* アーカイブログバックアップを削除する
* アーカイブログバックアップをマウントします
* アーカイブログのバックアップを解放します


プロファイルの作成時に、データ・ファイルのバックアップとアーカイブ・ログ・バックアップを分離するプロファイルを作成する際に、プロファイルが作成されたデータベースにアーカイブ・ログ・ファイルが存在しないと、アクティブ・ファイルシステムに警告メッセージ「アーカイブ・ログ・ファイル」が存在しません。<archive log thread version> ログファイルより前のアーカイブログファイルバージョンは、バックアップに含まれません。このデータベースのバックアップを作成する場合でも、データベースバックアップにアーカイブログファイルを使用できません。


NOTE: プロファイルの作成中にエラーが発生した場合は、smsapsystem dumpコマンドを使用します。プロファイルの作成後にエラーが発生した場合は、smsapoperation dumpコマンドとsmsapprofile dumpコマンドを使用します。

. ユーザ名、パスワード、およびポート（Oracle認証）を指定してプロファイルを作成するには、次のコマンドを入力します。
+
smsSMSAP profile create -profile profile[-profile-passwordprofileprofile_password]-repository -dbname -hojectpo_host-jectbox_host-jectbox_port-usernamerepo_username-dbdbname -hostdbnamedb_host[-siddb_sdb_sdb_host][-password-durerman [-drermanバージョン[--password-passwordname -password-drst_addressm -password][-drst_addressm -password][-dr全般[-drst_addressm -password-password[-dr全般][-dr全般][-dr全般][--password-password-password-atername -password-password-atername -atername -password][-drst全員[-drman][-drman][-drman]-password-password-password[-drst全員 電子メール[-drman[週次電子メール[-drman[週次電子メール[-drman][--password]-password]-password][--password-password-passwordパターン[-drman]サブパターン[-drman[週次電子メール[--

+
このコマンドの他のオプションは、次のとおりです。

+
[-force] [-nopromp]

+
また、プロファイルの作成時に、データベースへのアクセス方法に応じて、他のオプションを指定することもできます。

+
|===
| 状況 | 作業 


 a| 
* データベース認証を使用してプロファイルを作成する場合 *
 a| 
データベースログインの詳細を指定します。



 a| 
* バックアップの保持ポリシーを指定する場合 *
 a| 
保持クラスの保持数または保持期間、あるいはその両方を指定してください。期間はクラスの単位で指定します（たとえば、時間単位の場合は時間単位、日単位の場合は日単位）。

** -hourly は、時間単位の保持クラスです。 [-count n] [-duration m] はそれぞれ、保持数および保持期間です。
** -daily は、日単位の保持クラスです。 [-count n] [-durationm] は、それぞれ保持数および保持期間です。
** -weekly は、週単位の保持クラスです。 [-count n] [-duration m] は、それぞれ保持数および保持期間です。
** -monthly は、月単位の保持クラスです。 [-count n] [-durationm] は、それぞれ保持数および保持期間です。




 a| 
* データベース処理の完了ステータスの E メール通知を有効にする場合 *
 a| 
次のオプションと変数を指定します。

** -summary-notification を使用すると、リポジトリデータベース内の複数のプロファイルについて、サマリー E メール通知を設定できます。
** -notification を使用すると、プロファイルのデータベース処理の完了ステータスに関する E メール通知を受信できます。
** -success -email_address2 を使用すると、新規または既存のプロファイルを使用して実行されたデータベース処理の成功を通知する E メールを受け取ることができます。
** -failure-email_address2 を使用すると、新しいプロファイルまたは既存のプロファイルを使用して実行された、失敗したデータベース処理に関する E メール通知を受け取ることができます。
** -subjectsubjectsub_text ：新しいプロファイルまたは既存のプロファイルを作成する際の E メール通知の件名を指定します。リポジトリの通知設定が行われていない場合に、CLIを使用してプロファイル通知または概要通知を設定しようとすると、コンソールログに次のメッセージが記録されます。SMSAP-14577：Notification Settings not configured。
+
通知設定を行っている状況で、リポジトリの概要通知を有効にせずにCLIを使用して概要通知を設定しようとすると、コンソールログに次のメッセージが表示されます。________SMSAP-14575：このリポジトリで概要通知設定を使用できません





 a| 
* アーカイブ・ログ・ファイルをデータ・ファイルとは別にバックアップする場合 *
 a| 
次のオプションと変数を指定します。

** -Separe-archivelog -backup を使用すると、アーカイブログのバックアップをデータファイルのバックアップから分離できます。
** -retain-archivedlog backups ：アーカイブログのバックアップの保存期間を設定します。正の保持期間を指定する必要があります。
+
アーカイブログのバックアップは、アーカイブログの保持期間に基づいて保持されます。データファイルのバックアップは、既存の保持ポリシーに基づいて保持されます。

** -includes -with -online - バックアップには、アーカイブログのバックアップとオンラインデータベースのバックアップが含まれます。
+
このオプションを使用すると、クローニング用にオンラインのデータファイルバックアップとアーカイブログバックアップを一緒に作成できます。このオプションを設定すると、オンラインデータファイルバックアップを作成するたびに、アーカイブログバックアップがデータファイルと一緒にただちに作成されます。

** -no-include-y-online-backups ：データベース・バックアップとともにアーカイブ・ログ・バックアップを含みません




 a| 
* プロファイル作成処理が正常に完了したら、ダンプ・ファイルを収集できます。 *
 a| 
profile create コマンドの最後に -dump オプションを指定します。

|===


* 関連情報 *

xref:concept-how-to-collect-dump-files.adoc[ダンプ・ファイルの収集方法]
