---
permalink: windows/task-clone-databases-from-backups.html 
sidebar: sidebar 
keywords: clone, database, backup, create, command 
summary: バックアップからデータベースをクローニングするには、 clone create コマンドを使用します。 
---
= バックアップからデータベースをクローニングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「clone create」コマンドを使用すると、バックアップからデータベースをクローニングできます。



== このタスクについて

最初に、データベースのクローン仕様ファイルを作成する必要があります。SnapManager は、この仕様ファイル内の情報に基づいてクローンを作成します。

データベースのクローンを作成した後で'新しいクローン・データベース接続情報を使用して'クライアント・マシン上のtnsnames.oraファイルを更新する必要がある場合があります「tnsnames.ora」ファイルは、完全なデータベース情報を指定することなくOracleインスタンスに接続するために使用されます。SnapManager は'tnsnames.oraファイルを更新しません

--incluse-with -online-backups'で作成したプロファイルを使用している場合、SnapManager は常にアーカイブ・ログ・ファイルを含むバックアップを作成します。SnapManager でクローニングできるのは、フルデータベースバックアップのみです。

SnapManager （ 3.2 以降）では、データ・ファイルおよびアーカイブ・ログ・ファイルが含まれているバックアップをクローニングできます。

アーカイブログが外部の場所から利用できる場合、クローニング中に外部の場所を指定して、クローンデータベースを整合性のある状態にリカバリできます。外部の場所に Oracle からアクセスできることを確認する必要があります。アーカイブログのみのバックアップのクローニングはサポートされていません。

アーカイブログのバックアップは、オンラインのパーシャルバックアップとともに作成されますが、このバックアップを使用してデータベースのクローンを作成することはできません。

クローニングされたデータベースを整合性のある状態にリカバリするために外部アーカイブログの場所を指定する場合は、外部の場所の名前を完全に大文字で指定する必要があります。ファイルシステムでは、すべてのフォルダとサブフォルダの名前が大文字である必要があります。これは、 Oracle データベースではデスティネーションパスが大文字に変換され、外部のデスティネーションパス、フォルダ名、サブフォルダ名が大文字であることが前提となるためです。外部アーカイブログのデスティネーションパスを小文字で指定すると、指定されたパスがデータベースで識別できず、クローンデータベースのリカバリに失敗することがあります。

外部アーカイブログファイルの場所からデータベースバックアップをクローニングできるのは、スタンドアロンデータベースの場合だけです。

オプション・パラメータとして'-dump'オプションを指定すると'クローン作成の成功または失敗後にダンプ・ファイルを収集できます

* アーカイブログバックアップなしのデータファイルバックアップのクローニング *

データファイルのバックアップにアーカイブログバックアップが含まれていない場合、SnapManager for SAPはバックアップ時に記録されたSystem Change Number（SCN）に基づいてデータベースのクローンを作成します。クローニングされたデータベースをリカバリできない場合は、SnapManager for SAPがデータベースのクローニングを続行していて、最後にクローンの作成に成功したにもかかわらず、「Archived log file for thread <number>とchange <scn > required to complete recovery」というエラーメッセージが表示されます。

アーカイブログのバックアップを含めずにデータファイルのバックアップを使用してクローニングする場合、 SnapManager は、バックアップ中に記録される最後のアーカイブログ SCN まで、クローニングされたデータベースをリカバリします。

.手順
. クローン仕様ファイルを作成します。
. クローンを作成するには、次のコマンドを入力します。
+
「+ SMSAP clone create -backup-labelbackup_name -newsidnew_sid -labelclone_label -profileprofile_name -clonespfull_path_to clonespecfile [-taskspec_][-recover-from-location] path1[,<path2>]」 [-dump]+`


