---
permalink: windows/task-creating-database-backups.html 
sidebar: sidebar 
keywords: create, backup, database, portion, tablespace, data, file, control, creating 
summary: 表領域、データ・ファイル、制御ファイルなど、データベース全体またはデータベースの一部のバックアップを作成できます。 
---
= データベースバックアップを作成しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
表領域、データ・ファイル、制御ファイルなど、データベース全体またはデータベースの一部のバックアップを作成できます。

SnapManager は、NFS、Veritasなど、ホスト側の多くのストレージスタックにわたって、データベースにSnapshotコピー機能を提供します。

管理者は、 Oracle RMAN にバックアップを登録することもできます。これにより、 RMAN を使用したデータベースのリストアとリカバリが容易になり、ブロックなどのより細かい単位でデータベースをリストアおよびリカバリできます。

プロファイルを定義する際に、そのプロファイルのバックアップによって作成される Snapshot コピーの名前をカスタマイズできます。たとえば'hopsのプレフィクス文字列を挿入して'High Operationsのバックアップを示すことができます

バックアップで作成される Snapshot コピーに一意の名前を定義するだけでなく、バックアップ自体に一意のラベルを作成することもできます。作成したバックアップには、 -label パラメータを使用して簡単に識別できるように、バックアップ名を指定することを推奨します。この名前は、特定のプロファイルに作成されるすべてのバックアップに対して一意である必要があります。名前には、アルファベット、数字、アンダースコア（ _ ）、およびハイフン（ - ）を使用できます。1 文字目をハイフンにすることはできません。ラベルでは大文字と小文字が区別されます。オペレーティングシステムの環境変数、システムの日付、バックアップタイプなどの情報を追加できます。

ラベルを指定しない場合、 SnapManager はデフォルトのラベル名を scope_mode_datestring 形式で作成します。 scope は full または partial で、 mode は offline 、 online 、または automatic です（コールド、ホット、または自動の場合は c ）。

SnapManager 3.4 では、 SnapManager で作成されたデフォルトのバックアップ・ラベルを上書きすることにより、独自のバックアップ・ラベルを指定できます。override.default.backup.pattern パラメータの値を true に設定し、 new.default.backup.pattern パラメータに新しいバックアップラベルを指定する必要があります。バックアップラベルのパターンには、データベース名、プロファイル名、スコープ、モード、ホスト名など、アンダースコアで区切る必要のあるキーワードを含めることができます。たとえば、 new.default.backup.pattern=dbname_profile_hostname_scope_mode などです。


NOTE: 生成されたラベルの末尾にタイムスタンプが自動的に追加されます。

コメントを入力するときは、スペースと特殊文字を使用できます。一方、ラベルを入力する場合は、スペースや特殊文字は使用しないでください。

バックアップごとに、 SnapManager は自動的に 32 文字の 16 進数ストリングの GUID を生成します。GUID を確認するには、 -verbose オプションを指定して backup list コマンドを実行する必要があります。

データベースのフルバックアップは、オンラインまたはオフラインの間に作成できます。データベースがオンラインであるかオフラインであるかに関係なく、 SnapManager でそのバックアップを処理できるようにするには、 auto オプションを使用します。

バックアップの作成時に、プルーニングをイネーブルにし、サマリー通知がプロファイルでイネーブルになっている場合は、 2 つの個別の電子メールがトリガーされます。1 つの E メールはバックアップ処理用で、もう 1 つはプルーニング用です。これらの E メールに含まれるバックアップ名とバックアップ ID を比較することで、これらの E メールを関連付けることができます。

データベースがシャットダウン状態のときにコールドバックアップを作成できます。データベースがマウント状態の場合は、シャットダウン状態に変更し、オフラインバックアップ（コールドバックアップ）を実行します。

SnapManager （ 3.2 以降）では、アーカイブ・ログ・ファイルをデータ・ファイルとは別にバックアップできるため、アーカイブ・ログ・ファイルを効率的に管理できます。

アーカイブログのバックアップを個別に作成するには、新しいプロファイルを作成するか、または -separate-archivelog-backups オプションを使用してアーカイブログのバックアップを分離するように既存のプロファイルを更新する必要があります。プロファイルを使用すると、次の SnapManager 処理を実行できます。

* アーカイブログのバックアップを作成します。
* アーカイブログバックアップを削除する。
* アーカイブログバックアップをマウントします。
* アーカイブログのバックアップを解放します。


バックアップオプションは、プロファイルの設定によって異なります。

* 分離されていないプロファイルを使用してアーカイブ・ログ・バックアップを個別に作成すると、次の処理を実行できます。
+
** フルバックアップを作成します。
** パーシャル・バックアップを作成します。
** アーカイブログファイル用にバックアップするアーカイブログのデスティネーションを指定します。
** バックアップから除外するアーカイブログの送信先を指定します。
** アーカイブ・ログ・デスティネーションからアーカイブ・ログ・ファイルを削除する場合のプルーニング・オプションを指定します。


* 分離されたプロファイルを使用してアーカイブ・ログ・バックアップを作成すると、次のことが可能になります。
+
** データファイルのみのバックアップを作成
** アーカイブログのみのバックアップを作成する
** データファイルのみのバックアップを作成する場合は、アーカイブログのバックアップに加え、クローニング用のオンラインデータファイルのみのバックアップも含めます。
+
アーカイブ・ログ・バックアップとデータ・ファイルを SnapManager GUI から * Profile Create * ウィザードの * Profile Settings * ページに含めた場合は、次の手順を実行します。 また、 * バックアップの作成 * ウィザードで * アーカイブ・ログ * オプションを選択していない場合、 SnapManager は常に、すべてのオンライン・バックアップのデータ・ファイルとともにアーカイブ・ログ・バックアップを作成します。

+
このような場合、 SnapManager CLI から、 SnapManager 構成ファイルで指定された除外デスティネーションを除く、バックアップのすべてのアーカイブログデスティネーションを検討できます。ただし、これらのアーカイブログファイルの削除はできません。ただし、 -archivelog オプションを使用してアーカイブ・ログ・ファイルの保存先を指定し、 SnapManager CLI からアーカイブ・ログ・ファイルを削除できます。

+
auto オプションを使用してバックアップを作成し、 -archivelogs オプションを指定している場合、 SnapManager はバックアップの現在のステータスに基づいてオンラインまたはオフラインのバックアップを作成します。

+
*** SnapManager では、データベースがオフラインのときにオフラインバックアップが作成されます。バックアップにアーカイブログファイルは含まれません。
*** SnapManager は、データベースがオンラインのときに、アーカイブ・ログ・ファイルを含むオンライン・バックアップを作成します。


** アーカイブログのみのバックアップの作成中：
+
*** アーカイブログのみのバックアップとともにバックアップするアーカイブログのデスティネーションを指定します
*** アーカイブログのみのバックアップから除外するアーカイブログのデスティネーションを指定します
*** アーカイブ・ログ・デスティネーションからアーカイブ・ログ・ファイルを削除する場合のプルーニング・オプションを指定します




* * シナリオはサポートされていません *
+
** アーカイブログのみのバックアップは、オフラインデータファイルのみのバックアップとともに作成することはできません。
** アーカイブログファイルがバックアップされていない場合は、アーカイブログファイルの削除はできません。
** アーカイブログファイルに対して Flash Recovery Area （ FRA ）が有効になっている場合は、アーカイブログファイルのプルーニングを実行できません。
+
フラッシュリカバリ領域でアーカイブログの場所を指定する場合は、 archive_log_dest パラメータでアーカイブログの場所も指定してください。






NOTE: アーカイブログのバックアップを作成するときは、完全なアーカイブログのデスティネーションパスを二重引用符で囲み、デスティネーションパスをカンマで区切って入力する必要があります。パスの区切り文字は、 1 つではなく 2 つのバックスラッシュ（ \\ ）で指定する必要があります。

オンラインデータファイルバックアップのラベルにアーカイブログバックアップを含めるように指定すると、データファイルバックアップのラベルには接尾辞（ _logs ）が付加されます。このサフィックスを設定するには、 SnapManager 構成ファイルのパラメータサフィックス .backup.label.with .logs を変更します。

たとえば、値を suffix.backup.label.with .logs=arc と指定すると、 _logs のデフォルト値が _arc に変更されます。

バックアップに含めるアーカイブログのデスティネーションを指定していない場合、 SnapManager には、データベースに設定されているすべてのアーカイブログのデスティネーションが含まれます。

いずれかのデスティネーションに欠落しているアーカイブログファイルがある場合、 SnapManager は、欠落しているアーカイブログファイルが他のアーカイブログデスティネーションにある場合でも、それらのアーカイブログファイルの前に作成されたアーカイブログファイルをすべてスキップします。

アーカイブログのバックアップを作成する際には、バックアップに含めるアーカイブログファイルのデスティネーションを指定する必要があります。また、設定パラメータで、アーカイブログファイルをバックアップ内の欠落ファイルよりも常に多く含めるように設定できます。


NOTE: デフォルトでは、この構成パラメータは true に設定され、不足しているファイルを除くすべてのアーカイブログファイルが対象になります。独自のアーカイブ・ログ削除スクリプトを使用する場合、またはアーカイブ・ログ・デスティネーションからアーカイブ・ログ・ファイルを手動で削除する場合は、このパラメータを無効にして、 SnapManager でアーカイブ・ログ・ファイルをスキップし、バックアップをさらに続行できます。

SnapManager では、アーカイブログのバックアップに関して次の SnapManager 処理がサポートされません。

* アーカイブログのバックアップをクローニングする
* アーカイブログのバックアップをリストアする
* アーカイブログのバックアップを検証する


SnapManager では、フラッシュリカバリ領域のデスティネーションからアーカイブログファイルをバックアップすることもできます。

.ステップ
. 次のコマンドを入力します。
+
SMSAP backup create -profile profile_name｛[-full｛-online |-offline |-auto｝[-retain｛-hourly |-daily |-comment|-monthly |-unlimited｝][-verify]|[-data [[-files[files]|[-tablespaces [--tablespaces [--unlimited |-label]-retain-abell-ontap]|-retain-abel-backupabel|-ontap] [-backup-destpath1[,[path2]][-exclude-destpath1[,path2]][-prunelogs {-all |-untSCNuntilscn|-until -date yyyy-mm-dd：HH：MM：MM：-before｛-months |-days |-wee|-weeks |-que-destdumprune d]-destpath1 -destforce-destforce-untump[-dump][-d]-dest-dprune [-des]-destpath1}][-dprune

+
|===
| 状況 | 作業 


 a| 
* オンラインとオフラインのどちらのデータベースのバックアップを作成するかを指定します。 SnapManager でオンラインとオフラインのどちらのデータベースを処理するかは指定しません *
 a| 
オフラインデータベースのバックアップを作成するには、 -offline を指定します。オンラインデータベースのバックアップを作成するには、 -online を指定します。

これらのオプションを使用する場合は、autoオプションは使用できません。



 a| 
* データベースがオンラインかオフラインかにかかわらず、 SnapManager がデータベースのバックアップを処理できるようにするかどうかを指定します。 *
 a| 
auto オプションを指定します。このオプションを使用する場合は、 --offline オプションまたは -online オプションは使用できません。



 a| 
* 特定のファイルのパーシャル・バックアップを実行するかどうかを指定します *
 a| 
-data-filesオプションを指定し、ファイルをカンマで区切ってリストします。たとえば、F1、F2、およびF3のファイル名をオプションの後にリストします。

Windowsでデータファイルのパーシャル・バックアップを作成する例

[listing]
----

smsap backup create -profile nosep -data -files "J:\\mnt\\user\\user.dbf" -online
-label partial_datafile_backup -verbose
----


 a| 
* 特定の表領域のパーシャル・バックアップを実行するかどうかを指定します。 *
 a| 
-data-tablespacesオプションを指定し、カンマで区切った表領域をリストします。たとえば、オプションのあとにTS1、TS2、およびTS3を使用します。

SnapManager では、読み取り専用表領域のバックアップがサポートされます。バックアップの作成時に、 SnapManager は読み取り専用テーブルスペースを読み取り / 書き込みに変更します。バックアップの作成後、表領域は読み取り専用に変更されます。

例：パーシャル・テーブルスペース・バックアップを作成する

[listing]
----
smsap backup create -profile nosep -data -tablespaces tb2 -online -label partial_tablespace_bkup -verbose
----


 a| 
* 各バックアップに一意のラベルを作成するかどうかを full_hot_mybackup_label * という形式で指定します
 a| 
Windowsの場合は、次の例を入力します。

[listing]
----

smsap backup create -online -full -profile targetdb1_prof1
-label full_hot_my_backup_label   -verbose
----


 a| 
* アーカイブ・ログ・ファイルのバックアップを ' データ・ファイルとは別に作成するかどうかを指定します *
 a| 
次のオプションと変数を指定します。

** -archivelog アーカイブ・ログ・ファイルのバックアップを作成します
** -backup-dest では、バックアップするアーカイブ・ログ・ファイルのデスティネーションを指定します。
** -exclude-dest には、除外するアーカイブログのデスティネーションを指定します。
** -label は、アーカイブログファイルバックアップのラベルを指定します。



NOTE: backup-destオプションまたは-exclude-destオプションのいずれかを指定する必要があります。

この 2 つのオプションを両方指定してバックアップを実行すると、無効なバックアップオプションを指定した場合にエラー・メッセージが表示されます。backup-dest 、または exclude-dest のいずれかのオプションを指定します。

アーカイブログファイルのバックアップを Windows で別途作成する例

[listing]
----

smsap backup create -profile nosep -archivelogs -backup-dest "J:\\mnt\\archive_dest_2\\" -label archivelog_backup -verbose
----


 a| 
* データ・ファイルとアーカイブ・ログ・ファイルのバックアップを一緒に作成するかどうかを指定します *
 a| 
 Specify the following options and variables:
** データ・ファイルを指定する DATA オプション
** -archivelog オプションを使用してアーカイブ・ログ・ファイルを指定しますWindows でのデータ・ファイルとアーカイブ・ログ・ファイルのバックアップ例
+
[listing]
----

smsap backup create -profile nosep -data -online -archivelogs -backup-dest "J:\\mnt\\archive_dest_2\\" -label data_arch_backup
-verbose
----




 a| 
* バックアップ作成時にアーカイブ・ログ・ファイルのプルーニングを実行するかどうかを指定します *
 a| 
 Specify the following options and variables:
** -prunelogs ：アーカイブログのデスティネーションからアーカイブログファイルを削除するように指定します
+
*** -all は、アーカイブログデスティネーションからすべてのアーカイブログファイルを削除するように指定します。
*** -until -scnuntil -scn は、指定した SCN までアーカイブ・ログ・ファイルを削除するように指定します。
*** -until dateyyyyy-mm-dd ： HH ： MM ： ss ：指定した期間までアーカイブログファイルを削除するように指定します。
*** -before オプションは、指定した期間（日数、月数、週数、時間）前にアーカイブログファイルを削除するように指定します。
*** -prune-destprune_dest1 、 [prune_dest2 は、バックアップの作成時にアーカイブ・ログ・デスティネーションからアーカイブ・ログ・ファイルを削除するように指定します。* 注意： * アーカイブ・ログ・ファイルに対して Flash Recovery Area （ FRA ）が有効になっている場合、アーカイブ・ログ・ファイルのプルーニングはできません。




Windows でバックアップを作成する際に、すべてのアーカイブ・ログ・ファイルを削除する例を示します

[listing]
----

smsap backup create -profile nosep
 -archivelogs -label archive_prunebackup1 -backup-dest "E:\\oracle\\MDV\\oraarch\\MDVarch,J:\\
" -prunelogs -all -prune-dest "E:\\oracle\\MDV\\oraarch\\MDVarch,J:\\" -verbose
----


 a| 
* バックアップに関するコメントを追加するかどうかを指定します。 *
 a| 
comment に続けて概要文字列を指定します。



 a| 
* 現在の状態にかかわらず、指定した状態にデータベースを強制的にバックアップするかどうかを指定します
 a| 
force オプションを指定します。



 a| 
* バックアップの作成時に検証を実行するかどうかを指定します。 *
 a| 
verify オプションを指定します。



 a| 
* データベース・バックアップ処理後にダンプ・ファイルを収集するかどうかを指定します。 *
 a| 
backup create コマンドの最後に -dump オプションを指定します。

|===




== 例

[listing]
----
smsap backup create -profile targetdb1_prof1 -full -online -force  -verify
----
* 関連情報 *

xref:concept-snapshot-copy-naming.adoc[Snapshot コピーの命名規則]

xref:task-creating-pretask-post-task-and-policy-scripts.adoc[プリタスクスクリプト、ポストタスクスクリプト、ポリシースクリプトの作成]

xref:task-creating-task-scripts.adoc[タスクスクリプトの作成]

xref:task-storing-the-task-scripts.adoc[タスクスクリプトの保存]

xref:reference-the-smosmsapbackup-create-command.adoc[SMSAPのbackup createコマンドを使用します]

xref:task-creating-or-updating-post-scripts.adoc[ポストスクリプトの作成または更新]
