---
permalink: windows/task-delete-backups.html 
sidebar: sidebar 
keywords: delete, backup, free, space, occupy, remove, snapshot, copies, copy, volume 
summary: 不要になったバックアップを削除する必要があります。これにより、バックアップが占有するスペースが解放されます。バックアップを削除することにより、ボリュームあたりの Snapshot コピー数が上限の 255 に達する可能性が低くなります。 
---
= バックアップを削除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
不要になったバックアップを削除する必要があります。これにより、バックアップが占有するスペースが解放されます。バックアップを削除することにより、ボリュームあたりの Snapshot コピー数が上限の 255 に達する可能性が低くなります。



== 必要なもの

* バックアップを使用してクローンを作成していないことを確認する必要があります。




== このタスクについて

保持するバックアップは、保持クラスを変更することなく、無制限に削除できます。

必要に応じて、バックアップの削除処理が成功または失敗したあとにダンプファイルを収集できます。

アーカイブログバックアップを削除する場合は、アーカイブログバックアップに対して設定された保持期間を確認する必要があります。アーカイブログのバックアップが保持期間内にあり、リストアされたデータベースのリカバリにアーカイブログファイルが必要な場合、アーカイブログのバックアップを削除することはできません。

.手順
. 次のコマンドを入力して、処理が完了したことを確認します。
+
`* SMSAP operation list -profile_name__-dump -quiet -verbose *`

. バックアップを削除するには、次のコマンドを入力します。
+
'*SMSAP backup delete -profile _profile_name_[-label_[data|-archivelogs ]|-id_id_|-all][-force ][-dump][-quiet |-verbose *`

+
バックアップを強制的に削除するには'-forceオプションを使用します処理を完了していないバックアップを削除しようとすると、バックアップが不完全な状態のまま残ることがあります。


