---
permalink: windows/task-updating-storage-system-name-associated-with-a-profile.html 
sidebar: sidebar 
keywords: snapmanager, ability, update, host, name, ip, address, storage, system, associate, profile 
summary: SnapManager 3.3 以降では、プロファイルに関連付けられたストレージ・システムのホスト名または IP アドレスを更新できます。 
---
= プロファイルに関連付けられたストレージ・システムの名前を更新する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager 3.3 以降では、プロファイルに関連付けられたストレージ・システムのホスト名または IP アドレスを更新できます。

次の点を確認する必要があります。

* プロファイルには少なくとも 1 つのバックアップが含まれています。
+
プロファイルにバックアップがない場合は、そのプロファイルのストレージ・システム名を更新する必要はありません。

* プロファイルに対して実行中の処理はありません。


SnapManager コマンドラインインターフェイス（ CLI ）を使用して、ストレージシステムの名前または IP アドレスを更新できます。ストレージシステム名を更新する際、リポジトリデータベースに格納されているメタデータだけが更新されます。ストレージシステム名の変更後、 SnapManager の操作をすべて先に実行できます。


NOTE: ストレージシステム名は、 SnapManager のグラフィカルユーザインターフェイス（ GUI ）を使用して変更することはできません。

Snapshot コピーが新しいストレージシステムで使用可能であることを確認する必要があります。SnapManager は、ストレージ・システムに Snapshot コピーが存在するかどうかを検証しません。

ただし、ストレージシステム名の変更後にホストのロールアップグレードおよびロールバックを実行する際は、次の点に注意する必要があります。

* ストレージシステム名の変更後にホストのローリングアップグレードを実行する場合は、プロファイルを新しいストレージシステム名に更新する必要があります。
* ストレージシステムの名前を変更したあとにホストをロールバックする場合は、以前のストレージシステムのプロファイル、バックアップ、およびクローンを使用して SnapManager 処理を実行できるように、ストレージシステム名を元のストレージシステム名に戻してください。
+
.. 次のコマンドを入力します。「SMSAP storage rename -profile profile -oldnameold_volume_name -newnamenew_storage_name [quiet |-verbose」
+
|===
| 状況 | 作業 


 a| 
プロファイルに関連付けられたストレージ・システムの名前を更新します
 a| 
profile オプションを指定します。



 a| 
プロファイルに関連付けられたストレージ・システムの名前または IP アドレスを更新します
 a| 
次のオプションと変数を指定します。

*** -oldnameold_storage_name は、ストレージ・システムのホスト名または IP アドレスです。
*** newnamenew_storage_name は、ストレージシステムのホスト名または IP アドレスです。


|===




次の例は、更新するストレージシステムの名前を示しています。

[listing]
----
smsap storage rename -profile mjullian -oldname lech -newname hudson -verbose
----