---
permalink: windows/task-install-snapmanager-for-oracle-snapmanager-for-sap.html 
sidebar: sidebar 
keywords: install, snapmanager, host, database, manage, instance, sap 
summary: 管理対象のデータベースが 1 つ以上あるホストに SnapManager をインストールできます。インストールできる SnapManager インスタンスは、ホストごとに 1 つだけです。 
---
= SnapManager for SAPをインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理対象のデータベースが 1 つ以上あるホストに SnapManager をインストールできます。インストールできる SnapManager インスタンスは、ホストごとに 1 つだけです。



== 必要なもの

* インストール前に必要なタスクを完了しておく必要があります。
* 最新の SnapManager インストールパッケージをダウンロードする必要があります。
* すべてのターゲットホストに、適切なバージョンの SnapDrive for Windows をインストールし、設定する必要があります。
+
SnapDrive for Windows のインストールと設定については、 SnapDrive for Windows インストレーションアドミニストレーションガイドを参照してください。



.手順
. SnapManager インストールファイルをダブルクリックします。
+
|===
| オペレーティングシステム | 使用する方法 


 a| 
Windows x86 の場合
 a| 
「NetApp.smsap.windows-x86-version.exe`.」を参照してください



 a| 
Windows x64
 a| 
「NetApp.smsap.windows-x64- version.exe`」という形式でダウンロードしてください

|===
+
「パブリッシャを検証できませんでした」というメッセージが表示されます。このソフトウェアを実行してもよろしいですか

. [OK] をクリックします。
. [はじめに]ウィンドウで、[次へ]をクリックします。
. [インストールフォルダの選択*]ウィンドウで、[次へ*]をクリックしてデフォルトのインストール場所を受け入れるか、新しい場所を選択します。
+
デフォルトの場所は「C：\Program Files\NetApp\SnapManager for SAP~」です。

. [*メニューの可用性*]ウィンドウで、[*次へ*]をクリックします。
. [サービスプロパティの指定*]ウィンドウで、Windowsサービスのアカウントおよびパスワード情報を入力します。
+
指定するアカウントは、次のグループのメンバーである必要があります。

+
** ストレージ・システムのローカル・アドミニストレーション・グループ
** ローカル管理者のグループ
** ORA_DBA グループ：再起動後にサービスを自動的に開始するか ' 手動で開始するかを指定できます


. [* Pre-Installation Summary*（インストールの概要*）]ウィンドウで、[* Install*（インストール*）]をクリックします。
. [インストール完了*]ウィンドウで、[次へ]をクリックします。
. [重要な情報*]ウィンドウで、[完了]をクリックしてインストーラーを終了します。




== 完了後

インストールが完了したら、インストールが正常に完了したことを確認できます。

. SnapManager サーバを起動します。
+
.. Windowsサービスウィンドウで、* SnapManager バージョン_ for SAP *を選択します。
.. 左パネルで、 * スタート * をクリックします。


. SnapManager システムが正しく動作していることを確認します。
+
.. [* Start *>* Programs *>* NetApp *>* SnapManager for SAP *>* Start SMSAP Command Line Interface（CLI）*]をクリックします。
.. コマンドラインインターフェイス（CLI）で、+`*SMSAP system verify*`コマンドを入力します
+
「Operation ID number succeeded」というメッセージが表示されます。

+
number は、処理 ID 番号です。





* 関連情報 *

http://mysupport.netapp.com/["のドキュメントについては、ネットアップサポートサイトを参照してください"^]
