---
permalink: windows/task-view-backup-details.html 
sidebar: sidebar 
keywords: view, detail, information, backup, profile, smsap, show, command 
summary: プロファイル内の特定のバックアップに関する詳細情報を表示するには、SMSAPのbackup showコマンドを使用します。 
---
= バックアップの詳細を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「smsapbackup show」コマンドを使用すると、プロファイル内の特定のバックアップの詳細情報を表示できます。



== このタスクについて

「SMSAP backup show」コマンドを使用すると、各バックアップについて次の情報が表示されます。

* バックアップ ID
* バックアップの成功または失敗
* バックアップの範囲（フル、パーシャル、オンライン、オフライン）
* バックアップモード
* マウントステータス
* バックアップのラベル
* コメント（ Comment ）
* 処理の開始および終了日時
* バックアップが検証されたかどうかを示す情報
* バックアップ保持クラス
* データベースおよびホスト名
* チェックポイントのシステム変更番号（ SCN ）
* End backup SCN （オンライン・バックアップのみ）
* バックアップしたデータベースに含まれる表領域およびデータ・ファイル
* バックアップしたデータベースに含まれる制御ファイルです
* バックアップしたデータベースに含まれるアーカイブログです
* ファイルが置かれているストレージ・システムおよびボリューム
* 作成された Snapshot コピーとその場所
* プライマリストレージリソースのステータス
* バックアップの保護ステータス
* バックアップモード


「-verbose」オプションを指定すると、次の追加情報 が表示されます。

* バックアップから作成されたクローンがある場合は
* 検証情報
* バックアップがマウントされている場合は、使用中のマウントポイントが SnapManager に表示されます


アーカイブログファイルのバックアップについては、次の情報を除き、他のデータベースバックアップと同じ情報が表示されます。

* チェックポイント SCN
* バックアップ SCN の終了
* テーブルスペース
* 制御ファイル


ただし、アーカイブログファイルのバックアップには次の追加情報が含まれています。

* バックアップの最初の変更番号
* 次にバックアップを変更した番号
* スレッド番号
* ログ ID をリセットします
* インカネーション
* ログファイル名


.ステップ
. 次のコマンドを入力します。
+
「* SMSAP backup show -profile _profile_name_{-label_[data|-archivelogs ]|-id_id_[-quiet |-verbose」*


