---
permalink: windows/task-configure-e-mail-notification-for-a-new-profile.html 
sidebar: sidebar 
keywords: create, profile, configure, receive, email, notification, completion, database, operation, profile 
summary: 新しいプロファイルを作成する場合、データベース処理が完了したときに E メール通知を受け取るようにを設定できます。 
---
= 新しいプロファイルのEメール通知を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいプロファイルを作成する場合、データベース処理が完了したときに E メール通知を受け取るようにを設定できます。



== 必要なもの

* アラートの送信元 E メールアドレスを設定する必要があります。
* 複数の E メールアドレスを指定する場合は、カンマで区切って指定する必要があります。
+
カンマと次の E メールアドレスの間にスペースを入れないようにしてください。

+

NOTE: 一連の E メールアドレスは二重引用符で囲む必要があります。



.ステップ
. 次のコマンドを入力します。
+
`* SMSAP profile create -profile create -profile _profile_[-profile-password_profile_profile_profile_name_host-host_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_username -database_name -host_drman_password-drman [-dra_db_host_name]/<hourly_schedule_db1_db_host_host_host_domain>コマンド[-drman_password-drman_drman [-drman_password-drman [-drman_drman_username]-admin_password-drman_dm_host_password-drman [-drman_drman_password]-dailyrman_password-drman [-drman_drmanパスワード[-drmanパスワード[-drmanパスワード[-drman_dm_host_name]_tm_dm_host_name [-count_n_][-duration _m_]][-weekly[-count_m_]][-duration_n_][-duration _ m_]][-duration _ comment _m_]][-snapname=pattern_pattern_pattern_]][-protect [][-subject_address_email_address_email_address_address*][-durs1_email_address_address_email_address*

+
このコマンドの他のオプションは、次のとおりです。

+
[`-force `]

+
[`quiet `|`-verbose ]

+

NOTE: SnapManager では、 E メールアドレスが最大 1000 文字までサポートされます。

+
プロファイルを使用して（アーカイブログの個別バックアップを作成するために）データファイルとアーカイブログファイルのバックアップを作成し、データファイルのバックアップの作成に失敗した場合は、データバックアップとアーカイブログのバックアップではなく、処理名としてデータバックアップが送信されます。データファイルおよびアーカイブログファイルのバックアップ処理が成功すると、出力は次のようになります。

+
[listing]
----

Profile Name    : PROF_31
Operation Name 	: Data Backup and Archive Logs Backup
Database SID   	: TENDB1
Database Host 	 : repo1.rtp.org.com
Start Date 	    : Fri Sep 23 13:37:21 EDT 2011
End Date 	      : Fri Sep 23 13:45:24 EDT 2011
Status 	        : SUCCESS
Error messages 	:
----

