---
permalink: windows/task-cloning-a-database-to-an-alternate-host.html 
sidebar: sidebar 
keywords: clone, command, database, alternate, host, cloning 
summary: clone create コマンドを使用すると、代替ホスト上でデータベース・バックアップをクローニングできます。 
---
= 代替ホストへのデータベースのクローニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
clone create コマンドを使用すると、代替ホスト上でデータベース・バックアップをクローニングできます。

* プロファイルを作成するか、既存のプロファイルを用意します。
* フルバックアップを作成するか、既存のデータベースバックアップを用意します。
* クローン仕様を作成するか、既存のクローン仕様を用意します。


.ステップ
. 代替ホストにデータベースをクローニングするには、次のコマンドを入力します。
+
「SMSAP clone create -backup-backup-labelbackup_label_name -newsidnew_sid -hosttarget_host-labelclone_label -comment comment_text -profileprofileprofileprofileprofile_name -clonespfull_path_to_clonespecfile」を使用します

+
Oracle では、 SID が同じ 2 つのデータベースを、同じホスト上で同時に実行することはできません。そのため、クローンごとに新しい SID を指定する必要があります。ただし、同じ SID を持つデータベースを別のホストに配置することは可能です。



* 関連情報 *

xref:task-creating-profiles.adoc[プロファイルの作成]

xref:task-cloning-databases-from-backups.adoc[バックアップからデータベースをクローニングする]

xref:task-creating-clone-specifications.adoc[クローン仕様を作成しています]

xref:reference-the-smosmsapclone-create-command.adoc[SMSAPのclone createコマンドを使用します]
