---
permalink: windows/task-clear-user-credentials-for-all-hosts-repositories-and-profiles.html 
sidebar: sidebar 
keywords: clear, cache, credential, resource, host, repository, repositories, profile, delete, authenticate, host 
summary: リソース（ホスト、リポジトリ、およびプロファイル）のクレデンシャルのキャッシュをクリアできます。これにより、コマンドを実行しているユーザのリソースクレデンシャルがすべて削除されます。キャッシュをクリアしたら、クレデンシャルを再度認証して、これらのセキュアなリソースにアクセスできるようにする必要があります。 
---
= すべてのホスト、リポジトリ、およびプロファイルのユーザクレデンシャルを消去します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソース（ホスト、リポジトリ、およびプロファイル）のクレデンシャルのキャッシュをクリアできます。これにより、コマンドを実行しているユーザのリソースクレデンシャルがすべて削除されます。キャッシュをクリアしたら、クレデンシャルを再度認証して、これらのセキュアなリソースにアクセスできるようにする必要があります。

.手順
. クレデンシャルをクリアするには、SnapManager のCLIで「SMSAP credential clear」コマンドを入力するか、SnapManager のGUIで「* Admin *」>「* Credentials *」>「* Clear Cache *」を選択します。
. SnapManager GUI を終了します。
+
[NOTE]
====
** SnapManager GUI からクレデンシャルキャッシュをクリアした場合は、 SnapManager GUI を終了する必要はありません。
** SnapManager CLI からクレデンシャルキャッシュをクリアした場合は、 SnapManager GUI を再起動する必要があります。
** 暗号化されたクレデンシャルファイルを手動で削除した場合は、 SnapManager GUI を再起動する必要があります。


====
. クレデンシャルを再度設定するには、同じプロセスを繰り返して、リポジトリ、プロファイルホスト、およびプロファイルのクレデンシャルを設定します。ユーザクレデンシャルを再度設定する追加情報の場合は、「クレデンシャルキャッシュをクリアしたあとのクレデンシャルの設定」を参照してください。

