---
permalink: windows/task-reset-profile-password.html 
sidebar: sidebar 
keywords: reset, profile, password, remember 
summary: プロファイルの作成時に指定したパスワードがわからない場合は、プロファイルのパスワードをリセットできます。 
---
= プロファイルのパスワードをリセットします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プロファイルの作成時に指定したパスワードがわからない場合は、プロファイルのパスワードをリセットできます。



== 必要なもの

* SnapManager サーバがリポジトリデータベースで実行されていることを確認する必要があります。
* リポジトリデータベースが格納されているホストのローカル管理者のクレデンシャルが必要です。
* プロファイルのパスワードをリセットするときは、そのプロファイルがどの処理でも使用されていないことを確認してください。




== このタスクについて

パスワードは、 SnapManager の CLI または GUI からリセットできます。パスワードをリセットする際に、 SnapManager はリポジトリホスト上の SnapManager サーバを照会して、リポジトリホストのオペレーティングシステムを特定します。リポジトリホストに接続するための、許可されたユーザクレデンシャルを入力する必要があります。SnapManager サーバは、リポジトリデータベースのローカル管理者クレデンシャルを使用してユーザを認証します。認証が成功すると、 SnapManager は SnapManager サーバのプロファイルパスワードを新しいパスワードでリセットします。


NOTE: SnapManager は、パスワードのリセット操作の履歴を保持しません。

.ステップ
. 次のコマンドを入力して、プロファイルのパスワードをリセットします。
+
'*SMSAP password reset-profile_[-profile-password_profile_password_][-repository-hostadmin-password_admin_password_]*`


