---
permalink: windows/task-update-target-database-hostname-associated-with-a-profile.html 
sidebar: sidebar 
keywords: snapmanager, sap, provide, ability, update, host, name, target, database, profile, associate 
summary: SnapManager （3.2以降）for SAPでは、SnapManager プロファイルのターゲット・データベースのホスト名を更新できます。 
---
= プロファイルに関連付けられたターゲット・データベースのホスト名を更新します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager （3.2以降）for SAPでは、SnapManager プロファイルのターゲット・データベースのホスト名を更新できます。



== 必要なもの

* ローカルユーザのホームディレクトリには、プロファイルとリポジトリのマッピングが格納されている必要があります。
* SnapManager のグラフィカルユーザインターフェイス（ GUI ）セッションを終了する必要があります。




== このタスクについて

プロファイルを新しいホスト名で更新するには、 CLI を使用する必要があります。

* プロファイル * でターゲット・データベースのホスト名を変更するシナリオはサポートされていません

プロファイル内のターゲット・データベースのホスト名の変更では、次のシナリオはサポートされていません。

* SnapManager GUI を使用してターゲット・データベースのホスト名を変更する方法
* プロファイルのターゲットデータベースのホスト名を更新したあとに、リポジトリデータベースをロールバックする
* 1 つのコマンドを実行して、新しいターゲットデータベースホスト名に対する複数のプロファイルを更新する
* SnapManager 処理の実行中にターゲット・データベースのホスト名を変更する場合



NOTE: プロファイル内のターゲット・データベースのホスト名を更新すると、ターゲット・データベースのホスト名だけが変更されます。プロファイルに設定されている他の設定パラメータはすべて保持されます。

ターゲットデータベースのホスト名を更新したあとで、クローンまたはマウントされたバックアップが新しいホストで使用できない場合、バックアップを削除またはアンマウントできません。その場合、新しいホストから SnapManager 処理を実行すると、障害が発生したり、古いホストのエントリが古いエントリになったりすることがあります。SnapManager 操作を実行するには'profile updateを使用して'以前のホスト名に戻す必要があります

.手順
. 次のコマンドを入力します。
+
`* SMSAP profile update -profile update_profile_[-profile-password_profile_password_][-databname_db_dbname_host_host_[-sid_][-login-username db_username_password_db_password_db_password_db_port_][{-rman_duration]/[{-rman_duration]/[}rman_day] password-day][RMANパスワード[-day続く[RMANパスワード[RMANコマンド[RMANパスワード[RMANパスワード[RMAN _期間] [-comment_comment_][-snapname=pattery_pattery_][-summary-notification][-notification [-success -email_address1_,_email_address2_-subject_patter_][-failure-email_address1_,_email_address2_,_email_address2_address2_-subject_subject_pattery_pattern-day-アツ フ-day-アツ フ-アツ カイ-アツ ウチ[-dry_day_date-arch_アツ フ-アツ フ-arch_アツ ウチ-アツ フ-アツ フ-アツ フ-アツ ウチ]-アツ フ-アツ フ-アツ ウチ-アツ フ-アツ ウチ-アツ フ-アツ フ-アツ フ-アツ フ-アツ フ-アツ ファイル付き|-アツ フ-アツ フ-アツ フ付き|-アツ

+
このコマンドの他のオプションは、次のとおりです。

+
[`-force `][`-noprompt`]

+
[`quiet `|`-verbose ]

+
|===
| 状況 | 作業 


 a| 
* ターゲット・データベースのホスト名を変更します *
 a| 
「-host_new_db_host_`」を指定します

|===
. プロファイルのターゲット・データベースのホスト名を表示するには、次のコマンドを入力します。
+
「smsapprofile show」を参照してください


