---
permalink: windows/task-updating-target-database-hostname-associated-with-a-profile.html 
sidebar: sidebar 
keywords: snapmanager, sap, provide, ability, update, host, name, target, database, profile, updating, associate 
summary: SnapManager for SAPには、SnapManager プロファイルでターゲット・データベースのホスト名を更新できる機能があります。 
---
= プロファイルに関連付けられたターゲット・データベースのホスト名を更新しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager （3.2以降）for SAPでは、SnapManager プロファイルのターゲット・データベースのホスト名を更新できます。

* ローカルユーザのホームディレクトリには、プロファイルとリポジトリのマッピングが格納されている必要があります。
* SnapManager のグラフィカルユーザインターフェイス（ GUI ）セッションを終了する必要があります。


プロファイルを新しいホスト名で更新するには、 CLI を使用する必要があります。

* プロファイル * でターゲット・データベースのホスト名を変更するシナリオはサポートされていません

プロファイル内のターゲット・データベースのホスト名の変更では、次のシナリオはサポートされていません。

* SnapManager GUI を使用してターゲット・データベースのホスト名を変更する方法
* プロファイルのターゲットデータベースのホスト名を更新したあとに、リポジトリデータベースをロールバックする
* 1 つのコマンドを実行して、新しいターゲットデータベースホスト名に対する複数のプロファイルを更新する
* SnapManager 処理の実行中にターゲット・データベースのホスト名を変更する場合



NOTE: プロファイル内のターゲット・データベースのホスト名を更新すると、ターゲット・データベースのホスト名だけが変更されます。プロファイルに設定されている他の設定パラメータはすべて保持されます。

ターゲットデータベースのホスト名を更新したあとで、クローンまたはマウントされたバックアップが新しいホストで使用できない場合、バックアップを削除またはアンマウントできません。その場合、新しいホストから SnapManager 処理を実行すると、障害が発生したり、古いホストのエントリが古いエントリになったりすることがあります。SnapManager 処理を実行するには、プロファイルの更新を使用して、以前のホスト名に戻す必要があります。

.手順
. 次のコマンドを入力します。
+
smsapprofile update-profileprofile[-profile-passwordprofileprofileprofileprofileprofile_password][-datab_dbnamedb_dbdbname -host[jectsiddb_host][-login_usernamedb_username-passworddb -portdb_port]][{-rman-RMAN {-login-controlFile |password-usernamedrum_addressemst全員[-drum-email-email-password][-dursday][--email-email-email-email-email-password][-drster-password][--addressems[--addressemsembourme-mail-email-email-password][-dursday]-email-email-email-password][-dursday][--email-password][--email-email-email-email-password][-drman]-email-password][-drst全員 ウチ[--password][-dursday]-password][--password][--password][-dursday][--password][--password][--password][--password][-dursday][-dursday][-durb_

+
このコマンドの他のオプションは、次のとおりです。

+
[-force] [-nopromp]

+
|===
| 状況 | 作業 


 a| 
* ターゲット・データベースのホスト名を変更します *
 a| 
hostnew_db_host を指定します

|===
. プロファイルのターゲット・データベースのホスト名を表示するには、次のコマンドを入力します。
+
「smsapprofile show」を参照してください


