---
permalink: windows/task-update-the-existing-repository.html 
sidebar: sidebar 
keywords: update, exist, repository, upgrade, snapmanager, path 
summary: SnapManager 3.3.x から SnapManager 3.4 以降にアップグレードする場合、既存のリポジトリを更新する必要はありませんが、他のすべてのアップグレードパスでは、アップグレード後にアクセスできるように既存のリポジトリを更新する必要があります。 
---
= 既存のリポジトリを更新します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager 3.3.x から SnapManager 3.4 以降にアップグレードする場合、既存のリポジトリを更新する必要はありませんが、他のすべてのアップグレードパスでは、アップグレード後にアクセスできるように既存のリポジトリを更新する必要があります。



== 必要なもの

* アップグレードした SnapManager サーバを起動して確認しておく必要があります。
* 既存のリポジトリのバックアップが存在している必要があります。




== このタスクについて

* SnapManager 3.1 より前のバージョンから SnapManager 3.3 以降にアップグレードする場合は、まず SnapManager 3.2 にアップグレードする必要があります。
+
SnapManager 3.2 にアップグレードしたあと、 SnapManager 3.3 以降にアップグレードできます。

* リポジトリを更新すると、以前のバージョンの SnapManager ではそのリポジトリを使用できなくなります。


.ステップ
. 既存のリポジトリを更新します。
+
'*SMSAPリポジトリ・アップデート-repository-dbname_repository_service_name --host_repository_user_name --login-username_repository_user_name -port_repository_port_port_***リポジトリ・ユーザ名'リポジトリ・サービス名'およびリポジトリ・ホスト名には'英数字'マイナス記号'アンダースコア'ピリオドを使用できます**リポジトリポートには任意の有効なポート番号を使用できます。既存のリポジトリの更新時に使用されるその他のオプションは、次のとおりです。

+
** 「force」オプションを指定します
** noprompt`オプション
** 「quiet」オプション
** 「verbose」オプションです


+
* 例 *



[listing]
----
smsap repository update -repository -dbname HR1
-host server1 -login -username admin -port 1521
----


== 完了後

SnapManager サーバを再起動して、関連付けられているスケジュールをすべて再開します。
