---
permalink: unix-administration/concept-limitations.html 
sidebar: sidebar 
keywords: scenario, limitation, environment, snapmanager 
summary: 環境に影響する可能性があるシナリオと制限事項を把握しておく必要があります。 
---
= SnapManager で作業する際の制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
環境に影響する可能性があるシナリオと制限事項を把握しておく必要があります。

* データベースのレイアウトとプラットフォームに関する制限 *

* SnapManager は、ファイルシステム上の制御ファイルをサポートしますが、 raw デバイス上の制御ファイルはサポートしません。
* SnapManager は MSCS （ Microsoft クラスタリング）環境で動作しますが、 MSCS 構成の状態（アクティブまたはパッシブ）は認識されず、 MSCS クラスタ内のスタンバイサーバにリポジトリのアクティブ管理を転送しません。
* Red Hat Enterprise Linux （ RHEL ）および Oracle Enterprise Linux 4.7 、 5.0 、 5.1 、 5.2 、 5.3 では、マルチパスネットワーク I/O （ MPIO ）環境で動的マルチパス（ DMP ）を使用して raw デバイス経由で Oracle を導入する場合、 ext3 ファイルシステムはサポートされません。
+
この問題は、 SnapDrive で SnapManager 4.1 for UNIX 以前のバージョンを使用している場合にのみ使用されます。

* RHEL 上の SnapManager では、 * parted * ユーティリティを使用したディスクのパーティショニングはサポートされていません。
+
これは、 RHEL * Parted * ユーティリティを備えた問題です。

* RAC 構成で RAC ノード A からプロファイル名を更新すると、そのプロファイルのスケジュールファイルは RAC ノード A に対してのみ更新されます
+
RAC ノード B の同じプロファイルのスケジュールファイルは更新されず、以前のスケジュール情報が含まれます。ノード B からスケジュールされたバックアップがトリガーされると、以前のスケジュールファイルがノード B に含まれているため、スケジュールされたバックアップ処理は失敗します。ただし、プロファイル名が変更されたノード A から、スケジュールされたバックアップ処理は成功します。SnapManager サーバを再起動して、ノード B のプロファイルに関する最新のスケジュールファイルを受け取ることができます

* リポジトリ・データベースは、複数の IP アドレスを使用してアクセスできるホスト上に存在する場合があります。
+
複数の IP アドレスを使用してリポジトリにアクセスする場合は、 IP アドレスごとにスケジュールファイルが作成されます。IP アドレスのいずれか（ IP1 など）の下にあるプロファイル（プロファイル A など）のスケジュールバックアップが作成されると、その IP アドレスのスケジュールファイルだけが更新されます。プロファイル A が別の IP アドレス（ IP2 など）からアクセスされている場合、 IP2 のスケジュールファイルに IP1 で作成されたスケジュールのエントリがないため、スケジュールされたバックアップはリストに表示されません。

+
その IP アドレスとスケジュールファイルが更新されるのを待ってスケジュールがトリガーされるか、サーバを再起動します。



* SnapManager 構成に関する制限 *

* SnapDrive for UNIX では、特定のプラットフォーム上で、複数のタイプのファイルシステムとボリュームマネージャがサポートされます。
+
データベースファイルに使用するファイルシステムとボリュームマネージャは、 SnapDrive 構成ファイルにデフォルトのファイルシステムとボリュームマネージャとして指定する必要があります。

* SnapManager では、次の要件を持つ MultiStore ストレージシステム上のデータベースがサポートされます。
+
** MultiStore ストレージシステムのパスワードを設定するには、 SnapDrive を設定する必要があります。
** 基盤となるボリュームが同じ MultiStore ストレージ・システムに存在しない場合、 SnapDrive は MultiStore ストレージ・システムの qtree に常駐している LUN またはファイルの Snapshot コピーを作成できません。


* SnapManager では、単一のクライアント（ CLI と GUI の両方）から異なるポート上で実行されている 2 台の SnapManager サーバへのアクセスはサポートされていません。
+
ポート番号は、ターゲットホストとリモートホストで同じである必要があります。

* ボリューム内のすべての LUN は、ボリュームレベルまたは qtree 内に配置する必要がありますが、両方に配置することはできません。
+
これは、データが qtree に格納されていて、ボリュームをマウントした場合に、 qtree 内のデータが保護されないためです。

* SnapManager 処理は失敗し、リポジトリデータベースがダウンしていると GUI にアクセスできません。
+
SnapManager の処理を実行するときは、リポジトリデータベースが実行されていることを確認する必要があります。

* SnapManager は、 LPM （ Live Partition Mobility ）および LAM （ Live Application Mobility ）をサポートしていません。
* SnapManager は、 Oracle Wallet Manager および Transparent Data Encryption （ TDE ）をサポートしていません。
* Virtual Storage Console （ VSC ）ではまだ MetroCluster 構成がサポートされていないため、 SnapManager では raw デバイスマッピング（ RDM ）環境での MetroCluster 構成はサポートされません。


* プロファイル管理に関する制限 *

* アーカイブログバックアップを分離するようにプロファイルを更新すると、ホストでロールバック処理を実行できなくなります。
* GUI からプロファイルを有効にしてアーカイブ・ログ・バックアップを作成し、後で [ マルチプロファイル・アップデート ] ウィンドウまたは [ プロファイル・アップデート ] ウィンドウを使用してプロファイルを更新しようとしても、そのプロファイルを変更してフル・バックアップを作成することはできません。
* Multi Profile Update ウィンドウで複数のプロファイルを更新し、一部のプロファイルでは * Backup archivelogs separately * オプションが有効になっていて、その他のプロファイルではオプションが無効になっている場合、 * Backup archivelogs separately * オプションは無効になります。
* 複数のプロファイルを更新した場合に、一部のプロファイルで * Backup archivelogs separately * オプションが有効になっていて、他のプロファイルでオプションが無効になっていると、 Multi Profile Update ウィンドウの * Backup archivelogs separately * オプションが無効になります。
* プロファイルの名前を変更した場合、ホストをロールバックすることはできません。


* ローリングアップグレードまたはロールバック操作に関する制限 *

* リポジトリ内のホストでロールバック処理を実行せずに、以前のバージョンの SnapManager をホストにインストールしようとすると、次のことができない場合があります。
+
** 以前のバージョンまたは新しいバージョンの SnapManager で作成されたホストのプロファイルを表示します。
** 以前のバージョンまたは新しいバージョンの SnapManager で作成したバックアップまたはクローンにアクセスします。
** ホストでローリングアップグレードまたはロールバック処理を実行します。


* プロファイルを分けてアーカイブログバックアップを作成したあとで、関連するホストリポジトリでロールバック処理を実行することはできません。


* バックアップ操作に関する制限 *

* リカバリ中に、バックアップがすでにマウントされている場合、 SnapManager はバックアップを再マウントしないので、すでにマウントされているバックアップを使用します。
+
バックアップが別のユーザによってマウントされており、以前にマウントしたバックアップにアクセスできない場合は、そのユーザに権限を付与する必要があります。

+
すべてのアーカイブ・ログ・ファイルには、グループに割り当てられたユーザに対する読み取り権限があります。バックアップが別のユーザ・グループによってマウントされている場合は、アーカイブ・ログ・ファイルへのアクセス権限がない可能性があります。マウントされたアーカイブログファイルに対する権限をユーザが手動で付与し、リストアまたはリカバリ処理を再試行できます。

* SnapManager は、データベース・バックアップの Snapshot コピーの 1 つがセカンダリ・ストレージ・システムに転送される場合でも、バックアップ状態を「 protected 」として設定します。
* スケジュールされたバックアップには、 SnapManager 3.2 以降のタスク仕様ファイルのみを使用できます。
* SnapManager と Protection Manager の統合により、 SnapVault および qtree SnapMirror の場合、プライマリストレージ内の複数のボリュームをセカンダリストレージ内の 1 つのボリュームにバックアップできます。
+
セカンダリボリュームの動的なサイジングはサポートされていません。これの詳細については、『 Provisioning Manager and Protection Manager Administration Guide for Use with DataFabric Manager Server 3.8 』を参照してください。

* SnapManager では、ポストプロセススクリプトによるバックアップのバックアップはサポートされません。
* リポジトリデータベースが複数の IP アドレスを指していて、それぞれの IP アドレスが異なる場合、 1 つの IP アドレスに対するバックアップのスケジュール設定処理は成功しますが、もう 1 つの IP アドレスに対するバックアップのスケジュール設定処理は失敗します。
* SnapManager 3.4 以降にアップグレードしたあとに、 SnapManager 3.3.1 を使用したポストプロセススクリプトでスケジュールされたバックアップを更新することはできません。
+
既存のスケジュールを削除し、新しいスケジュールを作成する必要があります。



* リストア操作に関する制限 *

* リストア処理の実行に間接的に方法を使用し、リカバリに必要なアーカイブログファイルをセカンダリストレージシステムのバックアップでのみ使用できる場合、 SnapManager でデータベースをリカバリできません。
+
これは、 SnapManager がセカンダリストレージシステムのアーカイブログファイルのバックアップをマウントできないためです。

* SnapManager でボリュームリストア処理を実行した場合、対応するバックアップのリストア後に作成されたアーカイブログバックアップコピーはパージされません。
+
データファイルとアーカイブログファイルのデスティネーションが同じボリュームに存在する場合は、アーカイブログファイルのデスティネーションに使用できるアーカイブログファイルがない場合に、ボリュームのリストア処理によってデータファイルをリストアできます。このような場合、データファイルのバックアップ後に作成されたアーカイブログの Snapshot コピーは失われます。

+
アーカイブログデスティネーションからすべてのアーカイブログファイルを削除しないでください。



* クローン操作に関する制限 *

* クローンスプリット処理の進捗状況について、フレキシブルボリュームを含むストレージシステムで inode が検出されて処理される速度のため、 0~100 の数値を表示することはできません。
* SnapManager では、クローンスプリット処理が成功した場合にのみ E メールを受信することはサポートされていません。
* SnapManager でスプリットがサポートされるのは FlexClone のみです。
* リカバリの失敗が原因で、外部アーカイブログファイルの場所を使用する RAC データベースのオンラインデータベースバックアップをクローニングすると失敗します。
+
外部アーカイブログの場所からリカバリするアーカイブログファイルが Oracle で検出されて適用されないため、クローニングは失敗します。これは Oracle の制限事項です。詳細については、 Oracle バグ ID 13528007 を参照してください。Oracle では、デフォルト以外のにある場所からアーカイブログを適用しません http://metalink.oracle.com/["Oracle サポートサイト"^]。有効な Oracle Metalink ユーザ名とパスワードが必要です。

* SnapManager 3.3 以降では、 SnapManager 3.2 より前のリリースで作成されたクローン仕様 XML ファイルの使用はサポートされていません。
* 一時表領域がデータファイルの場所とは異なる場所に配置されている場合、クローン処理を実行すると、データファイルの場所に表領域が作成されます。
+
一時表領域が、データファイルの場所とは異なる場所にある Oracle Managed Files （ oMFS ）の場合、クローン処理ではデータファイルの場所に表領域が作成されません。oMFS は SnapManager によって管理されません。

* --resetlogsオプションを選択すると、SnapManager はRACデータベースのクローンを作成できません。


* アーカイブ・ログ・ファイルおよびバックアップに関する制限 *

* SnapManager では、フラッシュリカバリ領域のデスティネーションからアーカイブログファイルを削除することはできません。
* SnapManager は、スタンバイ・デスティネーションからのアーカイブ・ログ・ファイルの削除をサポートしていません。
* アーカイブログのバックアップは、保持期間とデフォルトの時間単位保持クラスに基づいて保持されます。
+
SnapManager の CLI または GUI を使用してアーカイブログバックアップの保持クラスを変更した場合、アーカイブログのバックアップは保持期間に基づいて保持されるため、変更した保持クラスはバックアップの対象とはみなされません。

* アーカイブログデスティネーションからアーカイブログファイルを削除すると、欠落しているアーカイブログファイルよりも古いアーカイブログファイルはアーカイブログバックアップに含まれません。
+
最新のアーカイブログファイルがない場合は、アーカイブログのバックアップ処理が失敗します。

* アーカイブ・ログ・デスティネーションからアーカイブ・ログ・ファイルを削除すると、アーカイブ・ログ・ファイルの削除に失敗します。
* SnapManager は、アーカイブログデスティネーションまたはアーカイブログファイルが破損した場合でも、アーカイブログバックアップを統合します。


* ターゲット・データベースのホスト名の変更に関する制限 *

ターゲットデータベースのホスト名を変更する場合、次の SnapManager 処理はサポートされません。

* SnapManager GUI からターゲット・データベースのホスト名を変更します。
* プロファイルのターゲットデータベースのホスト名を更新したあとに、リポジトリデータベースをロールバックする。
* 新しいターゲットデータベースのホスト名について、複数のプロファイルを同時に更新する。
* SnapManager 処理の実行中にターゲット・データベースのホスト名を変更する場合


* SnapManager CLI または GUI* に関する制限事項

* SnapManager GUIから生成される「profile create」操作用のSnapManager CLIコマンドには、履歴設定オプションはありません。
+
SnapManager CLIから履歴保持設定を構成するには'profile createコマンドは使用できません

* UNIX クライアントに使用できる Java Runtime Environment （ JRE ）がない場合、 Mozilla Firefox に SnapManager は GUI を表示しません。
* SnapManager CLI を使用してターゲットデータベースのホスト名を更新する際に、 SnapManager GUI セッションが 1 つ以上開いていると、開いている SnapManager GUI セッションすべてが応答しません。


* SnapMirror および SnapVault * に関する制限事項

* Data ONTAP 7-Mode を使用している場合は、 SnapVault ポストプロセススクリプトがサポートされません。
* ONTAP を使用している場合は、 SnapMirror 関係が確立されたボリュームで作成されたバックアップに Volume-Based SnapRestore （ VBSR ；ボリュームベースの SnapMirror ）を実行できません。
+
これは、 ONTAP の制限により、 VBSR で関係を解除できないためです。ただし、 SnapVault 関係が確立されているボリュームでのみ、最後または最後に作成されたバックアップに VBSR を実行できます。

* Data ONTAP 7-Modeを使用していて、SnapMirror関係が確立されたボリュームで作成されたバックアップに対してVBSRを実行する場合は、SnapDrive for UNIXで「override -vbsr -snapmirror-check」オプションを「* on *」に設定できます。
+
詳細については、 SnapDrive のマニュアルを参照してください。

* 場合によっては、ボリュームで SnapVault 関係が確立されていると、最初の Snapshot コピーに関連付けられていた最後のバックアップを削除できないことがあります。
+
バックアップを削除できるのは、関係を解除する場合のみです。この問題は、ベースの Snapshot コピーに関する ONTAP の制限が原因です。SnapMirror 関係では、ベースの Snapshot コピーは SnapMirror エンジンによって作成され、 SnapVault 関係では、ベースの Snapshot コピーは SnapManager を使用して作成されたバックアップです。ベースの Snapshot コピーは、更新のたびに、 SnapManager を使用して作成された最新のバックアップを参照します。



* Data Guard スタンバイ・データベースに関する制限 *

* SnapManager は、論理 Data Guard スタンバイデータベースをサポートしていません。
* SnapManager は、 Active Data Guard スタンバイデータベースをサポートしていません。
* SnapManager では、 Data Guard スタンバイデータベースのオンラインバックアップは許可されていません。
* SnapManager では、 Data Guard スタンバイデータベースのパーシャル・バックアップは許可されません。
* SnapManager では、 Data Guard スタンバイデータベースのリストアは許可されていません。
* SnapManager では、 Data Guard スタンバイ・データベースのアーカイブ・ログ・ファイルの削除は許可されません。
* SnapManager では、 Data Guard Broker はサポートされていません。


* 関連情報 *

http://mysupport.netapp.com/["のドキュメントについては、ネットアップサポートサイトを参照してください"^]
