---
permalink: unix-administration/concept-splitting-a-clone.html 
sidebar: sidebar 
keywords: snapmanager, enable, split, manage, clone, exist, flexclone, technology, data, block, database 
summary: SnapManager では、 FlexClone テクノロジを使用して作成された既存のクローンをスプリットして管理できます。FlexClone テクノロジでは、クローンと元のデータベースは同じ物理データブロックを共有します。 
---
= クローンのスプリット
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager では、 FlexClone テクノロジを使用して作成された既存のクローンをスプリットして管理できます。FlexClone テクノロジでは、クローンと元のデータベースは同じ物理データブロックを共有します。

クローンスプリット処理を実行する前に、スプリットされるクローンの推定サイズと、アグリゲートで使用可能なスペースを確認しておくことができます。

クローンスプリット処理が成功すると、 SnapManager によって新しいプロファイルが生成されます。SnapManager が新しいプロファイルの作成に失敗した場合は、手動で新しいプロファイルを作成できます。新しいプロファイルを使用すると、データベースのバックアップの作成、データのリストア、およびクローンの作成を行うことができます。クローンスプリット処理が成功した場合は、新しいプロファイルが作成されたかどうかに関係なく、クローン関連のメタデータがリポジトリデータベースから削除されます。

クローンのスプリットに関連して次のタスクを実行できます。

* クローンスプリットの見積もりを表示します。
* プライマリストレージ上のクローンをスプリットします。
* セカンダリストレージ上のクローンをスプリットします。
* クローンスプリット処理のステータスを表示します。
* クローンスプリット処理を停止します。
* プロファイルと基盤となるストレージを破棄します。
* スプリット・クローン用に作成されたプロファイルを削除します。


クローンを親ボリュームからスプリットすると、そのクローンボリュームに関連付けられている Snapshot コピーは削除されます。クローンスプリット処理の前にクローンデータベースに対して作成されたバックアップは使用できません。これらのバックアップの Snapshot コピーが削除され、バックアップはリポジトリ内の古いエントリのままになるためです。
