---
permalink: unix-administration/concept-snapshot-copy-naming.html 
sidebar: sidebar 
keywords: naming, name, snapshot, copy, convention, pattern, copies 
summary: 命名規則またはパターンを指定して、作成または更新するプロファイルに関連する Snapshot コピーを指定できます。すべての Snapshot コピー名にカスタムテキストを含めることもできます。 
---
= Snapshot コピーの命名規則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
命名規則またはパターンを指定して、作成または更新するプロファイルに関連する Snapshot コピーを指定できます。すべての Snapshot コピー名にカスタムテキストを含めることもできます。

Snapshot コピーの命名パターンは、プロファイルの作成時、またはプロファイルの作成後に変更できます。更新後のパターンは、まだ実行されていない Snapshot コピーにのみ適用されます。既存の Snapshot コピーには以前の snapname パターンが保持されます。

次の例は、ボリュームに対して作成された 2 つの Snapshot コピー名を示しています。表示された 2 つ目の Snapshot コピーの名前は、名前の途中に _F_H_1_in です。「 1 」は、バックアップセットで最初に作成された Snapshot コピーであることを示します。表示される最初の Snapshot コピーは最新のものであり、「 2 」が付いているため、 2 つ目の Snapshot コピーが作成されます。「 1 」 Snapshot コピーにはデータファイルが含まれ、「 2 」 Snapshot コピーには制御ファイルが含まれています。データファイルの Snapshot コピーのあとに制御ファイルの Snapshot コピーを作成する必要があるため、 2 つの Snapshot コピーが必要です。

[listing]
----
smsap_profile_sid_f_h_2_8ae482831ad14311011ad14328b80001_0
smsap_profile_sid_f_h_1_8ae482831ad14311011ad14328b80001_0
----
デフォルトのパターンには、次のように必要な smid が含まれます。

* デフォルトパターン：smsap_｛profile｝_｛db-sid｝_｛scope｝_｛mode｝_｛smid｝
* 例：smsap_my_profile_rac51_f_H_2_8abc01e915a55ac50115a55acc8d0001_0


Snapshot コピー名には、次の変数を使用できます。

[cols="1a,3a,2a"]
|===
| 変数名 | 説明 | 値の例 


 a| 
SMID （必須）
 a| 
Snapshot コピーの名前を作成する場合、 SnapManager の一意の ID だけが必要です。この ID により、一意の Snapshot 名が作成されます。
 a| 
8abc01e915a55ac50115a55acc8d0001_0



 a| 
クラス（オプション）
 a| 
プロファイルのバックアップに関連付けられた保持クラス。時間単位（ h ）、日単位（ d ）、週単位（ w ）、月単位（ m ）、または無制限（ u ）で指定します。
 a| 
D ： \



 a| 
コメント（オプション）
 a| 
プロファイルのバックアップに関連付けられたコメント。Snapshot コピー名が完了すると、このフィールドのスペースがアンダースコアに変換されます。
 a| 
SAMPLE_COMMENT_Spaces _ 置換済み



 a| 
日付（オプション）
 a| 
プロファイルに対してバックアップが実行される日付。必要に応じて、日付の値がゼロで埋められます。（ yyyymmdd ）
 a| 
20070218



 a| 
DB ホスト（オプション）
 a| 
作成または更新するプロファイルに関連付けられたデータベースのホスト名。
 a| 
my_host です



 a| 
db-name （オプション）
 a| 
作成する Snapshot コピーに関連付けられているデータベースの名前。
 a| 
RAC5



 a| 
db-sid （オプション）
 a| 
作成する Snapshot コピーに関連付けられているデータベース sid 。
 a| 
rac51



 a| 
ラベル（オプション）
 a| 
プロファイルのバックアップに関連付けられたラベル。
 a| 
SAMPLE_LABEL



 a| 
モード（オプション）
 a| 
バックアップがオンライン（ h ）とオフライン（ c ）のどちらで完了したかを示します。
 a| 
h



 a| 
プロファイル（オプション）
 a| 
作成するバックアップに関連付けられたプロファイルの名前。
 a| 
my_profile



 a| 
スコープ（オプション）
 a| 
バックアップがフル（ f ）であるかパーシャル（ p ）であるかを指定します。
 a| 
F



 a| 
時間（オプション）
 a| 
プロファイルに対してバックアップが実行される時間。この変数の時間値は 24 時間クロックを使用し、必要に応じてゼロで埋められます。たとえば、 5:32 および 8 秒は 053208 （ hhmmss ）と表示されます。
 a| 
170530



 a| 
タイムゾーン（オプション）
 a| 
ターゲットデータベースホストに指定されたタイムゾーン。
 a| 
概算値



 a| 
usertext （オプション）
 a| 
入力可能なカスタムテキスト。
 a| 
本番環境

|===

NOTE: SnapManager for SAPでは、Snapshotコピーの長い形式の名前にコロン（：）はサポートされません。
