---
permalink: unix-administration/concept-full-online-backups.html 
sidebar: sidebar 
keywords: full, online, backup, snapmanager, database, create, snapshot, copies, copy, volume, level, tablespace 
summary: フルオンラインバックアップでは、 SnapManager がデータベース全体をバックアップし、（表領域レベルではなく）ボリュームレベルで Snapshot コピーを作成します。 
---
= フルオンラインバックアップ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
フルオンラインバックアップでは、 SnapManager がデータベース全体をバックアップし、（表領域レベルではなく）ボリュームレベルで Snapshot コピーを作成します。

SnapManager は、バックアップごとに 2 つの Snapshot コピーを作成します。データベースに必要なすべてのファイルが 1 つのボリュームに格納されている場合は、そのボリューム内に両方の Snapshot コピーが表示されます。

フルバックアップを指定すると、 SnapManager は次の処理を実行します。

. データベース全体をオンライン・バックアップ・モードにします
. データベース・ファイルを含むすべてのボリュームの Snapshot コピーを作成します
. データベースのオンライン・バックアップ・モードを終了します
. ログ・スイッチを強制的に実行し、ログ・ファイルをアーカイブします
+
これにより、 REDO 情報もディスクにフラッシュされます。

. バックアップ制御ファイルを生成します
. ログファイルとバックアップ制御ファイルの Snapshot コピーが作成されます


フル・バックアップを実行する場合、 SnapManager はデータベース全体をオンライン・バックアップ・モードにします。個別の表領域（たとえば'/oracle/cer/sapdata1/system_1/system.data1）は'指定された特定の表領域またはデータ・ファイルよりも長いオンライン・バックアップ・モードになっています

データベースをバックアップモードにすると、 Oracle はブロック全体をログに書き込み、バックアップ間の差分だけを書き込むわけではありません。オンラインバックアップモードではデータベースの処理が増えるため、フルバックアップを選択するとホストの負荷が増大します。

フルバックアップを実行するとホストの負荷が増大しますが、フルバックアップで必要な Snapshot コピー数は少なくなり、必要なストレージ容量も少なくなります。
