---
permalink: unix-administration/concept-managing-profiles-for-efficient-backups.html 
sidebar: sidebar 
keywords: create, profile, snapmanager, database, operation, manage, managing, efficient 
summary: SnapManager で、処理を実行するデータベースのプロファイルを作成する必要があります。プロファイルを選択し、実行する処理を選択する必要があります。 
---
= 効率的なバックアップを行うためのプロファイルの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager で、処理を実行するデータベースのプロファイルを作成する必要があります。プロファイルを選択し、実行する処理を選択する必要があります。



== プロファイルに関連するタスク

次のタスクを実行できます。

* プロファイルを作成して、プライマリ、セカンダリ、さらにはターシャリストレージへのフルバックアップまたはパーシャルバックアップを有効にします。
+
プロファイルを作成して、アーカイブログのバックアップとデータファイルのバックアップを分けることもできます。

* プロファイルを確認します。
* プロファイルを更新します。
* プロファイルを削除します。




== プロファイルおよび認証について

プロファイルを作成するときに、データベースを指定し、データベースに接続するための次のいずれかの方法を選択できます。

* ユーザ名、パスワード、およびポートを使用した Oracle 認証
* ユーザ名、パスワード、またはポートを使用しない OS 認証。
+
OS 認証の場合は、 OS アカウントユーザおよびグループの情報を入力する必要があります。

+

NOTE: Real Application Cluster （ RAC ）データベースに OS 認証を使用するには、 RAC 環境の各ノードで SnapManager サーバを実行し、 RAC 環境内のすべての Oracle インスタンスでデータベースのパスワードを同じにする必要があります。SnapManager は、データベースのユーザ名とパスワードを使用して、プロファイル内のすべての RAC インスタンスに接続します。

* 「sqlnet.authentication_services`」が「*none*`」に設定されている場合のデータベース認証。SnapManager は、ターゲットデータベースへのすべての接続に、データベースのユーザ名とパスワードを使用します。
+

NOTE: Automatic Storage Management （ ASM ）インスタンスにデータベース認証を使用するには、 ASM インスタンスへのログインに使用するユーザ名とパスワードを入力する必要があります。



sqlnet.authentication_services`を'*none*'に設定できるのは'次の環境のみです

[cols="1a,1a,1a,1a"]
|===
| データベースレイアウト | Oracle のバージョン | ターゲットデータベースでサポートされているデータベース認証です | は、 ASM インスタンスでサポートされているデータベース認証です 


 a| 
ASM 以外および RAC 以外のデータベース
 a| 
Oracle 10g および Oracle 11g （ 11.2.0.3 未満）
 a| 
はい。
 a| 
いいえ



 a| 
UNIX 上のスタンドアロン ASM データベース
 a| 
Oracle 11.2.0.3 以降での「
 a| 
はい。
 a| 
はい。



 a| 
UNIX 上の RAC データベース上の ASM インスタンス
 a| 
Oracle 11.2.0.3 イコウ
 a| 
いいえ
 a| 
いいえ



 a| 
NFS 上の RAC データベース
 a| 
Oracle 11.2.0.3 イコウ
 a| 
はい。
 a| 
いいえ

|===

NOTE: sqlnet.authentication_services`を無効にし'認証方式をデータベース認証に変更した後'` sqlnet.authentication_services`を'*none*'に設定する必要があります

初めてプロファイルにアクセスする場合は、プロファイルのパスワードを入力する必要があります。クレデンシャルを入力すると、プロファイル内のデータベース・バックアップを表示できます。
