---
permalink: unix-administration/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, role-base, access, control, rbac, credential, management 
summary: SnapManager でセキュリティを管理するには、ユーザ認証とロールベースアクセス制御（ RBAC ）を適用します。ユーザ認証方式を使用すると、リポジトリ、ホスト、プロファイルなどのリソースにアクセスできます。RBAC を使用すると、データベース内のデータファイルが格納されたボリュームや LUN に対して SnapManager で実行できる処理を制限できます。 
---
= セキュリティと資格情報の管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager でセキュリティを管理するには、ユーザ認証とロールベースアクセス制御（ RBAC ）を適用します。ユーザ認証方式を使用すると、リポジトリ、ホスト、プロファイルなどのリソースにアクセスできます。RBAC を使用すると、データベース内のデータファイルが格納されたボリュームや LUN に対して SnapManager で実行できる処理を制限できます。

コマンドラインインターフェイス（ CLI ）またはグラフィカルユーザインターフェイス（ GUI ）を使用して処理を実行すると、 SnapManager はリポジトリおよびプロファイルに設定されているクレデンシャルを取得します。SnapManager は以前のインストールのクレデンシャルを保存します。

リポジトリとプロファイルは、パスワードで保護できます。クレデンシャルとは、ユーザがオブジェクト用に設定したパスワードであり、パスワードはオブジェクト自体には設定されません。

認証とクレデンシャルを管理するには、次のタスクを実行します。

* ユーザ認証は、操作時にパスワードプロンプトを使用するか、または「smsapscredential set」コマンドを使用して管理します。
+
リポジトリ、ホスト、またはプロファイルのクレデンシャルを設定する

* アクセスできるリソースを制御するクレデンシャルを表示します。
* すべてのリソース（ホスト、リポジトリ、およびプロファイル）について、ユーザのクレデンシャルをクリアします。
* 個々のリソース（ホスト、リポジトリ、およびプロファイル）に対するユーザのクレデンシャルを削除する。


ロールベースアクセスを管理するには、次のタスクを実行します。

* SnapDrive を使用して RBAC for SnapManager を有効にします。
* Operations Manager コンソールを使用して、ユーザをロールに割り当て、ロール機能を設定します。
* 必要に応じて、「SMSAP_CONFIG FILE」を編集して、暗号化されたパスワードをSnapManager に格納できるようにします。


Protection Manager がインストールされている場合、次の方法で機能へのアクセスに影響します。

* Protection Manager がインストールされている場合は、データベースプロファイルの作成時に、 SnapManager によってデータセットが作成され、データベースファイルが格納されたボリュームがデータセットに読み込まれます。
+
バックアップ処理の完了後、 SnapManager はデータセットの内容をデータベースファイルと同期させたままにします。

* Protection Manager がインストールされていないと、 SnapManager でデータセットを作成することはできず、プロファイルに対して保護を設定することもできません。

