---
permalink: unix-administration/concept-database-backup-management.html 
sidebar: sidebar 
keywords: snapmanager, enable, data, local, storage, resource, post-processing, script, protect, secondary, tertiary, additional, layer, disaster, back, up, database 
summary: SnapManagerを使用すると、ポストプロセススクリプトを使用したり、セカンダリストレージリソースやターシャリストレージリソースのバックアップを保護したりして、ローカルストレージリソースのデータをバックアップできます。セカンダリストレージにバックアップするように選択すると、災害発生時にデータを保持するためのレイヤが追加で提供されます。 
---
= データベースをバックアップしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager では、ポストプロセススクリプトを使用してセカンダリストレージリソースまたはターシャリストレージリソースのバックアップを保護することにより、ローカルストレージリソース上のデータをバックアップできます。セカンダリストレージにバックアップするように選択すると、災害発生時にデータを保持するためのレイヤが追加で提供されます。

また、ストレージ管理者は、ポリシー計画に基づいてバックアップを設定することもできます。 SnapManager管理者は、 SnapManager を使用して、ポリシーの要件に合わないバックアップを特定し、すぐに修正できます。

SnapManager には、データベースのデータをバックアップ、リストア、およびリカバリするための次のオプションがあります。

* データベース全体またはその一部をバックアップする。
+
一部をバックアップする場合は、表領域またはデータ・ファイルのグループを指定します。

* データファイルとアーカイブログファイルは別々にバックアップします。
* データベースをプライマリストレージ（ローカルストレージ）にバックアップし、セカンダリストレージまたはターシャリストレージ（リモートストレージとも呼ばれます）にバックアップすることで保護します。
* ルーチンバックアップのスケジュールを設定する。


* SnapManager （ 3.2 以降）と以前の SnapManager バージョン * との違い

SnapManager （ 3.1 以前）では、データファイル、制御ファイル、およびアーカイブログファイルを含むフルデータベースバックアップを作成できます。

SnapManager （ 3.1 以前）は、データファイルのみを管理します。アーカイブログファイルは、 SnapManager 以外のソリューションを使用して管理されます。

SnapManager （ 3.1 以前）では、データベース・バックアップの管理に次の制限があります。

* パフォーマンスへの影響
+
フルオンラインのデータベースバックアップを実行すると（データベースがバックアップモードの場合）、バックアップが作成されるまでの期間はデータベースのパフォーマンスが低下します。SnapManager （ 3.2 以降）では、制限されたデータベース・バックアップおよび短周期アーカイブ・ログ・バックアップを作成できます。頻繁なアーカイブログバックアップを作成すると、データベースをバックアップモードにできなくなります。

* 手動によるリストアとリカバリ
+
必要なアーカイブログファイルがアクティブファイルシステムにない場合、データベース管理者は、アーカイブログファイルが格納されているバックアップを特定し、データベースバックアップをマウントし、リストアされたデータベースをリカバリする必要があります。このプロセスには時間がかかります。

* スペース拘束
+
データベースバックアップが作成されると、アーカイブログのデスティネーションがいっぱいになり、ストレージに十分なスペースが作成されるまでデータベースが応答しなくなります。SnapManager （ 3.2 以降）では、アクティブファイルシステムからアーカイブログファイルを削除することにより、定期的にスペースを解放できます。



* アーカイブ・ログ・バックアップが重要な理由 *

アーカイブログファイルは、リストア処理の実行後にデータベースをロールフォワードするために必要です。Oracle データベース上のすべてのトランザクションは、アーカイブログファイルにキャプチャされます（データベースがアーカイブログモードの場合）。データベース管理者は、アーカイブログファイルを使用してデータベースバックアップをリストアできます。

* アーカイブログのみのバックアップの利点 *

* アーカイブログのみのバックアップに対して、別々の保持期間を提供します
+
リカバリに必要なアーカイブログのみのバックアップの保持期間を短縮できます。

* アーカイブログ保護ポリシーに基づいてアーカイブログのみのバックアップを保護します
+
アーカイブログのみのバックアップには、要件に基づいて異なる保護ポリシーを選択できます。

* データベースのパフォーマンスが向上します
* アーカイブログバックアップを統合します
+
SnapManager は、重複するアーカイブログのバックアップを解放することによって、バックアップを作成するたびにアーカイブログのバックアップを統合します。


