---
permalink: unix-administration/concept-what-snapmanager-operation-states-are.html 
sidebar: sidebar 
keywords: snapmanager, operation, backup, restore, clone, state 
summary: SnapManager 処理（バックアップ、リストア、およびクローニング）はさまざまな状態になり、各状態が処理の進捗状況を示します。 
---
= SnapManager の動作状態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager 処理（バックアップ、リストア、およびクローニング）はさまざまな状態になり、各状態が処理の進捗状況を示します。

[cols="1a,4a"]
|===
| 処理の状態 | 説明 


 a| 
成功しました
 a| 
処理が完了しました。



 a| 
実行中です
 a| 
処理は開始されましたが、完了していません。たとえば、 2 分かかるバックアップは、午前 11 時に実行されるようにスケジュールされています。午前 11 時 01 分に * Schedule * タブを表示すると、処理は running と表示されます。



 a| 
操作が見つかりません
 a| 
スケジュールが実行されていないか、最後に実行されたバックアップが削除されています。



 a| 
失敗しました
 a| 
処理に失敗しました。SnapManager によって中止プロセスが自動的に実行され、処理がクリーンアップされました。


NOTE: 作成したクローンをスプリットできます。開始したクローンスプリット処理を停止し、処理が正常に停止されると、クローンスプリット処理の状態は「 failed 」と表示されます。

|===


== リカバリ可能およびリカバリ不能なイベント

リカバリ可能な SnapManager イベントには、次の問題があります。

* データベースは、 Data ONTAP を実行するストレージ・システムには保存されません。
* SnapDrive for UNIX がインストールされていないか、ストレージ・システムにアクセスできません。
* ボリュームのスペースが不足している場合、 Snapshot コピーが最大数に達している場合、または予期しない例外が発生した場合、 SnapManager は Snapshot コピーの作成またはストレージのプロビジョニングに失敗します。


リカバリ可能なイベントが発生すると、 SnapManager は中断プロセスを実行し、ホスト、データベース、およびストレージシステムを開始状態に戻します。中断プロセスに失敗すると、 SnapManager はこのインシデントをリカバリ不能なイベントとみなします。

リカバリ不能な（アウトオブバンドの）イベントは、次のいずれかの状況で発生します。

* ホスト障害などのシステム問題が発生した場合。
* SnapManager プロセスが停止します。
* ストレージシステムに障害が発生した場合、論理ユニット番号（ LUN ）またはストレージボリュームがオフラインになった場合、またはネットワークに障害が発生した場合は、インバンドの中断処理が失敗します。


回復不能なイベントが発生すると、 SnapManager はただちに中断プロセスを実行します。ホスト、データベース、およびストレージシステムが初期状態に戻らない可能性があります。その場合は、孤立した Snapshot コピーを削除して SnapManager ロックファイルを削除することで、 SnapManager 処理が失敗したあとにクリーンアップを実行する必要があります。

SnapManager ロック・ファイルを削除する場合は'ターゲット・マシン上の$ORACLE_HOMEに移動し'SM_LOCK_TargetDBName_ファイルを削除しますファイルを削除したら、SnapManager for SAPサーバを再起動する必要があります。
