---
permalink: unix-administration/concept-general-layout-and-configuration.html 
sidebar: sidebar 
keywords: recommend, general, database, layout, storage, configuration, help, avoid, issue, relate, disk, group, file, type, tablespace 
summary: 推奨される一般的なデータベースレイアウトとストレージ構成を把握しておくと、ディスクグループ、ファイルタイプ、表領域に関する問題の回避に役立ちます。 
---
= 一般的なデータベースレイアウトとストレージ構成を推奨します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
推奨される一般的なデータベースレイアウトとストレージ構成を把握しておくと、ディスクグループ、ファイルタイプ、表領域に関する問題の回避に役立ちます。

* 複数のタイプの SAN ファイルシステムまたはボリュームマネージャのファイルをデータベースに含めないでください。
+
データベースを構成するすべてのファイルは、同じタイプのファイルシステム上に存在している必要があります。

* SnapManager には 4K ブロックのサイズが複数必要です。
* 「oratab」ファイルにデータベース・システム識別子を含めます。
+
管理対象の各データベースの「oratab」ファイル内にエントリを含めます。SnapManager は'oratabファイルに依存して'使用するOracleホームを判別します



新しいボリュームベースのリストアまたはディスクグループ全体のリストアを利用する場合は、ファイルシステムとディスクグループに関連する次のガイドラインを考慮してください。

* データファイルが含まれるディスクグループに他の種類のファイルを含めることはできません。
* データファイルディスクグループの Logical Unit Number （ LUN ；論理ユニット番号）は、ストレージボリューム内の唯一のオブジェクトである必要があります。


ボリュームを分離する際のいくつかのガイドラインを次に示します。

* ボリュームに格納できるのは、 1 つのデータベースのデータファイルだけです。
* データベースバイナリ、データファイル、オンライン REDO ログファイル、アーカイブ REDO ログファイル、および制御ファイルという分類のファイルごとに、別々のボリュームを使用する必要があります。
* SnapManager では一時データベースファイルがバックアップされないため、一時データベースファイル用に別のボリュームを作成する必要はありません。


SAPでは、Oracleデータベースのインストールに標準的なレイアウトを使用します。このレイアウトでは、SAPはOracle制御ファイルのコピーを「E：\Oracle\SID\origlogA」、「E：\Oracle\SID\origlogB」、「E：\Oracle\SID\sapdata1 file systems」に配置します。

sapdata1ファイルシステムに制御ファイルが配置されていると、制御ファイルとデータファイルを別々のボリュームに分離するためのSnapManager の要件と矛盾するため、高速リストア機能を使用するためには配置先を変更する必要があります。


NOTE: BR * Toolsバックアップには、OracleインストールのdbsサブディレクトリにあるOracleプロファイルとSAPプロファイルが含まれているため、Oracleをストレージにインストールする必要があります。

新規導入の場合、SAPinstを使用して制御ファイルの場所を変更し、sapdata1ファイルシステムに通常配置されている制御ファイルを、データファイルとは異なるファイルシステムに移動することができます。（SAPinstはSAPシステム導入ツールです）。

ただし、すでにインストールされているシステムの場合は、SnapManager を使用した高速リストアを実行するために、制御ファイルをファイルシステムから移動する必要があります。これを行うには、データファイルが含まれていないボリュームに新しいファイルシステムを作成し、そのファイルシステムに制御ファイルを移動して、前のファイルシステムから新しいファイルシステムのディレクトリへのシンボリックリンクを作成します。データベースエラーを回避するために、制御ファイルを移動する際には、SAPとOracleデータベースを停止する必要があります。

変更を行う前に、制御ファイルが格納されているsapdata1ディレクトリ内のファイルのリストが次のようになります。

[listing]
----
hostname:/
#  ls -l /oracle/SID/sapdata1/cntrl
-rw-r----- 1 orasid  dba  9388032 Jun 19 01:51 cntrlSID.dbf
----
変更後のリストは次のようになります。

[listing]
----
hostname:/
# ls -sl /oracle/SID/sapdata1
0 lrwxrwxrwx 1 root root 19 2008-08-06 14:55 cntrl -> /oracle/SID/control
0 -rw-r--r-- 1 root root 0 2008-08-06 14:57 data01.dbf

# ls -sl /oracle/SID/control
0 -rw-r--r-- 1 root root 0 2008-08-06 14:56 cntrlSID.dbf
----