---
permalink: unix-administration/concept-profile-usage-for-br-tools-backups.html 
sidebar: sidebar 
keywords: backint, snapmanager, profile, repository, backup 
summary: 'backintインターフェイスを使用するBR * Toolsコマンドを実行すると、SnapManager ではリポジトリのプロファイルが使用されます。リポジトリは"BR * Toolsコマンドを実行しているユーザーのSnapManager 資格情報によって決定されます' 
---
= BR * Toolsバックアップのプロファイルの使用方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
backintインターフェイスを使用するBR * Toolsコマンドを実行すると、SnapManager ではリポジトリのプロファイルが使用されます。リポジトリは'BR * Toolsコマンドを実行しているユーザーのSnapManager 資格情報によって決定されます

デフォルトでは、SnapManager はSAPデータベースシステムIDと同じ名前のプロファイルを使用します。



== リポジトリにアクセスするためのクレデンシャルの作成について

「SMSAP credential set」コマンドを使用してBR * Toolsユーザのリポジトリクレデンシャルを設定できます。



== 別のSnapManager プロファイル名の指定について

SnapManager プロファイルが特定のリポジトリ内にあるすべてのホストでシステム識別子が一意であるかぎり、デフォルトのプロファイル名で十分です。SnapManager プロファイルを作成し、データベースシステムIDの値を使用して名前を付けることができます。

ただし、同じシステムIDを別々のホストで使用する場合、または特定のSAPインスタンスのBR * Toolsで使用する複数のSnapManager プロファイルを指定する場合は、BR * Toolsコマンドのプロファイル名を定義する必要があります。

SAPアプリケーション内でスケジュールされたデータベース処理は、ユーザとして実行されます。BR * SAPアプリケーション内でスケジュールされたツールの操作は'sidadmとして実行されますこれらのユーザには、リポジトリおよびプロファイルへのアクセス権が必要です。

ユーザのクレデンシャルを設定するには、次の手順を実行します。

. 「sidadm」としてログインします。
. 次のコマンドを入力して、リポジトリのクレデンシャルを設定します。
+
「* SMSAP credential setコマンド*」を使用します

. 次のコマンドを入力して、プロファイルを同期します。
+
「* SMSAP profile sync *」と表示されます

. 次のコマンドを入力して、検出されたプロファイルのパスワードを設定します。
+
'*SMSAPのクレデンシャル・セット*





== バックアップユーティリティのパラメータファイルの作成について

BR * Toolsコマンドでは、オプションでバックアップユーティリティのパラメータ（.utlパラメータ）ファイルをbackintインターフェイスに渡すこともできます。デフォルトでは'このファイルの名前はinitSID.utl'ですここで'sidはデータベースのシステム識別子です

デフォルトでは'BR * Toolsは'initSID.sapファイルの'_util_par_file'パラメータで指定されたパラメータ・ファイルを使用しますバックアップ・ユーティリティのパラメータ・ファイルは通常'initSID.sapファイルと同じディレクトリに格納されます

'profile_name=<profile>'を'.utl`ファイルに追加して保存します`_profile_`は'BR*Toolsコマンドに使用するSnapManager プロファイルの名前です

次の表に'バックアップの保存'高速リストア'データ保護などのオペレーション用に'.utl'ファイルに含まれる追加のバックアップ・ユーティリティ・パラメータを示します

[cols="1a,3a"]
|===
| 処理 | バックアップユーティリティのパラメータ 


 a| 
バックアップの保持
 a| 
* キー：retain
* 値：unlimited | hourly | daily | weekly | monthly




 a| 
高速リストア
 a| 
* キー：高速
* 値：require|override|fallback|off




 a| 
データ保護
 a| 
* キー：保護
* 値：yes | no | left blank



NOTE: valueパラメータに指定されているオプションは'コマンド・ライン・インターフェイスで使用される-protectオプションと似ています



 a| 
ユーザの設定に従って、セカンダリストレージから設定された場所にデータをバックアップします
 a| 
* キー：preferred_backup_locations
* Value：データ保護ノード名をカンマで区切ったリストとして指定します。
* デフォルト：値は設定されていません。



NOTE: データ保護ポリシーのノード名については、を参照してください xref:concept-about-different-protection-policies.adoc[保護ポリシーの説明について]。



 a| 
セカンダリストレージから任意の場所にデータをリストアします
 a| 
* キー：restore_from_nearest_backup_location
* 値：yes | no
* デフォルト：はい


|===
次の表に、これらの処理のさまざまなバックアップユーティリティパラメータを示します。

[cols="1a,1a,1a"]
|===
| 操作 | キーを押します | 価値 


 a| 
バックアップの保持
 a| 
速い=
 a| 
フォールバック



 a| 
高速リストア
 a| 
保持=
 a| 
毎時



 a| 
データ保護
 a| 
保護=
 a| 
いいえ

|===


== BR * Tools初期化ファイルへのバックアップ・ユーティリティ・パラメータの追加

SAPは'$ORACLE_HOME/dbs/dbsの各SAPデータベース・インスタンスに'initSID.sap'という名前のバックアップ・プロファイル・ファイルを作成しますこのファイルを使用して'BR*Toolsコマンドに使用するデフォルトのバックアップ・ユーティリティ・パラメータ(`.utl')ファイルを指定できます

. initSID.sapファイルを編集し'util_par_file=で始まる行を探します
. この行のコメントを解除し'プロファイル名を含むバックアップ・ユーティリティ・パラメータ・ファイルへのパスを追加しますたとえば'util_par_file=initSA1.utl'のようにします
. 'util_par_file'に値を指定する場合は'ファイルが存在することを確認してください
+
ファイルが見つからない場合、BRBACKUPコマンドはそのファイルをバックアップに含めようとするので失敗します。



次のいずれかのエラー条件が見つかった場合は'プロファイル名として-uオプションを使用する必要があります

* 'parameter files does not exist'
* 「profile_nameエントリがありません」というメッセージが表示されます


orasidとsidadmはいずれも'BR*Toolsで作成されたバックアップの作成または管理に使用されるプロファイルへのアクセスを必要とします



== BR * Toolsコマンドでバックアップ・ユーティリティのパラメータ・ファイル名を指定する

オプションで'-rオプションを使用してBR * Toolsコマンドでバックアップ・ユーティリティ・パラメータ（.utlパラメータ）ファイルを指定できますコマンドラインの値は、SAP初期化ファイルで指定されている値よりも優先されます。

BR * Toolsは「$ORACLE_HOME/dbs/`」ディレクトリ内のパラメータ・ファイルを検索します。ファイルを別の場所に保存する場合は、-rオプションを使用してフルパスを指定する必要があります。例：

`*+brbackup -r /opt/NetApp/FCP_PRICE_10g_enterprise-vol1/dbs/initCER.utl...+*`
