---
permalink: unix-administration/concept-backup-schedule-and-retention-strategy.html 
sidebar: sidebar 
keywords: dba, ensure, backup, loss, data, disaster, regulatory, reason, retention, policy, database, schedule 
summary: データベース管理者は、データ損失や災害発生時のバックアップ、規制上の理由から、バックアップを確実に利用できるようにしたいと考えています。そのためには、さまざまなデータベースの保持ポリシーを慎重に検討する必要があります。 
---
= バックアップのスケジュールと保持に関する戦略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データベース管理者は、データ損失や災害発生時のバックアップ、規制上の理由から、バックアップを確実に利用できるようにしたいと考えています。そのためには、さまざまなデータベースの保持ポリシーを慎重に検討する必要があります。

生産給与データベースの場合、 DBA は次の TechCo 保持方針に従っています。

[cols="1a,1a,1a,1a"]
|===
| バックアップ頻度 | 保持期間 | バックアップ時間 | ストレージのタイプ 


 a| 
1 日 1 回
 a| 
10 日
 a| 
午後 7 時
 a| 
プライマリ（ローカル）



 a| 
1 日 1 回
 a| 
10 日
 a| 
午後 7 時
 a| 
セカンダリ（アーカイブ）



 a| 
週に 1 回
 a| 
52 週間
 a| 
土曜日の午前 1 時
 a| 
セカンダリ（アーカイブ）

|===
* * ローカルバックアップの利点 *
+
毎日のローカルバックアップでは、データベースを瞬時に保護できます。データベースの帯域幅はゼロで、追加ストレージスペースを最小限使用します。また、リストアは瞬時に実行され、バックアップとリストアの機能もきめ細かく実行できます。

+
給与データベースの最終週ごとのバックアップは、セカンダリストレージサイトで少なくとも 52 週間保持されるため、 10 日を超える日ごとのバックアップを保持する必要はありません。

* * 保護されたバックアップの利点 *
+
リモートサイトのセカンダリストレージへの日次バックアップと週次バックアップでは、プライマリストレージサイトのデータが破損してもターゲットデータベースは引き続き保護され、セカンダリストレージからリストアできることが保証されます。

+
プライマリストレージシステムの損傷を防ぐために、セカンダリストレージへの日次バックアップが作成されます。給与データベースの最終週ごとのバックアップは 52 週間以上保持されるため、毎日のバックアップを 10 日以上保持する必要はありません。


