---
permalink: unix-administration/concept-what-protection-states-are.html 
sidebar: sidebar 
keywords: snapmanager, state, backup, administrator, monitor, protection 
summary: SnapManager には、各バックアップの状態が表示されます。管理者は、さまざまな状態を把握し、バックアップの状態を監視する必要があります。 
---
= 保護状態とは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager には、各バックアップの状態が表示されます。管理者は、さまざまな状態を把握し、バックアップの状態を監視する必要があります。

データベースバックアップには、次の保護状態があります。

[cols="1a,2a,3a"]
|===
| ステータス | 定義（ Definition ） | 説明 


 a| 
保護
 a| 
保護が要求され、有効になりました。
 a| 
SnapManager のバックアップの保護が有効になり、 Protection Manager によって、別の物理ディスクセット（セカンダリストレージとも呼ばれます）にバックアップがコピーされました。保持ポリシーのために Protection Manager によってセカンダリストレージからバックアップが削除された場合、そのバックアップは保護されていない状態に戻ることがあります。



 a| 
保護されていない
 a| 
保護が要求されましたが、完了していません。
 a| 
バックアップの保護は有効ですが、バックアップは別の物理ディスクセットにコピーされません。バックアップがまだ保護されていないか、保護に失敗しているか、以前に保護されていたが保護されなくなっています。バックアップの作成時に、バックアップの初期保護状態が要求されていないか保護されていません。保護されていないバックアップは、セカンダリストレージに転送されるときに保護されます。



 a| 
要求されていません
 a| 
保護は要求されませんでした。
 a| 
バックアップの保護が有効になっていません。データの論理コピーは、同じ物理ディスクに存在します（ローカルバックアップとも呼ばれます）。バックアップ作成時に保護が要求されなかった場合、バックアップ上の保護は常に要求されなかった保護として表示されます。

|===