---
permalink: unix-administration/concept-restoring-database-backup.html 
sidebar: sidebar 
keywords: snapmanager, sap, enable, restore, database, state, snapshot, copy, addition, file-base, restoring, backup, mean-time-to-recoverr, mttr 
summary: SnapManager for SAPでは、データベースをSnapshotコピーが作成されたときの状態にリストアできます。SnapManager では、ファイルベースのリストアプロセスに加えて、ボリュームベースの高速リストアテクノロジがサポートされているため、他のリカバリ方法に比べてリストア時間が大幅に短縮されます。バックアップはより頻繁に作成されるため、適用する必要があるログの数が少なくなり、データベースの平均リカバリ時間（ MTTR ）が短縮されます。 
---
= データベースバックアップのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager for SAPでは、データベースをSnapshotコピーが作成されたときの状態にリストアできます。SnapManager では、ファイルベースのリストアプロセスに加えて、ボリュームベースの高速リストアテクノロジがサポートされているため、他のリカバリ方法に比べてリストア時間が大幅に短縮されます。バックアップはより頻繁に作成されるため、適用する必要があるログの数が少なくなり、データベースの平均リカバリ時間（ MTTR ）が短縮されます。

データベース内のデータのリストアとリカバリに関連して実行できるタスクの一部を次に示します。

* ファイルベースのリストアまたはボリュームベースのリストアを実行します。これは、データベースバックアップのリストアに最も適した方法であり、 SnapManager が使用するデフォルトのリストアです。
* バックアップ全体またはバックアップの一部をリストアできます。
+
一部をリストアする場合は、表領域またはデータ・ファイルのグループを指定します。制御ファイルは、データとともにリストアすることも、制御ファイル自体だけをリストアすることもできます。

* 特定の時点またはデータベースにコミットされた最後のトランザクションを格納している使用可能なすべてのログに基づいてデータをリカバリします。
+
特定の瞬間を指定する場合は、 Oracle System Change Number （ SCN ）または日付と時刻（ yyyy-mm-dd ： hh ： mm ： ss ）で指定します。SnapManager は 24 時間方式のクロックを使用します。

* プライマリストレージ上のバックアップからのリストア（ローカルバックアップ）
* SnapManager を使用してバックアップをリストアおよびリカバリするか、 SnapManager を使用してバックアップをリストアし、 Recovery Manager （ RMAN ）などの別のツールを使用してデータをリカバリします。
* 別の場所からバックアップをリストアする。
* リストア仕様ファイルを使用して、保護されたバックアップをセカンダリストレージ（リモートバックアップ）から、または別の場所からリストアします。


SnapManager 3.0 以降のバージョンを使用して、以前のバージョンの SnapManager で作成されたバックアップをリストアできます。

管理者は、 SnapManager のグラフィカルユーザインターフェイス（ GUI ）またはコマンドラインインターフェイス（ CLI ）を使用して、リストア処理またはリカバリ処理を実行できます。
