---
permalink: unix-administration/concept-what-full-and-partial-backups-are.html 
sidebar: sidebar 
keywords: entire, database, portion, tablespace, data, file, full, partial, backup 
summary: データベース全体をバックアップすることも、データベースの一部だけをバックアップすることもできます。データベースの一部をバックアップするように選択した場合は、表領域またはデータ・ファイルのグループをバックアップするように選択できます。表領域とデータ・ファイルの両方について、個別のバックアップを作成することもできます。 
---
= フル・バックアップおよびパーシャル・バックアップとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データベース全体をバックアップすることも、データベースの一部だけをバックアップすることもできます。データベースの一部をバックアップするように選択した場合は、表領域またはデータ・ファイルのグループをバックアップするように選択できます。表領域とデータ・ファイルの両方について、個別のバックアップを作成することもできます。

次の表に、各タイプのバックアップのメリットと結果を示します。

[cols="1a,2a,2a"]
|===
| バックアップタイプ | 利点 | 欠点 


 a| 
フル
 a| 
Snapshot コピーの数を最小限に抑えます。オンライン・バックアップでは、バックアップ処理の実行中、各表領域がバックアップ・モードになります。SnapManager は、データベースが使用するボリュームごとに 1 つの Snapshot コピーと、ログファイルを含むボリュームごとに 1 つの Snapshot コピーを作成します。
 a| 
オンライン・バックアップでは、バックアップ処理の実行中、各表領域がバックアップ・モードになります。



 a| 
一部有効です
 a| 
各表領域がバックアップ・モードに費やす時間を最小限に抑えます。SnapManager は、作成した Snapshot コピーを表領域単位でグループ化します。各表領域がバックアップ・モードになるのは、 Snapshot コピーを作成するのに十分な時間だけです。このように Snapshot コピーをグループ化することで、オンラインバックアップ中にログファイルに物理的に書き込まれるブロックを最小限に抑えることができます。
 a| 
バックアップでは、同じボリュームの複数の表領域について、 Snapshot コピーを作成する必要があります。原因 SnapManager では、バックアップ処理中に 1 つのボリュームの複数の Snapshot コピーを作成できます。

|===

NOTE: パーシャル・バックアップを実行できますが、データベース全体のフル・バックアップを常に実行する必要があります。
