---
permalink: unix-administration/concept-creating-task-specification-file-and-scripts-for-snapmanager-operations.html 
sidebar: sidebar 
keywords: snapmanager, sap, task, specification, extensible, markup, language, xml, pretask, backup, restore, clone, operation, creating, create, file, script, operation 
summary: SnapManager for SAPでは、バックアップ、リストア、クローニングの各処理のプリタスクとポストタスクを示すタスク仕様のXMLファイルを使用します。バックアップ、リストア、クローニングの処理の前後に実行するタスクについては、 XML ファイルにプリタスクスクリプトとポストタスクスクリプトの名前を追加できます。 
---
= SnapManager 処理用のタスク仕様ファイルおよびスクリプトの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager for SAPでは、バックアップ、リストア、クローニングの各処理のプリタスクとポストタスクを示すタスク仕様のXMLファイルを使用します。バックアップ、リストア、クローニングの処理の前後に実行するタスクについては、 XML ファイルにプリタスクスクリプトとポストタスクスクリプトの名前を追加できます。

SnapManager （ 3.1 以前）では、クローニング処理の場合にのみ、プリタスクスクリプトとポストタスクスクリプトを実行できます。SnapManager （3.2以降）for SAPでは、バックアップ、リストア、クローニングの各処理に対して、タスク実行前スクリプトとタスク実行後スクリプトを実行できます。

SnapManager （ 3.1 以前）では、タスク仕様セクションはクローン仕様 XML ファイルの一部です。SnapManager 3.2 for SAPでは、タスク仕様セクションは個別のXMLファイルです。


NOTE: SnapManager 3.3 以降では、 SnapManager 3.2 より前のリリースで作成されたクローン仕様 XML ファイルの使用はサポートされていません。

SnapManager （3.2以降）for SAPでSnapManager 処理を正常に実行するには、次の条件が満たされている必要があります。

* バックアップ処理とリストア処理には、タスク仕様 XML ファイルを使用します。
* クローニング処理については、クローン仕様 XML ファイルとタスク仕様 XML ファイルの 2 つの仕様ファイルを提供します。
+
プリタスクまたはポストタスクアクティビティを有効にする場合は、オプションでタスク仕様 XML ファイルを追加できます。



タスク仕様ファイルは、 SnapManager のグラフィカルユーザインターフェイス（ GUI ）、コマンドラインインターフェイス（ CLI ）、またはテキストエディタを使用して作成できます。適切な編集機能を有効にするには、ファイルに .xml 拡張子を使用する必要があります。このファイルを保存しておくと、以降のバックアップ、リストア、およびクローニングの処理に使用できます。

タスク仕様 XML ファイルには、次の 2 つのセクションがあります。

* プリタスクセクションには、バックアップ、リストア、およびクローニングの処理の前に実行可能なスクリプトが含まれます。
* タスク後のセクションでは、バックアップ、リストア、およびクローニングの処理後に実行できるスクリプトを説明します。


プリタスクおよびポストタスクのセクションに含まれる値は、次のガイドラインに従っている必要があります。

* タスク名:タスクの名前は'スクリプトの名前と一致している必要がありますこれは'plugin.sh -describeコマンドを実行したときに表示されます
+

NOTE: 不一致がある場合は、「ファイルが見つかりません」というエラーメッセージが表示されることがあります。

* パラメータ名：パラメータの名前は、環境変数の設定として使用できる文字列である必要があります。
+
文字列は'カスタム・スクリプト内のパラメータ名と一致している必要がありますこれは'plugin.sh -describeコマンドを実行したときに表示されます



次のサンプルタスク仕様ファイルの構造に基づいて、仕様ファイルを作成できます。

[listing]
----

<task-specification>
  <pre-tasks>
<task>
      <name>name</name>
      <parameter>
          <name>name</name>
          <value>value</value>
       </parameter>
    </task>
  </pre-tasks>
  <post-tasks>
    <task>
      <name>name</name>
      <parameter>
          <name>name</name>
          <value>value</value>
       </parameter>
    </task>
  </post-tasks>
</task-specification>
----

NOTE: タスク仕様 XML ファイルにポリシーを含めることはできません。

SnapManager GUI では、パラメータ値を設定して XML ファイルを保存できます。バックアップ作成ウィザード、リストアまたはリカバリウィザード、クローン作成ウィザードのタスク有効化ページを使用して、既存のタスク仕様 XML ファイルをロードし、選択したファイルをタスク前またはタスク後のアクティビティに使用できます。

同じパラメータと値の組み合わせを使用して、 1 つのタスクを複数回実行できます。たとえば、保存タスクを使用して複数のファイルを保存できます。


NOTE: SnapManager では、タスク仕様ファイルに記載されている XML タグを使用して、バックアップ、リストア、クローニングの各処理の前処理または後処理を実行します。タスク仕様ファイルのファイル拡張子は関係ありません。
