---
permalink: unix-administration/concept-when-can-you-use-fast-restore.html 
sidebar: sidebar 
keywords: rule, apply, fast, restore, achieve, optimal, performance, guidelines 
summary: 高速リストアを使用して最適なリストアパフォーマンスを実現するには、特定のルールが適用されます。場合によっては、高速リストアを使用できないこともあります。 
---
= 高速リストアを使用できる状況については、次のガイドラインを参照してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
高速リストアを使用して最適なリストアパフォーマンスを実現するには、特定のルールが適用されます。場合によっては、高速リストアを使用できないこともあります。

リストアのパフォーマンスを最適化するには（ボリュームのリストアまたはディスクグループ全体のリストア）、次のルールに従う必要があります。

* 高速リストアの対象となるのは、フル・バックアップの完全なリストアだけです。
* 高速リストアの対象となるのはデータファイルのみです。
* 高速リストアを実行するには、ボリューム内のファイルがデータファイルだけである必要があります。
+
一時データファイルはボリュームに格納できますが、制御ファイル、ログ、 pfiles 、またはその他のファイルは、データファイルとは別のボリュームに格納する必要があります。制御ファイル、アーカイブログ、オンラインログファイルとは別のボリュームにデータファイルを格納するように Oracle データベースを設定する必要があります。

* ボリューム内に存在する必要があるのは、 1 つのデータベースのデータファイルだけです。
* 複数のファイルシステムを使用できますが、ファイルシステム内のファイルは 1 つのデータベースのデータファイルでなければなりません。
* SAPでは、ファイルレイアウトが多少異なります。
+
「一般的なレイアウトと構成」のセクションに詳細が記載されています。

* BRRESTOREを使用してデータベースをリストアする場合は'バックアップ・ユーティリティ・パラメータ・ファイルのfastパラメータを使用して高速リストアを実行します



NOTE: 以前に作成したバックアップが高速リストアを使用してリストア可能かどうかを確認するには、「SMSAP backup restore」コマンドの「-preview」オプションを使用します。

高速リストアプロセスは、次の場合には使用できません。

* パーシャル・バックアップの場合
* プライマリストレージにバックアップが存在する場合、セカンダリストレージからのバックアップ
+
ファイルベースまたはボリュームベースのリストアを使用してリストアすることはできません。

* SnapVault で保護されているバックアップ
+
高速リストアプロセスは、前回の保護されたバックアップよりも前に作成されたバックアップには使用できません。ただし、前回の保護されたバックアップのあとに作成されたバックアップには高速リストアプロセスを使用できます。たとえば、バックアップ A 、 B 、 C について考えてみましょうb は、 SnapVault を使用してセカンダリストレージに転送する最後のバックアップです。B および C を高速リストアできますが、前回の保護されたバックアップよりも前に作成されたので、高速リストア A は実行できません。SnapVault では、次回のセカンダリストレージへのバックアップ転送時に、時間差を計算してセカンダリストレージに送信するためにベースライン SnapVault が必要です。最後に保護されたバックアップがベースライン Snapshot コピーとして機能します。そのため、高速リストアプロセスを使用すると、 SnapVault でベースラインを認識できなくなります。

* ボリュームのリバート先の Snapshot コピーのあとに作成された Snapshot コピーを使用する FlexClone または LUN クローン
+
クローンは、あとで SnapManager でマウントまたはクローニングされるバックアップの結果として作成されます。

* アクティブな SnapDrive Snapshot コピーに含まれていない LUN


同じバックアップに対して、他の種類のリストアと併せて高速リストアを実行することはできません。たとえば、高速リストアプロセスを使用して 1 つのデータボリュームをリストアできても、別のデータボリュームではリストアできない場合、高速リストアプロセスを使用してリストアすることはできません。この場合は、ファイルベースのリストアを選択できます。

また、データベースのリストアについては、次の点にも注意してください。

* SnapManager では、アーカイブログや REDO ログをリストアすることはありませんが、アーカイブログファイルのバックアップをマウントしてリカバリに使用します。
* SnapManager では、ボリュームリストアを使用して制御ファイルをリストアすることはありません。
* 制御ファイルとデータファイルをリストアする場合は、 SnapManager によってリストアが 2 つの手順で実行されます。
+
SnapManager は、最初に制御ファイル、次にデータ・ファイルをリストアします。

* SnapManager が標準表領域ファイルと同じボリューム内に一時ファイルを検出した場合、ボリュームレベルのリストアを実行するために上書きを問題に設定する必要はありません。
+
ボリュームのリストア後、 TEMP 表領域はオンラインに戻ります。



SnapManager for SAPとBACKINTインターフェイスで使用するリストアメカニズムを決定する際には、どちらのインターフェイスでも同じロジックを使用します。リストアの方法は、SnapManager for SAPとBACKINTインターフェイスのどちらでバックアップを実行したかに関係なく、SnapManager for SAPとBACKINTインターフェイスのどちらでリストアを実行するかに関係なく、すべてのリストア方法を使用できます。

* 関連情報 *

http://mysupport.netapp.com/["ネットアップサポートサイトのドキュメント： mysupport.netapp.com"]
