---
permalink: unix-administration/concept-what-database-restore-is.html 
sidebar: sidebar 
keywords: snapmanager, enable, volume-based, file-based, backup, restore, operation, database, restore 
summary: SnapManager では、ボリュームベースまたはファイルベースのバックアップとリストアの処理を実行できます。 
---
= データベースリストアとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager では、ボリュームベースまたはファイルベースのバックアップとリストアの処理を実行できます。

次の表に、リストア方式を示します。

[cols="1a,3a"]
|===
| リストアプロセス | 詳細 


 a| 
ボリュームベースの高速リストア（プライマリストレージから）
 a| 
SnapManager では、ボリューム全体をリストアすることによって、データベースのデータファイルをリストアします。このデフォルトのプロセスは、データベースをリストアするための最速の方法です。



 a| 
ファイルベースのリストア
 a| 
ストレージ側のファイルシステムのフルリストア（プライマリまたはセカンダリから）： SnapManager は完全な論理ユニット番号（ LUN ）のリストアを実行します。



 a| 
ストレージ側のファイルのリストア：SnapManager は、NAS環境で単一ファイルのsnap restore（SFSR）を実行します。SFSRでは、保護対象オブジェクトを表すファイルまたはLUNがそれぞれリストアされます。



 a| 
ホスト側のファイルコピーのリストア（プライマリまたはセカンダリから）： SnapManager は、 LUN または FlexClone を使用してローカルバックアップをクローニングします。クローンがマウントされ、 SnapManager がクローンのホストファイルをアクティブファイルシステムにコピーします。

|===

NOTE: プライマリストレージにバックアップが存在する場合、セカンダリストレージからバックアップをリストアすることはできません。

高速リストア処理が完了すると、 SnapManager は次のタスクを実行します。

* プライマリストレージには Snapshot コピーが存在しなくなるため、同じプロファイル内の（バックアップのリストア後に作成された）より新しいバックアップを解放します。
* 高速リストア処理で Snapshot コピーが自動的に削除されたプロファイルにあるバックアップの Snapshot コピーをすべて削除します。
+
これにより、バックアップの一部が解放されることはありません。たとえば、 Backup_A が最初に作成され、次に Backup_B が作成されたとします。各には、データファイル用とアーカイブログ用の Snapshot コピーが 1 つずつあります。高速リストアプロセスを使用して SnapManager が Backup_A をリストアすると、 SnapManager はデータファイル Snapshot コピーを Backup_B から自動的に削除します高速リストアプロセスではアーカイブログがリストアされないため、高速リストアプロセスが完了したあとに、 SnapManager でアーカイブログの Backup_B の Snapshot コピーを削除する必要があります。





== 高速リストア

高速リストアまたはボリュームベースリストアは、高速リストア方式としては最速であるため、という名前が付けられます。ストレージシステムボリューム全体が Snapshot コピーにリバートされます。ストレージレベルでは、このリストアがほぼ瞬時に行われます。ただし、ボリュームリストアを実行すると次のような悪影響が生じる可能性があるため、注意して使用する必要があります。

* ストレージ側ボリューム全体がリバートされ、以下が含まれます。
+
** バックアップの一部とみなされなかったファイル
** ボリューム上のその他のファイル、ファイルシステム、または LUN


* ボリュームのリバート先の Snapshot コピーよりもあとに作成された Snapshot コピーがすべて削除されます。
+
たとえば、ボリュームで月曜日のバックアップをリストアした場合、火曜日のバックアップはリストアできなくなります。

* リストアした Snapshot コピーが関係のベースライン Snapshot コピーよりも古い場合、セカンダリストレージシステムとの関係は解除されます。




== ストレージ側のフルファイルシステムのリストア

ストレージ側でファイルシステムのフルリストアは、ボリュームをリストアできない場合に実行されますが、ファイルシステム全体をストレージシステム上でリストアできます。

ストレージ側でファイルシステムのリストアを実行すると、次のような処理が行われます。

* SAN 環境では、ファイルシステムで使用されているすべての LUN （および基盤となるボリュームグループがある場合はそのボリュームグループ）がストレージシステム上でリストアされます。
* NAS 環境では、ファイルシステム内のすべてのファイルがストレージシステム上にリストアされます。
+
NAS 環境では、このリストアメカニズムによってストレージ側でのファイルリストアに比べてメリットが得られません。



ストレージ側でファイルシステムのリストアを実行すると、ストレージの場所に応じて次の処理が実行されます。

* SnapManager がプライマリストレージシステムからリストアする場合は、 SFSR を使用して LUN （ SAN ）またはファイル（ NAS ）を元の場所にリストアします。
* SnapManager がセカンダリストレージシステムからリストアされると、セカンダリストレージシステムからネットワーク経由でプライマリストレージシステムに LUN （ SAN ）またはファイル（ NAS ）がコピーされます。


ファイルシステムは完全にリストアされるため、バックアップに含まれていないファイルもリストアされます。リストア対象のファイルシステムに、リストア対象外のファイルが存在する場合は、上書きが必要です。



== ストレージ側のファイルのリストア

ストレージ側のファイルシステムのリストアを実行できない場合、ストレージ側でファイルシステムのリストアが実行されることがあります。ストレージ側でのファイルのリストアでは、ファイルシステム内の個々のファイルは、ストレージシステム上で直接リストアされます。

このタイプのリストアは、NFS環境またはASM環境でのみ実行できます。

ストレージ側でファイルをリストアすると、次のような処理が行われます。

* SnapManager がプライマリストレージシステムから NFS ファイルをリストアするときは、 SFSR を使用して個別のファイルを元の場所にリストアします。
* SnapManager がセカンダリストレージシステムから NFS ファイルをリストアすると、個々のファイルがストレージネットワーク経由でプライマリストレージシステムにコピーされます。




== ホスト側のファイルのリストア

高速リストア、ストレージ側のファイルシステムのリストア、ストレージ側のファイルのリストアを実行できない場合、 SAN 環境ではホスト側でファイルのコピーリストアを最後の手段として使用します。

ホスト側のファイルコピーのリストアでは、次のタスクを実行します。

* ストレージをクローニングする
* クローニングされたストレージをホストに接続します
* クローン・ファイルシステムからアクティブ・ファイルシステムにファイルをコピーします
* ホストからクローンストレージを切断しています
* クローンストレージを削除しています


SnapManager は、セカンダリストレージからリストアする際、最初に（ホストを介さずに）セカンダリストレージシステムからプライマリストレージシステムへのデータの直接リストアを試みます。SnapManager がこのタイプのリストアを実行できない場合（たとえば、リストアの一部ではないファイルがファイルシステムにある場合）、 SnapManager はホスト側のファイルコピーリストアを実行します。SnapManager では、ホスト側のファイルコピーのリストアをセカンダリストレージから 2 つの方法で実行できます。SnapManager で選択したメソッドは'SMSAP_config'ファイルで設定されています

* 直接： SnapManager はセカンダリストレージ上のデータのクローンを作成し、クローニングされたデータをセカンダリストレージシステムからホストにマウントして、クローンのデータをアクティブな環境にコピーします。これはデフォルトのセカンダリアクセスポリシーです。
* 間接： SnapManager は、最初にプライマリストレージ上の一時ボリュームにデータをコピーしてから、一時ボリュームからホストにデータをマウントし、一時ボリュームからアクティブ環境にデータをコピーします。このセカンダリアクセスポリシーは、ホストがセカンダリストレージシステムに直接アクセスできない場合にのみ使用してください。この方法でのリストアでは、データのコピーが 2 つ作成されるため、セカンダリへの直接アクセスポリシーの作成に 2 倍の時間がかかります。


直接方式と間接方式のどちらを使用するかは'smsap.config'構成ファイルのrestore.secondaryAccessPolicy`パラメータの値によって決まりますデフォルトは direct です。
