---
permalink: unix-administration/concept-advantages-and-disadvantages-of-using-fast-restore.html 
sidebar: sidebar 
keywords: dba, aware, advantage, disadvantage, volume-base, fast, restore, disadvantage 
summary: DBA は、ボリューム・ベースの高速リストアを使用することには利点と欠点があることに留意する必要があります。 
---
= 高速リストアを使用する利点と欠点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
DBA は、ボリューム・ベースの高速リストアを使用することには利点と欠点があることに留意する必要があります。

高速リストアを使用したデータベース・バックアップのリストアには、次のような利点があります。

* ボリューム・ベースのリストアにより、バックアップのリストアに要する時間が短縮されます。
* SnapManager では、高速リストア対応状況をチェックできます。SnapManager はデータベースバックアップを分析し、ボリュームベースのリストアを実行できるかどうかに関する情報を表示します。
* リストア処理をプレビューして、推奨されるパスで続行するか、選択したプロセスで推奨構成を無視するかを選択できます。


高速リストアを使用したデータベース・バックアップのリストアには ' 次の欠点があります

* バックアップの一部とみなされなかったファイルも含めて、ファイルシステム全体がリバートされます。ボリューム上の他のファイル、ファイルシステム、または LUN もリバートされます。
* SnapManager は、リバート後に作成された Snapshot コピーをすべて削除します。実質的には、 Snapshot コピーの日付以降の履歴は失われます。たとえば、月曜日のバックアップをリストア済みの場合は、火曜日のバックアップをリストアできません。


次の推奨事項に従うことで、欠点を回避できます。

* ベストプラクティスに基づいてデータベースレイアウトを最適化
* セカンダリストレージへのバックアップを保護する。ただし、プライマリストレージから Snapshot コピーを削除した場合、高速リストアを使用してセカンダリストレージから Snapshot コピーをリストアすることはできません。

