---
permalink: unix-administration/concept-fast-restore-eligibility-checks.html 
sidebar: sidebar 
keywords: perform, restore, backup, snapmanager, eligibility, check, fast 
summary: バックアップの高速リストアを実行するように選択した場合は、まず SnapManager で適格性チェックが実行され、高速リストア・プロセスを使用できるかどうかが確認されます。 
---
= リストアへの対応状況のチェックが高速
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップの高速リストアを実行するように選択した場合は、まず SnapManager で適格性チェックが実行され、高速リストア・プロセスを使用できるかどうかが確認されます。

SnapManager では、次の種類のチェックを実行できます。

* 必須チェック： SnapManager では、このチェックに合格したすべての条件に該当する場合にのみ、高速リストアプロセスを実行できます。
* オーバーライド可能なチェック : このチェックの条件が失敗した場合、管理者はチェックをオーバーライドして高速なリストアプロセスを強制できます。ただし、これらのチェックは無視してください。


次の表に、発生する可能性のある問題と、高速リストアの適格性チェックを無効にできるかどうかを示します。

|===
| 問題 | 合格が必要です | 詳細 


 a| 
ACFS 、投票ディスク、または OCR は 11gR2 の ASM ディスクグループに存在します
 a| 
はい。
 a| 
高速リストアは実行できません。解決方法：なし

上書きできません。



 a| 
リストアには、 SnapManager 3.0 以降を使用して作成されたバックアップのみを使用できます
 a| 
はい。
 a| 
上書きできません。



 a| 
リストアには、 SnapDrive for UNIX 4.0 以降を使用して作成された Snapshot コピーのみを使用できます
 a| 
はい。
 a| 
上書きできません。



 a| 
volume はルートボリュームです
 a| 
はい。
 a| 
リストア対象のボリュームは、ストレージシステム上のルートボリュームです。解決方法：ストレージシステムのルートボリュームは使用しないでください。

上書きできません。



 a| 
ボリュームリストアは Windows では使用できません
 a| 
はい。
 a| 
リストア対象のボリュームは、ストレージシステム上のルートボリュームです。解決方法：なし

上書きできません。



 a| 
ボリュームリストアは無効になっています
 a| 
はい。
 a| 
ボリュームリストアが無効になっています。解決方法：リストアの開始時に異なるオプションを選択してボリュームのリストアを有効にします。コマンドライン・インターフェイスでは'-ffast-off'を使用しないでください

上書きできません。



 a| 
同じボリューム上の制御ファイルとデータファイル
 a| 
はい。
 a| 
オンラインバックアップでは、制御ファイルとデータファイルを同じボリュームに配置することはできません。これは、 SnapManager がボリュームの Snapshot コピーを 2 つ作成するためです（データファイルがホットバックアップモードで整合性があるもの）。 ホットバックアップモードの完了後にバックアップ制御ファイルの整合性が保たれます）。ボリュームリストアは最初の Snapshot コピーにリバートされ、バックアップ制御ファイルを含む 2 つ目の Snapshot コピーが削除されます。データファイルのみのリストアを実行すると、制御ファイルは非一貫性状態に戻ります。 SnapManager はバックアップ制御ファイルをリストアし、 resetlogs オプションを指定してデータベースを開きます。これは望ましい動作ではありません。

解決方法：制御ファイルとデータファイルを、基盤となる同じボリュームを共有しない別のファイルシステムに移行します。これは、チェックが失敗したリストアには役立ちませんが、今後のバックアップリストア処理にも役立ちます。

上書きできません。



 a| 
アーカイブログとデータファイルが同じボリュームに存在していないことを確認する必要があります
 a| 
はい。
 a| 
データベース・アーカイブ・ログとデータ・ファイルは、同じストレージ・システム・ボリュームによってサポートされるファイルシステムに格納されます。ボリュームリストアを実行した場合、データベースのホットバックアップモードが解除されたあとに書き込まれたアーカイブログファイルを使用できないため、オンラインバックアップのリストア後に SnapManager でデータベースを開くことができません。また、アーカイブログファイル内にある以降のトランザクションをロールフォワードすることもできません。

解決方法：アーカイブログとデータファイルを、基盤となる同じストレージシステムボリュームを共有しない別のファイルシステムに移行します。これは、チェックが失敗したリストアには役立ちませんが、今後のバックアップリストア処理にも役立ちます。

上書きできません。



 a| 
オンラインログとデータファイルが同じボリュームに存在していてはなりません
 a| 
はい。
 a| 
データベースのオンライン REDO ログとデータファイルは、同じストレージシステムボリュームによってバックアップされたファイルシステムに格納されています。ボリュームリストアを実行した場合、オンライン REDO ログはリバートされているため、リカバリでは使用できません。

解決策：オンライン REDO ログとデータファイルを、基盤となるストレージシステムボリュームを共有していない別のファイルシステムに移行します。これは、チェックが失敗したリストアには役立ちませんが、今後のバックアップリストア処理にも役立ちます。

上書きできません。



 a| 
リストアスコープに含まれていないファイルシステム内のファイルがリバートされます
 a| 
はい。
 a| 
リストア対象のファイル以外のホストが認識できるファイルが、ボリューム上のファイルシステムに存在する。高速リストアまたはストレージ側のファイルシステムのリストアを実行した場合、ホストで認識されるファイルは、 Snapshot コピー作成時に元のコンテンツに戻されます。SnapManager が 20 個以下のファイルを検出した場合、資格チェックにリストされます。それ以外の場合は、ファイルシステムを調査する必要があることを示すメッセージが SnapManager に表示されます。

解決方法：データベースで使用していないファイルを、別のボリュームを使用する別のファイルシステムに移行します。または、ファイルを削除します。

SnapManager がファイルの目的を判断できない場合は、チェックのエラーを無視できます。このチェックを無効にすると、リストアスコープに含まれていないファイルがリバートされます。このチェックは、ファイルを復元しても悪影響がないことが確実である場合にのみ無視してください。



 a| 
リストアスコープに含まれていない、指定したボリュームグループ内のファイルシステムがリバートされます
 a| 
いいえ
 a| 
複数のファイルシステムが同じボリュームグループに含まれていますが、すべてのファイルシステムのリストアが要求されるわけではありません。ボリュームグループが使用する LUN にはすべてのファイルシステムのデータが含まれているため、ストレージ側のファイルシステムのリストアと高速リストアを使用してボリュームグループ内の個々のファイルシステムをリストアすることはできません。高速リストアまたはストレージ側のファイルシステムのリストアを使用するには、ボリュームグループ内のすべてのファイルシステムを同時にリストアする必要があります。SnapManager が 20 個以下のファイルを検出した場合、 SnapManager は資格チェックにそれらのファイルをリストします。それ以外の場合は、ファイルシステムを調査するように SnapManager からメッセージが表示されます。

解決策：データベースで使用していないファイルを別のボリュームグループに移行します。または、ボリュームグループ内のファイルシステムを削除します。

オーバーライドできます。



 a| 
リストアスコープに含まれていない、指定したボリュームグループ内のホストボリュームがリバートされます
 a| 
いいえ
 a| 
複数のホストボリューム（論理ボリューム）が同じボリュームグループに含まれているが、すべてのホストボリュームのリストアが要求されるわけではない。このチェックは、リストアスコープの一部ではないボリュームグループ内のファイルシステムに似ていますが、ボリュームグループ内の他のホストボリュームがホスト上のファイルシステムとしてマウントされていない点が異なります。解決策：データベースで使用するホストボリュームを別のボリュームグループに移行します。または、ボリュームグループ内の他のホストボリュームを削除します。

このチェックを無視すると、ボリュームグループ内のすべてのホストボリュームがリストアされます。他のホストボリュームをリバートしても悪影響がないことが確実な場合にのみ、このチェックを無効にしてください。



 a| 
前回のバックアップ以降にファイルエクステントが変更されています
 a| 
はい。
 a| 
上書きできません。



 a| 
リストアスコープに含まれないボリューム内のマッピングされた LUN がリバートされます
 a| 
はい。
 a| 
ボリュームでのリストアが要求されていない LUN は、現在ホストにマッピングされています。ボリュームリストアは実行できません。これらの LUN を使用する他のホストやアプリケーションが不安定になるためです。LUN 名の末尾がアンダースコアと整数（ _0 や _1 など）の場合、通常、これらの LUN は同じボリューム内の他の LUN のクローンです。データベースの別のバックアップがマウントされているか、別のバックアップのクローンが存在している可能性があります。

解決策：データベースで使用していない LUN を別のボリュームに移行します。マッピングされた LUN がクローンの場合は、同じデータベースまたはデータベースのクローンのマウントされたバックアップを検索し、バックアップをアンマウントするか、クローンを削除します。

上書きできません。



 a| 
リストアスコープに含まれていない、ボリューム内のマッピングされていない LUN はリバートされます
 a| 
いいえ
 a| 
ボリュームへのリストアが要求された LUN 以外の LUN が存在します。これらの LUN は現在どのホストにもマッピングされていないため、リストアしてもアクティブなプロセスが中断されることはありません。ただし、 LUN のマッピングが一時的に解除される可能性があります。解決策：データベースで使用していない LUN を別のボリュームに移行するか、または LUN を削除します。

このチェックを無視すると、ボリューム・リストアにより、これらの LUN が Snapshot コピーが作成された状態に戻ります。Snapshot コピーの作成時に LUN が存在しなかった場合、ボリュームのリストア後に LUN が存在しなくなります。このチェックは、 LUN のリバートが悪影響を受けないことが確実である場合にのみ無視してください。



 a| 
リバート時に、ボリュームの Snapshot コピーに含まれる LUN の整合性が確保されないことがあります
 a| 
いいえ
 a| 
Snapshot コピーの作成時に、 Snapshot コピーが要求された LUN とは別の LUN がボリュームに存在していました。その他の LUN は整合性が確保された状態でない可能性があります。解決策：データベースで使用していない LUN を別のボリュームに移行するか、または LUN を削除します。これは、チェックが失敗したリストア・プロセスには役立ちませんが、 LUN の移動または削除後に作成された以降のバックアップのリストアに役立ちます。

このチェックを無効にすると、 LUN は Snapshot コピーが作成された時点で不整合状態に戻ります。このチェックは、 LUN のリバートが悪影響を受けないことが確実である場合にのみ無視してください。



 a| 
新しい Snapshot コピーにはボリュームクローンが作成されます
 a| 
はい。
 a| 
Snapshot コピーのリストアが要求されたあとに作成された Snapshot コピーのクローンが作成されています。ボリュームリストアではあとで Snapshot コピーが削除されます。また、クローンが含まれている Snapshot コピーは削除できないため、ボリュームリストアを実行できません。解決方法：あとで作成した Snapshot コピーのクローンを削除します。

上書きできません。



 a| 
新しいバックアップがマウントされている
 a| 
はい。
 a| 
バックアップのリストア後に作成されたバックアップがマウントされます。ボリュームリストアではあとで Snapshot コピーが削除されるため、クローンがある場合は Snapshot コピーを削除できず、バックアップマウント処理ではクローンストレージが作成され、ボリュームリストアを実行できません。解決方法：あとでバックアップをアンマウントするか、マウントしたバックアップ後に作成されたバックアップからリストアする。

上書きできません。



 a| 
新しいバックアップのクローンが存在します
 a| 
はい。
 a| 
バックアップのリストア後に作成されたバックアップは、クローニングされています。ボリュームリストアではあとで Snapshot コピーが削除されます。また、クローンが含まれている Snapshot コピーは削除できないため、ボリュームリストアを実行できません。解決方法：新しいバックアップのクローンを削除するか、クローンが作成されたあとに作成されたバックアップからリストアします。

上書きできません。



 a| 
ボリュームの新しい Snapshot コピーは失われます
 a| 
いいえ
 a| 
ボリュームリストアを実行すると、ボリュームのリストア先である Snapshot コピーのあとに作成された Snapshot コピーがすべて削除されます。SnapManager があとで同じプロファイルの SnapManager バックアップに Snapshot コピーをマッピングして戻すと、「 newer backups will be freed or deleted 」というメッセージが表示されます。SnapManager があとで同じプロファイルの SnapManager バックアップに Snapshot コピーをマッピングし直すことができない場合、このメッセージは表示されません。解決方法：あとでバックアップからリストアするか、あとで作成した Snapshot コピーを削除します。

オーバーライドできます。



 a| 
新しいバックアップは解放または削除されます
 a| 
いいえ
 a| 
ボリュームリストアを実行すると、ボリュームのリストア先である Snapshot コピーのあとに作成された Snapshot コピーがすべて削除されます。そのため、リストア対象のバックアップのあとに作成されたバックアップは、削除または解放されます。それ以降のバックアップは、次の場合に削除されます。

* バックアップ状態は保護されていません
* retain.alwaysFreeExpiredBackupsは'SMSAP-config'の*false*'です


以降のバックアップは、次のシナリオで解放されます。

* バックアップの状態は保護されます
* retain.alwaysFreeExpiredBackupsは'SMSAP-config'の真の「*false*」です


解決方法：あとでバックアップしてリストアするか、またはあとでバックアップを解放または削除してください。

このチェックを無視すると、リストア対象のバックアップ後に作成されたバックアップは削除され、解放されます。



 a| 
ボリュームの SnapMirror 関係が失われました
 a| 
○（ RBAC を無効にしている場合、または RBAC 権限を持っていない場合）
 a| 
SnapMirror 関係のベースライン Snapshot コピーよりも前の Snapshot コピーにボリュームをリストアすると、関係が削除されます。解決策：関係のベースライン Snapshot コピーのあとに作成されたバックアップからリストアします。または、ストレージ関係を手動で解除し（リストア完了後に関係を再作成して再ベースラインします）、

RBAC が有効で、 RBAC 権限が付与されている場合は、を上書きできます。



 a| 
高速リストアプロセスが実行されると、ボリュームの SnapVault 関係は失われます
 a| 
○（ RBAC を無効にしている場合、または RBAC 権限を持っていない場合）
 a| 
SnapVault 関係のベースライン Snapshot コピーよりも前の Snapshot コピーにボリュームをリストアすると、関係が削除されます。解決策：関係のベースライン Snapshot コピーのあとに作成されたバックアップからリストアします。または、ストレージ関係を手動で解除し（リストア完了後に関係を再作成して再ベースラインします）、

RBAC が有効になっていて RBAC 権限がある場合、を上書きできません。



 a| 
リストアスコープに含まれないボリューム内の NFS ファイルがリバートされます
 a| 
いいえ
 a| 
ボリュームリストアが実行されると、ホストに表示されないストレージシステムボリューム内のファイルはリバートされます。解決策：データベースで使用されていないファイルを別のボリュームに移行するか、ファイルを削除します。

オーバーライドできます。このチェックエラーを無視すると、 LUN が削除されます。



 a| 
ボリュームには CIFS 共有が存在します
 a| 
いいえ
 a| 
リストア対象のボリュームには CIFS 共有があります。ボリュームリストア中に、他のホストがボリューム内のファイルにアクセスしている可能性があります。解決方法：不要な CIFS 共有を削除します。

オーバーライドできます。



 a| 
別の場所からのリストア
 a| 
はい。
 a| 
別の場所からファイルをリストアするように指定する、リストア処理のリストア仕様が指定されています。代替保存場所からのリストアには、ホスト側のコピーユーティリティのみを使用できます。

解決方法：なし。

上書きできません。



 a| 
ストレージ側のファイルシステムのリストアはRACデータベースではサポートされません
 a| 
はい。
 a| 
上書きできません。

|===