---
permalink: unix-administration/concept-database-state-needed-for-restore-process.html 
sidebar: sidebar 
keywords: state, database, restore, process, perform 
summary: リストアされるデータベースの状態は、実行するリストアプロセスのタイプ、およびリストアに含めるファイルのタイプによって異なります。 
---
= リストアプロセスに必要なデータベースの状態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リストアされるデータベースの状態は、実行するリストアプロセスのタイプ、およびリストアに含めるファイルのタイプによって異なります。

次の表に、選択したリストアオプションおよびリストアに含めるファイルのタイプに応じた、データベースの状態を示します。

[cols="1,1,1,1"]
|===
| リストアのタイプ | 含まれるファイル | このインスタンスのデータベースの状態 | その他のインスタンスのデータベースの状態（ RAC のみ） 


.3+| リストアのみ | 制御ファイル | シャットダウン | シャットダウン 


| システムファイル | マウントまたはシャットダウン | マウントまたはシャットダウン 


| システムファイルがありません | すべての状態 | すべての状態 


.3+| リストアとリカバリ | 制御ファイル | シャットダウン | シャットダウン 


| システムファイル | マウント | マウントまたはシャットダウン 


| システムファイルがありません | マウントまたはオープン | 任意 
|===
SnapManager によるリストア処理に必要なデータベースの状態は、実行するリストアのタイプ（完全ファイル、部分ファイル、制御ファイル）によって異なります。force オプションを指定しないかぎり、 SnapManager はデータベースを下位の状態（たとえば、 Open から Mount ）に移行しません。

SnapManager for SAPでは、SAPが実行されているかどうかは検証されません。SnapManager for SAPはタイムアウトが経過するまで待機したあと、データベースをシャットダウンします。これにより、リストアに1時間かかることがあります。
