---
permalink: unix-administration/concept-about-different-protection-policies.html 
sidebar: sidebar 
keywords: policies, policy, protect, backup, secondary, tertiary, storage, system, protection 
summary: 別のポリシーを選択して、セカンダリストレージシステムまたはターシャリストレージシステム上のバックアップを保護できます。 
---
= 各種の保護ポリシーについて
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
別のポリシーを選択して、セカンダリストレージシステムまたはターシャリストレージシステム上のバックアップを保護できます。

Data ONTAP 7-Mode を使用していて、 SnapManager が Protection Manager に統合されている場合は、プロファイルの作成時に次のいずれかの保護ポリシーを選択する必要があります。Protection Manager の管理コンソールには、データセットの保護ポリシーを設定するためのテンプレートが用意されています。ディザスタリカバリ保護ポリシーは SnapManager ユーザインターフェイスに表示されますが、サポートされていません。

[cols="1a,3a"]
|===
| ポリシー | 説明 


 a| 
バックアップ
 a| 
データセットは、 SnapVault または SnapMirror を使用して、ローカルストレージとプライマリストレージからセカンダリストレージにもバックアップされます。



 a| 
バックアップしてからミラーリングします
 a| 
SnapVault または SnapMirror を使用してプライマリストレージからセカンダリストレージにデータセットをバックアップし、 SnapMirror パートナーにミラーリングします。



 a| 
ローカル Snapshot コピーのみ
 a| 
データセットは、プライマリストレージ内のローカル Snapshot コピーのみを使用します。



 a| 
ミラー
 a| 
SnapMirror を使用して、データセットがプライマリストレージからセカンダリストレージにミラーリングされます。



 a| 
ミラーリングとバックアップ
 a| 
SnapMirror を使用してプライマリストレージからセカンダリストレージにデータセットがミラーリングされ、 SnapVault または SnapMirror を使用してセカンダリストレージにバックアップされます。



 a| 
ミラーとミラー
 a| 
データセットは、 2 つの異なる SnapMirror パートナー上のプライマリストレージからセカンダリストレージにミラーリングされます。



 a| 
ミラーリングしてからバックアップします
 a| 
データセットは、 SnapMirror を使用してプライマリストレージからセカンダリストレージにミラーリングされ、 SnapVault または SnapMirror を使用して 3 番目のストレージにバックアップされます。



 a| 
ミラーリングしてからミラーリングします
 a| 
データセットは、 SnapMirror を使用してプライマリストレージからセカンダリストレージにミラーリングされ、追加の SnapMirror パートナーにミラーリングされます。



 a| 
保護なし
 a| 
データセットには、 Snapshot コピー、バックアップ、ミラーコピーによる保護などの機能はありません。



 a| 
リモートバックアップのみ
 a| 
ストレージシステム上のデータは、 SnapVault または SnapMirror を使用して、リモートでセカンダリストレージにバックアップされます。ライセンスされたアプリケーションは、プライマリストレージ上でローカルバックアップを実行しません。この保護ポリシーは、 Open Systems SnapVault がインストールされているサードパーティシステムに適用できます。

|===
clustered Data ONTAP を使用している場合は、プロファイルの作成時に次のいずれかの保護ポリシーを選択する必要があります。

[cols="1a,1a"]
|===
| ポリシー | 説明 


 a| 
SnapManager_cDOT ミラー
 a| 
バックアップがミラーされます。



 a| 
SnapManager_cDOT ボールト
 a| 
バックアップをバックアップします。

|===