---
permalink: unix-administration/reference-the-smosmsaprepository-create-command.html 
sidebar: sidebar 
keywords: command, create, repository, store, database, profile, associate, credentials, block, size, adequate, smsap 
summary: このコマンドは、データベースプロファイルおよび関連付けられたクレデンシャルを格納するリポジトリを作成します。また、このコマンドはブロックサイズが適切かどうかもチェックします。 
---
= SMSAP repository createコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== 構文

このコマンドは、データベースプロファイルおよび関連付けられたクレデンシャルを格納するリポジトリを作成します。また、このコマンドはブロックサイズが適切かどうかもチェックします。

[listing]
----
smsap repository create
-repository
-port repo_port
-dbname repo_service_name
-host repo_host
-login -username repo_username
[-force] [-noprompt]
[-quiet | -verbose]
----


== パラメータ

* `*-repository*``
+
--repository_'の後に続くオプションは'リポジトリのデータベースの詳細を指定します

* `*-port_repo_port_*``
+
リポジトリが格納されたデータベースへのアクセスに使用する TCP ポート番号を指定します。

* `*-dbdbname_repo_service_name *``
+
リポジトリが格納されたデータベースの名前を指定します。グローバル名または SID を使用します。

* `*-host_repo_host_*``
+
リポジトリ・データベースが稼働しているホスト・コンピュータの名前または IP アドレスを指定します。

* `*-login*``
+
リポジトリ・ログインの詳細設定を開始します。

* `*-username_repo_username_*``
+
リポジトリが格納されたデータベースにアクセスするために必要なユーザ名を指定します。

* `*-force *``
+
リポジトリを強制的に作成しようとします。このオプションを使用すると、 SnapManager により、リポジトリを作成する前にリポジトリのバックアップを促すプロンプトが表示されます。

* `*-noprompt*``
+
は'-forceオプションを使用している場合'リポジトリを作成する前にリポジトリをバックアップするよう求めるプロンプトを表示しません-nopromptオプションを使用すると'プロンプトが表示されなくなり'スクリプトを使用したリポジトリの作成が容易になります

* `*-quiet *``
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* `*-verbose *`
+
エラー、警告、および情報メッセージがコンソールに表示されます。





== コマンド例

次の例では、ホストHotspur上のSMSAPEPOデータベースにリポジトリを作成します。

[listing]
----
smsap repository create -repository -port 1521 -dbname SMSAPREPO -host hotspur -login -username grabal21 -verbose
SMSAP-09202 [INFO ]: Creating new schema as grabal21 on jdbc:oracle:thin:@//hotspur:1521/SMSAPREPO.
SMSAP-09205 [INFO ]: Schema generation complete.
SMSAP-09209 [INFO ]: Performing repository version INSERT.
SMSAP-09210 [INFO ]: Repository created with version: 30
SMSAP-13037 [INFO ]: Successfully completed operation: Repository Create
SMSAP-13049 [INFO ]: Elapsed Time: 0:00:08.844
----