---
permalink: unix-administration/reference-the-backint-register-sld-command.html 
sidebar: sidebar 
keywords: sap, br, tools, backint, register-sld, command, snapmanager, backint, interface, system, landscape, directory, sld 
summary: SAP BR * Toolsを使用する場合は、SnapManager for SAPでbackint register-sldコマンドを実行して、System Landscape Directory（SLD）でbackintインターフェイスを登録できます。backintインターフェイスは、ストレージシステムをBR * Toolsコマンドと連携させるためにストレージベンダーが提供します。SnapManager for SAPでは、backintインターフェイスファイルが/opt/NetApp/smsap/bin/にインストールされます。 
---
= backint register-sldコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SAP BR * Toolsを使用する場合は、SnapManager for SAPでbackint register-sldコマンドを実行して、System Landscape Directory（SLD）でbackintインターフェイスを登録できます。backintインターフェイスは、ストレージシステムをBR * Toolsコマンドと連携させるためにストレージベンダーが提供します。SnapManager for SAPでは、backintインターフェイスファイルが/opt/NetApp/smsap/bin/にインストールされます。



== 構文

[listing, subs="+macros"]
----
pass:quotes[backint register-sld-host  _host_name_-port  _port_id_-username
_username_-password _password_-template _template_ID_]
----


== パラメータ

* `*-host_host_name_*`
+
SAP SLDが実行されているホストの名前を指定します。

* `*-port_id_id_*`
+
SAP SLDがHTTP要求を受け入れるポートのIDを指定します。IDは数字で、9桁以下である必要があります。

* `*-username_*`
+
有効で許可されたSAP SLDユーザ名を指定します。

* '*-password_password_*'
+
有効で許可されたSAP SLDユーザパスワードを指定します。これはオプションです。passwordを使用してパスワードを設定しない場合は、次の形式でパスワードを入力するように求められます。

+
「* username @ http://_host:port_*`」という名前になります



正しいパスワードを入力しなかった場合は、3回入力してもコマンドは失敗し、終了します。

* '*-template_template_id_*
+
カスタムファイルのベースとして使用できるマスターテンプレートXMLファイルの名前を指定します。





== コマンドの例

次の例は、コマンドが正常に完了したことを示しています。

[listing, subs="+macros"]
----
pass:quotes[backint register-sld -host jack12 -port 50100
-username j2ee_admin -password user123 -template /u/template.xml
Operation Id [N96f4142a1442b31ee4636841babbc1d7] succeeded.
----