---
permalink: unix-administration/reference-error-messages.html 
sidebar: sidebar 
keywords: information, error, message, associate, snapmanager, operation 
summary: ここでは、さまざまな SnapManager 処理に関連するエラーメッセージについて説明します。 
---
= エラーメッセージ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ここでは、さまざまな SnapManager 処理に関連するエラーメッセージについて説明します。



== 最も一般的なエラーメッセージです

次の表に、SnapManager for SAPに関する最も一般的なエラーと重要なエラーを示します。

[cols="1a,1a,1a"]
|===
| エラーメッセージです | 説明 | 解決策： 


 a| 
'SD-10038:ファイルシステムは書き込み可能ではありません
 a| 
SnapManager プロセスには、ファイルシステムへの書き込みアクセス権がありません。
 a| 
SnapManager プロセスがファイルシステムに書き込みアクセスできることを確認する必要があります。これを修正した後、別のスナップショットを作成する必要がある場合があります。



 a| 
「SMSAP-05075:プロファイルを作成できません。DP/XDP関係を適切に設定するか'基盤となる関係ごとに適切な保護ポリシーを選択する必要があります
 a| 
基盤となるボリュームが SnapVault 関係または SnapMirror 関係にない。
 a| 
ソースボリュームとデスティネーションボリュームの間にデータ保護関係を設定し、その関係を初期化する必要があります。



 a| 
「[smsap-05503]プロファイルに同じ名前を指定しました。別の名前を指定して'プロファイル名を変更します
 a| 
同じ名前のプロファイルはリポジトリに存在できません
 a| 
使用されていないプロファイル名を指定してください。



 a| 
「SMSAP-05505:データセットメタデータを更新できません。
 a| 
データセットが削除されているか、存在しません。
 a| 
データセットのメタデータを更新する前に、 NetApp Management Console を使用してデータセットが存在することを確認します。



 a| 
'smsap-0506：プロファイル上で実行中の処理があるため、プロファイルを更新できません。操作が完了するまで待ってから'プロファイルを更新する必要があります
 a| 
バックアップ、リストア、クローニングの各処理が実行中の場合、プロファイルを更新できません。
 a| 
現在の処理が完了したら、プロファイルを更新してください。



 a| 
'smsap-05509:無効なアーカイブログのプライマリ保存期間-正の整数値を指定します
 a| 
アーカイブログバックアップの保持期間を負の値にすることはできません。
 a| 
アーカイブログバックアップの保持期間には正の値を指定します。



 a| 
「SMSAP-07463」：このバックアップ・リストアでは、データベースが必須の状態である必要があります。データベースを必要な状態にできませんでした
 a| 
データベースがバックアップ処理に必要な状態ではありません。
 a| 
バックアップコピーを作成する前に、データベースが関連する状態であることを確認します。リストアされるデータベースの状態は、実行するリストアプロセスのタイプ、およびリストアに含めるファイルのタイプによって異なります。



 a| 
'SMSAP-09315:リポジトリのアップグレードまたは更新操作を実行した後'通知ホストの詳細を使用してサマリー通知を更新しない限り'前のバージョンで設定された通知のサマリー通知を受信できない場合があります
 a| 
ローリングアップグレードの実行後は、リポジトリの通知設定は行われません。
 a| 
ローリングアップグレードの実行後、通知を受信するように通知の概要設定を更新します。



 a| 
「smsap-02076：ラベル名にはアンダースコア以外の特殊文字は使用できません。
 a| 
ラベル名には、アンダースコア以外の特殊文字が含まれています。
 a| 
ラベル名は、プロファイル内で一意である必要があります。名前には、アルファベット、数字、アンダースコア（ _ ）、およびハイフン（ - ）を使用できます（ 1 文字目をハイフンにすることはできません）。ラベルにアンダースコア以外の特殊文字が含まれていないことを確認してください。



 a| 
`SMSAP-06308:スケジュール開始時の例外: java.lang.NullPointerException
 a| 
プロファイルホストの完全修飾ドメイン名（ FQDN ）がシステムのホスト名ではなく設定されており、プロファイルホストの FQDN を解決できません。
 a| 
FQDN ではなく、システムのホスト名を使用してください。



 a| 
ExecuteRestoreSteps: Oracle-10003:SQLの実行エラー"DROP DISKGROU;コントロール・ディスクグループ名; Oracleデータベース+ASM1:ORA-15039:ディスクグループが削除されないORA-15027:ディスクグループがアクティブに使用されていること;コントロール・ディスクグループ名はディスマウントされません
 a| 
制御ファイルを含むバックアップをリストアする処理で、制御ディスクグループが削除されません。この問題は、制御ディスクグループに古いバックアップ制御ファイルがある場合に発生します。
 a| 
古いバックアップされた制御ファイルを特定し、手動で削除します。



 a| 
「rman-06004:リカバリ・カタログ・データベースからのOracleエラー: ORA-01424:エスケープ文字の後に文字がないか、不正です。
 a| 
SnapManager が RMAN に統合されている場合、バックアップ作成処理でカタログからバックアップコピーを削除できませんでした。
 a| 
RMAN からバックアップを削除するために使用する外部スクリプトがあるかどうかを確認します。RMANでコマンド「*CROSCHECK BACKUP *」を実行してRMANリポジトリを更新し、「*resync catalog *」コマンドを実行して、ターゲット・データベースの制御ファイルをリカバリ・カタログと同期させます。



 a| 
[debug]:バックアップのプルーニング中に例外が発生しましたjava.lang.IllegalStateException:[Assertion failed]-この状態不変はtrue'でなければなりません
 a| 
1 つの処理 ID に対して複数の Snapshot コピーが作成される。
 a| 
Snapshot コピーを手動で削除し、スクリプトを使用してリポジトリからエントリを削除します。



 a| 
システム時間と SnapManager によってログファイルに表示される時間が一致しないか、同期されていません。
 a| 
タイムゾーンの変更は、 Java 7 ではまだサポートされていません。
 a| 
Oracleが提供するtzupdater'パッチを適用します



 a| 
DiSC -00001:ストレージを検出できません:次の識別子が存在しないか'必要なタイプのものではありません: ASMファイル
 a| 
データファイル、制御ファイル、または REDO ログは、 ASM データベースで多重化されます。
 a| 
Oracle 多重化を削除します。



 a| 
0001-DS-10021:保護ポリシーがすでに<old-protection-policy>に設定されているため、データセット<dataset-name>の保護ポリシーを<new-protection-policy>に設定できません。Protection Managerを使用して保護ポリシーを変更してください
 a| 
データセットの保護ポリシーを設定したあとは、 SnapManager で保護ポリシーを変更することはできません。これは、ベースライン関係の再割り当てが必要になって、セカンダリストレージの既存のバックアップが失われる場合があるためです。
 a| 
Protection Manager の管理コンソールを使用して保護ポリシーを更新します。このコンソールでは、ある保護ポリシーから別の保護ポリシーへの移行に関するオプションを利用できます。



 a| 
'0001-SD-10028: SnapDrive Error(id:2618 code:102) Unable to discover the device associated with "lun_path（LUN_pathに関連するデバイスを検出できません）マルチパスを使用している場合、マルチパス構成のエラーの可能性があります。構成を確認してから再試行してください
 a| 
ストレージシステムに作成された LUN は、ホストで検出できません。
 a| 
転送プロトコルが正しくインストールおよび設定されていることを確認します。SnapDrive がストレージシステム上に LUN を作成して検出できることを確認します。



 a| 
'0001-SD-10028: SnapDrive Error(id:2836 code:110) Failed to acquire dataset lock on volume "storage name":"temp_volume_name"`
 a| 
間接ストレージ方式を使用してリストアを試行しましたが、指定した一時ボリュームはプライマリストレージに存在しません。
 a| 
プライマリストレージに一時ボリュームを作成します。または、一時ボリュームがすでに作成されている場合は、正しいボリューム名を指定します。



 a| 
0001-SMSAP-02016：このバックアップ処理の一環として、データベースに外部テーブルがバックアップされていない可能性があります（このバックアップ中にデータベースが開かれていなかったため、EXTERNAL_LONAL_LONADationsに対してクエリーを実行して、外部テーブルが存在するかどうかを確認できませんでした）
 a| 
SnapManager では、外部テーブル（たとえば、 .dbf ファイルに格納されていないテーブル）はバックアップされません。この問題は、バックアップ中にデータベースが開かれておらず、 SnapManager が外部テーブルが使用されているかどうかを判断できないために発生します。
 a| 
バックアップ中にデータベースが開かれなかったために、この処理でバックアップされない外部テーブルがデータベースに存在する場合があります。



 a| 
0001-SMSAP-11027：スナップショットがビジー状態のため、セカンダリストレージからスナップショットをクローニングまたはマウントできません。古いバックアップからのクローニングまたはマウントを試してください
 a| 
最新の保護されたバックアップのセカンダリストレージからクローンを作成するか、 Snapshot コピーをマウントしようとしました。
 a| 
古いバックアップからクローニングまたはマウントする。



 a| 
「0001-SMSAP-12346：Protection Manager製品がインストールされていないか、SnapDrive が保護ポリシーを使用するように設定されていないため、保護ポリシーを一覧表示できません。Protection Managerをインストールするか'Protection Manager SnapDrive を構成してください
 a| 
SnapDrive が Protection Manager を使用するように設定されていないシステム上で保護ポリシーをリストしようとしました。
 a| 
Protection Manager をインストールし、 Protection Manager を使用するように SnapDrive を設定します。



 a| 
「0001 - smsap-13032：操作を実行できません：バックアップの削除。ルート原因 ：0001-smsap-02039：データセットのバックアップを削除できません：SD-10028：SnapDrive エラー（ID：2406コード：102）バックアップIDの削除に失敗しました。データセットの「backup_id」、エラー（23410）：ボリューム「volume_name」のSnapshot「snapshot_name」がビジーです
 a| 
ミラー関係のベースラインである Snapshot コピーを含む、最新の保護されたバックアップを解放または削除しようとしました。
 a| 
保護されたバックアップを解放または削除する。



 a| 
0002-332 Admin ERROR: Operations Managerサーバ"dfm_server"上のユーザ・ユーザ名に対するsd.snapshot.Cloneアクセスを確認できませんでした理由：無効なリソースが指定されました。Operations Managerサーバ「dfm_server」にIDが見つかりません
 a| 
適切なアクセス権限とロールが設定されていません。
 a| 
コマンドを実行するユーザのアクセス権限またはロールを設定します。



 a| 
`[warn] flow-1101111:Operation aborted [error] flow-11008:操作が失敗しました: Javaヒープ空間
 a| 
データベース内のアーカイブログファイルの数が、許容される最大数を超えています。
 a| 
. SnapManager のインストールディレクトリに移動します。
. 「launch-java」ファイルを開きます。
. Java ヒープ領域パラメータ java -Xmx160m`Java heap space パラメータの値を大きくしますたとえば 'javA-Xmx200m というデフォルト値の 160m から 200 m に変更できます




 a| 
'SD-10028: SnapDrive Error(id:2868code:102) Could not locate remote snapshot or remote qtree.`（SD-10028：リモートスナップショットまたはリモートqtreeを見つけることができませんでした
 a| 
SnapManager では、 Protection Manager の保護ジョブが部分的にしか成功していない場合でも、バックアップは保護済みと表示されます。この状況は、データセットの適合性が進行中の場合（ベースライン Snapshot がミラーリングされている場合）に発生します。
 a| 
データセットが適合している場合は、新しいバックアップを作成します。



 a| 
`SMSAP-21019:アーカイブログの削除がデスティネーションで失敗しました:"/mnt/destination_name/" with the reason："Oracle-00101: Error executing RMAN command：[delete noprompt ARCHIVE'/mnt/destination_name/']'
 a| 
アーカイブ・ログの削除は、いずれかのデスティネーションで失敗します。このようなシナリオでは、 SnapManager は、アーカイブログファイルを他のデスティネーションから削除し続けます。アクティブ・ファイルシステムからファイルを手動で削除した場合、 RMAN はアーカイブ・ログ・ファイルをそのデスティネーションから削除しません。
 a| 
SnapManager ホストから RMAN に接続します。rman *CROSCHECK ARCHIVELOG ALL *`コマンドを実行し、アーカイブ・ログ・ファイルのプルーニング処理を再度実行します。



 a| 
'SMAP-13032:操作を実行できません:アーカイブログプルーニング。Root原因 ：RMAN Exception: Oracle-00101: Error executing rman command
 a| 
アーカイブログの保存先からアーカイブログファイルが手動で削除されます。
 a| 
SnapManager ホストから RMAN に接続します。rman *CROSCHECK ARCHIVELOG ALL *`コマンドを実行し、アーカイブ・ログ・ファイルのプルーニング処理を再度実行します。



 a| 
シェル出力を解析できません(java.util.regex.Matcher[pattern=command complete)region=0,18 lastmatch=])が一致しません(名前:backup_script

シェル出力を解析できません(java.util.regex.Matcher[pattern=command complete)region=0,25 lastmatch=])が一致しません(説明:バックアップスクリプト

シェル出力を解析できません(java.util.regex.Matcher[pattern=command complete)region=0,9 lastmatch=])が一致しません(タイムアウト:0)`
 a| 
プリタスクスクリプトまたはポストタスクスクリプトで環境変数が正しく設定されていません。
 a| 
プリタスクスクリプトまたはポストタスクスクリプトが標準の SnapManager プラグイン構造に準拠しているかどうかを確認します。スクリプトでの環境変数の使用については、を参照してください追加情報 xref:concept-operations-in-task-scripts.adoc[タスクスクリプト内の操作]。



 a| 
ORA-01450:キーの最大長（6398）を超えています
 a| 
SnapManager 3.2 for SAPからSnapManager 3.3 for SAPへのアップグレードを実行すると、アップグレード処理が失敗して次のエラーメッセージが表示されます。この問題は、次のいずれかの理由で発生する可能性があります。

* リポジトリが存在するテーブルスペースのブロックサイズが 8k 未満である。
* 'NLS_LENGTH_SEMANTICS 'パラメータはcharに設定されます

 a| 
次のパラメータに値を割り当てる必要があります。

* `block_size=*8192 *`
* `NLS_LENGTH=* BYTE *`


パラメータ値を変更したら、データベースを再起動する必要があります。

詳細については、記事 2017632 を参照してください。

|===


== データベース・バックアップ・プロセスに関連するエラー・メッセージ（ 2000 シリーズ）

次の表に、データベースバックアッププロセスに関連する一般的なエラーを示します。

[cols="1a,1a,1a"]
|===
| エラーメッセージです | 説明 | 解決策： 


 a| 
「SMSAP-02066:バックアップはデータバックアップ「data-logs」に関連付けられているため、アーカイブログバックアップ「data-logs」を削除したり解放したりすることはできません
 a| 
アーカイブログのバックアップがデータファイルのバックアップとともに作成され、アーカイブログのバックアップを削除しようとしました。
 a| 
バックアップを削除または解放するには'--force_'オプションを使用します



 a| 
'SMSAP-02067:バックアップはデータ・バックアップ「データ・ログ」に関連づけられており'割り当てられた保存期間内にあるため'アーカイブ・ログ・バックアップ「データ・ログ」を削除したり解放したりすることはできません
 a| 
アーカイブログバックアップはデータベースバックアップに関連付けられており、保持期間内にあるため、アーカイブログバックアップを削除しようとしました。
 a| 
バックアップを削除または解放するには'--force_'オプションを使用します



 a| 
'SMSAP-07142-除外パターン<exclusion)によりアーカイブログが除外されました
 a| 
プロファイルの作成またはバックアップの作成処理では、一部のアーカイブ・ログ・ファイルを除外します。
 a| 
対処は不要です。



 a| 
「smsap-07155：<count>アーカイブログファイルは、アクティブファイルシステムに存在しません。これらのアーカイブ・ログ・ファイルはbackup.`には含まれません
 a| 
プロファイルの作成処理またはバックアップの作成処理中に、アクティブファイルシステムにアーカイブログファイルが存在しません。これらのアーカイブ・ログ・ファイルは、バックアップに含まれません。
 a| 
対処は不要です。



 a| 
'SMSAP-07148:アーカイブされたログファイルは使用できません
 a| 
プロファイルの作成処理またはバックアップの作成処理中に、現在のデータベースに対応したアーカイブログファイルは作成されません。
 a| 
対処は不要です。



 a| 
'smsap-07150:アーカイブログファイルが見つかりません
 a| 
ファイルシステムにアーカイブログファイルがないか、プロファイルの作成処理またはバックアップの作成処理で除外されています。
 a| 
対処は不要です。



 a| 
「SMSAP-13032：操作を実行できません：Backup Create。Root 原因： oracle-20001 ：データベースインスタンス dfcln1 に対して状態をオープンに変更しようとしてエラーが発生しました。 Oracle-20004 ： RESETLOGS オプションを指定せずにデータベースを開くことを期待していますが、 RESETLOGS オプションを指定してデータベースを開く必要があると Oracle から報告されています。予期せずログをリセットしないようにするため、プロセスは続行されません。RESETLOGSオプションを使用せずにデータベースを開くことができることを確認してから、もう一度やり直してください
 a| 
no-resetlogs オプションで作成されたクローンデータベースをバックアップしようとします。クローンデータベースは完全なデータベースではありません。ただし、クローンデータベースではプロファイルやバックアップの作成、クローンのスプリットなどの SnapManager 処理は実行できますが、クローンデータベースが完全なデータベースとして設定されていないため SnapManager 処理は失敗します。
 a| 
クローンデータベースをリカバリするか、データベースを Data Guard Standby データベースに変換します。

|===


== データ保護エラー

次の表に、データ保護に関連する一般的なエラーを示します。

[cols="1a,1a,1a"]
|===
| エラーメッセージです | 説明 | 解決策： 


 a| 
'バックアップ保護が要求されましたが'データベース・プロファイルには保護ポリシーがありませんデータベース・プロファイルで保護ポリシーを更新するか'バックアップ作成時に保護オプションを使用しないでください
 a| 
セカンダリストレージを保護するバックアップを作成しようとしていますが、このバックアップに関連付けられたプロファイルには保護ポリシーが指定されていません。
 a| 
プロファイルを編集し、保護ポリシーを選択します。バックアップを再作成します。



 a| 
データ保護が有効になっているが'Protection Managerが一時的に使用できないため'プロファイルを削除できません後でもう一度試してください
 a| 
保護が有効になっているプロファイルを削除しようとしましたが、 Protection Manager は使用できません。
 a| 
適切なバックアップがプライマリストレージとセカンダリストレージのどちらにも格納されていることを確認します。プロファイルで保護を無効にします。Protection Manager を再び使用できるようになったら、プロファイルに戻って削除します。



 a| 
Protection Managerが一時的に使用できないため'保護ポリシーを一覧表示できません後でもう一度試してください
 a| 
バックアッププロファイルを設定する際に、バックアップがセカンダリストレージに保存されるように、バックアップの保護を有効にしておきます。ただし、 SnapManager は Protection Manager 管理コンソールから保護ポリシーを取得できません。
 a| 
プロファイルの保護を一時的に無効にします。新しいプロファイルの作成または既存のプロファイルの更新を続行します。Protection Manager を再び使用できるようになったら、プロファイルに戻ります。



 a| 
保護ポリシーを一覧表示できませんProtection Manager製品がインストールされていないか'Protection Manager製品が使用するようにSnapDrive が構成されていませんProtection Managerをインストールするか'Protection Manager SnapDrive を構成してください
 a| 
バックアッププロファイルを設定する際に、バックアップがセカンダリストレージに保存されるように、バックアップの保護を有効にしておきます。ただし、 SnapManager は Protection Manager の管理コンソールから保護ポリシーを取得できません。Protection Manager がインストールされていないか、 SnapDrive が設定されていません。
 a| 
Protection Manager をインストールします。SnapDrive を設定します。

プロファイルに戻り、保護を再度有効にして、 Protection Manager の管理コンソールで使用可能な保護ポリシーを選択します。



 a| 
Protection Managerが一時的に使用できないため'保護ポリシーを設定できません後でもう一度試してください
 a| 
バックアッププロファイルを設定する際に、バックアップがセカンダリストレージに保存されるように、バックアップの保護を有効にしておきます。ただし、 SnapManager は Protection Manager の管理コンソールから保護ポリシーを取得できません。
 a| 
プロファイルの保護を一時的に無効にします。プロファイルの作成または更新を続行します。Protection Manager の管理コンソールが使用可能になったら、プロファイルに戻ります。



 a| 
「ホスト<host>.」上のデータベース<dbname>の新しいデータセット<dataset_name>を作成しています
 a| 
バックアッププロファイルを作成しようとしました。SnapManager は、このプロファイルのデータセットを作成します。
 a| 
対処は不要です。



 a| 
'Protection Managerがインストールされていないため'データ保護は使用できません
 a| 
バックアッププロファイルの設定中に、バックアップがセカンダリ・ストレージに保存されるように、バックアップの保護を有効にしようとしました。ただし、 SnapManager は Protection Manager の管理コンソールから保護ポリシーにアクセスできません。Protection Manager がインストールされていません。
 a| 
Protection Manager をインストールします。



 a| 
「このデータベースの削除されたデータセット<dataset_name>。
 a| 
プロファイルを削除しました。SnapManager によって、関連付けられているデータセットが削除されます。
 a| 
対処は不要です。



 a| 
保護が有効になっているプロファイルを削除し'Protection Managerが構成されなくなったSnapManager からプロファイルを削除しても'Protection Managerでデータセットをクリーンアップすることはありません
 a| 
保護が有効になっているプロファイルを削除しようとしましたが、 Protection Manager がインストールされていないか設定されていないか、期限切れになっています。SnapManager はプロファイルを削除しますが、プロファイルのデータセットは Protection Manager の管理コンソールから削除されません。
 a| 
Protection Manager を再インストールまたは再設定します。プロファイルに戻って削除します。



 a| 
'無効な保持クラスです「SMSAP help backup」を使用して、使用可能な保持クラスのリストを表示します
 a| 
保持ポリシーを設定するときに ' 無効な保持クラスを使用しようとしました
 a| 
有効な保持クラスのリストを作成するには、「* SMSAP help backup *」コマンドを入力します

使用可能なクラスのいずれかで保持ポリシーを更新します。



 a| 
'指定された保護ポリシーは使用できません「SMSAPの保護ポリシーリスト」を使用して、使用可能な保護ポリシーのリストを表示します
 a| 
プロファイルの設定中に保護を有効にし、使用できない保護ポリシーを入力しました。
 a| 
使用可能な保護ポリシーを特定するには、次のコマンドを入力します：「* SMSAP protection-policy list *」



 a| 
データベース<host>上のデータベース<dataset_name>に、データセットが既に存在しているため、既存のデータセット<dataset_name>を使用しています
 a| 
プロファイルを作成しようとしましたが、同じデータベースプロファイルのデータセットがすでに存在します。
 a| 
既存のプロファイルのオプションをチェックし、新しいプロファイルで必要なものと一致することを確認してください。



 a| 
同じRACデータベースのプロファイル<profile_name>は、<SID>ホスト<hostname>のインスタンスにすでに存在するため、RACデータベース<dataset_name>の既存のデータセットを使用する
 a| 
RAC データベースのプロファイルを作成しようとしましたが、同じ RAC データベースプロファイルのデータセットがすでに存在します。
 a| 
既存のプロファイルのオプションをチェックし、新しいプロファイルで必要なものと一致することを確認してください。



 a| 
「保護ポリシー<既存のポリシー名>を持つデータセット<データセット名>は、このデータベースにすでに存在します。保護ポリシー <new_policy_name> が指定されています。データセットの保護ポリシーは <new_policy_name> に変更されます。プロファイルを更新すると'保護ポリシーを変更できます
 a| 
保護が有効で保護ポリシーが選択されたプロファイルを作成しようとしました。ただし、同じデータベースプロファイルのデータセットはすでに存在しますが、保護ポリシーが異なります。SnapManager は、既存のデータセットに新しく指定したポリシーを使用します。
 a| 
この保護ポリシーを確認して、データセットに使用するポリシーかどうかを判断します。設定されていない場合は、プロファイルを編集してポリシーを変更します。



 a| 
SnapManager for SAP'によって作成されたローカル・バックアップはProtection Managerによって削除されます
 a| 
Protection Manager の管理コンソールでは、 Protection Manager で定義された保持ポリシーに基づいて、 SnapManager によって作成されたローカルバックアップを削除または解放します。ローカルバックアップの削除中または解放中にローカルバックアップに設定された保持クラスは考慮されません。ローカルバックアップがセカンダリストレージシステムに転送されると、プライマリストレージシステム上のローカルバックアップに設定された保持クラスは考慮されません。転送スケジュールで指定された保持クラスがリモートバックアップに割り当てられます。
 a| 
新しいデータセットが作成されるたびにProtection Managerサーバから「dfpmデータセットfix_smsap」コマンドを実行します。これで、Protection Managerの管理コンソールで設定された保持ポリシーに基づいてバックアップが削除されることはありません。



 a| 
'このプロファイルの保護を無効にすることを選択しましたこれにより、 Protection Manager で関連付けられているデータセットが削除され、そのデータセットに対して作成されたレプリケーション関係が削除される可能性があります。また、このプロファイルでは、セカンダリ・バックアップまたはターシャリ・バックアップをリストアまたはクローニングするなど、 SnapManager 処理を実行することもできません。続行しますか(Y/N)
 a| 
SnapManager CLI または GUI からプロファイルを更新中に、保護されたプロファイルの保護を無効にしようとしました。SnapManager CLIの-noprotectオプションを使用するか、SnapManager GUIのPoliciesプロパティ・ウィンドウで* Protection Manager Protection Policy *チェック・ボックスをオフにすると、プロファイルの保護を無効にできます。プロファイルの保護を無効にすると、SnapManager for SAPはProtection Managerの管理コンソールからデータセットを削除し、そのデータセットに関連付けられているセカンダリおよびターシャリバックアップコピーのすべての登録を解除します。

データセットを削除すると、セカンダリバックアップコピーとターシャリバックアップコピーがすべて孤立します。Protection ManagerとSnapManager for SAPのどちらも、これらのバックアップ・コピーにアクセスすることはできません。SnapManager for SAPを使用してバックアップコピーをリストアすることはできなくなりました。


NOTE: プロファイルが保護されていない場合でも、同じ警告メッセージが表示されます。
 a| 
これは、SnapManager for SAPの既知の問題 であり、データセットを削除する場合のProtection Managerでの想定される動作です。対処方法はありません。孤立したバックアップは手動で管理する必要があります。

|===


== リストア・プロセスに関連するエラー・メッセージ（ 3000 シリーズ）

次の表に、リストアプロセスに関連する一般的なエラーを示します。

[cols="1a,1a,1a"]
|===
| エラーメッセージです | 説明 | 解決策： 


 a| 
「SMSAP-03031：Backup <variable>のストレージ・リソースはすでに解放されているため、バックアップのリストアにはリストア仕様が必要です。
 a| 
ストレージ・リソースが解放されているバックアップを、リストア仕様を指定しないでリストアしようとしました。
 a| 
リストア仕様を指定します。



 a| 
「SMSAP-03032：リストア仕様には、バックアップ用のストレージ・リソースがすでに解放されているため、リストアするファイルのマッピングが含まれている必要があります。マッピングが必要なファイルは次のとおりです。<variable> from Snapshots:<variable>`
 a| 
ストレージ・リソースが解放されているバックアップを、リストア対象の全ファイルのマッピングが定義されていないリストア仕様を指定してリストアしようとしました。
 a| 
リストア仕様ファイルを修正して、マッピングがリストア対象のファイルと一致するようにします。



 a| 
'oracle-30028:ログファイル<filename>をダンプできません。ファイルが見つからないか、アクセスできないか、破損している可能性があります。このログ・ファイルは'recovery.`には使用されません
 a| 
オンライン REDO ログファイルまたはアーカイブログファイルをリカバリに使用できません。このエラーは次の理由で発生します。

* エラーメッセージに記載されているオンラインの REDO ログファイルまたはアーカイブログファイルには、リカバリに適用する十分な変更番号がありません。これは、データベースがトランザクションなしでオンラインになっている場合に発生します。REDO ログまたはアーカイブログファイルには、リカバリに適用できる有効な変更番号はありません。
* エラーメッセージに記載されたオンライン REDO ログファイルまたはアーカイブログファイルには、 Oracle に対する十分なアクセス権限がありません。
* エラーメッセージに記載されたオンライン REDO ログファイルまたはアーカイブログファイルが破損しており、 Oracle で読み取ることができません。
* エラーメッセージに記載されているオンライン REDO ログファイルまたはアーカイブログファイルが、記載されたパスに見つかりません。

 a| 
エラーメッセージに記載されているファイルがアーカイブログファイルであり、リカバリのために手動で指定した場合は、そのファイルに Oracle に対するフルアクセス権限があることを確認します。ファイルにフルアクセス権限がある場合でも、 メッセージが続くと、アーカイブログファイルにリカバリに適用される変更番号がないため、このメッセージは無視してかまいません。



 a| 
「SMSAP-03038:プライマリにストレージリソースが残っているため、セカンダリからリストアできません。プライマリから復元してください
 a| 
セカンダリストレージからリストアしようとしたが、プライマリストレージに Snapshot コピーが存在する。
 a| 
バックアップが解放されていない場合は、必ずプライマリからリストアしてください。



 a| 
「smsap-03054:アーカイブログにデータを供給するためにバックアップarchbkp1をマウントしています。DS-10001 ：マウントポイントの接続[error] flow-11019: ExecuteConnectionSteps:SD-10028: SnapDrive Error(id:2618 code:305) でエラーが発生しました。次のファイルを削除できませんでした。対応するボリュームは読み取り専用である可能性があります。古いスナップショットを使用してコマンドを再試行します。[error] flow-11010:以前の失敗のために、操作が中断されます
 a| 
リカバリ中に、 SnapManager はセカンダリから最新のバックアップをマウントして、セカンダリからアーカイブログファイルを取得しようとします。ただし、他のバックアップがある場合は、リカバリが成功します。ただし、他のバックアップがない場合は、リカバリが失敗する可能性があります。
 a| 
SnapManager がリカバリにプライマリバックアップを使用できるように、プライマリから最新のバックアップを削除しないでください。

|===


== クローニングプロセスに関連するエラーメッセージ（ 4000 シリーズ）

次の表に、クローニングプロセスに関連する一般的なエラーを示します。

[cols="1a,1a,1a"]
|===
| エラーメッセージです | 説明 | 解決策： 


 a| 
「SMSAP-04133：ダンプの送信先は存在できません」
 a| 
SnapManager を使用して新しいクローンを作成していますが、その新しいクローンで使用されるダンプデスティネーションはすでに存在します。ダンプの送信先が存在する場合、 SnapManager でクローンを作成することはできません。
 a| 
クローンを作成する前に、古いダンプデスティネーションを削除するか、名前を変更してください。



 a| 
「SMSAP-04908：FlexCloneではありません。
 a| 
このクローンは LUN クローンです。これは、 Data ONTAP 8.1 7-Mode と clustered Data ONTAP に該当します。
 a| 
SnapManager でクローンスプリットがサポートされるのは、 FlexClone テクノロジのみです。



 a| 
「SMSAP-04904：_split-idsplit_id _」で実行されているクローン・スプリット・オペレーションはありません
 a| 
処理 ID が無効であるか、実行中のクローンスプリット処理がありません。
 a| 
クローンスプリットのステータス、結果、および停止処理に有効なスプリット ID またはスプリットラベルを指定します。



 a| 
「SMSAP-04906：クローンスプリットの停止操作が_split-idsplit_id _」で失敗しました
 a| 
スプリット処理が完了しました。
 a| 
「* clone split-status *」または「* clone split-result *」コマンドを使用して、スプリット処理が進行中であるかどうかを確認します。



 a| 
「SMSAP-13032：操作を実行できません：クローンの作成。Root 原因： Oracle-00001 ： SQL の実行中にエラーが発生しました： [ALTER DATABASE OPEN RESETLOGS;]返されたコマンドORA-3856: cannot mark instance_instance_2 (REDOスレッド2) as enabled
 a| 
次のセットアップを実行してスタンバイデータベースからクローンを作成すると、クローンの作成に失敗します。

* プライマリデータベースは RAC セットアップで、スタンバイデータベースはスタンドアロンです。
* スタンバイは、 RMAN を使用してデータファイルのバックアップを作成し、

 a| 
クローンを作成する前に'クローン仕様ファイルに'_no_recovery_through _resetlogs=true'パラメータを追加します追加情報については、 Oracle のマニュアル（ ID 334899.1 ）を参照してください。Oracle MetaLink のユーザー名とパスワードがあることを確認します。



 a| 
[INFO]操作が失敗しましたクローン仕様の構文エラー：[error:CVC-complex -type .2.4c: expected elements' value @ http://www.example.com default@http://www.example.com' before the end of the content in element parameter]@http://www.example.com]`
 a| 
クローン仕様ファイルで、パラメータの値を指定していません。
 a| 
パラメータの値を指定するか、クローン仕様ファイルで不要な場合はそのパラメータを削除する必要があります。

|===


== プロファイル管理プロセスに関連するエラー・メッセージ（ 5000 シリーズ）

次の表に、クローニングプロセスに関連する一般的なエラーを示します。

[cols="1a,1a,1a"]
|===
| エラーメッセージです | 説明 | 解決策： 


 a| 
「SMSAP-20600：プロファイル「profile1」がリポジトリ「repo_name」に見つかりません。プロファイルとリポジトリ間のマッピングを更新するには、「profile sync」を実行してください
 a| 
プロファイルの作成に失敗した場合は、ダンプ処理を実行できません。
 a| 
「smsapsystem dump」を使用します。

|===


== バックアップ・リソースの解放に関するエラー・メッセージ（ Backup 6000 シリーズ）

次の表に、バックアップタスクに関する一般的なエラーを示します。

[cols="1a,1a,1a"]
|===
| エラーメッセージです | 説明 | 解決策： 


 a| 
'SMSAP-06030:使用中のバックアップは削除できません:<variable>`
 a| 
バックアップがマウントされているか、保持期限が設定されている場合に、コマンドを使用してバックアップの解放処理を実行しようとしました。
 a| 
バックアップをアンマウントするか、保持ポリシーを無制限に変更します。クローンが存在する場合は削除します。



 a| 
「SMSAP-06045: Cannot free backup < variable > because the storage resources have already been freed」（バックアップ用のストレージ・リソースはすでに解放されています
 a| 
バックアップがすでに解放されている場合、コマンドを使用してバックアップの解放処理を実行しようとしました。
 a| 
すでに解放されているバックアップは解放できません。



 a| 
'SMSAP-06047:解放できるのは成功したバックアップのみですバックアップ<ID>のステータスは<status>.`です
 a| 
バックアップのステータスが失敗したときに、コマンドを使用してバックアップの解放処理を実行しようとしました。
 a| 
バックアップが正常に完了してから再試行してください。



 a| 
「SMSAP-13082: Cannot perform operation <variable> on backup <ID> because the storage resources have been freed」という理由で、バックアップ<ID>を実行できません
 a| 
コマンドを使用して、ストレージ・リソースが解放されているバックアップをマウントしようとしました。
 a| 
ストレージリソースが解放されているバックアップでは、BACKINTリストアをマウント、クローニング、検証、または実行することはできません。

|===


== virtual storage interface errors （仮想ストレージインターフェイス 8000 シリーズ）

次の表に、仮想ストレージインターフェイスのタスクに関する一般的なエラーを示します。

[cols="1a,1a,1a"]
|===
| エラーメッセージです | 説明 | 解決策： 


 a| 
「smsap-08017」でのストレージの検出でエラーが発生しました
 a| 
SnapManager は'ストレージ・リソースの検索を試みましたが'データ・ファイル'制御ファイル'またはログが'root/ディレクトリに見つかりましたこれらのファイルはサブディレクトリに存在する必要があります。ルートファイルシステムは、ローカルマシンのハードドライブになる場合があります。SnapDrive はこの場所に Snapshot コピーを作成できず、 SnapManager はこれらのファイルに対して処理を実行できません。
 a| 
データ・ファイル'制御ファイル'またはREDOログが'root'ディレクトリにあるかどうかを確認しますその場合は、正しい場所に移動するか、制御ファイルまたは REDO ログを正しい場所に再作成します。基本的なマウントポイントは常にです

* UNIXベースの環境では'/oracle/<SID>'
* Windowsベースの環境では'[drive:]\Oracle\<SID>`


SAPでは、次の2つのメンバーで構成された4つのREDOロググループ

* 1つのメンバーがoriglog｛A|B｝に格納されています。
* もう一方のメンバーはミラーされており、ミラーログ｛A|B｝になっています。


|===


== ローリングアップグレードプロセスに関連するエラーメッセージ（ 9000 シリーズ）

次の表に、ローリングアップグレードプロセスに関連する一般的なエラーを示します。

[cols="1a,1a,1a"]
|===
| エラーメッセージです | 説明 | 解決策： 


 a| 
'smsap-09234:古いリポジトリに次のホストが存在しません<hostname>
 a| 
以前のリポジトリバージョンに存在しないホストのローリングアップグレードを実行しようとしました。
 a| 
SnapManager CLIの以前のバージョンのrepository show -repositoryコマンドを使用して'ホストが以前のリポジトリに存在するかどうかを確認します



 a| 
'smsap-0955:新しいリポジトリに次のホストが存在しません<hostname>
 a| 
新しいリポジトリバージョンに存在しないホストのロールバックを実行しようとしました。
 a| 
新しいリポジトリにホストが存在するかどうかを確認するには、SnapManager CLIの新しいバージョンから「repository show -repository」コマンドを使用します。



 a| 
'SMSAP-09256:指定されたホスト<hostname>に新しいプロファイル<profilename>が存在するため、ロールバックはサポートされていません
 a| 
リポジトリに存在する新しいプロファイルを含むホストをロールバックしようとしました。ただし、これらのプロファイルは、以前のバージョンの SnapManager のホストには存在しませんでした。
 a| 
ロールバックの前に、 SnapManager の以降のバージョンまたはアップグレードされたバージョンの新しいプロファイルを削除します。



 a| 
'SMSAP-09257:ロールバックはサポートされていません。バックアップ<backupid>は新しいホストにマウントされています
 a| 
バックアップをマウントしている SnapManager ホストの新しいバージョンをロールバックしようとしました。これらのバックアップは、以前のバージョンの SnapManager ホストにはマウントされていません。
 a| 
新しいバージョンの SnapManager ホストでバックアップをアンマウントし、ロールバックを実行します。



 a| 
'smsap-09258:バックアップ<backupid>は新しいホストでアンマウントされるため、ロールバックはサポートされていません
 a| 
アンマウントされているバックアップがある新しいバージョンの SnapManager ホストをロールバックしようとしました。
 a| 
新しいバージョンの SnapManager ホストにバックアップをマウントし、ロールバックを実行する。



 a| 
'SMSAP-09298:このリポジトリには'すでに上位バージョンのホストがあるため'このリポジトリを更新できません代わりに'すべてのホストのロールアップグレードを実行してください
 a| 
単一のホストでローリングアップグレードを実行し、そのホストのリポジトリを更新した。
 a| 
すべてのホストでローリングアップグレードを実行します。



 a| 
`SMSAP-09297:制約を有効にしているときにエラーが発生しました。リポジトリの状態が不整合である可能性があります。現在のオペレーションの前に行ったリポジトリのバックアップをリストアすることをお勧めします
 a| 
リポジトリデータベースが不整合な状態のままになっている場合は、ローリングアップグレードまたはロールバック操作を実行しようとしました。
 a| 
以前にバックアップしたリポジトリをリストアします。

|===


== 作業の実施 (12,000 シリーズ )

次の表に、操作に関連する一般的なエラーを示します。

[cols="1a,1a,1a"]
|===
| エラーメッセージです | 説明 | 解決策： 


 a| 
「SMSAP-12347」[エラー]：SnapManager サーバがホスト<host>とポート<port>で実行されていません。SnapManager サーバを実行しているホストでこのコマンドを実行してください
 a| 
プロファイルの設定中に、ホストおよびポートに関する情報を入力しました。ただし SnapManager 、 SnapManager サーバは指定したホストおよびポートで実行されていないため、これらの処理を実行できません。
 a| 
SnapManager サーバを実行しているホストでコマンドを入力します。lsnrctl statusコマンドを使用してポートをチェックし'データベースが稼働しているポートを確認できます必要に応じて、バックアップコマンドでポートを変更します。

|===


== プロセスコンポーネントの実行（ 13,000 シリーズ）

次の表に、 SnapManager のプロセスコンポーネントに関連する一般的なエラーを示します。

[cols="1a,1a,1a"]
|===
| エラーメッセージです | 説明 | 解決策： 


 a| 
「SMSAP-13083：値が「x」のsnapnameパターンには、アルファベット、数字、アンダースコア、ダッシュ、中かっこなど以外の文字が含まれています
 a| 
プロファイルを作成するときは、 snapname パターンをカスタマイズしますが、使用できない特殊文字が含まれています。
 a| 
アルファベット、数字、アンダースコア、ダッシュ、および波かっこ以外の特殊文字を削除します。



 a| 
「SMSAP-13084：snapname pattern with value "x" does not contain the same number of left and rightブレース.」
 a| 
プロファイルを作成しているときに、 snapname パターンをカスタマイズしていますが、左波カッコと右波カッコは一致しません。
 a| 
snapname パターンに、対応する開閉用ブラケットを入力します。



 a| 
「smsap-13085：値「x」のsnapnameパターンには無効な変数名「y」が含まれています
 a| 
プロファイルを作成しているときは、 snapname パターンをカスタマイズしていますが、変数は使用できません。
 a| 
問題のある変数を削除します。使用できる変数のリストについては、を参照してください xref:concept-snapshot-copy-naming.adoc[Snapshot コピーの命名規則]。



 a| 
「smsap-13086」は、値が「x」のsnapnameパターンには変数「smid」を含める必要があります
 a| 
プロファイルを作成する際には、snapnameパターンをカスタマイズしますが、必須の「_smid_」変数は省略しています。
 a| 
必要な「_smpid_」変数を挿入します。



 a| 
「SMSAP-13902：クローンスプリットの開始に失敗しました。
 a| 
このエラーには、次のような複数の原因が考えられます。

* ボリュームにスペースがありません。
* SnapDrive が実行されていません。
* clone には LUN クローンを指定できます。
* FlexVol ボリュームに制限された Snapshot コピーがあります。

 a| 
「* clone split-estimate *」コマンドを使用して、ボリューム内の利用可能なスペースを確認します。FlexVol ボリュームに制限された Snapshot コピーがないことを確認します。



 a| 
'SMSAP-13904:クローンスプリットの結果が失敗しました
 a| 
SnapDrive またはストレージシステムの障害が原因の可能性があります。
 a| 
新しいクローンを作成してみてください。



 a| 
「SMSAP-13906：Split operation already running for clone label_clone -label_or ID_.」という名前のファイルが作成されます
 a| 
すでにスプリットされているクローンをスプリットしようとしています。
 a| 
クローンはすでにスプリットされており、クローン関連のメタデータは削除されます。



 a| 
「SMSAP-13907：スプリット操作はすでにクローンlabel_clone -label_or ID_clone」に対して実行されています。
 a| 
スプリット処理を実行中のクローンをスプリットしようとしています。
 a| 
スプリット処理が完了するまで待つ必要があります。

|===


== SnapManager ユーティリティに関連するエラーメッセージ（ 14,000 シリーズ）

次の表に、 SnapManager ユーティリティに関連する一般的なエラーを示します。

[cols="1a,1a,1a"]
|===
| エラーメッセージです | 説明 | 解決策： 


 a| 
「SMSAP-14501：メールIDを空白にすることはできません。
 a| 
E メールアドレスが入力されていません。
 a| 
有効な E メールアドレスを入力してください。



 a| 
「SMSAP-14502：メールの件名を空白にすることはできません。
 a| 
E メールの件名が入力されていません。
 a| 
適切な E メールの件名を入力します。



 a| 
「SMSAP-14506：メールサーバフィールドを空白にすることはできません。
 a| 
E メールサーバのホスト名または IP アドレスを入力していません。
 a| 
有効なメールサーバのホスト名または IP アドレスを入力してください。



 a| 
「SMSAP-14507：Mail Portフィールドを空白にすることはできません。
 a| 
E メールポート番号が入力されていません。
 a| 
E メールサーバのポート番号を入力します。



 a| 
「SMSAP-14508」：メールIDから空白にすることはできません
 a| 
送信者の E メールアドレスが入力されていません。
 a| 
有効な送信者の E メールアドレスを入力してください。



 a| 
「smsap-14509：ユーザ名を空にすることはできません。
 a| 
認証を有効にしましたが、ユーザ名が指定されていません。
 a| 
E メール認証のユーザ名を入力します。



 a| 
「SMSAP-14510：パスワードを空白にすることはできません。パスワードを入力してください
 a| 
認証を有効にしましたが、パスワードが指定されていません。
 a| 
E メール認証パスワードを入力します。



 a| 
「SMSAP-14550：電子メールのステータス<success / failure>.」
 a| 
ポート番号、メールサーバ、または受信者の E メールアドレスが無効です。
 a| 
E メールの設定時に適切な値を指定します。



 a| 
'SMSAP-14559:電子メール通知の送信に失敗しました:<error>
 a| 
ポート番号が無効であるか、メールサーバが無効であるか、受信者のメールアドレスが無効である可能性があります。
 a| 
E メールの設定時に適切な値を指定します。



 a| 
「SMSAP-14560：通知が失敗しました：通知設定は使用できません。
 a| 
通知設定を使用できないため、通知の送信に失敗しました。
 a| 
通知設定を追加



 a| 
'SMSAP-14565:無効な時刻形式です時刻の形式をHH：MM.`で入力してください
 a| 
時刻の形式が正しくありません。
 a| 
時刻を hh:mm の形式で入力します。



 a| 
'SMSAP-14566:無効な日付値です有効な日付範囲は1～31.です
 a| 
設定された日付が正しくありません。
 a| 
日付は 1~31 の範囲で指定します。



 a| 
'SMSAP-14567：日付値が無効です。有効な日付範囲は1～7です
 a| 
設定された日付が正しくありません。
 a| 
1 ～ 7 の範囲で日を入力します。



 a| 
「SMSAP-14569：サーバはサマリー通知スケジュールを開始できませんでした。
 a| 
原因不明のエラーにより SnapManager サーバがシャットダウンしました。
 a| 
SnapManager サーバを起動します。



 a| 
「SMSAP-14570：サマリー通知は使用できません。
 a| 
概要通知が設定されていません。
 a| 
サマリー通知を設定します。



 a| 
'SMSAP-14571:プロファイル通知とサマリー通知の両方を有効にすることはできません
 a| 
プロファイル通知とサマリー通知の両方のオプションを選択しました。
 a| 
プロファイル通知またはサマリー通知のいずれかをイネーブルにします。



 a| 
'smsap-14572:通知の成功または失敗のオプションを提供します
 a| 
成功オプションまたは失敗オプションが有効になっていません。
 a| 
success または failure オプションか、あるいはその両方を選択する必要があります。

|===


== SnapDrive for UNIX の一般的なエラーメッセージです

次の表に、 SnapDrive for UNIX に関する一般的なエラーを示します。

[cols="1a,1a"]
|===
| エラーメッセージです | 説明 


 a| 
「0001-136管理エラー：ファイラーにログオンできません：<filer><filer>にユーザ名またはパスワードを設定してください
 a| 
初期設定エラー



 a| 
「0001-382 Admin error：マルチパス再スキャンに失敗しました
 a| 
LUN 検出エラー



 a| 
0001-462 Admin ERROR:<lun>:spd5:デバイスを停止できませんでしたデバイスがビジーです
 a| 
LUN 検出エラー



 a| 
0001-476 Admin error:関連付けられているデバイスを検出できません
 a| 
LUN 検出エラー



 a| 
0001-680 Admin Error:ホストOSは'LUNの作成または接続を可能にするために内部データの更新を必要とします'lun config prepare LUN'を使用SnapDrive するか'この情報を手動で更新してください
 a| 
LUN 検出エラー



 a| 
0001-710管理エラー: LUNのOS更新に失敗しました...`
 a| 
LUN 検出エラー



 a| 
0001-817 Admin ERROR:ボリューム・クローンの作成に失敗しました... : FlexCloneのライセンスがありません
 a| 
初期設定エラー



 a| 
0001-817 Admin ERROR:ボリューム・クローンの作成に失敗しました... :スペースはクローンの保証ができないため'要求は失敗しました
 a| 
Space 問題の略



 a| 
0001-878 Admin error: HBAアシスタントが見つかりません。LUN を含むコマンドは失敗します
 a| 
LUN 検出エラー



 a| 
「SMSAP-12111：SnapDrive コマンド「SnapDrive command>」の実行中にエラーが発生しました：SnapDrive error>`
 a| 
SnapDrive for UNIX の一般的なエラーです

|===