---
permalink: unix-administration/reference-troubleshooting-snapdrive-issues.html 
sidebar: sidebar 
keywords: common, issue, snapmanager, snapdrive, troubleshooting, product 
summary: SnapDrive 製品で SnapManager を使用する際には、いくつかの一般的な問題が発生する可能性があります。 
---
= SnapDrive の問題のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive 製品で SnapManager を使用する際には、いくつかの一般的な問題が発生する可能性があります。

まず、問題 がSnapManager for SAPまたはSnapDrive に関連しているかどうかを確認する必要があります。問題 でSnapDrive エラーが発生すると、SnapManager for SAPに次のようなエラーメッセージが表示されます。

[listing]
----
SMSAP-12111: Error executing snapdrive command "<snapdrive command>": <snapdrive error>
----
次に、SnapDrive のエラーメッセージの例を示します。「SMSAP-12111」はSnapManager のエラー番号です。「0001-770」の番号付け方式は、UNIXエラーのSnapDrive を表します。

[listing]
----
SMSAP-12111: Error executing snapdrive command
"/usr/sbin/snapdrive snap restore -file
/mnt/pathname/ar_anzio_name_10gR2_arrac1/data/undotbs02.dbf -snapname pathname.company.com:
/vol/ar_anzio_name_10gR2_arrac1:
TEST_ARRAC1_YORKTOW_arrac12_F_C_0_8abc01b20f9ec03d010f9ec06bee0001_0": 0001-770
Admin error: Inconsistent number of files returned when listing contents of
/vol/ar_anzio_name_10gR2_arrac1/.snapshot/
TEST_ARRAC1_YORKTOW_arrac12_F_C_0_8abc01b20f9ec03d010f9ec06bee0001_0/data
on filer pathname.
----
SnapDrive for UNIX の検出、設定の問題、およびスペースに関する最も一般的なエラーメッセージを次に示します。これらのエラーが表示された場合は、『 SnapDrive インストレーションアドミニストレーションガイド』の「トラブルシューティング」の章を参照してください。

[cols="3a,1a"]
|===
| 現象 | 説明 


 a| 
`0001-136管理エラー:ファイラーにログオンできません:<filer><filer><filer>``のユーザー名とパスワードを設定してください
 a| 
SnapDrive の初期設定



 a| 
「0001-382 Admin error：マルチパス再スキャンに失敗しました
 a| 
LUN 検出エラー



 a| 
0001-462 Admin ERROR:<lun>:spd5:デバイスを停止できませんでしたデバイスがビジーです
 a| 
LUN 検出エラー



 a| 
`0001-476管理エラー:次のデバイスに関連付けられているデバイスを検出できません... 0001-710管理エラー：LUNのOS更新に失敗しました
 a| 
LUN 検出エラー



 a| 
`0001-680 Admin error:ホストOSは'LUNの作成または接続を可能にするために内部データを更新する必要があります'lun config prepare LUN'を使用SnapDrive するか'この情報を手動で更新してください
 a| 
LUN 検出エラー



 a| 
0001-817 Admin ERROR:ボリューム・クローンの作成に失敗しました... : FlexCloneのライセンスがありません
 a| 
SnapDrive の初期設定



 a| 
`0001-878 Admin error: HBAアシスタントが見つかりませんLUNを含むコマンドは失敗します
 a| 
LUN 検出エラー

|===