---
permalink: unix-administration/reference-the-smosmsap-notification-set-command.html 
sidebar: sidebar 
keywords: notification, set, command, configure, mail, server, smsap 
summary: 通知セットコマンドを使用してメールサーバを設定できます。 
---
= SMSAPの通知セットのコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
メール・サーバを構成するには'notification setコマンドを使用します



== 構文

[listing, subs="+macros"]
----
pass:quotes[smsap notification set
-sender-email _email_address_
-mailhost _mailhost_
-mailport _mailport_
[-authentication
-username _username_
-password _password_]]
pass:quotes[-repository
-dbname _repo_service_name_
-port _repo_port_]]
pass:quotes[-host _repo_host_
-login -username _repo_username_
[-quiet | -verbose]]

----


== パラメータ

* `*-sender -email_email_address_*`
+
E メールアラートの送信元の E メールアドレスを指定します。SnapManager 3.2 for SAPでは、Eメールアドレスのドメイン名を指定する際にハイフン（-）を使用できます。たとえば、送信者の E メールアドレスを -sender-email07lbfmdatacenter@continental-corporation.com と指定できます。

* `*-mailhost_mailhost_*`
+
E メール通知を処理するホストサーバの名前または IP アドレスを指定します。

* `*-mailport_mailport_*`
+
メールサーバのポート番号を指定します。

* `*-authentication-username_USERNAME__ PASSWORD_PASSWORD_*`
+
E メールアドレスの認証の詳細を指定します。ユーザ名とパスワードを指定する必要があります。

* `*-repository*`
+
リポジトリ・データベースの詳細を指定します。

* '*-port_repo_port_*'と入力します
+
リポジトリデータベースへのアクセスに使用する TCP （ Transmission Control Protocol ）ポート番号を指定します。

* `*-dbname_repo_service_name *`
+
リポジトリ・データベースの名前を指定します。グローバル名またはシステム ID を使用できます。

* `*-host_repo_host_*`
+
リポジトリ・データベースが置かれているホストの名前または IP アドレスを指定します。

* '*-login*
+
リポジトリ・ログインの詳細を指定します。これはオプションです。指定しない場合、 SnapManager はデフォルトで OS 認証接続モードになります。

* `*-username_repo_username_*`
+
リポジトリ・データベースへのアクセスに必要なユーザ名を指定します。

* 「*- quiet *」と入力します
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* `*-verbose *`
+
エラー、警告、および情報メッセージがコンソールに表示されます。



'''


== 例

次の例では、メールサーバを設定します。

[listing]
----
smsap notification set -sender-email admin@org.com -mailhost hostname.org.com -mailport 25 authentication -username davis -password davis -repository -port 1521 -dbname SMSAPREPO -host hotspur
-login -username grabal21 -verbose
----
'''