---
permalink: unix-administration/reference-error-message-classifications.html 
sidebar: sidebar 
keywords: determine, cause, error, message, classification 
summary: メッセージの分類がわかっている場合は、エラーの原因を判断できます。 
---
= エラーメッセージの分類
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
メッセージの分類がわかっている場合は、エラーの原因を判断できます。

次の表に、 SnapManager で表示されるさまざまなタイプのメッセージの数値範囲に関する情報を示します。

[cols="2a,1a,3a"]
|===
| グループ | 範囲 | 使用方法 


 a| 
環境
 a| 
1000 ～ 1999
 a| 
SnapManager の動作環境の状態や問題点を記録するために使用します。このグループには、 SnapManager が通信するシステムに関するメッセージ（ホスト、ストレージシステム、データベースなど）が含まれます。



 a| 
バックアップ
 a| 
2000 ～ 2999
 a| 
データベースバックアッププロセスに関連付けられています。



 a| 
リストア
 a| 
3000-3999
 a| 
データベースリストアプロセスに関連付けられています。



 a| 
クローン
 a| 
4 、 000-4999
 a| 
データベースクローンプロセスに関連付けられます。



 a| 
プロファイル（ Profile ）
 a| 
5000 ～ 5999
 a| 
プロファイルの管理に使用します。



 a| 
管理
 a| 
6000-6999
 a| 
バックアップの管理に使用します。



 a| 
仮想データベースインターフェイス
 a| 
7000-7999
 a| 
仮想データベースインターフェイスに関連付けられています。



 a| 
仮想ストレージインターフェイス
 a| 
8000 ～ 8999
 a| 
仮想ストレージインターフェイスに関連付けられます。



 a| 
リポジトリ
 a| 
9000-9999
 a| 
リポジトリインターフェイスに関連付けられています。



 a| 
指標
 a| 
10000 ～ 10999
 a| 
データベースバックアップのサイズ、バックアップの実行経過時間、データベースのリストア時間、データベースのクローニング回数などに関連します。



 a| 
仮想ホストインターフェイス
 a| 
11000-11999
 a| 
仮想ホストインターフェイスに関連付けられます。ホストオペレーティングシステムとのインターフェイスです。



 a| 
実行
 a| 
12000-12999
 a| 
オペレーティングシステムコールの生成や処理など、実行パッケージに関連します。



 a| 
プロセス
 a| 
13000-13999
 a| 
SnapManager のプロセスコンポーネントに関連付けられます。



 a| 
ユーティリティ
 a| 
14000-14999
 a| 
SnapManager ユーティリティ、グローバルコンテキストなどに関連しています。



 a| 
ダンプ / 診断
 a| 
15000~15999
 a| 
ダンプまたは診断処理に関連付けられます。



 a| 
ヘルプ
 a| 
16000-16999
 a| 
ヘルプに関連付けられています。



 a| 
サーバ
 a| 
17000-17999
 a| 
SnapManager サーバの管理で使用します。



 a| 
API
 a| 
18000-18999
 a| 
API に関連付けられています。



 a| 
backint
 a| 
19000-19999
 a| 
backintと関連付けられます。



 a| 
認証
 a| 
20000-20999
 a| 
クレデンシャルの許可に関連付けられます。

|===