---
permalink: unix-administration/reference-the-smosmsapclone-delete-command.html 
sidebar: sidebar 
keywords: run, clone, delete, command, operation, smsap 
summary: クローンを削除するには、 clone delete コマンドを実行します。どの処理でもクローンが使用されている場合、クローンは削除できません。 
---
= SMSAPのclone deleteコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クローンを削除するには'clone deleteコマンドを実行しますどの処理でもクローンが使用されている場合、クローンは削除できません。



== 構文

[listing, subs="+macros"]
----
pass:quotes[smsap clone delete
-profile _profile_name_
[-id _guid_ | -label _clone_name_\]
[-login
[-username _db_username_ -password _db_password_ -port _db_port_\]
[-asminstance -asmusername _asminstance_username_ -asmpassword _asminstance_password_\]]]
[-syspassword _syspassword_] -force
[-dump] [-quiet | -verbose]

----


== パラメータ

* ``*-profile_name_*``
+
削除するクローンが含まれているプロファイルの名前を指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* `*-force *``
+
クローンに関連付けられたリソースがある場合も、クローンを削除します。

* `*-id_GUID_*``
+
削除するクローンの GUID を指定します。GUID はクローンを作成するときに SnapManager によって生成されます。「SMSAP clone list」コマンドを使用して、各クローンのGUIDを表示できます。

* `*-label_name_*``
+
削除するクローンのラベルを指定します。

* `*-asminstance*`
+
Automatic Storage Management （ ASM ）インスタンスへのログインに使用するクレデンシャルを指定します。

* ``*-asmusername_asminstance_username_*``
+
ASM インスタンスへのログインに使用するユーザ名を指定します。

* `*-asmpassword_asminstance_password_*``
+
ASM インスタンスへのログインに使用するパスワードを指定します。

* `*-syspassword_syspassword_*``
+
sys 特権ユーザのパスワードを指定します。

+

NOTE: 指定されたデータベースクレデンシャルが sys 特権ユーザに対して同じでない場合は、 sys 特権ユーザのパスワードを指定する必要があります。

* `*-login*``
+
データベースログインの詳細を入力できます。

* ``*-username_db_username_*``
+
データベースへのアクセスに必要なユーザ名を指定します。

* `*-password_ddb_password_*``
+
データベースへのアクセスに必要なパスワードを指定します。

* `*-port_db_port_*``
+
プロファイルに記述されるデータベースへのアクセスに使用する TCP ポート番号を指定します。

* `*-dump*``
+
クローンの削除処理後にダンプファイルを収集するように指定します。

* `*-quiet *``
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* `*-verbose *`
+
エラー、警告、および情報メッセージがコンソールに表示されます。



'''


== 例

次の例は、クローンを削除します。

[listing]
----
smsap clone delete -profile SALES1 -label SALES_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
'''