---
permalink: unix-administration/reference-the-smosmsapbackup-update-command.html 
sidebar: sidebar 
keywords: run, backup, update, command, retention, policy, smsap 
summary: バックアップ保持ポリシーは、 backup update コマンドを実行して更新できます。 
---
= SMSAPのbackup updateコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップ保持ポリシーを更新するには'backup updateコマンドを実行します



== 構文

[listing, subs="+macros"]
----
pass:quotes[smsap backup update
-profile _profile_name_
[-label _label_ [-data | -archivelogs\] | [-id _guid_\]
[-retain {-hourly | -daily | -weekly | -monthly | -unlimited}\]
[-comment _comment_text_\]
[-quiet | -verbose]]
----


== パラメータ

* ``*-profile_name_*``
+
バックアップを更新するプロファイルを指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* `*-id_GUID_*``
+
指定した GUID を持つバックアップを検証します。GUID はバックアップを作成するときに SnapManager によって生成されます。SMSAPのbackup listコマンドを使用して、各バックアップのGUIDを表示できます。

* `*-label_label_*``
+
バックアップのラベルと範囲をデータファイルまたはアーカイブログとして指定します。

* `*-data*``
+
データファイルを指定します。

* `*-archivelogs *``
+
アーカイブログファイルを指定します。

* `*-comment_comment_text_*``
+
バックアップの更新に関するテキスト（最大 200 文字）を入力します。スペースを含めることができます。

* `*-quiet *``
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* `*-verbose *`
+
エラー、警告、および情報メッセージがコンソールに表示されます。

* `*-retain {-hourly|-daily|-weekly|-monthly|-unlimited }*``
+
バックアップを時間単位、日単位、週単位、月単位、または無制限単位で保持するかどうかを指定します。-retainが指定されていない場合'保存クラスはデフォルトで-hourlyに設定されますバックアップを無期限に保持するには、「無制限」オプションを使用します。-unlimitedオプションを使用すると'バックアップは削除できなくなります



'''


== 例

次の例では、バックアップを更新して保持ポリシーを unlimited に設定しています。

[listing]
----
smsap backup update -profile SALES1 -label full_backup_sales_May
-retain -unlimited -comment save_forever_monthly_backup
----
'''