---
permalink: unix-administration/reference-the-smosmsap-notification-updatesummarynotification-command.html 
sidebar: sidebar 
keywords: run, notification, update-summary-notification, command, enable, summary, repository, database, smsap 
summary: notification update-summary-notification コマンドを実行すると、リポジトリデータベースのサマリー通知をイネーブルにできます。 
---
= SMSAPの通知update summary-notificationコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
notification update-summary-notification コマンドを実行すると、リポジトリデータベースのサマリー通知をイネーブルにできます。



== 構文

[listing, subs="+macros"]
----
pass:quotes[smsap notification update-summary-notification
-repository
-port _repo_port_
-dbname  _repo_service_name_
-host _repo_host_
-login -username _repo_username_
-email _email-address1,email-address2_
-subject _subject-pattern_
-frequency
[-daily –time _daily_time_ |
-hourly –time _hourly_time_ |
-monthly –time _monthly_time_ -date [_1_|_2_|_3_|...|_31_\] |
-weekly  –time _weekly_time_ -day [_1_|_2_|_3_|_4_|_5_|_6_|_7_\]\]
-profiles _profile1,profile2_ -notification-host _notification-host_
[-quiet | -verbose]]

----


== パラメータ

* `*-repository*`
+
リポジトリ・データベースの詳細を指定します。

* '*-port_repo_port_*'と入力します
+
リポジトリ・データベースへのアクセスに使用する TCP ポート番号を指定します。

* `*-dbname_repo_service_name *`
+
リポジトリ・データベースの名前を指定します。グローバル名またはシステム ID を使用できます。

* `*-host_repo_host_*`
+
リポジトリ・データベースが格納されているホストの名前または IP アドレスを指定します。

* '*-login*
+
リポジトリ・ログインの詳細を指定します。これはオプションです。指定しない場合、 SnapManager はデフォルトで OS 認証接続モードになります。

* `*-username_repo_username_*`
+
リポジトリ・データベースへのアクセスに必要なユーザ名を指定します。

* `*-email_email-address1, e-mail -address2_*`
+
受信者の E メールアドレスを指定します。

* `*-subject_subject-pattery_*`
+
E メールの件名のパターンを指定します。

* `*-frequency {-daily --hour_daily_time_|-hourly --hourly_schedule_hourly_schedule_time_|-monthly --time _monthly_schedule_-date {_1_|_2_|_3_...|_31_}|-weekly-time _weekly_schedule_day{_1_|_2_|_3_|_3}|_4}|_4}|
+
E メール通知を使用するスケジュールのタイプとスケジュールの時刻を指定します。

* `*-profiles_profile1'profile2_*`
+
E メール通知を必要とするプロファイル名を指定します。

* `*-notification-host_notification-host_*`
+
サマリー通知 E メールの送信元である SnapManager サーバホストを指定します。通知ホストのホスト名または IP アドレスを指定できます。ホストの IP 名またはホスト名を更新することもできます。

* 「*- quiet *」と入力します
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* `*-verbose *`
+
エラー、警告、および情報メッセージがコンソールに表示されます。



'''


== 例

次に、リポジトリデータベースのサマリー通知をイネーブルにする例を示します。

[listing]
----

smsap notification update-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login –username oba5 –email admin@org.com –subject success –frequency -daily -time 19:30:45 –profiles sales1
----
'''