---
permalink: unix-administration/reference-the-smosmsapbackup-create-command.html 
sidebar: sidebar 
keywords: run, backup, create, command, database, storage, system, smsap 
summary: backup create コマンドを実行すると、 1 つ以上のストレージシステム上にデータベースバックアップを作成できます。 
---
= SMSAPのbackup createコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
backup createコマンドを実行して'1つ以上のストレージ・システム上にデータベース・バックアップを作成できます



== 構文


NOTE: このコマンドを実行する前に、 profile create コマンドを使用してデータベースプロファイルを作成する必要があります。

[listing, subs="+macros"]
----
pass:quotes[smsap backup create
-profile profile_name
{[-full{-auto | -online | -offline} [-retain {_-hourly_ | _-daily_ | _-weekly_ | _-monthly_ | _-unlimited_} [-verify\]  |
[-data [[-files _files_ [_files_]] |
pass:quotes[[-tablespaces _tablespaces_ [_tablespaces_]] pass:quotes[[-label _label_]] {-auto | -online | -offline}
pass:quotes[[-retain {_-hourly_ | _-daily_ | _-weekly_ | _-monthly_ | _-unlimited_} [-verify] |
pass:quotes[[-archivelogs [-label _label_]] pass:quotes[[-comment _comment_\]}
[-protect | -noprotect | -protectnow\]
[-backup-dest _path1_ [ _, path2_\]\]
[-exclude-dest path1 [ _, path2_\]\]
[-prunelogs {-all | -until-scn _until-scn_ | -until-date _yyyy-MM-dd:HH:mm:ss_\] | -before {-months | -days | -weeks | -hours}}
-prune-dest _prune_dest1_,[_prune_dest2_\]\]
[-taskspec _taskspec_\]
[-dump]-force
[-quiet | -verbose]]
----


== パラメータ

* `*-profile_name_*`
+
バックアップするデータベースに関連するプロファイルの名前を指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* '*-auto*`*option*
+
データベースがマウント済み状態またはオフライン状態の場合、 SnapManager はオフラインバックアップを実行します。データベースが OPEN または ONLINE 状態の場合、 SnapManager はオンライン・バックアップを実行します。--offline]オプションを指定して--forceオプションを使用した場合、SnapManager はデータベースが現在オンラインであってもオフライン・バックアップを強制します。

* '*-ONLINE *'* OPTION *
+
オンライン・データベース・バックアップを指定します。

+
Real Application Clusters （ RAC ）データベースのオンラインバックアップは、プライマリがオープン状態である場合、またはプライマリがマウントされていてインスタンスがオープン状態である場合にかぎり作成できます。ローカル・インスタンスがSHUTDOWN状態であるか'インスタンスがOPEN状態でない場合には'オンライン・バックアップに-forceオプションを使用できますOracle のバージョンは 10.2.0.5 である必要があります。そうでない場合、 RAC 内のいずれかのインスタンスがマウントされると、データベースは停止します。

+
** ローカル・インスタンスがSHUTDOWN状態で、少なくとも1つのインスタンスがOPEN状態の場合には、「-force」オプションを使用して、ローカル・インスタンスをMOUNTED状態に変更できます。
** オープン状態のインスタンスがない場合は、 -force オプションを使用して、ローカルインスタンスをオープン状態に変更できます。


* '*-offline*'*option*
+
データベースがシャットダウン状態のときに、オフラインバックアップを実行するように指定します。データベースが OPEN または MOUNTED の場合には、バックアップは失敗します。「-force」オプションを使用すると、SnapManager はオフライン・バックアップのためにデータベースをシャットダウンするためにデータベースの状態を変更しようとします。

* '*-full*'*オプション*
+
データベース全体がバックアップされます。これには、すべてのデータ、アーカイブログ、および制御ファイルが含まれます。アーカイブ REDO ログおよび制御ファイルは、実行するバックアップのタイプに関係なくバックアップされます。データベースの一部のみをバックアップする場合は'-files'オプションまたは--tablespacesオプションを使用します

* '*-data*'*オプション*
+
データファイルを指定します。

* `*-files_list_*`
+
指定されたデータファイル、およびアーカイブされたログファイルと制御ファイルのみをバックアップします。ファイル名のリストはスペースで区切ります。データベースが OPEN 状態の場合、 SnapManager は該当する表領域がオンライン・バックアップ・モードになっているかどうかを確認します。

* `*- tablespaces _ tablespaces _*'
+
指定されたデータベースの表領域、およびアーカイブされたログファイルと制御ファイルのみをバックアップします。表領域名はスペースで区切ります。データベースが OPEN 状態の場合、 SnapManager は該当する表領域がオンライン・バックアップ・モードになっているかどうかを確認します。

* '*-label_label_*
+
このバックアップのオプション名を指定します。この名前はプロファイル内で一意である必要があります。名前には、アルファベット、数字、アンダースコア（ _ ）、およびハイフン（ - ）を使用できます。1 文字目をハイフンにすることはできません。ラベルを指定しない場合、 SnapManager は scope_type_date 形式でデフォルトのラベルを作成します。

+
** 範囲は F でフル・バックアップを示し 'P ではパーシャル・バックアップを示します
** type は、オフライン（コールド）バックアップを示す C 、オンライン（ホット）バックアップを示す H 、または自動バックアップを示す A です（例： P_A_20081010060037IST ）。
** date は、バックアップを作成した年月日、および時刻です。
+
SnapManager は 24 時間方式のクロックを使用します。



+
たとえば、 2007 年 1 月 16 日の午後 5 時 45 分 16 分にデータベースをオフラインにしてフルバックアップを実行したとします東部標準時、 SnapManager はラベル F_C_20070116174516EST を作成します。

* `*-comment_string_*`
+
このバックアップに関するコメントを指定します。文字列は一重引用符（ ' ）で囲みます。

+

NOTE: 一部のシェルでは、引用符が除去されます。この場合は、引用符にバックスラッシュ（ \ ）を含める必要があります。たとえば、次のように入力する必要があります。「 \ 」これはコメントです。

* '*-verify*'*option*
+
Oracle の dbv ユーティリティを実行して、バックアップ内のファイルが破損していないかどうかが検証されます。

+

NOTE: -verifyオプションを指定した場合、検証処理が完了するまで、バックアップ処理は完了しません。

* '*-force *`*オプション*
+
データベースが正しい状態でない場合に、状態を強制的に変更します。たとえば、指定したバックアップのタイプおよびデータベースの状態に基づいて、 SnapManager によってデータベースの状態がオンラインからオフラインに変更されることがあります。

+
RACデータベースのオンライン・バックアップでは'ローカル・インスタンスがSHUTDOWN状態であるか'どのインスタンスもOPEN状態でない場合に'-forceオプションを使用します

+

NOTE: Oracle のバージョンは 10.2.0.5 である必要があります。そうでない場合、 RAC 内のいずれかのインスタンスがマウントされると、データベースは停止します。

+
** ローカル・インスタンスがSHUTDOWN状態で'少なくとも1つのインスタンスがOPEN状態の場合に'-forceオプションを使用すると'ローカル・インスタンスがMOUNTED状態に変更されます
** オープン状態になっているインスタンスがない場合は'-forceオプションを使用して'ローカル・インスタンスをオープン状態に変更します


* 「*- quiet *」と入力します
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* `*-verbose *`
+
エラー、警告、および情報メッセージがコンソールに表示されます。

* *-protect|-noprotect|-protectnow*`
+
バックアップをセカンダリストレージで保護するかどうかを指定します。noprotect オプションは、バックアップをセカンダリ・ストレージで保護しないように指定します。フルバックアップのみが保護されます。どちらのオプションも指定しない場合、バックアップがフルバックアップで、プロファイルで保護ポリシーが指定されていれば、 SnapManager はバックアップをデフォルトとして保護します。「-protectnow」オプションは、7-Modeで動作するData ONTAP にのみ適用されます。オプションは、バックアップをセカンダリストレージですぐに保護するように指定します。

* `*-retain {-hourly|-daily|-weekly|-monthly|-unlimited }*`
+
バックアップを時間単位、日単位、週単位、月単位、または無制限単位で保持するかどうかを指定します。-retainオプションが指定されていない場合'リテンション・クラスはデフォルトの-hourlyオプションに設定されますバックアップを無期限に保持するには、「無制限」オプションを使用します。-unlimitedオプションを使用すると'バックアップは保持ポリシーによる削除の対象外になります

* '*-archivelogs*`*option*
+
アーカイブログバックアップを作成します。

* `*-backup-dest path1_,[,_[path2]_*`
+
アーカイブログバックアップ用にバックアップするアーカイブログのデスティネーションを指定します。

* `*-exclude-dest_path1_,[,_[path2]_]*`
+
バックアップから除外するアーカイブログの送信先を指定します。

* `*-prunelogs {-all|-until -scnuntil -scnuntil -date_yyyy-mm -dd：HH：MM:ss_|-before {-months |-days |-weeks |-hours｝*`
+
バックアップの作成時に指定したオプションに基づいて、アーカイブログデスティネーションからアーカイブログファイルを削除します。-allオプションを指定すると'アーカイブ・ログの保存先からすべてのアーカイブ・ログ・ファイルが削除されます--until scn’オプションを指定すると、指定したSystem Change Number（SCN）までアーカイブ・ログ・ファイルが削除されます。--until dateオプションは'指定した期間までアーカイブ・ログ・ファイルを削除します-beforeオプションを指定すると'指定した期間（日'月'週'時間）前のアーカイブ・ログ・ファイルが削除されます

* `*prune-dest_prune_dest1'prune_dest2_*`
+
バックアップの作成時に、アーカイブログデスティネーションからアーカイブログファイルを削除します。

* `*-taskspec_taskspec_*`
+
バックアップ処理の前処理アクティビティまたは後処理アクティビティに使用できるタスク仕様 XML ファイルを指定します。taskspec オプションを指定するときに、 XML ファイルの完全なパスを指定する必要があります。

* `*-dump*`*オプション*
+
データベースバックアップ処理が成功したか失敗したあとにダンプファイルを収集します。



'''


== コマンドの例

次のコマンドでは、フルオンラインバックアップを作成し、セカンダリストレージにバックアップを作成して、保持ポリシーを daily に設定します。

[listing]
----
smsap backup create -profile SALES1 -full -online
-label full_backup_sales_May -profile SALESDB -force -retain -daily
Operation Id [8abc01ec0e79356d010e793581f70001] succeeded.
----
'''