---
permalink: unix-administration/reference-the-smosmsapcredential-delete-command.html 
sidebar: sidebar 
keywords: command, delete, user, credentials, secure, resource, smsap 
summary: このコマンドは、特定のセキュアリソースのユーザクレデンシャルを削除します。 
---
= SMSAPのcredential deleteコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このコマンドは、特定のセキュアリソースのユーザクレデンシャルを削除します。



== 構文

[listing, subs="+macros"]
----
pass:quotes[smsap credential delete
[-host -name _host_name_
-username _username_\] |
[-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_
-port _repo_port_\] |
[-profile
-name _profile_name_\]
[-quiet | -verbose]]
----


== パラメータ

* `*-host_hostname_*`
+
SnapManager が実行されているホストサーバの名前を指定します。

+
-hostパラメータには'次のオプションがあります

+
** `-name_host_name_`:パスワードを削除するホストの名前を指定します
** `-username_user_name :ホスト上のユーザ名を指定します


* `*-repository-dbname*`
+
プロファイルが格納されたデータベースの名前を指定します。グローバル名または SID を使用します。

+
-repositoryパラメータには'次のオプションが含まれます

+
** `-dbname_repo_service_name：プロファイルが格納されているデータベースの名前を指定します。グローバル名または SID を使用します。
** `-host_repo_host_`:リポジトリ・データベースが稼働するホスト・サーバの名前またはIPアドレスを指定します
** `-login-username repo_username_`:リポジトリが格納されたデータベースにアクセスするために必要なユーザ名を指定します
** `-port_repo_port_`:リポジトリが格納されているデータベースへのアクセスに使用するTCPポート番号を指定します。


* `*-profile-name_profile_name_*`
+
データベースに関連付けられたプロファイルを指定します。

+
「-profile」パラメータには、次のオプションが含まれています。

+
** `-name_profilename_`:パスワードを削除するプロファイルの名前を指定します


* 「*- quiet *」と入力します
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* `*-verbose *`
+
エラー、警告、および情報メッセージがコンソールに表示されます。



'''


== コマンドの例

次に、プロファイルのクレデンシャルを削除する例を示します。

[listing]
----
smsap credential delete -profile -name user1 -verbose
----
[listing]
----
SMSAP-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
次に、リポジトリのクレデンシャルを削除する例を示します。

[listing]
----
smsap credential delete -repository -dbname SMSAPREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMSAP-20023 [INFO ]: Deleted repository credentials for "user1@SMSAPREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
次に、ホストのクレデンシャルを削除する例を示します。

[listing]
----
smsap credential delete -host -name Host2
----
[listing]
----
SMSAP-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
'''