---
permalink: unix-administration/reference-the-smosmsapcredential-set-command.html 
sidebar: sidebar 
keywords: command, credentials, user, access, resource, secure, host, repositories, repository, database, profile, snapmanager, run, password, smsap 
summary: このコマンドを使用すると、ホスト、リポジトリ、データベースプロファイルなどのセキュアなリソースにアクセスするためのクレデンシャルをユーザに設定できます。ホストパスワードは、 SnapManager が実行されているホスト上のユーザのパスワードです。リポジトリのパスワードは、 SnapManager リポジトリスキーマが格納されている Oracle ユーザのパスワードです。プロファイルパスワードは、プロファイルを作成するユーザーが構成するパスワードです。ホストとリポジトリのオプションを指定して、オプションの -password オプションを指定した場合は、コマンド引数で指定したタイプのパスワードを入力するように求められます。 
---
= SMSAPのcredential setコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このコマンドを使用すると、ホスト、リポジトリ、データベースプロファイルなどのセキュアなリソースにアクセスするためのクレデンシャルをユーザに設定できます。ホストのパスワードは、 SnapManager が実行されているホストでのユーザのパスワードです。リポジトリのパスワードは、 SnapManager リポジトリスキーマが格納されている Oracle ユーザのパスワードです。プロファイルパスワードは、プロファイルを作成するユーザーが構成するパスワードです。ホストおよびリポジトリのオプションにオプションの-passwordオプションが含まれていない場合は'コマンド引数で指定したタイプのパスワードを入力するように求められます



== 構文

[listing, subs="+macros"]
----
pass:quotes[smsap credential set
[-host
-name _host_name_
-username _username_\]
[-password _password_\] \] |
[-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_\] [-password _repo_password_\] \]
-port _repo_port_ |
[-profile
-name _profile_name_\]
[-password _password_\] \]
[-quiet | -verbose]]
----


== パラメータ

* `*-host_hostname_*`
+
SnapManager を実行しているホストサーバの名前または IP アドレスを指定します。

+
-hostパラメータには'次のオプションがあります

+
** `-name_host_name_`:パスワードを設定するホストの名前を指定します
** `-username_user_name :ホスト上のユーザ名を指定します
** `-password_password_`ホスト上のユーザーのパスワードを指定します。


* `*-repository-dbname*`
+
プロファイルが格納されたデータベースの名前を指定します。グローバル名または SID を使用します。

+
-repositoryパラメータには'次のオプションが含まれます

+
** `-dbname_repo_service_name：プロファイルが格納されているデータベースの名前を指定します。グローバル名または SID を使用します。
** `-host_repo_host_`:リポジトリ・データベースが稼働するホスト・サーバの名前またはIPアドレスを指定します
** `-login-username repo_username_`:リポジトリが格納されたデータベースにアクセスするために必要なユーザ名を指定します
** `-password_password_`:リポジトリが格納されたデータベースにアクセスするために必要なパスワードを指定します。
** `-port_repo_port_`:リポジトリが格納されているデータベースへのアクセスに使用するTCPポート番号を指定します。


* `*-profile-name_profile_name_*`
+
データベースに関連付けられたプロファイルを指定します。

+
「-profile」パラメータには、次のオプションが含まれています。

+
** `-name_profilename_`:パスワードを設定するプロファイルの名前を指定します
** `-password_password_`：プロファイルにアクセスするために必要なパスワードを指定します。


* 「*- quiet *」と入力します
+
コンソールにエラーメッセージのみを表示します。デフォルトでは、エラーおよび警告メッセージが表示されます。

* `*-verbose *`
+
エラー、警告、および情報メッセージがコンソールに表示されます。



'''


== リポジトリクレデンシャルを設定するコマンドの例

次に、リポジトリのクレデンシャルを設定する例を示します。

[listing]
----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----
[listing]
----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----
'''
'''


== ホストクレデンシャルを設定するためのコマンドの例

ホストクレデンシャルは実際のオペレーティングシステムクレデンシャルを表すため、パスワードのほかにユーザ名も含める必要があります。

[listing]
----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----
'''