---
permalink: unix-administration/reference-the-smosmsapbackup-restore-command.html 
sidebar: sidebar 
keywords: run, backup, restore, command, database, portion, recover, information, smsap 
summary: backup restore コマンドを実行してデータベースまたはデータベースの一部のバックアップをリストアし、必要に応じてデータベース情報をリカバリすることができます。 
---
= SMSAPのbackup restoreコマンドを使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「backup restore」コマンドを実行してデータベースまたはデータベースの一部のバックアップをリストアし、オプションでデータベース情報をリカバリすることができます。



== 構文

[listing, subs="+macros"]
----
pass:quotes[smsap backup restore
-profile _profile_name_
[-label _label_ | -id _id_\]
[-files files [_files..._\] |
-tablespaces _tablespaces [tablespaces...\]_\] |
-complete | -controlfiles\]
[-recover {-alllogs | -nologs | -until _until_} [-using-backup-controlfile\] \]
[-restorespec _restorespec_ | -from-secondary [-temp-volume _temp_volume_\] [-copy-id _id_\]\]
[-preview\]
[-fast {-require | -override | -fallback | -off}\]
[-recover-from-location _path1_ [_, path2_\]\] [-taskspec _taskspec_\][-dump\]
[-force\]
[-quiet | -verbose\]]
----


== パラメータ

* `*-profile_name_*`
+
リストアするデータベースを指定します。プロファイルには、データベースの識別子およびその他のデータベース情報が含まれています。

* '*-label_name_*'
+
指定したラベルを持つバックアップをリストアします。

* '*-id_GUID_*'
+
指定した GUID を持つバックアップをリストアします。GUID はバックアップを作成するときに SnapManager によって生成されます。SMSAPのbackup listコマンドを使用して、各バックアップのGUIDを表示できます。

* * すべてのファイルまたは指定されたファイルを選択 *
+
必要に応じて、次のいずれかのオプションを使用できます。

+
** 「-complete」を指定すると、バックアップ内のすべてのデータ・ファイルがリストアされます。
** `-tablespaces -list_`：指定した表領域だけをバックアップからリストアします。
+
リスト内で名前を区切るには、スペースを使用する必要があります。

** `-files_list：指定したデータ・ファイルだけをバックアップからリストアします。
+
リスト内で名前を区切るには、スペースを使用する必要があります。データベースが稼働している場合、 SnapManager はファイルを含む表領域がオフラインであることを確認します。



* `*-controlfiles *`
+
制御ファイルをリストアします。SnapManager では、バックアップ内のデータ・ファイルと制御ファイルを一度にリストアできます。controlcontrolcontrolfilesオプションは'-s'complete'`-tablespaces '-files'などのリストア範囲パラメータから独立しています

* '*-recover*
+
リストア後にデータベースをリカバリします。また、次のいずれかのオプションを使用して、 SnapManager でデータベースのリカバリ・ポイントを指定する必要があります。

+
** -nologs:データベースをバックアップ時刻までリカバリし'ログを適用しません
+
このパラメータは、オンラインバックアップまたはオフラインバックアップに使用できます。

** -alllogs:データベースを最後のトランザクションまたはコミットまでリカバリし'必要なすべてのログを適用します
** `-until date`:指定された日時までデータベースをリカバリします
+
年-月-日：時：分：秒（_yyyy-mm-dd：hh：mm：ss_）の形式で指定する必要があります。データベースの設定に応じて、 12 時間形式または 24 時間形式のどちらかを使用してください。

** `-until scn `:指定したシステム変更番号(scn)に達するまで'データファイルをロールして転送します
** `-using-backup-controlfile：バックアップ制御ファイルを使用してデータベースをリカバリします。


* `*-restorespec *`
+
元の各 Snapshot コピーがアクティブファイルシステムにマッピングされているため、データをアクティブファイルシステムにリストアし、指定したデータからリストアすることができます。オプションを指定しない場合、 SnapManager はプライマリストレージ上の Snapshot コピーからデータをリストアします。次のいずれかのオプションを指定できます。

+
** `-restorespec`：リストアするデータとリストア形式を指定します。
** --from-secondary]：セカンダリ・ストレージからデータをリストアします
+
プライマリストレージにバックアップが存在する場合は、このオプションを使用できません。セカンダリストレージからバックアップをリストアするには、プライマリバックアップを解放しておく必要があります。一時ボリュームを使用する場合は'-dtemp-volume'オプションを使用してボリュームを指定する必要があります

+
--from-secondaryオプションを指定する場合は、必ず-copy-idオプションを指定する必要があります。セカンダリ・ストレージ・システムに複数のバックアップが存在する場合は'-copy-idオプションを使用して'リストア処理に使用するセカンダリ・ストレージ上のバックアップ・コピーを指定します

+

NOTE: Data ONTAP 7-Modeを使用している場合は、「-copy-id」オプションに有効な値を指定する必要があります。ただし、clustered Data ONTAP を使用している場合、-copy-id`オプションは不要です

+
SnapManager は、セカンダリストレージからリストアする際、最初に（ホストを介さずに）セカンダリストレージシステムからプライマリストレージシステムにデータを直接リストアします。SnapManager がこのタイプのリストアを実行できない場合（ファイルがファイルシステムの一部でない場合など）、 SnapManager はホスト側のファイルコピーのリストアにフォールバックします。SnapManager では、セカンダリからホスト側のファイルコピーのリストアを 2 つの方法で実行できます。SnapManager で選択される方法は'SMSAP_CONFIG'ファイルで設定されています

** 直接： SnapManager はセカンダリストレージ上にデータのクローンを作成し、クローニングされたデータをセカンダリストレージシステムからホストにマウントして、クローンのデータをアクティブ環境にコピーします。
+
これはデフォルトのセカンダリアクセスポリシーです。

** 間接： SnapManager は、最初にプライマリストレージ上の一時ボリュームにデータをコピーし、一時ボリュームからホストにデータをマウントしてから、一時ボリュームからアクティブな環境にデータをコピーします。
+
このポリシーは、ホストがセカンダリストレージシステムに直接アクセスできない場合にのみ使用してください。間接方式を使用したリストアでは、データのコピーが 2 つ作成されるため、セカンダリへの直接アクセスポリシーに 2 倍の時間がかかります。



+
直接方式と間接方式のどちらを使用するかは'smsap.config'構成ファイルの_restore.secondaryAccessPolicy_`パラメータの値によって決まります

* '*- preview *'
+
次の情報を表示します。

+
** 各ファイルのリストアに使用するリストアメカニズム（高速リストア、ストレージ側のファイルシステムのリストア、ストレージ側のファイルのリストア、またはホスト側のファイルコピーのリストア
** 各ファイルのリストアに'より効率的なメカニズムが使用されなかった理由-previewオプションを使用している場合'-verboseオプションを指定すると'次のことが必要になります
** 「-force」オプションは、コマンドには影響しません。
** -recoverオプションは'コマンドには影響しません
** -fast`オプション(--require,-override,-fallback,`-off`)は出力に大きな影響を与えます。リストア処理をプレビューするには、データベースをマウントする必要があります。リストア計画をプレビューする際に、データベースが現在マウントされていない場合は、 SnapManager によってデータベースがマウントされます。データベースをマウントできない場合、コマンドは失敗し、 SnapManager はデータベースを元の状態に戻します。


+
「-preview」オプションを使用すると、最大20個のファイルが表示されます。「SMSAP_CONFIG」ファイルに表示されるファイルの最大数を設定できます。

* '*-ffast*'
+
リストア処理で使用するプロセスを選択できます。必須のリストア条件がすべて満たされている場合は、 SnapManager で他のリストアプロセスではなくボリュームベースの高速リストアプロセスを強制的に使用できます。ボリュームリストアを実行できないことがわかっている場合は、このプロセスを使用して、高速リストアプロセスを使用して、 SnapManager で適格性チェックとリストア処理を実行できないようにすることもできます。

+
--fast'オプションには'次のパラメータが含まれます

+
** -require`：すべてのリストアの条件が満たされた場合に、SnapManager にボリュームのリストアを強制的に実行させることができます。
+
--fast'オプションを指定しても'-ffast'のパラメータを指定しない場合、SnapManager はデフォルトとして-require`パラメータを使用します。

** -override:非必須の適格性チェックをオーバーライドし'ボリューム・ベースの高速リストア・プロセスを実行できます
** `-fallback`: SnapManager が決定する任意の方法を使用してデータベースをリストアできます
+
-fast`オプションを指定しない場合、SnapManager はデフォルトの「backup restore-fast fallback」オプションを使用します。

** `-off`:資格チェックを実行するのに必要な時間を避けることができます


* `*-recovery-from-location*`
+
アーカイブログファイルの外部アーカイブログの場所を指定します。SnapManager は外部の場所からアーカイブログファイルを取得し、リカバリプロセスに使用します。

* `*-taskspec*`
+
リストア処理の前処理アクティビティまたは後処理アクティビティのタスク仕様 XML ファイルを指定します。タスク仕様 XML ファイルの完全なパスを指定する必要があります。

* `*-dump*`
+
リストア処理後にダンプファイルを収集するように指定します。

* 「*-force *」を使用します
+
必要に応じて、データベースの状態を現在の状態よりも低い状態に変更します。Real Application Clusters（RAC）の場合、SnapManager でRACインスタンスの状態を低いレベルに変更する必要がある場合は、「-force」オプションを含める必要があります。

+
デフォルトでは、 SnapManager は処理中にデータベースを高いレベルの状態に変更できます。SnapManager でデータベースを高いレベルの状態に変更する場合、このオプションは必要ありません。

* 「*- quiet *」と入力します
+
コンソールにエラーメッセージのみを表示します。デフォルト設定では、エラーおよび警告メッセージが表示されます。

* `*-verbose *`
+
エラー、警告、および情報メッセージがコンソールに表示されます。このオプションを使用すると、より効率的なリストアプロセスでファイルをリストアできなかった理由を確認できます。



'''


== 例

次に、データベースおよび制御ファイルをリストアする例を示します。

[listing]
----
smsap backup restore -profile SALES1 -label full_backup_sales_May
-complete -controlfiles -force
----
'''