---
permalink: unix-administration/task-preview-backup-restore-information.html 
sidebar: sidebar 
keywords: preview, information, backup, restore, process, snapmanager, sap, successful 
summary: バックアップのリストアプロセスに関する情報を実行前にプレビューして、SnapManager for SAPでバックアップに見つかったリストア対応状況を確認できます。SnapManager はバックアップ上のデータを分析して、リストアプロセスを正常に完了できるかどうかを判断します。 
---
= バックアップリストア情報をプレビューします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップのリストアプロセスに関する情報を実行前にプレビューして、SnapManager for SAPでバックアップに見つかったリストア対応状況を確認できます。SnapManager はバックアップ上のデータを分析して、リストアプロセスを正常に完了できるかどうかを判断します。

* このタスクについて *

リストアプレビューでは次の情報を確認できます。

* 各ファイルのリストアに使用できるリストアメカニズム（高速リストア、ストレージ側のファイルシステムのリストア、ストレージ側のファイルのリストア、またはホスト側のファイルコピーのリストア）
* 「-verbose」オプションを指定した場合に、各ファイルの復元に、より効率的なメカニズムが使用されなかった理由。


「backup restore」コマンドで「-preview」オプションを指定した場合、SnapManager は何もリストアしませんが、リストアするファイルとリストア方法を一覧表示します。


NOTE: すべてのタイプのリストアメカニズムをプレビューできます。プレビューには、最大 20 個のファイルに関する情報が表示されます。

.手順
. 次のコマンドを入力します。
+
'*SMSAP backup restore -profile profile_name'-label_label_-complete-preview -verbose *

+
* 例 *

+
たとえば、次のように入力します。

+
[listing]
----
smsap backup restore -profile targetdb1_prof1
      -label full_bkup_sales_nov_08  -complete -preview -verbose
----
+
次に、ホスト側のファイルコピーリストアプロセスを使用してリストアされるファイルと、高速リストアオプションを使用してリストアできないファイルの例を示します。「-verbose」オプションを指定すると、SnapManager にプレビュー・セクションと、高速リストア・プロセスを使用して各ファイルをリストアできない理由を説明する解析セクションが表示されます。

+
[listing]
----
PREVIEW:
The following files will be restored via host side file copy restore:
+DG2/sid/datafile10.dbf
+DG2/sid/datafile11.dbf

ANALYSIS:
The following reasons prevent certain files from being restored via fast restore:
Reasons:
 Newer snapshots of /vol/volume2 have volume clones: SNAP_1
*Newer backups will be freed: nightly2, nightly3
Files to Restore:
/mnt/systemB/volume2/system.dbf
/mnt/systemB/volume2/users.dbf
/mnt/systemB/volume2/sysaux.dbf
/mnt/systemB/volume2/datafile04.dbf
/mnt/systemB/volume2/datafile05.dbf

The following reasons prevent certain files from being restored via fast restore:
Reasons:
* Newer snapshots of /vol/adm_disks will be lost: ADM_SNAP_5
* Luns present which were created after snapshot SNAP_0 was created: /vol/adm_disks/disk5.lun
* Files not part of the restore scope will be reverted in file system: +DG2

Files Not in Restore Scope: +DG2/someothersid/data01.dbf
+DG2/someothersid/data02.dbf
Files to Restore:
+DG2/sid/datafile08.dbf +DG2/sid/datafile09.dbf
+DG2/sid/datafile10.dbf +DG2/sid/datafile11.dbf

* Reasons denoted with an asterisk (*) are overridable.
----
. 他のリストア・プロセスを使用できない理由を確認します。
. 上書き可能な理由だけが表示されている場合は'-preview'オプションを使用せずにリストア操作を開始します
+
必須でないチェックは無視してもかまいません。


