---
permalink: unix-administration/task-prune-archive-log-files.html 
sidebar: sidebar 
keywords: prune, archive, log, file, backup, pruning 
summary: バックアップを作成する際に、アーカイブログの場所からアーカイブログファイルの削除を実行できます。 
---
= アーカイブログファイルのプルーニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップを作成する際に、アーカイブログの場所からアーカイブログファイルの削除を実行できます。

* 必要なもの *

* アーカイブログファイルは、現在のバックアップ処理でバックアップする必要があります。
+
プルーニングをアーカイブログファイルを含まない他のバックアップとともに指定すると、アーカイブログファイルはプルーニングされません。

* データベースはマウント済み状態である必要があります。
+
データベースがマウント状態でない場合は、 backup コマンドとともに -force オプションを入力します。



* このタスクについて *

バックアップ処理を実行する際には、次の項目を指定できます。

* プルーニングの範囲：
+
** すべてのアーカイブログファイルを削除します。
** 指定の System Change Number （ SCN ）までアーカイブログファイルを削除してください。
** 指定された時間までアーカイブログファイルを削除します。
** 指定した期間が経過する前にアーカイブログファイルを削除します。


* アーカイブログファイルの削除元となるデスティネーション。
+

NOTE: アーカイブ・ログ・ファイルの削除が 1 つのデスティネーションで失敗した場合でも、 SnapManager は、アーカイブ・ログ・ファイルを他のデスティネーションから削除し続けます。



アーカイブログファイルを削除する前に、 SnapManager では次のことが検証されます。

* アーカイブログファイルは少なくとも 1 回はバックアップされます。
* アーカイブログファイルがある場合は、 Oracle Dataguard Standby データベースに送付されます。
* アーカイブログファイルは、 Oracle ストリームキャプチャプロセスによってキャプチャされます（存在する場合）。


アーカイブログファイルがバックアップされ、スタンバイに出荷され、キャプチャプロセスでキャプチャされた場合、 SnapManager はすべてのアーカイブログファイルを 1 回の実行で削除します。ただし、バックアップされていないアーカイブログファイル、スタンバイに出荷されていないアーカイブログファイル、またはキャプチャプロセスでキャプチャされていないアーカイブログファイルがある場合、 SnapManager はアーカイブログファイルを 1 つずつ削除します。アーカイブログファイルを 1 回の実行で削除するよりも、アーカイブログを 1 つずつ削除するほうが短時間で完了します。

SnapManager では、アーカイブログファイルをグループ化してバッチ単位で削除することもできます。各バッチの最大ファイル数は 998 です。この値は'smsap.config'ファイルの構成パラメータmaximum.archivelog.files.toprune.atATime'を使用して'998未満に設定できます

SnapManager では、 Oracle Recovery Manager （ RMAN ）コマンドを使用してアーカイブ・ログ・ファイルを削除します。ただし、 SnapManager は、 RMAN 保持ポリシーおよび削除ポリシーと統合しません。


NOTE: アーカイブ・ログ・デスティネーションからアーカイブ・ログ・ファイルを削除すると、アーカイブ・ログ・ファイルの削除に失敗します。

次のシナリオでは、 SnapManager はアーカイブログファイルの削除をサポートしていません。

* アーカイブログファイルはフラッシュリカバリ領域にあります。
* アーカイブログファイルはスタンバイデータベースにあります。
* アーカイブ・ログ・ファイルは、 SnapManager と RMAN の両方で管理されます。


.ステップ
. 次のコマンドを入力します。
+
`* SMSAP backup create -profile profile_profile_name_{[-full｛-online |-offline |-auto｝[-retain｛-hourly |[-daily |-weekly |-unlimited｝][-verify]|[-data [[-files_[_files_]|[-monthly |]-retain-daily. [-archivelogs [-label_label_][-comment_comment_][-prot|-proten][-backup-dest_path1_[,[_path2_]][-exclude-dest_path1_path1_[_,path2_]][-prunelogn {-prunte_date-months {-dest-des|-dest-drivers]-dest-drivers_unted|-date-spec_unted|までの実行日数}～月～月～月～{dest-des|月～{dest-des|月～分～分～分～分～分～分～分～日～分～分～分～分～分～{～}～分～分～分～分～分～分～分～分～～分～分～分～{～{～{～{～{～{～{～}

+
[cols="1a,3a"]
|===
| 状況 | 作業 


 a| 
* アーカイブログファイルをプルーニング *
 a| 
次のオプションを指定します。

** -logprunsは'バックアップを作成するときにアーカイブ・ログ・ファイルを削除するように指定します
+
*** 「-all」は、すべてのアーカイブ・ログ・ファイルを削除することを指定します。
*** 「-untilscn」は、指定したSCNまでアーカイブ・ログ・ファイルを削除することを指定します。
*** 「-until date」は、指定した日時を含むアーカイブ・ログを削除することを指定します。
*** `-before `{months|-days|-wee|-hours}-指定した期間内にアーカイブ・ログ・ファイルを削除するように指定します。






 a| 
* アーカイブログファイルを削除する場所を指定します。 *
 a| 
-prune-dest`オプションを指定します

|===

