---
permalink: unix-administration/task-add-new-profile-to-summary-notification.html 
sidebar: sidebar 
keywords: configure, summary, email, notification, repository, database, profile, command 
summary: リポジトリデータベースのサマリー E メール通知を設定したら、 summary notification コマンドを使用して、新しいプロファイルをサマリー通知に追加できます。 
---
= 概要Eメール通知に新しいプロファイルを追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リポジトリデータベースのサマリー E メール通知を設定したら、 summary notification コマンドを使用して、新しいプロファイルをサマリー通知に追加できます。

.ステップ
. 次のコマンドを入力します。
+
`* SMSAP profile create -profile profile_profile_name_[-profile-password-password_profile_profile_name_host-repository_repo_repo_repo_repo_repo_repo_repo_repo_repo_port_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_username -host_namea_datab_database-db_hosts_[-sidbost_account_host_sdc_account_host_name]-RMANパスワード[-sdb_password-dry_host_domain_domain_group]-RMANパスワード[-drmanパスワード[-drmanパスワード[-drman_domain_domain_domain_domain_domain_domain_domain_リストア_オプション[-drmanパスワード[-drmanパスワード[-drman_password_password_host_host_host_host_domain_host_host_domain_domain_host_host_host_domain_domain_domain_domain_リストア]-RMANパスワード]-RMANパスワード[-drmanパスワード[-sid]-RMANパスワード[-drmanパスワード[-drmanパスワード[-drmanパスワード[-drmanパスワード]-RMANパスワード [-weekly-count_n_][-duration _m_]][-monthly-count_n_][-duration _m_]][-comment_comment_][-snapname-pattern_][-protect[-protect[-policy_policy_policy_policy_policy_policy_policy_policy_name][-summary-notification]*

+
このコマンドの他のオプションは、次のとおりです。

+
「[-force]``」

+
「[-quiet |-verbose ]」


