---
permalink: unix-administration/task-update-storage-system-name-associated-with-a-profile.html 
sidebar: sidebar 
keywords: snapmanager, provide, ability, update, host, name, ip, address, storage, system, associate, profile, updating 
summary: SnapManager 3.3 以降では、プロファイルに関連付けられたストレージ・システムのホスト名または IP アドレスを更新できます。 
---
= プロファイルに関連付けられたストレージ・システムの名前を更新します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager 3.3 以降では、プロファイルに関連付けられたストレージ・システムのホスト名または IP アドレスを更新できます。

* 必要なもの *

次の点を確認する必要があります。

* プロファイルには少なくとも 1 つのバックアップが含まれています。
+
プロファイルにバックアップがない場合は、そのプロファイルのストレージ・システム名を更新する必要はありません。



* このタスクについて *

* プロファイルに対して実行中の処理はありません。


SnapManager コマンドラインインターフェイス（ CLI ）を使用して、ストレージシステムの名前または IP アドレスを更新できます。ストレージシステム名を更新する際、リポジトリデータベースに格納されているメタデータだけが更新されます。ストレージシステム名の変更後、 SnapManager の操作をすべて先に実行できます。


NOTE: ストレージシステム名は、 SnapManager のグラフィカルユーザインターフェイス（ GUI ）を使用して変更することはできません。

Snapshot コピーが新しいストレージシステムで使用可能であることを確認する必要があります。SnapManager は、ストレージ・システムに Snapshot コピーが存在するかどうかを検証しません。

ただし、ストレージシステム名の変更後にホストのロールアップグレードおよびロールバックを実行する際は、次の点に注意する必要があります。

* ストレージシステム名の変更後にホストのローリングアップグレードを実行する場合は、プロファイルを新しいストレージシステム名に更新する必要があります。
+
SnapDrive コマンドを使用してストレージシステム名を変更する方法については、「ストレージシステム名の問題のトラブルシューティング」を参照してください。

* ストレージシステムの名前を変更したあとにホストをロールバックする場合は、以前のストレージシステムのプロファイル、バックアップ、およびクローンを使用して SnapManager 処理を実行できるように、ストレージシステム名を元のストレージシステム名に戻してください。



NOTE: SnapDrive がストレージ・システムを識別できず ' エラー・メッセージが表示された場合は 'ipmigrate コマンドに ' ストレージ・システムの以前のホスト名とそれ以降のホスト名を入力できますストレージシステム名の問題に関する追加情報の詳細については、ストレージシステム名の問題のトラブルシューティング _ を参照してください。

.ステップ
. 次のコマンドを入力します。
+
'*SMSAP storage rename - profile_profile_-oldname_old_storage_name -- newname_new_storage_name_[quiet |-verbose '*

+
[cols="1a,2a"]
|===
| 状況 | 作業 


 a| 
プロファイルに関連付けられたストレージ・システムの名前を更新します
 a| 
「-profile」オプションを指定します。



 a| 
プロファイルに関連付けられたストレージ・システムの名前または IP アドレスを更新します
 a| 
次のオプションと変数を指定します。

** `-oldname_old_storage_nameは、ストレージ・システムのホスト名またはIPアドレスです。
** `-newname_new_storage_name_`は、ストレージシステムのホスト名またはIPアドレスです。


|===
+
'''
+
次の例は、更新するストレージシステムの名前を示しています。



[listing]
----
smsap storage rename -profile mjullian -oldname lech -newname hudson -verbose
----
'''