---
permalink: unix-administration/task-delete-clones.html 
sidebar: sidebar 
keywords: delete, clone, size, snapshot, copy, backup, guarantee, data, deleting 
summary: 'Snapshot コピーのサイズがバックアップの 10~20% の間に達した時点でクローンを削除できます。これにより、クローンに最新のデータが保持されます。' 
---
= クローンを削除します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshot コピーのサイズがバックアップの 10~20% の間に達した時点でクローンを削除できます。これにより、クローンに最新のデータが保持されます。

* このタスクについて *

ラベルは、プロファイル内の各クローンの一意の識別子です。クローンを削除するときは、システム ID （ SID ）ではなく、クローンのラベルまたは ID を使用できます。


NOTE: クローンの SID とクローンのラベルが異なります。

クローンを削除する場合は、データベースが実行されている必要があります。そうしないと、既存のクローンのファイルやディレクトリが多数削除されないため、別のクローンを作成する前により多くの作業が行われるようになります。

クローンを削除すると、クローン内の特定の Oracle パラメータに対して指定されたディレクトリが破棄されます。このディレクトリには、クローンデータベースのアーカイブログのデスティネーション、バックグラウンド、コア、およびユーザダンプのデータのみが含まれている必要があります。監査ファイルは削除されません。


NOTE: クローンが他の処理で使用されている場合、クローンを削除することはできません。

必要に応じて、クローンの削除処理が成功した場合や失敗した場合にダンプファイルを収集できます。

.ステップ
. 次のコマンドを入力します。
+
`* SMSAP clone delete -profile profile_profile_name_[-label_label_|-id_GUID_][-syspassword_]|[login-username db_username_password]_db_password_[-asminstance -asmusername _asm_port_username][-fasminstance-asmusername_sp_username_password][asquiet]-password*



'''


== 例

[listing]
----
smsap clone delete -profile targetdb1_prof1 -label sales0908_clone1
----
'''