---
permalink: unix-administration/task-clone-databases-from-backups.html 
sidebar: sidebar 
keywords: clone, database, backup, create, command, cloning 
summary: バックアップからデータベースをクローニングするには、 clone create コマンドを使用します。 
---
= バックアップからデータベースをクローニングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「clone create」コマンドを使用すると、バックアップからデータベースをクローニングできます。

* このタスクについて *

最初に、データベースのクローン仕様ファイルを作成する必要があります。SnapManager は、この仕様ファイル内の情報に基づいてクローンを作成します。

データベースのクローンを作成した後で'新しいクローン・データベース接続情報を使用して'クライアント・マシン上のtnsnames.oraファイルを更新する必要がある場合があります「tnsnames.ora」ファイルは、完全なデータベース情報を指定することなくOracleインスタンスに接続するために使用されます。SnapManager は'tnsnames.oraファイルを更新しません

--incluse-with -online-backups'で作成したプロファイルを使用している場合、SnapManager は常にアーカイブ・ログ・ファイルを含むバックアップを作成します。SnapManager でクローニングできるのは、フルデータベースバックアップのみです。

SnapManager （ 3.2 以降）では、データ・ファイルおよびアーカイブ・ログ・ファイルが含まれているバックアップをクローニングできます。

アーカイブログが外部の場所から利用できる場合、クローニング中に外部の場所を指定して、クローンデータベースを整合性のある状態にリカバリできます。外部の場所に Oracle からアクセスできることを確認する必要があります。アーカイブログのみのバックアップのクローニングはサポートされていません。

アーカイブログのバックアップは、オンラインのパーシャルバックアップとともに作成されますが、このバックアップを使用してデータベースのクローンを作成することはできません。

外部アーカイブログファイルの場所からデータベースバックアップをクローニングできるのは、スタンドアロンデータベースの場合だけです。

外部アーカイブログファイルの場所を使用した Real Application Clusters （ RAC ）データベースのオンラインデータベースバックアップのクローニングが、リカバリエラーのために失敗します。これは、データベースバックアップのクローニング中に、 Oracle データベースが外部アーカイブログの場所からリカバリ用のアーカイブログファイルを検出して適用できないためです。

オプション・パラメータとして'-dump'オプションを指定すると'クローン作成の成功または失敗後にダンプ・ファイルを収集できます

* アーカイブログバックアップなしのデータファイルバックアップのクローニング *

データファイルのバックアップにアーカイブログバックアップが含まれていない場合、SnapManager for SAPはバックアップ時に記録されたSystem Change Number（SCN）に基づいてデータベースのクローンを作成します。クローニングされたデータベースをリカバリできない場合は、SnapManager for SAPがデータベースのクローニングを続行していて、最後にクローンの作成に成功したにもかかわらず、「Archived log file for thread <number>とchange <scn > required to complete recovery」というエラーメッセージが表示されます。

アーカイブログのバックアップを含めずにデータファイルのバックアップを使用してクローニングする場合、 SnapManager は、バックアップ中に記録される最後のアーカイブログ SCN まで、クローニングされたデータベースをリカバリします。

.手順
. クローン仕様ファイルを作成します。
. クローンを作成するには、次のコマンドを入力します。
+
*SMSAP clone create -backup-label_backup_name _-newsid_news_sid_-label_label_profile_name_-clonespecfile_[-taskspec_spec_][-recover-from-location]_path1[,<path2>>ダンプ


