---
permalink: unix-administration/task-delete-backups.html 
sidebar: sidebar 
keywords: delete, backup, free, space, remove, snapshot, copies, copy, volume, deleting 
summary: 不要になったバックアップを削除する必要があります。これにより、バックアップが占有するスペースが解放されます。バックアップを削除することにより、ボリュームあたりの Snapshot コピー数が上限の 255 に達する可能性が低くなります。 
---
= バックアップを削除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
不要になったバックアップを削除する必要があります。これにより、バックアップが占有するスペースが解放されます。バックアップを削除することにより、ボリュームあたりの Snapshot コピー数が上限の 255 に達する可能性が低くなります。

* 必要なもの *

* バックアップを使用してクローンを作成していないことを確認する必要があります。


* このタスクについて *

保護されたバックアップを削除すると、 SnapManager はセカンダリストレージと SnapManager リポジトリからバックアップを削除します。次の表に、ローカルバックアップを削除したときにプライマリストレージとセカンダリストレージで実行される処理を示します。

[cols="2a,1a,3a,3a,4a"]
|===
| 保護状態 | ローカルステータス | プライマリストレージに対する処理 | セカンダリストレージに対する処理 | 説明 


 a| 
要求されていない（保護対象）
 a| 
が存在します
 a| 
Snapshot コピーを削除します
 a| 
対処は不要です。
 a| 
SnapManager によってローカルバックアップが削除されます。



 a| 
解放済み
 a| 
対処は不要です。
 a| 
対処は不要です。
 a| 
ローカルバックアップはすでに解放されています。解放されたバックアップを削除すると、バックアップのメタデータはリポジトリから削除されます。



 a| 
保護されていない
 a| 
が存在します
 a| 
Snapshot コピーを削除します
 a| 
対処は不要です。
 a| 
SnapManager は、保護されているかどうかに関係なく、ローカルバックアップを削除します。



 a| 
解放済み
 a| 
対処は不要です。
 a| 
対処は不要です。
 a| 
ローカルバックアップはすでに解放されています。解放されたバックアップを削除すると、バックアップのメタデータはリポジトリから削除されます。



 a| 
保護
 a| 
が存在します
 a| 
Snapshot コピーを削除します
 a| 
SnapManager は、セカンダリストレージ上のバックアップを削除します
 a| 
SnapManager によって、ローカルバックアップとセカンダリコピーが削除されます。



 a| 
解放済み
 a| 
対処は不要です。
 a| 
SnapManager がセカンダリストレージ上のバックアップを解放します
 a| 
SnapManager によって、ローカルバックアップとセカンダリコピーが削除されます。

|===
セカンダリストレージで保護されているバックアップを削除しようとすると、 Snapshot コピーは削除対象としてマークされ、あとで Protection Manager で削除される可能性があります。

保持するバックアップは、保持クラスを変更することなく、無制限に削除できます。

必要に応じて、バックアップの削除処理が成功または失敗したあとにダンプファイルを収集できます。

アーカイブログバックアップを削除する場合は、アーカイブログバックアップに対して設定された保持期間を確認する必要があります。アーカイブログのバックアップが保持期間内にあり、リストアされたデータベースのリカバリにアーカイブログファイルが必要な場合、アーカイブログのバックアップを削除することはできません。

.手順
. 次のコマンドを入力して、処理が完了したことを確認します。
+
`* SMSAP operation list -profile_name__-dump -quiet -verbose *`

. バックアップを削除するには、次のコマンドを入力します。
+
'*SMSAP backup delete -profile _profile_name_[-label_[data|-archivelogs ]|-id_id_|-all][-force ][-dump][-quiet |-verbose *`

+
force オプションを使用して、バックアップを強制的に削除します。処理を完了していないバックアップを削除しようとすると、バックアップが不完全な状態のまま残ることがあります。


