---
permalink: unix-administration/task-configure-e-mail-notification-for-a-new-profile.html 
sidebar: sidebar 
keywords: creating, create, configure, configuring, email, notification, profile, database, operation 
summary: 新しいプロファイルを作成する場合、データベース処理が完了したときに E メール通知を受け取るようにを設定できます。 
---
= 新しいプロファイルのEメール通知を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいプロファイルを作成する場合、データベース処理が完了したときに E メール通知を受け取るようにを設定できます。

* 必要なもの *

* アラートの送信元 E メールアドレスを設定する必要があります。
* 複数の E メールアドレスを指定する場合は、カンマで区切って指定する必要があります。
+
カンマと次の E メールアドレスの間にスペースを入れないようにしてください。



.ステップ
. 次のコマンドを入力します。
+
`* SMSAP profile create -profile create -profile profile_[-profile-password_profile_profile_password_]-repository -dbname_repo_repo_repo_host_host_-port_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_username -host_db1_db_host_db1_host_db1_host_db1_host_db1_host_db1_host_[-drd_db_sid_account]-osdba_password-drman [-drman_drman_password-drman [-drman_password-drman_drman_password-drman_drman_db1_account_group]-RMANパスワード[-drman_drman_host_name[-drman_password-drman_drman_password-drman_password-drman_drman_host_name]日間[-drman_password-drman_host_name]日間[-drman_host_name]日間[-drman_db1_group]-RMANパスワード[-drman [-count_n_][-duration _m_]][-weekly[-count_m_]][-duration_n_][-duration _ m_]][-duration _ comment _m_]][-snapname=パターンsnapname=パターン1_email_address_address_email][-durs1_email_address_address_email

+
このコマンドの他のオプションは、次のとおりです。

+
「[-force]``」

+
「[-quiet |-verbose ]」

+

NOTE: SnapManager では、 E メールアドレスが最大 1000 文字までサポートされます。

+
プロファイルを使用して（アーカイブログの個別バックアップを作成するために）データファイルとアーカイブログファイルのバックアップを作成し、データファイルのバックアップの作成に失敗した場合は、データバックアップとアーカイブログのバックアップではなく、処理名としてデータバックアップが送信されます。データファイルおよびアーカイブログファイルのバックアップ処理が成功すると、出力は次のようになります。

+
[listing]
----

Profile Name    : PROF_31
Operation Name 	: Data Backup and Archive Logs Backup
Database SID   	: TENDB1
Database Host 	 : repo1.rtp.org.com
Start Date 	    : Fri Sep 23 13:37:21 EDT 2011
End Date 	      : Fri Sep 23 13:45:24 EDT 2011
Status 	        : SUCCESS
Error messages 	:
----


'''
次の例は、新しいプロファイルの作成時に設定された E メール通知を表示します。

[listing]
----

smsap profile create -profile sales1 -profile-password sales1 -repository -dbname repo2 -host 10.72.197.133 -port 1521 -login -username oba5 -database -dbname DB1 -host 10.72.197.142 -sid DB1 -osaccount oracle
-osgroup dba -notification -success -email admin1@org.com -subject {profile}_{operation-name}_{db-sid}_{db-host}_{start-date}_{end-date}_{status}
----
'''