---
permalink: unix-administration/task-perform-backup-restore-and-clone-operations-using-prescript-and-post-scripts.html 
sidebar: sidebar 
keywords: script, initiate, initiating, backup, restore, clone, operation, snapmanager, display, task-enabling, create, wizard, restore, recover, parameter, post-script 
summary: 独自のスクリプトを使用して、バックアップ、リストア、またはクローニングの処理を開始できます。SnapManager では、バックアップ作成ウィザード、リストアウィザード、リカバリウィザード、またはクローン作成ウィザードのタスク有効化ページが表示されます。このページで、スクリプトを選択し、スクリプトに必要なパラメータの値を指定できます。 
---
= プリスクリプトとポストスクリプトを使用して、バックアップ、リストア、クローニングの処理を実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
独自のスクリプトを使用して、バックアップ、リストア、またはクローニングの処理を開始できます。SnapManager では、バックアップ作成ウィザード、リストアウィザード、リカバリウィザード、またはクローン作成ウィザードのタスク有効化ページが表示されます。このページで、スクリプトを選択し、スクリプトに必要なパラメータの値を指定できます。

* 必要なもの *

* プラグインスクリプトを、正しい SnapManager のインストール場所にインストールします。
* コマンドを使用して、プラグインが正しくインストールされていることを確認します。
* bash シェルを使用していることを確認します。


* このタスクについて *

コマンドラインインターフェイス（ CLI ）で、スクリプト名をリストし、パラメータを選択して値を設定します。

.手順
. bashシェルを使用していることを確認するには、コマンドプロンプトで次のコマンドを入力します。
+
*bash *`

+
または、プロンプトで「which -bash」コマンドを入力し、スクリプトの開始パラメータとしてコマンド出力を使用することもできます。

+
bash シェルは、エラーが表示されなければ正常に動作しています。

. バックアップ・オペレーションの場合は'-taskspec'オプションを入力し'バックアップ・オペレーションの前または後に発生する前処理または後処理アクティビティを実行するためのタスク仕様XMLファイルの絶対パスを指定します
+
`* SMSAP backup create -profile profile_profile_name_{[-full｛-online |-offline |-auto｝[-retain｛-hourly |[-daily |-weekly |-unlimited｝][-verify]|[-data [[-files_[_files_]|[-monthly |]-retain-daily. [-archivelogs [-label_label_][-comment_comment_][-prot|-proten][-backup-dest path1_[,[_path2_]][-exclude-dest_path1_path1_][,_path2_]][,-prunelogn {-unted-dest scn {-des|-dest-dre-date-months |-dest-dest days -unte-dest-drage_date-vol|-unted|-dest-de -date-dest-de -date-vol|-d]-unted|-dest-de -dest-de-dest-de-dest-dest -date-dest_オプションを含む][-de-dest_path1_path1_path1_path1_path|-dest_オプションを含む][-dest | yyyy-mm-de-specs|-date-dest-de-dest_オプションを含む][-dest | yyyy-mm-de | yyyy-mmd|-date-

+
バックアッププラグイン処理に失敗した場合は、プラグイン名と戻りコードのみが表示されます。プラグインスクリプトにログメッセージを含め、ユーザ定義のログファイルにメッセージをリダイレクトする必要があります。

. バックアップ・リストア操作の場合は'-taskspec'オプションを入力し'前処理またはリストア処理の前後に実行する後処理アクティビティを実行するためのタスク仕様XMLファイルの絶対パスを指定します
+
`* SMSAP backup restore -profile profile_name_{-label_<label>_|-id_<id>_ files>_|-tablespaces _<tablespaces >_|-complete |-controlfiles｝[-recover｛_alllogs_|__-nologs_|_until _<untify_spec]-restorespecle-until _test\task[cret_ spec]-untest\t_¥\ tempからの-unpreview [creator|temp_dump]サブテーブル\<files|-unpreview [creview]サブテーブル\ tempからのボリュームをリストアする[ジョブ\実行する[ジョブ<files>検証\実行します

+
リストアプラグインの処理に失敗した場合は、プラグイン名と戻りコードのみが表示されます。プラグインスクリプトにログメッセージを含め、ユーザ定義のログファイルにメッセージをリダイレクトする必要があります。

. クローン作成処理の場合、-taskspecオプションを使用してタスク仕様XMLファイルの絶対パスを指定することで、前処理や後処理を実行してクローン処理の前後に処理を実行できます。
+
`* SMSAP clone create -profile _profile_name_{-backup-label_backup_name_|-backup-id_<backup-id>_<backup-id>_|-current｝-newsid_new_sid_clonespecfile_[-reserve_<yes, inherite_<yes, inherite_host_name>][-dask_comment]<cluster_comment><2></2>-spec<cluster_comment>からのコマンドを実行します

+
クローンプラグイン処理に失敗した場合は、プラグイン名と戻りコードのみが表示されます。プラグインスクリプトにログメッセージを含め、ユーザ定義のログファイルにメッセージをリダイレクトする必要があります。



'''


== タスク仕様 XML ファイルを使用したバックアップの作成例

[listing]
----
smsap backup create -profile SALES1 -full -online -taskspec sales1_taskspec.xml -force -verify
----
'''