---
permalink: unix-administration/task-create-database-backups.html 
sidebar: sidebar 
keywords: create, backup, entire, database, portion, tablespace, data, file, control, creating 
summary: 表領域、データ・ファイル、制御ファイルなど、データベース全体またはデータベースの一部のバックアップを作成できます。 
---
= データベースのバックアップを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
表領域、データ・ファイル、制御ファイルなど、データベース全体またはデータベースの一部のバックアップを作成できます。

* このタスクについて *

SnapManager は、NFS、Veritasなど、ホスト側の多くのストレージスタックにわたって、データベースにSnapshotコピー機能を提供します。


NOTE: Real Application Clusters （ RAC SnapManager ）構成の場合、プロファイル内のホスト側でバックアップが実行されます。

管理者は、 Oracle RMAN にバックアップを登録することもできます。これにより、 RMAN を使用したデータベースのリストアとリカバリが容易になり、ブロックなどのより細かい単位でデータベースをリストアおよびリカバリできます。

プロファイルを定義する際に、そのプロファイルのバックアップによって作成される Snapshot コピーの名前をカスタマイズできます。たとえば、のプレフィックス文字列を挿入できます

'*Hops*'

High Operationsバックアップを指す。

バックアップで作成される Snapshot コピーに一意の名前を定義するだけでなく、バックアップ自体に一意のラベルを作成することもできます。バックアップを作成するときは'バックアップ名を指定することをお勧めしますしたがって'-label'パラメータを使用してバックアップを容易に識別できますこの名前は、特定のプロファイルに作成されるすべてのバックアップに対して一意である必要があります。名前には、アルファベット、数字、アンダースコア（ _ ）、およびハイフン（ - ）を使用できます。1 文字目をハイフンにすることはできません。ラベルでは大文字と小文字が区別されます。オペレーティングシステムの環境変数、システムの日付、バックアップタイプなどの情報を追加できます。

ラベルを指定しない場合、SnapManager はデフォルトのラベル名を「_scope_mode_datestring_」という形式で作成します。スコープは完全または部分で、モードはオフライン、オンライン、または自動（コールドの場合はc、ホットの場合はh、自動の場合はa）です。

SnapManager 3.4 では、 SnapManager で作成されたデフォルトのバックアップ・ラベルを上書きすることにより、独自のバックアップ・ラベルを指定できます。override.default.backup.pattern`パラメータの値をtrueに設定し'`new.default.backup.pattern`パラメータで新しいバックアップ・ラベルを指定する必要がありますバックアップラベルのパターンには、データベース名、プロファイル名、スコープ、モード、ホスト名など、アンダースコアで区切る必要のあるキーワードを含めることができます。たとえば、「new.default.backup.pattern=_dbname_profile_hostname_scope_mode_.`」と入力します


NOTE: 生成されたラベルの末尾にタイムスタンプが自動的に追加されます。

コメントを入力するときは、スペースと特殊文字を使用できます。一方、ラベルを入力する場合は、スペースや特殊文字は使用しないでください。

バックアップごとに、 SnapManager は自動的に 32 文字の 16 進数ストリングの GUID を生成します。GUIDを確認するには'-verboseオプションを指定して'backup list'コマンドを実行する必要があります

データベースのフルバックアップは、オンラインまたはオフラインの間に作成できます。SnapManager がデータベースのバックアップをオンラインとオフラインのどちらであるかに関係なく処理できるようにするには'auto'オプションを使用する必要があります

バックアップの作成時に、プルーニングをイネーブルにし、サマリー通知がプロファイルでイネーブルになっている場合は、 2 つの個別の電子メールがトリガーされます。1 つの E メールはバックアップ処理用で、もう 1 つはプルーニング用です。これらの E メールに含まれるバックアップ名とバックアップ ID を比較することで、これらの E メールを関連付けることができます。

データベースがシャットダウン状態のときにコールドバックアップを作成できます。データベースがマウント状態の場合は、シャットダウン状態に変更し、オフラインバックアップ（コールドバックアップ）を実行します。

SnapManager （ 3.2 以降）では、アーカイブ・ログ・ファイルをデータ・ファイルとは別にバックアップできるため、アーカイブ・ログ・ファイルを効率的に管理できます。

アーカイブ・ログ・バックアップを個別に作成するには'新しいプロファイルを作成するか'または既存のプロファイルを更新して'別個の-archivedlog -bbackupsオプションを使用してアーカイブ・ログ・バックアップを分離する必要がありますプロファイルを使用すると、次の SnapManager 処理を実行できます。

* アーカイブログのバックアップを作成します。
* アーカイブログバックアップを削除する。
* アーカイブログバックアップをマウントします。
* アーカイブログのバックアップを解放します。


バックアップオプションは、プロファイルの設定によって異なります。

* 分離されていないプロファイルを使用してアーカイブ・ログ・バックアップを個別に作成すると、次の処理を実行できます。
+
** フルバックアップを作成します。
** パーシャル・バックアップを作成します。
** アーカイブログファイル用にバックアップするアーカイブログのデスティネーションを指定します。
** バックアップから除外するアーカイブログの送信先を指定します。
** アーカイブ・ログ・デスティネーションからアーカイブ・ログ・ファイルを削除する場合のプルーニング・オプションを指定します。


* 分離されたプロファイルを使用してアーカイブ・ログ・バックアップを作成すると、次のことが可能になります。
+
** データファイルのみのバックアップを作成
** アーカイブログのみのバックアップを作成する
** データファイルのみのバックアップを作成する場合は、アーカイブログのバックアップに加え、クローニング用のオンラインデータファイルのみのバックアップも含めます。
+
アーカイブ・ログ・バックアップとデータ・ファイルを SnapManager GUI から * Profile Create * ウィザードの * Profile Settings * ページに含めた場合は、次の手順を実行します。 また、 * バックアップの作成 * ウィザードで * アーカイブ・ログ * オプションを選択していない場合、 SnapManager は常に、すべてのオンライン・バックアップのデータ・ファイルとともにアーカイブ・ログ・バックアップを作成します。

+
このような場合、 SnapManager CLI から、 SnapManager 構成ファイルで指定された除外デスティネーションを除く、バックアップのすべてのアーカイブログデスティネーションを検討できます。ただし、これらのアーカイブログファイルの削除はできません。ただし'-archivelogsオプションを使用してアーカイブ・ログ・ファイルの保存先を指定し'アーカイブ・ログ・ファイルをSnapManager CLIから削除することもできます

+
-auto'オプションを使用してバックアップを作成し'--archivelogsオプションを指定すると'バックアップの現在のステータスに基づいてSnapManager はオンラインまたはオフラインのいずれかのバックアップを作成します

+
*** SnapManager では、データベースがオフラインのときにオフラインバックアップが作成されます。バックアップにアーカイブログファイルは含まれません。
*** SnapManager は、データベースがオンラインのときに、アーカイブ・ログ・ファイルを含むオンライン・バックアップを作成します。


** アーカイブログのみのバックアップの作成中：
+
*** アーカイブログのみのバックアップとともにバックアップするアーカイブログのデスティネーションを指定します
*** アーカイブログのみのバックアップから除外するアーカイブログのデスティネーションを指定します
*** アーカイブ・ログ・デスティネーションからアーカイブ・ログ・ファイルを削除する場合のプルーニング・オプションを指定します




* * シナリオはサポートされていません *
+
** アーカイブログのみのバックアップは、オフラインデータファイルのみのバックアップとともに作成することはできません。
** アーカイブログファイルがバックアップされていない場合は、アーカイブログファイルの削除はできません。
** アーカイブログファイルに対して Flash Recovery Area （ FRA ）が有効になっている場合は、アーカイブログファイルのプルーニングを実行できません。
+
Flash Recovery Areaでアーカイブ・ログの場所を指定する場合は'archive_log_destパラメータでアーカイブ・ログの場所も指定する必要があります





オンラインデータファイルバックアップのラベルをアーカイブログバックアップとともに指定すると、データファイルバックアップのラベルが適用され、アーカイブログバックアップのサフィックスには「（_logs）」が付加されます。このサフィックスを設定するには、SnapManager 構成ファイルのパラメータ「suffix.backup.label.with .logs」を変更します。

たとえば'suffix.backup.label.with .logs=arc`の値を指定すると'_logsのデフォルト値が'_carc'に変更されます

バックアップに含めるアーカイブログのデスティネーションを指定していない場合、 SnapManager には、データベースに設定されているすべてのアーカイブログのデスティネーションが含まれます。

いずれかのデスティネーションに欠落しているアーカイブログファイルがある場合、 SnapManager は、欠落しているアーカイブログファイルが他のアーカイブログデスティネーションにある場合でも、それらのアーカイブログファイルの前に作成されたアーカイブログファイルをすべてスキップします。

アーカイブログのバックアップを作成する際には、バックアップに含めるアーカイブログファイルのデスティネーションを指定する必要があります。また、設定パラメータで、アーカイブログファイルをバックアップ内の欠落ファイルよりも常に多く含めるように設定できます。


NOTE: デフォルトでは'この構成パラメータは'*true*'に設定されており'欠落しているファイル以外のすべてのアーカイブ・ログ・ファイルが含まれます独自のアーカイブ・ログ削除スクリプトを使用する場合、またはアーカイブ・ログ・デスティネーションからアーカイブ・ログ・ファイルを手動で削除する場合は、このパラメータを無効にして、 SnapManager でアーカイブ・ログ・ファイルをスキップし、バックアップをさらに続行できます。

SnapManager では、アーカイブログのバックアップに関して次の SnapManager 処理がサポートされません。

* アーカイブログのバックアップをクローニングする
* アーカイブログのバックアップをリストアする
* アーカイブログのバックアップを検証する


SnapManager では、フラッシュリカバリ領域のデスティネーションからアーカイブログファイルをバックアップすることもできます。

. 次のコマンドを入力します。
+
`* SMSAP backup create -profile profile_profile_name_{[-full｛-online |-offline |-auto｝[-retain｛-hourly |-daily |-weekly |-unlimited｝][-verify]|[-data [[-files_[_[_files_]|[-unlimited |]-monthly]-tablespaces |-retain-abel-daily. [-archivelogs [-label_label_][-comment_comment_][-snapvaultlabel_label_][-protect|-nopectnow][-backup-destpath1][,path2_scn ,path2_scn }-dest-dprune date_unted|-dest-drivers]-dest_prune de_unted|-dest-des|-drivers]-dest-des|-dest-druntile|-date|-dest-deまでの実行日数[-des|-dest_untum|-date][-des|-date][-dest～月数}～月～月～月～}]～{dest_untmpe|-untmpe|-untmpe|-untmpe|-untmpe|-untal|-untmpe|-untal|-untal|-until

+
[cols="1a,3a"]
|===
| 状況 | 作業 


 a| 
* _SnapManager_cDOT _Vault 保護ポリシー * を使用して、セカンダリストレージにバックアップを作成します
 a| 
「-snapvaultlabel」を指定します。

SnapMirror 関係を SnapVault に設定するときに、 SnapMirror ポリシーのルールで指定した SnapMirror ラベルを指定する必要があります。



 a| 
* オンラインとオフラインのどちらのデータベースのバックアップを作成するかを指定します。 SnapManager でオンラインとオフラインのどちらのデータベースを処理するかは指定しません *
 a| 
オフライン・データベースのバックアップを作成するには'-offline'を指定します

オンライン・データベースのバックアップを作成するには'-conline-'を指定します

これらのオプションを使用する場合は'-auto'オプションは使用できません



 a| 
* データベースがオンラインかオフラインかにかかわらず、 SnapManager がデータベースのバックアップを処理できるようにするかどうかを指定します。 *
 a| 
-auto'オプションを指定しますこのオプションを使用する場合は'--offline]オプションまたは--onlineオプションは使用できません



 a| 
* 特定のファイルのパーシャル・バックアップを実行するかどうかを指定します *
 a| 
「-data-files」オプションを指定し、カンマで区切って「_files_」をリストします。たとえば、F1、F2、およびF3のファイル名をオプションの後にリストします。

UNIXで部分的なデータファイルバックアップを作成する例

[listing]
----
smsap backup create -profile nosep -data -files /user/user.dbf -online
-label partial_datafile_backup -verbose
----


 a| 
* 特定の表領域のパーシャル・バックアップを実行するかどうかを指定します。 *
 a| 
--data-tablespacesオプションを指定して'_tablespaces _をカンマで区切って指定しますたとえば、オプションのあとにTS1、TS2、およびTS3を使用します。

SnapManager では、読み取り専用表領域のバックアップがサポートされます。バックアップの作成時に、 SnapManager は読み取り専用テーブルスペースを読み取り / 書き込みに変更します。バックアップの作成後、表領域は読み取り専用に変更されます。

例：パーシャル・テーブルスペース・バックアップを作成する

[listing]
----
smsap backup create -profile nosep -data -tablespaces tb2 -online -label partial_tablespace_bkup -verbose
----


 a| 
* 各バックアップに一意のラベルを作成するかどうかを full_hot_mybackup_label * という形式で指定します
 a| 
Linuxの場合、次の例を入力します。

[listing]
----
smsap backup create -profile targetdb1_prof1
-label full_hot_my_backup_label -online -full  -verbose
----


 a| 
* アーカイブ・ログ・ファイルのバックアップを ' データ・ファイルとは別に作成するかどうかを指定します *
 a| 
次のオプションと変数を指定します。

** -archivelogsアーカイブ・ログ・ファイルのバックアップを作成します
** --backup-destでは'バックアップするアーカイブ・ログ・ファイルの保存先を指定します
** --exclude-dest-除外するアーカイブ・ログ・デスティネーションを指定します
** -labelは'アーカイブ・ログ・ファイル・バックアップのラベルを指定します
** -protect：アーカイブ・ログのバックアップに対する保護を有効にします



NOTE: 「-backup-dest」オプションまたは「-exclude-dest」オプションのいずれかを指定する必要があります。

これらのオプションを両方ともバックアップとともに指定すると'無効なバックアップ・オプションが指定されたというエラー・メッセージが表示されますオプションの1つである-backup-destまたはexclude-dest.を指定します

アーカイブログファイルのバックアップを UNIX で別途作成する例

[listing]
----
smsap backup create -profile nosep -archivelogs -backup-dest /mnt/archive_dest_2/ -label archivelog_bkup -verbose
----


 a| 
* データ・ファイルとアーカイブ・ログ・ファイルのバックアップを一緒に作成するかどうかを指定します *
 a| 
次のオプションと変数を指定します。

** データ・ファイルを指定するための'-data'オプション
** アーカイブ・ログ・ファイルを指定するための-archivelogsオプションUNIX でのデータ・ファイルとアーカイブ・ログ・ファイルのバックアップ例
+
[listing]
----

smsap backup create -profile nosep -data -online -archivelogs -backup-dest  mnt/archive_dest_2 -label data_arch_backup
-verbose
----




 a| 
* バックアップ作成時にアーカイブ・ログ・ファイルのプルーニングを実行するかどうかを指定します *
 a| 
次のオプションと変数を指定します。

** --logprunsアーカイブ・ログの保存先からアーカイブ・ログ・ファイルを削除するように指定します
+
*** 「-all」は、アーカイブ・ログ・デスティネーションからすべてのアーカイブ・ログ・ファイルを削除するように指定します。
*** `-until scn _until -scn _`は、指定したSCNまでアーカイブ・ログ・ファイルを削除するように指定します。
*** `-until date_yyyy-mm-dd：HH：MM：ss_`は、指定した期間までアーカイブログファイルを削除するように指定します。
*** --beforeオプションは'指定された期間（日'月'週'時間）前にアーカイブ・ログ・ファイルを削除するように指定します
*** --prune-destprune __ dest1、[prune_dest2_]は、バックアップの作成時にアーカイブ・ログ・デスティネーションからアーカイブ・ログ・ファイルを削除するように指定します。





NOTE: アーカイブログファイルに対して Flash Recovery Area （ FRA ）が有効になっている場合は、アーカイブログファイルのプルーニングを実行できません。

UNIX でバックアップを作成する際に、すべてのアーカイブ・ログ・ファイルを削除する例を示します

[listing]
----
smsap backup create -profile nosep
 -archivelogs -label archive_prunebackup1 -backup-dest /mnt/arc_1,/mnt/arc_2  -prunelogs -all -prune-dest /mnt/arc_1,/mnt/arc_2 -verbose
----


 a| 
* バックアップに関するコメントを追加するかどうかを指定します。 *
 a| 
「-comment」に続けて概要 文字列を指定します。



 a| 
* 現在の状態にかかわらず、指定した状態にデータベースを強制的にバックアップするかどうかを指定します
 a| 
「-force」オプションを指定します。



 a| 
* バックアップの作成時に検証を実行するかどうかを指定します。 *
 a| 
-verifyオプションを指定します



 a| 
* データベース・バックアップ処理後にダンプ・ファイルを収集するかどうかを指定します。 *
 a| 
backup createコマンドの最後に'-dump'オプションを指定します

|===


'''


== 例

[listing]
----
smsap backup create -profile targetdb1_prof1 -full -online -force  -verify
----
'''