---
permalink: unix-administration/task-use-protection-manager-to-configure-a-secondary-backup-protection-policy.html 
sidebar: sidebar 
keywords: configure, configuring, backup, schedule, storage, administrator, protect, protection, manager, secondary, policy 
summary: バックアップスケジュールを設定したら、保護されたバックアップストレージポリシーをそのスケジュールに含めるようにストレージ管理者が設定します。 
---
= Protection Managerを使用して、セカンダリバックアップ保護ポリシーを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップスケジュールを設定したら、保護されたバックアップストレージポリシーをそのスケジュールに含めるようにストレージ管理者が設定します。

* 必要なもの *

保護ポリシーを設定する前に ' ストレージ管理者は次の情報について DBA パートナーに相談します

* セカンダリストレージの保持期間を指定します
* 必要なセカンダリストレージ保護のタイプ


* このタスクについて *

作成された保護ポリシーは'DBAパートナーによってSnapManager for SAPに表示され'保護するデータのデータベース・プロファイルに割り当てられます

. Protection Manager の NetApp Management Console に移動します。
. メニューバーから、 * Policies * > * Protection * > * Overview * をクリックします。
+
Protection Policies （保護ポリシー）ウィンドウの Overview （概要）タブが表示されます。

. [Add Policy*]をクリックして、* Add Protection Policy *ウィザードを開始します。
. ウィザードで次の手順を実行します。
+
.. わかりやすいポリシー名を指定します。
+
この例では、「 *TechCo Payroll Data: Backup* 」と概要と入力し、「 * 次へ * 」をクリックします。

.. ベースポリシーを選択します。
+
この例では、「バックアップ * 」を選択し、「 * 次へ * 」をクリックします。

.. [*プライマリデータ*]ノードポリシーのプロパティ・シートで、デフォルト設定を受け入れ、[*次へ*]をクリックします。
+

NOTE: この例では、 SnapManager で設定されたローカルバックアップスケジュールが適用されます。この方法で指定したローカルバックアップスケジュールはすべて無視されます。

.. [*プライマリ・データからバックアップ*]接続プロパティ・シートで、バックアップ・スケジュールを選択します。
+
この例では、バックアップスケジュールとして * 毎週午前 1 時と午後 7 時の * 給与計算土曜日を選択し、 * 次へ * をクリックします。

+
次の例では、選択したスケジュールに、前に設定した週単位と日単位の両方のスケジュールが含まれています。

.. *バックアップポリシー*プロパティ・シートで、バックアップ・ノードの名前、および日次、週次、または月次バックアップの保持時間を指定します。
+
この例では、日次バックアップ保持を 10 日、週次バックアップ保持を 52 週間に指定します。各プロパティシートを完成したら、 * 次へ * をクリックします。

+
すべてのプロパティシートが完了すると、保護ポリシーの追加ウィザードに、作成する保護ポリシーの概要シートが表示されます。



. [ 完了 ] をクリックして変更を保存します。


* 結果 *

Protection Manager に設定されている他のポリシーの中に '*TechCo Payroll Data: Backup * 保護ポリシーが表示されています

* 終了後 *

DBAパートナーは、SnapManager for SAPを使用して、保護対象のデータのデータベースプロファイルを作成する際にこのポリシーをリストし、割り当てられるようになりました。
