---
permalink: unix-administration/task-use-snapmanager-for-oraclesnapmanager-for-sapto-restore-a-local-backup-on-primary-storage.html 
sidebar: sidebar 
keywords: restore, local, backup, exist, primary, storage, entire, process, perform, snapmanager, sap 
summary: プライマリストレージにあるローカルバックアップをリストアすることができます。プロセス全体は、SnapManager for SAPを使用して実行します。 
---
= SnapManager for SAPを使用して、プライマリストレージにローカルバックアップをリストアします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プライマリストレージにあるローカルバックアップをリストアすることができます。プロセス全体は、SnapManager for SAPを使用して実行します。

* このタスクについて *

バックアップのリストアプロセスに関する情報をプレビューすることもできます。この操作を実行すると、バックアップのリストア対応に関する情報を確認できます。SnapManager はバックアップのデータを分析し、ボリュームベースのリストアまたはファイルベースのリストア方式を使用してリストアプロセスを完了できるかどうかを判断します。

リストアプレビューには次の情報が表示されます。

* 各ファイルのリストアに使用するリストアメカニズム（高速リストア、ストレージ側のファイルシステムのリストア、ストレージ側のファイルのリストア、またはホスト側のファイルコピーのリストア）
* 各ファイルのリストアに、より効率的なメカニズムが使用されなかった理由。


リストア計画のプレビューでは、 SnapManager は何もリストアしません。プレビューには、 20 ファイルまでの情報が表示されます。

データファイルのリストアをプレビューする際に、データベースがマウントされていない場合は、 SnapManager によってデータベースがマウントされます。データベースをマウントできない場合、処理は失敗し、 SnapManager はデータベースを元の状態に戻します。

.手順
. [*Repository]ツリーで、リストアするバックアップを右クリックし、[*Restore]を選択します。
. [ リストアとリカバリウィザード ] の [ ようこそ ] ページで、 [ 次へ ] をクリックします。
. [構成情報の復元*]ページで、[完全なデータファイル/テーブルスペースの復元と制御ファイル*]を選択します。
. [ 必要に応じてデータベースのシャットダウンを許可する ] をクリックします。 *
+
SnapManager は、必要に応じてデータベースの状態を変更します。たとえば、データベースがオフラインでオンラインにする必要がある場合、 SnapManager によってデータベースが強制的にオンラインに切り替えられます。

. [* Recovery Configuration Information*（リカバリ設定情報*）]ページで、[* All Logs]（すべてのログ）をクリックします。
+
SnapManager は、データベースを最後のトランザクションまでリストアおよびリカバリし、必要なすべてのログを適用します。

. ［* Restore Source Location Configuration *］ページで、プライマリのバックアップに関する情報を表示し、［* Next］をクリックします。
+
バックアップがプライマリストレージ上にのみ存在する場合、 SnapManager はプライマリストレージからバックアップをリストアします。

. [* Volume Restore Configuration Information*]ページで、[* Attempt volume restore]を選択して、ボリューム・リストア方式を試みます。
. [ ファイルベースの復元へのフォールバック * ] をクリックします。
+
これにより、ボリュームのリストア方式を使用できない場合でも、 SnapManager でファイルベースのリストア方式を使用できます。

. [* Preview] をクリックして、高速リストアの資格チェックと、必須およびオーバーライド可能なチェックに関する情報を表示します。
. [操作の実行*]ページで、入力した情報を確認し、[*Restore*]をクリックします。
. プロセスの詳細を表示するには、 [* 操作の詳細 * ] をクリックします。

