---
permalink: unix-administration/task-use-protection-manager-to-configure-secondary-backup-schedules.html 
sidebar: sidebar 
keywords: support, backup, database, secondary, storage, administrator, protection, manager, configure, schedule 
summary: ストレージ管理者は、セカンダリストレージへのデータベースのバックアップをサポートするために、 Protection Manager を使用してバックアップスケジュールを設定します。 
---
= Protection Managerを使用して、セカンダリバックアップスケジュールを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ管理者は、セカンダリストレージへのデータベースのバックアップをサポートするために、 Protection Manager を使用してバックアップスケジュールを設定します。

* 必要なもの *

セカンダリ・バックアップのスケジュールを設定する前に ' ストレージ管理者は次の情報について DBA パートナーに相談します

* データベース管理者がセカンダリ・バックアップの実行を希望するスケジュール
+
この場合、 1 日 1 回のバックアップが午後 7 時に実行されます週 1 回のバックアップは、土曜日の午前 1 時に実行されます



.手順
. Protection Manager の NetApp Management Console に移動します。
. メニューバーで、 * Policies * > * Protection * > * Schedules * の順にクリックします。
+
Protection Policies ウィンドウの Schedules タブが表示されます。

. スケジュールのリストから、毎日 8:00 PM ** を選択します。
. [* コピー（ Copy ） ] をクリックします
+
新しい日次スケジュール「 * Copy of Daily at 8 ： 00 PM * 」がリストに表示されます。すでに選択されています。

. [ 編集（ Edit ） ] をクリックします。
+
日次スケジュールの編集 ] プロパティ・シートが開き ' スケジュールタブが表示されます

. スケジュール名を *Payroll Daily at 7 PM* に変更し、概要を更新してから、 *Apply* をクリックします。
+
変更が保存されます。

. [ 毎日のイベント *] タブをクリックします。
+
スケジュールの現在の日次バックアップ時刻の午後 8 時が表示されます

. [ 追加（ Add ） ] をクリックし、新しい時間フィールドに「 * 7 ： 00 PM * 」と入力して、 [ * 適用（ Apply ） ] をクリックします。
+
スケジュールの現在の日次バックアップ時刻は、午後 7 時になります

. [OK] をクリックして変更を保存し、プロパティシートを終了します。
+
新しい日次スケジュール「 * 給与日の午後 7 時 * 」がスケジュールのリストに表示されます。

. スケジュールのリストから、毎週のスケジュール ** 日曜日の午後 8 時 + 毎日 ** を選択します。
. [* コピー（ Copy ） ] をクリックします
+
新しい週次スケジュール * 日曜日の午後 8 時と毎日の午後 8 時のコピー * がリストに表示されます。すでに選択されています。

. [ 編集（ Edit ） ] をクリックします。
+
週次スケジュールを編集 (Edit Weekly Schedule) プロパティ・シートが開き ' スケジュールタブが表示されます

. スケジュール名を「 * 給与土曜日の午前 1 時と毎日の午後 7 時 * 」に変更して、概要を更新します。
. ［ * 日次スケジュール * ］ ドロップダウンリストから、作成した日次スケジュールを選択します。 ［ * 給与日（毎日） ］ は午後 7 時 * です。
+
［ * 給与明細日次（ 7 PM ） ］ を選択すると、このスケジュールでは、 ［ * 給与土曜日（ 1 AM ） ］ と ［ 毎日（ 7 PM ） ］ のスケジュールがポリシーに適用されるときに、日次（ Daily ）オペレーションが実行されるタイミングを定義できます。

. [OK] をクリックして変更を保存し、プロパティシートを終了します。
+
新しい週次スケジュール、 * 週次土曜日の午前 1 時 + 毎日午後 7 時 * がスケジュールのリストに表示されます。


