---
permalink: unix-administration/task-free-backups.html 
sidebar: sidebar 
keywords: free, backup, delete, snapshot, copies, copy, deleting, metadata, function, smsap, command 
summary: バックアップを解放して、バックアップのメタデータを削除することなく Snapshot コピーを削除できます。この機能により、バックアップが占有するスペースが解放されます。SMSAPのbackup freeコマンドを使用してバックアップを解放できます。 
---
= バックアップを解放します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップを解放して、バックアップのメタデータを削除することなく Snapshot コピーを削除できます。この機能により、バックアップが占有するスペースが解放されます。SMSAPのbackup freeコマンドを使用してバックアップを解放できます。

* 必要なもの *

バックアップを解放できるようにするには、次の点を確認する必要があります。

* バックアップは成功しました
* バックアップはマウントされません
* バックアップにクローンがありません
* バックアップは、保持ポリシーを無制限に設定して保持することはできません
* バックアップはまだ解放されていません


* このタスクについて *

プロファイルで保護が有効になっていて、保護ポリシーにミラー関係を使用するプライマリノードからの接続が含まれている場合、バックアップが解放されると、プライマリノード上の Snapshot コピーは削除されます。これらの Snapshot コピーは、セカンダリストレージへの次回の転送時にミラーノードからも削除されます。

保護されたバックアップを解放すると、 SnapManager は、そのバックアップのローカル Snapshot コピーを削除するように Protection Manager に要求します。保護されているバックアップの空き処理が成功すると、 Protection Manager によって Snapshot コピーが非同期的に削除されます。

[cols="2a,1a,3a,3a,4a"]
|===
| 保護状態 | ローカルステータス | プライマリストレージに対する処理 | セカンダリストレージに対する処理 | 説明 


 a| 
要求されていない（保護対象）
 a| 
が存在します
 a| 
バックアップを解放します
 a| 
対処は不要です。
 a| 
SnapManager がローカルバックアップを解放します。



 a| 
解放済み
 a| 
対処は不要です。
 a| 
対処は不要です。
 a| 
ローカルバックアップはすでに解放されています。



 a| 
保護されていない
 a| 
が存在します
 a| 
バックアップを解放します
 a| 
対処は不要です。
 a| 
セカンダリストレージにコピーが存在しない場合でも、 SnapManager はローカルバックアップを解放します。



 a| 
解放済み
 a| 
対処は不要です。
 a| 
対処は不要です。
 a| 
ローカルバックアップはすでに解放されています。



 a| 
保護
 a| 
が存在します
 a| 
バックアップを解放します
 a| 
対処は不要です。セカンダリのバックアップはそのまま残ります
 a| 
SnapManager がローカルバックアップを解放します。コピーはセカンダリストレージに残ります。



 a| 
解放済み
 a| 
対処は不要です。
 a| 
対処は不要です。
 a| 
ローカルバックアップはすでに解放されています。

|===
オプションのパラメータとして -dump オプションを指定すると、バックアップの解放処理の成功後または失敗後にダンプファイルを収集できます。

.ステップ
. 次のコマンドを入力します。
+
'*SMSAP backup free-profile_profile_name_{-label_[data|-archivelogs]|-id_id_|-all｝-force [-dump][-quiet][-force]*`


