---
permalink: unix-administration/task-consolidate-archive-log-backups.html 
sidebar: sidebar 
keywords: snapmanager, consolidate, archivelog-only, backup, consolidation, consolidating, archive, log 
summary: SnapManager は、重複するアーカイブログのみのバックアップを解放することにより、バックアップを作成するたびにアーカイブログのみのバックアップを統合します。デフォルトでは、統合は有効になっています。 
---
= アーカイブログバックアップを統合する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager は、重複するアーカイブログのみのバックアップを解放することにより、バックアップを作成するたびにアーカイブログのみのバックアップを統合します。デフォルトでは、統合は有効になっています。

* このタスクについて *

SnapManager は、他のバックアップにアーカイブログファイルが含まれているアーカイブログのみのバックアップを識別し、アーカイブログのみのバックアップを一意のアーカイブログファイルを使用して最小限の数だけ保持できるようにします。

アーカイブログのみのバックアップが統合によって解放された場合、アーカイブログの保持期間に基づいてこれらのバックアップが削除されます。

アーカイブ・ログの統合中にデータベースが shutdown または nomount 状態になると、 SnapManager はデータベースをマウント状態に変更します。

アーカイブ・ログ・ファイルのバックアップまたは削除に失敗した場合、統合は実行されません。アーカイブログのみのバックアップの統合は、バックアップが正常に完了し、プルーニング処理が成功した後にのみ実行されます。

.手順
. アーカイブログのみのバックアップの統合を有効にするには、構成パラメータ「Consolidation」を変更し、SnapManager 構成ファイル（SMSAP_CONFIG）で値を「true」に設定します。
+
パラメータを設定すると、アーカイブログのみのバックアップが統合されます。

+
新しく作成されたアーカイブログのみのバックアップに、以前のアーカイブログのみのバックアップのいずれかに同じアーカイブログファイルが含まれている場合、以前のアーカイブログのみのバックアップは解放されます。

+

NOTE: SnapManager では、作成されたアーカイブログバックアップとデータファイルのバックアップは統合されません。SnapManager はアーカイブログのみのバックアップを統合します。

+

NOTE: SnapManager は、ユーザがアーカイブログデスティネーションからアーカイブログファイルを手動で削除した場合や、アーカイブログファイルが破損してバックアップが含まれている可能性がある場合でも、アーカイブログバックアップを統合します。

. アーカイブ・ログ・バックアップの統合を無効にするには'構成パラメータのConsolidationを変更し' SnapManager 構成ファイル（SMSAP_CONFIG）で値をfalseに設定します

