---
permalink: unix-administration/task-create-clone-specifications.html 
sidebar: sidebar 
keywords: snapmanager, sap, clone, specification, xml, file, mapping, option, parameter, operation, information, diagnostic, creating, create 
summary: SnapManager for SAPでは、クローン仕様XMLファイルを使用します。このファイルには、クローン処理で使用するマッピング、オプション、およびパラメータが含まれています。SnapManager は、この情報を使用して、クローニングするファイルの配置場所、および診断情報、制御ファイル、パラメータなどの処理方法を決定します。 
---
= クローン仕様の作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager for SAPでは、クローン仕様XMLファイルを使用します。このファイルには、クローン処理で使用するマッピング、オプション、およびパラメータが含まれています。SnapManager は、この情報を使用して、クローニングするファイルの配置場所、および診断情報、制御ファイル、パラメータなどの処理方法を決定します。

* このタスクについて *

クローン仕様ファイルは、 SnapManager のグラフィカルユーザインターフェイス（ GUI ）、コマンドラインインターフェイス（ CLI ）、またはテキストエディタを使用して作成できます。

テキスト・エディタを使用してクローン仕様ファイルを作成する場合は、そのファイルを「.xml」ファイルとして保存する必要があります。この XML ファイルは、他のクローニング処理に使用できます。

クローン仕様テンプレートを作成し、カスタマイズすることもできます。SMSAP clone templateコマンドを使用するか、GUIでCloneウィザードを使用します。

SnapManager for SAPでは、生成されるクローン仕様テンプレートにバージョン文字列が追加されます。SnapManager for SAPは、バージョン文字列がないクローン仕様ファイルの最新バージョンを前提としています。

リモートクローニングを実行する場合は、クローン仕様ファイル内のデータファイル、 REDO ログファイル、および制御ファイルのデフォルトの場所を変更しないでください。デフォルトの場所を変更した場合、 SnapManager は、 Snapshot 機能をサポートしていないデータベース上でクローンの作成に失敗するか、クローンを作成しません。そのため、プロファイルの自動作成は失敗します。


NOTE: マウントポイントと ASM ディスクグループの情報は GUI から編集できますが、変更できるのはファイル名のみで、ファイルの場所は変更できません。

同じパラメータと値の組み合わせを使用して、タスクを複数回実行できます。

SAPでは、データベース設定に特定のOracle設定を使用します。これらの設定は、「$ORACLE_HOME/dbs」にある「init<SID>.ora」にあります。これらはクローン仕様に含める必要があります。

.手順
. テキストファイルを開き、次の例に示すようにテキストを入力します。
+
* 例 *

+
[listing]
----
<clone-specification xmlns="http://www.example.com>
     <storage-specification/>
     <database-specification/>
 </clone-specification>
----
. ストレージ仕様コンポーネントで、データファイルのマウントポイントを入力します。
+
ストレージ仕様には、データ・ファイルのマウント・ポイントや raw デバイスなど、クローン用に作成された新しいストレージの場所が表示されます。これらの項目は、ソースからデスティネーションにマッピングする必要があります。

+
次に、NFS接続ストレージ上の単一のNFSマウントポイントの例を示します。

+
* 例 *

+
[listing]
----
<mountpoint>
      <source>/oracle/<SOURCE SID>_sapdata</source>
      <destination>/oracle/<TARGET SID>_sapdata</destination>
</mountpoint>
----
. *オプション：*ソース上にrawデバイスがある場合、ソース上のrawデバイスのパスを指定してから、を指定する必要があります
+
`* destination auto-generate="true"*`

+
をクリックします。

+
以前のバージョンのSnapManager for SAPのクローン・マッピング・ファイルとは異なり、デスティネーション上のrawデバイスの場所は指定できません。クローニングされたrawデバイスには、SnapManager for SAPによって次に使用可能なデバイス名が選択されます。

+
* 例 *

+
次に、クローン仕様で使用する raw デバイスの構文を表示する例を示します。

+
[listing]
----
<raw-device>
     <source>/dev/raw/raw1</source>
     <destination auto-generate="true"/>
</raw-device>
----
. データベース仕様コンポーネントで、制御ファイルの情報を、クローン用に作成する制御ファイルのリストとして指定します。
+
データベース仕様では、制御ファイル、 REDO ログ、アーカイブ・ログ、 Oracle パラメータなど、クローンのデータベース・オプションを指定しています。

+
* 例 *

+
次に、クローン仕様で使用する制御ファイルの構文の例を示します。

+
[listing]
----
<controlfiles>
     <file>/oracle/<TARGET SID>/origlogA/cntrl/cntrl<TARGET SID>.dbf</file>
     <file>/oracle/<TARGET SID>/origlogB/cntrl/cntrl<TARGET SID>.dbf</file>
     <file>/oracle/<TARGET SID>/sapdata1/cntrl/cntrl<TARGET SID>.dbf</file>
</controlfiles>
----
. クローンの REDO ログ構造を指定します。
+
* 例 *

+
次に、クローニングの REDO ログディレクトリの構造を表示する例を示します。

+
[listing]
----
<redologs>
     <redogroup>
        <file>/oracle/<TARGET SID>/origlogA/log_g11m1.dbf</file>
        <file>/oracle/<TARGET SID>/mirrlogA/log_g11m2.dbf</file>
        <number>1</number>
        <size unit="M">100</size>
     </redogroup>
     <redogroup>
        <file>/oracle/<TARGET SID>/origlogB/log_g12m1.dbf</file>
        <file>/oracle/<TARGET SID>/mirrlogB/log_g12m2.dbf</file>
        <number>2</number>
        <size unit="M">100</size>
     </redogroup>
     <redogroup>
        <file>/oracle/<TARGET SID>/origlogA/log_g13m1.dbf</file>
        <file>/oracle/<TARGET SID>/mirrlogA/log_g13m2.dbf</file>
        <number>3</number>
        <size unit="M">100</size>
     </redogroup>
     <redogroup>
        <file>/oracle/<TARGET SID>/origlogB/log_g14m1.dbf</file>
        <file>/oracle/<TARGET SID>/mirrlogB/log_g14m2.dbf</file>
        <number>4</number>
        <size unit="M">100</size>
     </redogroup>
</redologs>
----
. クローニングしたデータベースで、別の値に設定する Oracle パラメータを指定します。Oracle 10 を使用している場合は、次のパラメータを指定する必要があります。
+
** バックグラウンド・ダンプ
** コアダンプ
** ユーザダンプ
** *オプション：*ログをアーカイブします
+

NOTE: パラメータ値が正しく設定されていないとクローニング処理が停止し、エラーメッセージが表示されます。



+
アーカイブ・ログの保存場所を指定しない場合、SnapManager はNOARCHIVELOGモードでクローンを作成します。SnapManager は'このパラメータ情報をクローンのinit.oraファイルにコピーします



* 例 *

次に、クローン仕様で使用するパラメータ構文を表示する例を示します。+

[listing]
----
<parameters>
     <parameter>
          <name>log_archive_dest</name>
          <value>LOCATION=>/oracle/<TARGET SID>/oraarch</value>
     </parameter>
     <parameter>
          <name>background_dump_dest</name>
          <value>/oracle/<TARGET SID>/saptrace/background</value>
     </parameter>
     <parameter>
          <name>core_dump_dest</name>
          <value>/oracle/<TARGET SID>/saptrace/background</value>
     </parameter>
     <parameter>
     <name>user_dump_dest</name>
     <value>/oracle/<TARGET SID>/saptrace/usertrace</value>
     </parameter>
</parameters>
----
* 例 *

デフォルト値を使用するには'パラメータ要素内のデフォルト要素を使用します次の例では'os_authentication_prefix'パラメータにデフォルト値が指定されていますこれは'デフォルトの要素が指定されているためです

[listing]
----
<parameters>
     <parameter>
          <name>os_authent_prefix</name>
          <default></default>
     </parameter>
</parameters>
----
* 例 *

空のエレメントを使用して、パラメーターの値として空のストリングを指定できます。次の例では'os_authentication_prefix'は空の文字列に設定されます

[listing]
----
<parameters>
     <parameter>
          <name>os_authent_prefix</name>
          <value></value>
     </parameter>
</parameters>
----

NOTE: ソース・データベースのinit.oraファイルの値は'エレメントを指定せずにパラメータに使用できます

* 例 *

パラメータに複数の値が指定されている場合は、パラメータ値をカンマで区切って指定できます。たとえば'データ・ファイルをある場所から別の場所に移動する場合は'db_file_name _convertパラメータを使用し'次の例に示すように'データ・ファイルのパスをカンマで区切って指定できます

* 例 *

ログファイルを別の場所に移動する場合は'log_file_name _convertパラメータを使用して'ログファイルのパスをコンマで区切って指定できます例を参照してください

. *オプション：*オンラインのときにクローンに対して実行する任意のSQLステートメントを指定します。
+
SQLステートメントを使用すると、クローニングされたデータベース内で「temp files」を再作成するなどのタスクを実行できます。

+

NOTE: SQL ステートメントの最後にセミコロンが含まれていないことを確認してください。

+
次に、クローニング処理の一環として実行する SQL ステートメントの例を示します。

+
[listing]
----
<sql-statements>
   <sql-statement>
     ALTER TABLESPACE TEMP ADD
     TEMPFILE '/mnt/path/clonename/temp_user01.dbf'
     SIZE 41943040 REUSE AUTOEXTEND ON NEXT 655360
     MAXSIZE 32767M
   </sql-statement>
</sql-statements>
----
+
*クローン仕様の例*

+
次に、ストレージおよびデータベース仕様の両方のコンポーネントを含む、クローン仕様の構造を表示する例を示します。

+
[listing]
----
<clone-specification xmlns="http://www.example.com>

   <storage-specification>
     <storage-mapping>
        <mountpoint>
           <source>/oracle/<SOURCE SID>_sapdata</source>
           <destination>/oracle/<TARGET SID>_sapdata</destination>
        </mountpoint>
        <raw-device>
          <source>/dev/raw/raw1</source>
          <destination auto-generate="true"/>
        </raw-device>
        <raw-device>
          <source>/dev/raw/raw2</source>
          <destination auto-generate="true"/>
        </raw-device>
     </storage-mapping>
   </storage-specification>

   <database-specification>
     <controlfiles>
        <file>/oracle/<TARGET SID>/origlogA/cntrl/cntrl<TARGET SID>.dbf</file>
        <file>/oracle/<TARGET SID>/origlogB/cntrl/cntrl<TARGET SID>.dbf</file>
        <file>/oracle/<TARGET SID>/sapdata1/cntrl/cntrl<TARGET SID>.dbf</file>
       </controlfiles>

       <redologs>
        <redogroup>
          <file>/oracle/<TARGET SID>/origlogA/log_g11m1.dbf</file>
          <file>/oracle/<TARGET SID>/mirrlogA/log_g11m2.dbf</file>
          <number>1</number>
          <size unit="M">100</size>
        </redogroup>
        <redogroup>
          <file>/oracle/<TARGET SID>/origlogB/log_g12m1.dbf</file>
          <file>/oracle/<TARGET SID>/mirrlogB/log_g12m2.dbf</file>
          <number>2</number>
          <size unit="M">100</size>
        </redogroup>
        <redogroup>
          <file>/oracle/<TARGET SID>/origlogA/log_g13m1.dbf</file>
          <file>/oracle/<TARGET SID>/mirrlogA/log_g13m2.dbf</file>
          <number>3</number>
          <size unit="M">100</size>
        </redogroup>
        <redogroup>
          <file>/oracle/<TARGET SID>/origlogB/log_g14m1.dbf</file>
          <file>/oracle/<TARGET SID>/mirrlogB/log_g14m2.dbf</file>
          <number>4</number>
          <size unit="M">100</size>
       </redogroup>
       </redologs>

    <parameters>
      <parameter>
          <name>log_archive_dest</name>
          <value>LOCATION=>/oracle/<TARGET SID>/oraarch</value>
     </parameter>
     <parameter>
          <name>background_dump_dest</name>
          <value>/oracle/<TARGET SID>/saptrace/background</value>
     </parameter>
     <parameter>
          <name>core_dump_dest</name>
          <value>/oracle/<TARGET SID>/saptrace/background</value>
     </parameter>
     <parameter>
     <name>user_dump_dest</name>
     <value>/oracle/<TARGET SID>/saptrace/usertrace</value>
     </parameter>

    </parameters>
   </database-specification>
</clone-specification>
----
+
'''

