---
settings:
  name: SnapManager for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: SnapManager for SAPのドキュメント
    url: "/index.html"
  - title: リリースノート
    url: "/reference-releasenotes.html"
  - section: unix-installation-cmode
  - section: unix-installation-7mode
  - section: unix-administration
  - section: windows
  - title: 法的通知
    url: "/legal-notices.html"
