---
permalink: unix-installation-cmode/concept-prerequisites-for-performing-rolling-upgrade.html 
sidebar: sidebar 
keywords: perform, roll, upgrade, ensure, environment, certain, requirement, prerequisite 
summary: ローリングアップグレードを実行する前に、環境が一定の要件を満たしていることを確認する必要があります。 
---
= ローリングアップグレードを実行するための前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローリングアップグレードを実行する前に、環境が一定の要件を満たしていることを確認する必要があります。

* SnapManager 3.1 より前のバージョンを使用していて、 SnapManager 3.3 以降へのローリングアップグレードを実行する場合は、まず 3.2 にアップグレードしてから、最新バージョンにアップグレードする必要があります。
+
SnapManager 3.2 から SnapManager 3.3 以降に直接アップグレードできます。

* 外部データ保護またはデータ保持を実行するために使用する外部スクリプトをバックアップしておく必要があります。
* アップグレード先の SnapManager バージョンがインストールされている必要があります。
+

NOTE: SnapManager 3.1 より前のバージョンから SnapManager 3.3 以降にアップグレードする場合は、まず SnapManager 3.2 をインストールし、ローリングアップグレードを実行する必要があります。3.2 にアップグレードしたら、 SnapManager 3.3 以降をインストールし、 SnapManager 3.3 以降への別のローリングアップグレードを実行できます。

* アップグレード先の SnapManager バージョンでサポートされる SnapDrive for UNIX バージョンをインストールする必要があります。
+
SnapDrive のインストールの詳細については、 SnapDrive のマニュアルを参照してください。

* リポジトリデータベースをバックアップしておく必要があります。
* SnapManager リポジトリの使用率が最小になるようにしてください。
* アップグレード対象のホストがリポジトリを使用している場合は、同じリポジトリを使用している他のホストで SnapManager 処理を実行しないでください。
+
スケジュールされた処理または他のホストで実行されている処理は、ローリングアップグレードが終了するまで待機します。

+

NOTE: リポジトリの負荷が最も低いとき、たとえば週末のリポジトリや処理のスケジュールが設定されていないときは、ローリングアップグレードを実行することを推奨します。

* 同じリポジトリデータベースを参照するプロファイルは、 SnapManager サーバホスト内で別の名前を使用して作成する必要があります。
+
同じ名前のプロファイルを使用すると、そのリポジトリ・データベースに関連するローリング・アップグレードが失敗します。

* アップグレード対象のホストで SnapManager 処理を実行しないでください。



NOTE: ローリングアップグレードは、アップグレードされるホストのバックアップ数が増えるにつれて長く実行されます。アップグレードの所要時間は、特定のホストに関連付けられたプロファイルとバックアップの数によって異なります。

http://mysupport.netapp.com/["ネットアップサポートサイトのドキュメント： mysupport.netapp.com"^]
