---
permalink: unix-installation-cmode/reference-trademark.html 
sidebar: sidebar 
keywords: trademark, information 
summary: 商標に関する情報 
---
= 商標に関する情報
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Active IQ、 AltaVault、Arch Design、ASUP、 AutoSupport、Campaign Express、Clustered Data ONTAP、Customer Fitness、 Data ONTAP、DataMotion、Element、Fitness、 Flash Accel、Flash Cache、Flash Pool、 FlexCache、 FlexClone、 FlexPod、FlexScale、FlexShare、 FlexVol、FPolicy、Fueled by SolidFire、GetSuccessful、Helix Design、LockVault、Manage ONTAP、 MetroCluster、 MultiStore、 NetApp、 NetApp Insight、 OnCommand、 ONTAP、ONTAPI、 RAID DP、 RAID-TEC、 SANscreen、 SANshare、 SANtricity、 SecureShare、Simplicity、Simulate ONTAP、Snap Creator、 SnapCenter、 SnapCopy、 SnapDrive、 SnapIntegrator、 SnapLock、 SnapManager、 SnapMirror、 SnapMover、 SnapProtect、 SnapRestore、Snapshot、 SnapValidator、 SnapVault、 SolidFire、 SolidFire Helix、 StorageGRID、 SyncMirror、 Tech OnTap、Unbound Cloud、 WAFLおよびその他の名前は、米国およびその他の国におけるNetApp, Inc. の商標または登録商標です。その他のすべてのブランドまたは製品は、それぞれの所有者の商標または登録商標であり、そのように扱われる必要があります。NetAppの商標の最新のリストは、以下でご覧いただけます。

http://www.netapp.com/us/legal/netapptmlist.aspx[]
