---
permalink: unix-installation-cmode/task-smsap-isg-create-a-profile-for-your-database.html 
sidebar: sidebar 
keywords: create, profile, database, perform, operation, contain, information, reference, multiple 
summary: データベースに対して処理を実行するには、そのデータベースのプロファイルを作成する必要があります。プロファイルにはデータベースに関する情報が格納されており、参照できるデータベースは 1 つだけですが、データベースは複数のプロファイルから参照できます。1 つのプロファイルを使用して作成されたバックアップは、両方のプロファイルが同じデータベースに関連付けられていても、別のプロファイルからはアクセスできません。 
---
= データベースのプロファイルを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データベースに対して処理を実行するには、そのデータベースのプロファイルを作成する必要があります。プロファイルにはデータベースに関する情報が格納されており、参照できるデータベースは 1 つだけですが、データベースは複数のプロファイルから参照できます。1 つのプロファイルを使用して作成されたバックアップは、両方のプロファイルが同じデータベースに関連付けられていても、別のプロファイルからはアクセスできません。



== 必要なもの

ターゲット・データベースの詳細が/etc/oratabファイルに含まれていることを確認する必要があります。



== このタスクについて

以下の手順では、 SnapManager UI を使用してデータベースのプロファイルを作成する方法を示します。必要に応じて、 CLI を使用することもできます。

CLIを使用してプロファイルを作成する方法については、SnapManager for SAPアドミニストレーションガイドUNIX_を参照してください。

.手順
. リポジトリツリーで ' リポジトリまたはホストを右クリックし ' プロファイルの作成 * を選択します
. [*プロファイル設定情報*（Profile Configuration Information *）]ページで、プロファイルのカスタム名とパスワードを入力します。
. [*Database Configuration Information*]ページで、次の情報を入力します。
+
|===
| フィールド | 手順 


 a| 
* データベース名 *
 a| 
バックアップするデータベースの名前を入力します。



 a| 
* データベース SID *
 a| 
データベースの Secure ID （ SID ；セキュア ID ）を入力します。データベース名とデータベース SID は同じにすることができます。



 a| 
* ホスト *
 a| 
ターゲット・データベースが置かれているホストの IP アドレスを入力します。ホスト名を Domain Name System （ DNS ；ドメインネームシステム）で指定した場合は、ホスト名も指定できます。



 a| 
* ホストアカウント *
 a| 
ターゲットデータベースの Oracle ユーザ名を入力します。ユーザのデフォルト値は oracle です。



 a| 
* ホストグループ *
 a| 
Oracle ユーザグループの名前を入力します。デフォルト値は、 dba です。

|===
. [データベース接続情報*]ページで、次のいずれかを選択します。
+
|===
| 選択する内容 | 状況 


 a| 
* O/S 認証 * を使用します
 a| 
データベースにアクセスするユーザを認証するには、オペレーティングシステムが管理しているクレデンシャルを使用します。



 a| 
* データベース認証を使用 *
 a| 
Oracle がパスワードファイル認証を使用して管理ユーザを認証できるようにします。適切なデータベース接続情報を入力します。

** [*SYSDBA 特権ユーザー名 *] フィールドに、管理者権限を持つデータベース管理者の名前を入力します。
** ［ * パスワード * ］ フィールドに、データベース管理者のパスワードを入力します。
** [* ポート *] フィールドに、データベースが存在するホストへの接続に使用するポート番号を入力します。
+
デフォルト値は1527です。





 a| 
* ASM インスタンス認証を使用 *
 a| 
Automatic Storage Management （ ASM ）データベースインスタンスによる管理ユーザの認証を許可します。適切な ASM インスタンス認証情報を入力します。

** [*SYSDBA / SYSASM Privileged User Name*] フィールドに、管理者権限を持つ ASM インスタンス管理者のユーザ名を入力します。
** [* パスワード *] フィールドに、管理者のパスワードを入力します。


|===
+
[NOTE]
====
ASM認証モードは、データベースホストにASMインスタンスがある場合にのみ選択できます。

====
. [RMAN構成情報*]ページで、次のいずれかを選択します。
+
|===
| 選択する内容 | 状況 


 a| 
*** RMAN を使用しないでください ***
 a| 
バックアップ処理とリストア処理の管理に RMAN を使用しない。



 a| 
*** 制御ファイルを使用して RMAN を使用する ***
 a| 
制御ファイルを使用して RMAN リポジトリを管理している。



 a| 
*** リカバリ・カタログを使用して RMAN を使用 ***
 a| 
リカバリカタログデータベースを使用して RMAN リポジトリを管理している。透過ネットワーク印刷材（ TNS ）接続を管理するデータベースのリカバリカタログデータベース、パスワード、および Oracle ネットサービス名にアクセスできるユーザー名を入力します。

|===
. [* Snapshot Naming Information]ページで、Snapshotコピーの命名形式を指定する変数を選択します。
+
smid 変数を命名形式に含める必要があります。_smid_変数 は、一意のSnapshot識別子を作成します。

. [* Policy Settings]ページで、次の手順を実行します。
+
.. 各保持クラスの保持数と保持期間を入力します。
.. [* 保護ポリシー *] ドロップダウンリストから、保護ポリシーを選択します。
+
SnapMirror 関係と SnapVault 関係のどちらが確立されているかに応じて、 _SnapManager_cDOT _ ミラー _ または _SnapManager_cDOT _ ボールト _ ポリシーを選択する必要があります。

.. アーカイブ・ログを個別にバックアップする場合は '[* バックアップ・アーカイブ・ログを個別にバックアップする *] チェックボックスをオンにし ' 保存期間を指定して ' 保護ポリシーを選択します
+
データファイルに関連付けられているポリシーとは異なるポリシーを選択できます。たとえば、データファイルに _SnapManager_cDOT _ ミラー _ を選択している場合は、アーカイブログに _SnapManager_cDOT _ ボールト _ を選択できます。



. [通知設定の構成*]ページで、電子メール通知設定を指定します。
. [履歴構成情報*]ページで、SnapManager 操作の履歴を保持するオプションを1つ選択します。
. [プロファイル作成操作の実行*]ページで、情報を確認し、[作成*]をクリックします。
. 「 * 完了」をクリックしてウィザードを閉じます。
+
処理が失敗した場合は、 * Operation Details * をクリックして、処理が失敗した原因を確認します。



* 関連情報 *

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453["『SnapManager 3.4.1 for SAP Administration Guide for UNIX』を参照してください"^]
