---
permalink: unix-installation-cmode/task-smsap-isg-configure-the-snapmanager-repository.html 
sidebar: sidebar 
keywords: configure, snapmanager, repository, database, instance, metadata 
summary: リポジトリデータベースインスタンスに SnapManager リポジトリを設定する必要があります。リポジトリデータベースには、 SnapManager で管理されているデータベースのメタデータが格納されます。 
---
= SnapManager リポジトリを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リポジトリデータベースインスタンスに SnapManager リポジトリを設定する必要があります。リポジトリデータベースには、 SnapManager で管理されているデータベースのメタデータが格納されます。



== 必要なもの

* リポジトリデータベースのインスタンスを作成しておく必要があります。
* 必要な権限を持つリポジトリデータベースインスタンスの Oracle ユーザを作成しておく必要があります。
* リポジトリ・データベース・インスタンスの詳細をtnsnames.oraファイルに含める必要があります




== このタスクについて

SnapManager リポジトリの設定は、 SnapManager のユーザインターフェイス（ UI ）またはコマンドラインインターフェイス（ CLI ）で行うことができます。以下の手順では、 SnapManager UI を使用してリポジトリを作成する方法を示します。必要に応じて、 CLI を使用することもできます。

CLIを使用してリポジトリを作成する方法については、UNIXのSnapManager for SAPアドミニストレーションガイドを参照してください。

.手順
. SnapManager UI の左ペインで、 * リポジトリ * を右クリックします。
. [ 新しいリポジトリの作成 ] を選択し、 [ 次へ ] をクリックします。
. [*Repository Database Configuration Information*]ウィンドウで、次の情報を入力します。
+
|===
| フィールド | 手順 


 a| 
* ユーザー名 *
 a| 
リポジトリデータベースインスタンス用に作成したユーザの名前を入力します。



 a| 
* パスワード *
 a| 
パスワードを入力します。



 a| 
* ホスト *
 a| 
リポジトリデータベースインスタンスを作成するホストの IP アドレスを入力します。



 a| 
* ポート *
 a| 
リポジトリデータベースインスタンスへの接続に使用するポートを入力します。デフォルトのポートは 1521 です。



 a| 
* サービス名 *
 a| 
SnapManager がリポジトリデータベースインスタンスへの接続に使用する名前を入力します。「tnsnames.ora」ファイルに含まれている詳細に応じて、これは短いサービス名または完全修飾サービス名のいずれかになります。

|===
. [リポジトリ追加操作の実行]ウィンドウ*で、設定の概要を確認し、[*追加]をクリックします。
+
処理が失敗した場合は、 * Operation Details * タブをクリックして、処理が失敗した原因を確認します。エラーの詳細は'/var/log/smsap.'にあるオペレーション・ログにも記録されます

. [ 完了 ] をクリックします。
+
リポジトリは左側のペインの *Repositories* ツリーの下に一覧表示されますリポジトリが表示されない場合は '[*Repositories*] を右クリックし '[*Refresh*] をクリックします



* 関連情報 *

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453["『SnapManager 3.4.1 for SAP Administration Guide for UNIX』を参照してください"^]
