---
permalink: unix-installation-cmode/task-perform-rolling-upgrade-on-a-single-host-or-multiple-hosts.html 
sidebar: sidebar 
keywords: perform, roll, upgrade, single, multiple, snapmanager, server, host, command-line, interface, cli, manage 
summary: コマンドラインインターフェイス（ CLI ）を使用して、 1 つまたは複数の SnapManager サーバホストでローリングアップグレードを実行できます。アップグレードした SnapManager サーバホストは、新しいバージョンの SnapManager でのみ管理されます。 
---
= 単一のホストまたは複数のホストでローリングアップグレードを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドラインインターフェイス（ CLI ）を使用して、 1 つまたは複数の SnapManager サーバホストでローリングアップグレードを実行できます。アップグレードした SnapManager サーバホストは、新しいバージョンの SnapManager でのみ管理されます。



== 必要なもの

ローリングアップグレードを実行するための前提条件をすべて満たしていることを確認する必要があります。

.手順
. 単一ホストでローリングアップグレードを実行するには、次のコマンドを入力します。「* SMSAP repository rollingupgrade-repository -dbname_repo_repo_service_name _-host_-login -username repo_repo_repo_username _port_repo_repo_port_-upgradehost_with _target_database-force [-quiet | verbose]」*
+
* 例 *

+
次のコマンドでは、 hostA にマウントされたすべてのターゲットデータベース、および repo_host に格納されている repoA という名前のリポジトリデータベースの、ローリングアップグレードが実行されます。

+
[listing]
----

smsap repository rollingupgrade
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -upgradehost hostA
----
. 複数のホストでローリングアップグレードを実行するには、次のコマンドを入力します。*SMSAP repository rollingupgrade-repository -dbname_repo_repo_service_name -host_repo_host_-login -username repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_repo_port_--upgradehost_with _target_database1、_host_具体 的なデータベースを使用します。*quiet
+

NOTE: 複数のホストの場合は、ホスト名をカンマで区切って入力し、カンマと次のホスト名の間にスペースを入れないようにします。 Real Application Clusters （ RAC ）構成を使用している場合は、 RAC に関連付けられているすべてのホストを手動でアップグレードする必要があります。「-allhosts」を使用して、すべてのホストのローリングアップグレードを実行できます。

+
* 例 *

+
次のコマンドでは、 repo_host に格納された、 hostA および hostB にマウントされているすべてのターゲット・データベース、および repoA というリポジトリ・データベースのローリング・アップグレードが実行されます。

+
[listing]
----

smsap repository rollingupgrade
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -upgradehost hostA,hostB
----
. リポジトリデータベース上のすべてのホストでローリングアップグレードを実行するには、次のコマンドを入力します。
+
`* SMSAPリポジトリロールアップupgrade -repository -dbdbname_repo_service_name -host_repo_username -login-username repo_repo_repo_repo_username -port_repo_port_allhosts -force [-quiet |-verbose *`

+
リポジトリデータベースのアップグレードが完了したら、ターゲットデータベースに対してすべての SnapManager 処理を実行できます。

+
* 例 *

+
次のコマンドでは、 repo_host に格納された repoA という名前のリポジトリ・データベース上にあるすべてのターゲット・データベースのローリング・アップグレードが実行されます。

+
[listing]
----

smsap repository rollingupgrade
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
      -allhosts
----




== 完了後

* SnapManager サーバが自動的に起動した場合は、スケジュールを表示できるようにサーバを再起動する必要があります。
* 関連する 2 つのホストのいずれかをアップグレードする場合は、 1 つ目のホストをアップグレードしたあとに 2 つ目のホストをアップグレードする必要があります。
+
たとえば、ホスト A からホスト B へのクローンを作成した場合や、ホスト A からホスト B へのバックアップのマウントを行った場合は、ホスト A とホスト B が相互に関連付けられます。ホスト A をアップグレードするときに、ホスト A のアップグレード後すぐにホスト B をアップグレードするよう求める警告メッセージが表示されます

+

NOTE: ホスト A のローリングアップグレードでは、クローンが削除された場合、またはホスト B からバックアップがアンマウントされた場合でも、警告メッセージが表示されますこれは、リモートホストで実行される処理のメタデータがリポジトリに存在するためです。


