---
permalink: unix-installation-7mode/concept-smsap-isg-defining-a-backup-strategy.html 
sidebar: sidebar 
keywords: define, defining, backup, strategy, creating, create, ensure, service, level, agreement, sla 
summary: バックアップを作成する前にバックアップ戦略を定義しておくと、データベースを正常にリストアするためのバックアップを確実に作成できます。SnapManager は、サービスレベルアグリーメント（ SLA ）に合わせて、柔軟にきめ細かなバックアップのスケジュールを設定できます。 
---
= バックアップ戦略の定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップを作成する前にバックアップ戦略を定義しておくと、データベースを正常にリストアするためのバックアップを確実に作成できます。SnapManager は、サービスレベルアグリーメント（ SLA ）に合わせて、柔軟にきめ細かなバックアップのスケジュールを設定できます。


NOTE: SnapManager のベストプラクティスについては、 TR 3761 _ を参照してください。



== 必要な SnapManager バックアップのモード

SnapManager では、 2 つのバックアップモードがサポートされてい

[cols="1a,3a"]
|===
| バックアップモード | 説明 


 a| 
オンラインバックアップ
 a| 
データベースがオンライン状態のときに、データベースのバックアップを作成します。このバックアップモードは、ホットバックアップとも呼ばれます。



 a| 
オフラインバックアップ
 a| 
データベースが MOUNTED または SHUTDOWN 状態のときに、データベースのバックアップを作成します。このバックアップモードはコールドバックアップとも呼ばれます。

|===


== 必要な SnapManager バックアップのタイプ

SnapManager は、次の 3 種類のバックアップをサポートします。

[cols="1a,3a"]
|===
| バックアップタイプ | 説明 


 a| 
フルバックアップ
 a| 
データベース全体のバックアップを作成します。このバックアップには、すべてのデータファイル、制御ファイル、およびアーカイブログファイルが含まれます。



 a| 
パーシャル・バックアップ
 a| 
選択したデータファイル、制御ファイル、表領域、およびアーカイブ・ログ・ファイルのバックアップを作成します



 a| 
ログのみのバックアップをアーカイブする
 a| 
アーカイブログファイルのみのバックアップを作成します。プロファイルの作成中に、 * バックアップアーカイブログを個別に * 選択する必要があります。

|===


== 必要なデータベースプロファイルのタイプ

SnapManager では、データベースプロファイルと、アーカイブログバックアップとデータファイルバックアップの分離が関係しているかどうかに基づいてバックアップが作成されます。

[cols="2a,3a"]
|===
| プロファイルタイプ | 説明 


 a| 
データ・ファイルとアーカイブ・ログのバックアップを組み合わせた、単一のデータベース・プロファイル
 a| 
次の項目を作成できます。

* すべてのデータ・ファイル、アーカイブ・ログ・ファイル、および制御ファイルを含むフル・バックアップ
* 選択されたデータ・ファイル、表領域、アーカイブ・ログ・ファイル、および制御ファイルを含むパーシャル・バックアップ




 a| 
アーカイブログのバックアップとデータファイルのバックアップについては、データベースプロファイルが別途必要になります
 a| 
次の項目を作成できます。

* バックアップと各種ラベルの組み合わせによる、データファイルのバックアップとアーカイブログのバックアップ
* データファイルのみ - すべてのデータファイルと制御ファイルのバックアップ
* 選択したデータ・ファイルまたは表領域の、部分的なデータ・ファイルのみのバックアップ、および制御ファイルのバックアップ
* ARCHIVE - ログのみのバックアップ


|===


== Snapshot コピーにはどのような命名規則を使用する必要がありますか。

バックアップで作成された Snapshot コピーには、カスタムの命名規則を使用できます。プロファイル名、データベース名、 SnapManager が提供するデータベース SID など、カスタムテキストまたは組み込みの変数を使用して命名規則を作成できます。ポリシーを作成する際に命名規則を作成できます。


NOTE: smid 変数を命名形式に含める必要があります。smid 変数は ' 一意のスナップショット識別子を作成します

Snapshot コピーの命名規則は、プロファイルの作成中または作成後に変更できます。更新後のパターンは、まだ作成されていない Snapshot コピーにのみ適用されます。既存の Snapshot コピーは以前のパターンを保持します。



== プライマリストレージシステムとセカンダリストレージシステムにバックアップコピーを保持する期間

バックアップの保持ポリシーでは、保持する正常バックアップの数を指定します。保持ポリシーはポリシーの作成時に指定できます。

保持クラスとして、毎時、毎日、毎週、毎月、または無制限を選択できます。保持クラスごとに、保持数と保持期間を一緒に、または個別に指定できます。

* 保持数によって、特定の保持クラスのバックアップのうち、保持するバックアップの最小数が決まります。
+
たとえば、バックアップスケジュールが _daily__ で保持数が _10_ の場合、日次バックアップは 10 個保持されます。

+

NOTE: Data ONTAP で保持できる Snapshot コピーの最大数は 255 個です。上限に達すると、デフォルトでは新しい Snapshot コピーの作成は失敗します。ただし、古い Snapshot コピーを削除するように Data ONTAP のローテーションポリシーを設定することはできます。

* 保持期間によって、バックアップを保持する最小日数が決まります。
+
たとえば、バックアップスケジュールが _daily_ で保持期間が _10_ の場合、日次バックアップが 10 日保持されます。



SnapMirror レプリケーションを設定すると、デスティネーションボリュームに保持ポリシーがミラーリングされます。


NOTE: バックアップコピーを長期にわたって保持する場合は、 SnapVault を使用する必要があります。



== ソースボリュームまたはデスティネーションボリュームを使用したバックアップコピーの検証

SnapMirror または SnapVault を使用する場合は、プライマリストレージシステム上の Snapshot コピーではなく、 SnapMirror または SnapVault デスティネーションボリューム上の Snapshot コピーを使用してバックアップコピーを検証できます。デスティネーションボリュームを検証に使用すると、プライマリストレージシステムの負荷が軽減されます。
