---
permalink: unix-installation-7mode/concept-limitations-for-performing-a-rollback.html 
sidebar: sidebar 
keywords: scenario, perform, rollback, task, limitation 
summary: ロールバックを実行できない状況に注意してください。ただし、一部のシナリオでは、ロールバックを実行する前にいくつかの追加タスクを実行できます。 
---
= ロールバックの実行に関する制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロールバックを実行できない状況に注意してください。ただし、一部のシナリオでは、ロールバックを実行する前にいくつかの追加タスクを実行できます。

ロールバックを実行できない場合や、追加のタスクを実行する必要がある場合は、次のようになります。

* ローリングアップグレードの実行後に次のいずれかの処理を実行する場合
+
** 新しいプロファイルを作成します。
** クローンをスプリットします。
** プロファイルの保護ステータスを変更します。
** 保護ポリシー、保持クラス、または SnapVault 関係と SnapMirror 関係を割り当てます。
+
このシナリオでは、ロールバックの実行後に、割り当てられていた保護ポリシー、保持クラス、または SnapVault 関係と SnapMirror 関係を手動で削除する必要があります。

** バックアップのマウントステータスを変更します。
+
このシナリオでは、最初にマウントステータスを元の状態に変更してからロールバックを実行する必要があります。

** バックアップをリストアします。
** 認証モードをデータベース認証からオペレーティングシステム（ OS ）認証に変更します。
+
このシナリオでは、ロールバックの実行後に認証モードを OS からデータベースに手動で変更する必要があります。



* プロファイルのホスト名が変更された場合
* アーカイブログのバックアップを作成するためにプロファイルが分離されている場合
+
このシナリオでは、 SnapManager 3.2 より前のバージョンにロールバックすることはできません。


