---
permalink: unix-installation-7mode/task-perform-a-rollback-on-a-single-host-or-multiple-hosts.html 
sidebar: sidebar 
keywords: perform, rollback, single, multiple, snapmanager, server, host, command-line, cli 
summary: コマンドラインインターフェイス（ CLI ）を使用して、 1 つまたは複数の SnapManager サーバホストでロールバックを実行できます。 
---
= 単一のホストまたは複数のホストでロールバックを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドラインインターフェイス（ CLI ）を使用して、 1 つまたは複数の SnapManager サーバホストでロールバックを実行できます。

* 必要なもの *

ロールバックを実行するためのすべての前提条件が完了していることを確認する必要があります。

.手順
. 単一のホストでロールバックを実行するには、次のコマンドを入力します。
+
「* smsaprepository rollback -repository -dbdbname_repo_service_name」-host_repo_host__ login -username repo_repo_username -port_repo_repo_port_-rollbackhost_with _target_database-*」

+
* 例 *

+
次の例は、 hostA にマウントされているすべてのターゲットデータベース、およびリポジトリホスト repo_host に格納されている repoA という名前のリポジトリデータベースをロールバックするコマンドを示しています。

+
[listing]
----

smsap repository rollback
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -rollbackhost hostA
----
. 複数のホストでロールバックを実行するには、次のコマンドを入力します。
+
`*smsaprepository rollback -repository-dbname_repo_repo_service_name_-login-username_repo_username -port_repo_repo_port_-rollback_hosthost_with _target_dos, host_ase2_*`

+

NOTE: 複数のホストの場合は、ホスト名をカンマで区切って入力し、カンマと次のホスト名の間にスペースが入れられていないことを確認します。

+
Real Application Clusters （ RAC ）構成を使用している場合は、 RAC に関連付けられたすべてのホストを手動でロールバックする必要があります。allhosts を使用すると、すべてのホストのロールバックを実行できます。

+
* 例 *

+
次に、ホスト hostA 、 hostB 、およびリポジトリホスト repo_host に格納されている repoA という名前のリポジトリデータベースにマウントされているすべてのターゲットデータベースをロールバックするコマンドの例を示します。

+
[listing]
----

smsap repository rollback
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -rollbackhost hostA,hostB
----
+
ホストのターゲットデータベースのプロファイルに関連付けられているホスト、プロファイル、スケジュール、バックアップ、およびクローンが、以前のリポジトリにリバートされます。


